using System.Globalization;
using System.Text;

namespace NVOAMASIS.Services;

public sealed class DepotHaiPhongReport
{
    public string Code { get; init; } = string.Empty;
    public string MenuNo { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public string TableName { get; init; } = string.Empty;
    public string DefaultDepot { get; init; } = string.Empty;
    public bool UseSectionParser { get; init; }
    public string[] SkipSheets { get; init; } = Array.Empty<string>();
    public string[] Columns { get; init; } = Array.Empty<string>();
}

public static class DepotHaiPhongCatalog
{
    public static IReadOnlyList<DepotHaiPhongReport> All { get; } = new DepotHaiPhongReport[]
    {
        new DepotHaiPhongReport
        {
            Code = "8_3_9_1",
            MenuNo = "8.3.9.1",
            Title = "Nam Dinh Vu Stock",
            TableName = "8_3_9_1_Nam_Dinh_Vu_Stock",
            DefaultDepot = "NAM DINH VU",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "Seq",
            "Container_No",
            "SzTp",
            "OPR",
            "Export_Seal",
            "Carrier_Seal",
            "BL_No",
            "Booking_No",
            "FE",
            "Vessel_Name",
            "User_Voyage",
            "In_Date",
            "Stack_Days",
            "Truck_No_In",
            "Consignee_Name",
            "WGT",
            "Remark",
            "SzTp2",
            "Mode",
            "SO_No",
            "Status",
            "Block",
            "Bay",
            "Row",
            "Tier",
            "Area",
            "Vessel_Code",
            "Calling_Year",
            "Calling_Seq",
            "ATB",
            "In_Voyage",
            "Out_Voyage",
            "Second_Vessel",
            "Second_User_Voyage",
            "Private_SzTp",
            "Cntr_Len",
            "Cntr_H_W",
            "Cntr_Type",
            "Weight_Group",
            "Billing_OPR",
            "Loading_Confirm_Status",
            "Return_Cancel_Reason",
            "BL_Location",
            "Ship_Loc_D",
            "Discharging_Hold_Deck",
            "Discharging_Hatch_Index",
            "Ship_Loc_L",
            "Loading_Hold_Deck",
            "Loading_Hatch_Index",
            "Delivery",
            "Trans_Type_In",
            "Trans_Type_Out",
            "POR",
            "POL",
            "POD",
            "FPOD",
            "FDEST",
            "COD",
            "VGM",
            "VGM_Check",
            "Cargo_Type",
            "Temp_C",
            "Temp_F",
            "IMDG",
            "UNNo",
            "Packing_Group",
            "Handling_Inst_S",
            "AbsoluteConst_S",
            "Handling_Inst_Y",
            "Dispatch_Mode_In",
            "Dispatch_Mode_Out",
            "Customs_Seal",
            "Job_Order_No_In",
            "Job_Order_No_Out",
            "Shifting_Time",
            "Shifting_Type",
            "Shifting_RSN",
            "Container_Condition",
            "Defective_Code",
            "Damage_Condition",
            "Clean_Code",
            "Complete_Clean_Date",
            "Complete_Repair_Date",
            "Power_Code",
            "Customs_Hold",
            "Terminal_Hold",
            "Damage_Check",
            "Stuff_Check",
            "DG_Check",
            "Overland_Check",
            "Release_Check",
            "Empty_Check",
            "Inspection_Check",
            "Discharging_EQU_No",
            "Loading_EQU_No",
            "Trucker_In",
            "Trucker_Out",
            "Truck_No_Out",
            "Train_Voyage_In",
            "Train_Voyage_Out",
            "Shipper_Consignee",
            "Forwarder",
            "Commodity",
            "Commodity_Desc",
            "Storage_Code",
            "In_Lane",
            "Out_Lane",
            "Terminal_In_Date",
            "Out_Date",
            "Customs_Approval_Type",
            "Domestic_Check",
            "Customer_Reference_Number",
            "Customer_Name"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_2",
            MenuNo = "8.3.9.2",
            Title = "Nam Dinh Vu Report",
            TableName = "8_3_9_2_Nam_Dinh_Vu_Report",
            DefaultDepot = "NAM DINH VU",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "Container_No",
            "SZTP",
            "F_E",
            "Move_Type",
            "Move_Date",
            "BL_No",
            "Booking_No",
            "Consignee",
            "Vessel_Name",
            "In_Voyage",
            "Out_Voyage",
            "Partner_Code",
            "Dispatch_Mode",
            "Truck_In",
            "Truck_Out",
            "Carrier_Seal",
            "Export_Seal",
            "Weight",
            "VGM",
            "Remark"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_3",
            MenuNo = "8.3.9.3",
            Title = "ICD Hai Phong TCHP",
            TableName = "8_3_9_3_ICD_Hai_Phong_TCHP",
            DefaultDepot = "ICD HAI PHONG TCHP",
            UseSectionParser = false,
            SkipSheets = new[] { "Inventory" },
            Columns = new[]
            {
            "METHOD",
            "OPERATION_METHOD",
            "EXEC_TS",
            "LINE",
            "AGENT",
            "ITEM_KEY",
            "SOCONT",
            "KICHCO",
            "PORT_GRADE",
            "LINE_GRADE",
            "TRANGTHAI",
            "TRONGLUONG",
            "TRONGLUONG_VGM",
            "BL_NO",
            "BOOK_NO",
            "RELEASE_NO",
            "HUONG",
            "HUONG1",
            "CANGCT",
            "CANGDEN",
            "GIAO",
            "NHAN",
            "DGS_CLASS",
            "GHICHU",
            "ENTRY_VOY_NO",
            "ENTRY_VES_NAME",
            "EXIT_VOY_NO",
            "EXIT_VES_NAME",
            "ENTRY_TRUCK_ID",
            "EXIT_TRUCK_ID",
            "SOSEAL",
            "ORG_METHOD",
            "CUR_METHOD",
            "FUTURE_METHOD",
            "ITEM_NO",
            "ISO",
            "FEL",
            "TEMP",
            "WEIGHT",
            "BILL_OF_LADING",
            "LOCATION",
            "CATEGORY",
            "ARR_BY",
            "ARR_CAR",
            "ARR_VES_NAME",
            "ARR_TS",
            "DEP_BY",
            "DEP_CAR",
            "DEP_VES_NAME",
            "DEP_TS",
            "DISCH_PORT",
            "FINAL_DISCH_PORT",
            "PLACE_OF_RECEIPT",
            "PLACE_OF_DELIVERY",
            "CUSTOM_CLEARANCE",
            "CC_TS",
            "UN_NO",
            "DAM"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_4",
            MenuNo = "8.3.9.4",
            Title = "ICD Nam Hai Stock",
            TableName = "8_3_9_4_ICD_Nam_Hai_Stock",
            DefaultDepot = "ICD NAM HAI",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "Hang_khai_thac",
            "Container",
            "Kich_co",
            "Kich_co_ISO",
            "Ghi_chu",
            "Ghi_chu_noi_bo",
            "Tinh_trang_vo",
            "Nam_san_xuat",
            "So_ngay_luu_bai",
            "Lich_trinh_tau",
            "Ten_tau",
            "Chuyen_nhap",
            "Chuyen_xuat",
            "Huong",
            "Trang_thai",
            "F_E",
            "Phuong_an",
            "Vi_tri_tren_bai",
            "Cang_xep",
            "Cang_do",
            "Cang_dich",
            "Ngay_nhap_bai",
            "Ngay_ra_bai",
            "Loai_Hang",
            "Hang_Hoa",
            "Trong_Luong",
            "VGM",
            "Nhiet_do",
            "CLASS",
            "UNNO",
            "Chu_hang",
            "So_Booking",
            "So_Van_Don",
            "So_niem_chi",
            "So_niem_chi_1",
            "So_niem_chi_2",
            "Thanh_Ly_Hai_Quan",
            "So_to_khai",
            "Hang_noi_ngoai",
            "Cang_chuyen"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_5",
            MenuNo = "8.3.9.5",
            Title = "Sao A Depot",
            TableName = "8_3_9_5_Sao_A_Depot",
            DefaultDepot = "SAO A DEPOT",
            UseSectionParser = false,
            SkipSheets = new[] { "General", "General_Status" },
            Columns = new[]
            {
            "Seq",
            "EIR",
            "Date_in",
            "Time",
            "Container",
            "Type",
            "ISO_SZTP",
            "Opt",
            "F_E",
            "Move",
            "Bill_of_lading",
            "Consignee",
            "Truck",
            "YOM",
            "Seal_No",
            "Seal_No1",
            "Seal_No2",
            "VGM",
            "Clean",
            "Max_gross",
            "Tare_weight",
            "Remark",
            "Status",
            "Grade",
            "Note",
            "Ins_Date",
            "Date_out",
            "Booking",
            "Vessel",
            "Voyage",
            "POL",
            "POD",
            "Shipper",
            "SealNo",
            "Note1",
            "Required_Grade",
            "TruckNo",
            "TruckerPhone",
            "DateIn",
            "Days",
            "ISO_Type",
            "Opr",
            "Position",
            "Location",
            "Note2",
            "Note3",
            "Clean_Status",
            "PTI_date",
            "PTI_setting",
            "PTI_status",
            "Estimated_date",
            "Appoval_date",
            "Reject_date",
            "Repaired_date",
            "Registered_date",
            "Cash"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_6",
            MenuNo = "8.3.9.6",
            Title = "Hai An Movement Report",
            TableName = "8_3_9_6_Hai_An_Movement",
            DefaultDepot = "HAI AN",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "SQ",
            "SHIPPER",
            "CONTAINER",
            "SIZE",
            "LINE",
            "SEAL",
            "BL_BK",
            "F_E",
            "VESSEL_VOYAGE",
            "GATE_OUT",
            "GATE_IN",
            "TRUCK",
            "WEIGHT",
            "VGM",
            "REMARKS",
            "IMP_DAYS",
            "UNSTUFF",
            "STUFF"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_7",
            MenuNo = "8.3.9.7",
            Title = "Hai An Stock Report",
            TableName = "8_3_9_7_Hai_An_Stock",
            DefaultDepot = "HAI AN",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "No",
            "Container",
            "Line",
            "Seal",
            "Size",
            "B_L_No",
            "BK_No",
            "Shipper",
            "Vessel_Voyage",
            "Fulimp",
            "Trimp",
            "Imp_Days",
            "Remarks",
            "GW",
            "Location",
            "Noted",
            "Shippers",
            "Date_In",
            "Date_Order",
            "Type",
            "Remark_AV_DM",
            "DAO_CHUYEN"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_8",
            MenuNo = "8.3.9.8",
            Title = "ICD Nam Hai Movement",
            TableName = "8_3_9_8_ICD_Nam_Hai_Movement",
            DefaultDepot = "ICD NAM HAI",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "So_Container",
            "So_lenh",
            "Lich_trinh_tau",
            "Hang_KT",
            "Kich_co_noi_bo",
            "Kich_co_ISO",
            "F_E",
            "Trong_luong",
            "VGM",
            "CLASS",
            "UNNO",
            "Nhiet_do",
            "Vent",
            "So_niem_chi",
            "So_niem_chi_1",
            "So_niem_chi_2",
            "Tinh_trang_Container",
            "Phuong_an_ve_sinh",
            "Vao_Ra",
            "Cong_vao",
            "Nam_san_xuat",
            "Xe_vao_cong",
            "Cong_ra",
            "Xe_ra_cong",
            "Container_vao_bai",
            "Container_ra_bai",
            "So_ngay_luu_bai",
            "Phuong_tien",
            "So_xe_Sa_lan",
            "So_romooc",
            "Vi_tri_bai",
            "Phuong_an",
            "PTGN",
            "Chu_hang",
            "DTTT",
            "HTTT",
            "So_hoa_don",
            "Loai_hang",
            "Hang_hoa",
            "So_BILL",
            "So_Booking",
            "Hang_noi_ngoai",
            "Cang_chuyen",
            "Cang_giao_nhan",
            "Ghi_chu",
            "TLHQ",
            "Giao_qua_han_lenh"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_9",
            MenuNo = "8.3.9.9",
            Title = "GFT Depot",
            TableName = "8_3_9_9_GFT_Depot",
            DefaultDepot = "GFT DEPOT",
            UseSectionParser = true,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "SEQ",
            "CONTAINER_NO",
            "TYPE",
            "STATUS",
            "IN_DATE",
            "TIME",
            "Location",
            "TRUCK_NO",
            "ORDER_NO",
            "From",
            "Cont_Type",
            "Machine",
            "MFY",
            "IN_USER",
            "VESS",
            "VOY",
            "RMK",
            "OUT_DATE",
            "VSL",
            "OUT_USER",
            "REPAIR_DATE",
            "GRADE",
            "STAY_DAYS",
            "PTI_STATUS",
            "BOOK_NO_AT",
            "PLAN_NO_IN",
            "CASH",
            "REMARK",
            "Place",
            "DEPOT_NAME"
            }
        },
        new DepotHaiPhongReport
        {
            Code = "8_3_9_10",
            MenuNo = "8.3.9.10",
            Title = "HICT",
            TableName = "8_3_9_10_HICT",
            DefaultDepot = "HICT",
            UseSectionParser = false,
            SkipSheets = Array.Empty<string>(),
            Columns = new[]
            {
            "METHOD",
            "PHUONGAN",
            "LINE",
            "AGENT",
            "ITEM_KEY",
            "SOCONT",
            "KICHCO",
            "TRANGTHAI",
            "BOOK_NO",
            "RELEASE_NO",
            "SOSEAL",
            "NGAYNHAPBAI",
            "NGAYTHUCHIEN",
            "HUONG",
            "CANGCT",
            "CANGDEN",
            "GIAO",
            "NHAN",
            "DGS_CLASS",
            "GHICHU",
            "CHIDINHCONTAINER",
            "TAUNHAP",
            "CHUYENNHAP",
            "TAUXUAT",
            "CHUYENXUAT",
            "TAUXUATDUKIEN",
            "CHUYENXUATDUKIEN",
            "XEVAO",
            "XERA",
            "TRONGLUONG_HANGHOA",
            "TRONGLUONG_VO",
            "TRONGLUONG_TONG",
            "TRONGLUONG_VGM",
            "TRONGLUONG_VGM_LOADLIST",
            "PHANLOAI",
            "TG_CAMDIEN",
            "TG_RUTDIEN",
            "ISO",
            "NHIETDO",
            "PTI_OK",
            "TRONGLUONG",
            "TRONGLUONG_VGM_LOATLIST",
            "BILL_OF_LADING",
            "VITRI",
            "KHUVUC",
            "LOAIPHUONGTIEN_VAO",
            "PHUONGTIEN_VAO",
            "LOAIPHUONGTIEN_RA",
            "PHUONGTIEN_RA",
            "NGAYROIBAI",
            "CANGCHUYENTAI",
            "CANGDICH",
            "TLHQ",
            "UN_NO",
            "DAM"
            }
        }
    };

    public static DepotHaiPhongReport Get(string? code)
    {
        if (string.IsNullOrWhiteSpace(code))
            return All[0];

        return All.FirstOrDefault(x =>
                   string.Equals(x.Code, code, StringComparison.OrdinalIgnoreCase)
                   || string.Equals(x.MenuNo, code, StringComparison.OrdinalIgnoreCase)
                   || string.Equals(x.TableName, code, StringComparison.OrdinalIgnoreCase))
               ?? All[0];
    }

    public static string NormalizeKey(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return string.Empty;

        text = text.Replace("2nd", "Second", StringComparison.OrdinalIgnoreCase);

        var formD = text.Normalize(NormalizationForm.FormD);
        var sb = new StringBuilder(formD.Length);
        foreach (var ch in formD)
        {
            var cat = CharUnicodeInfo.GetUnicodeCategory(ch);
            if (cat == UnicodeCategory.NonSpacingMark)
                continue;
            var c = ch == 'đ' || ch == 'Đ' ? 'D' : ch;
            if (char.IsLetterOrDigit(c))
                sb.Append(char.ToUpperInvariant(c));
        }
        return sb.ToString();
    }
}
