-- 8.3.8 Phương Đông Depot
-- Drop old Alpine inventory test table and recreate as 8_3_8_Phuong_Dong_Depot.
-- Data is discarded on purpose.

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.M_8_3_8_YARD_ALPINE_INVENTORY', N'U') IS NOT NULL
    DROP TABLE dbo.M_8_3_8_YARD_ALPINE_INVENTORY;
GO

IF OBJECT_ID(N'dbo.[8_3_8_Phuong_Dong_Depot]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_8_Phuong_Dong_Depot];
GO

CREATE TABLE dbo.[8_3_8_Phuong_Dong_Depot]
(
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_8_Phuong_Dong_Depot PRIMARY KEY,
    DEPOT NVARCHAR(150) NULL,
    DepotId UNIQUEIDENTIFIER NULL,
    SOURCE_FILE NVARCHAR(260) NULL,
    SHEET_NAME NVARCHAR(100) NULL,
    EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL,
    REPORT_TO DATETIME2 NULL,
    REPORT_DATE DATETIME2 NULL,
    SEQ DECIMAL(18,4) NULL,
    EIR NVARCHAR(100) NULL,
    CONTAINER NVARCHAR(50) NULL,
    CONTAINER_TYPE NVARCHAR(50) NULL,
    ISO_SZTP NVARCHAR(50) NULL,
    ISO_TYPE NVARCHAR(50) NULL,
    OPT NVARCHAR(50) NULL,
    OPR NVARCHAR(50) NULL,
    FE NVARCHAR(20) NULL,
    MOVE NVARCHAR(50) NULL,
    DATE_IN DATETIME2 NULL,
    TIME_IN NVARCHAR(50) NULL,
    DATE_OUT DATETIME2 NULL,
    LOCATION NVARCHAR(250) NULL,
    BOOKING NVARCHAR(200) NULL,
    VESSEL NVARCHAR(200) NULL,
    VOYAGE NVARCHAR(100) NULL,
    POL NVARCHAR(100) NULL,
    POD NVARCHAR(100) NULL,
    SHIPPER NVARCHAR(500) NULL,
    CONSIGNEE NVARCHAR(500) NULL,
    YOM NVARCHAR(50) NULL,
    SEAL_NO NVARCHAR(100) NULL,
    SEAL_NO2 NVARCHAR(100) NULL,
    NOTE1 NVARCHAR(1000) NULL,
    NOTE2 NVARCHAR(1000) NULL,
    NOTE3 NVARCHAR(1000) NULL,
    REQUIRED_GRADE NVARCHAR(100) NULL,
    VGM DECIMAL(18,4) NULL,
    MAX_GROSS DECIMAL(18,4) NULL,
    TARE_WEIGHT DECIMAL(18,4) NULL,
    TRUCK_NO NVARCHAR(100) NULL,
    TRUCKER_PHONE NVARCHAR(100) NULL,
    POSITION NVARCHAR(150) NULL,
    DAYS DECIMAL(18,4) NULL,
    REMARK NVARCHAR(2000) NULL,
    STATUS NVARCHAR(100) NULL,
    GRADE NVARCHAR(50) NULL,
    CLEAN_METHOD NVARCHAR(100) NULL,
    CLEAN_STATUS NVARCHAR(100) NULL,
    PTI_DATE DATETIME2 NULL,
    PTI_SETTING NVARCHAR(100) NULL,
    PTI_STATUS NVARCHAR(100) NULL,
    ESTIMATED_DATE DATETIME2 NULL,
    APPROVAL_DATE DATETIME2 NULL,
    REJECT_DATE DATETIME2 NULL,
    REPAIRED_DATE DATETIME2 NULL,
    REGISTERED_DATE DATETIME2 NULL,
    INS_DATE DATETIME2 NULL,
    ROW_SIGNATURE CHAR(64) NOT NULL,
    DATE_IMPORT DATETIME2 NULL,
    USER_IMPORT NVARCHAR(100) NULL,
    CREATED_AT DATETIME2 NULL
);
GO

CREATE UNIQUE INDEX UX_8_3_8_Phuong_Dong_Depot_SIGNATURE
    ON dbo.[8_3_8_Phuong_Dong_Depot](ROW_SIGNATURE);
GO

CREATE INDEX IX_8_3_8_Phuong_Dong_Depot_CONTAINER
    ON dbo.[8_3_8_Phuong_Dong_Depot](CONTAINER, DATE_IN, DATE_OUT);
GO

CREATE NONCLUSTERED INDEX IX_8_3_8_Phuong_Dong_Depot_DepotId
    ON dbo.[8_3_8_Phuong_Dong_Depot](DepotId);
GO
