-- 8.3.5 Cảng VICT
-- Drop old VSS Exp test table used by DepotContainerImportPro_835 and recreate as 8_3_5_Cang_VICT.
-- Data is discarded on purpose. YardMovement_VSS_26040808_Imp is left unchanged.

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.YardMovement_VSS_26040808_Exp', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_VSS_26040808_Exp;
GO

IF OBJECT_ID(N'dbo.YardMovement_VSS_26040808', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_VSS_26040808;
GO

IF OBJECT_ID(N'dbo.M_8_3_VSS_IN_OUT_YARD_Exp', N'U') IS NOT NULL
    DROP TABLE dbo.M_8_3_VSS_IN_OUT_YARD_Exp;
GO

IF OBJECT_ID(N'dbo.[8_3_5_Cang_VICT]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_5_Cang_VICT];
GO

CREATE TABLE dbo.[8_3_5_Cang_VICT]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_8_3_5_Cang_VICT] PRIMARY KEY DEFAULT NEWID(),
    [DEPOT] NVARCHAR(100) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [METHOD] NVARCHAR(50) NULL,
    [OPERATION_METHOD] NVARCHAR(50) NULL,
    [EXEC_TS] DATETIME2 NULL,
    [LINE] NVARCHAR(50) NULL,
    [AGENT] NVARCHAR(100) NULL,
    [KHACHHANG] NVARCHAR(200) NULL,
    [ITEM_KEY] NVARCHAR(50) NULL,
    [SOCONT] NVARCHAR(50) NULL,
    [KICHCO] NVARCHAR(20) NULL,
    [PORT_GRADE] NVARCHAR(50) NULL,
    [LINE_GRADE] NVARCHAR(50) NULL,
    [TRANGTHAI] NVARCHAR(20) NULL,
    [TRONGLUONG] DECIMAL(18,4) NULL,
    [TRONGLUONG_VGM] DECIMAL(18,4) NULL,
    [BL_NO] NVARCHAR(100) NULL,
    [BOOK_NO] NVARCHAR(100) NULL,
    [RELEASE_NO] NVARCHAR(100) NULL,
    [HUONG] NVARCHAR(50) NULL,
    [HUONG1] NVARCHAR(50) NULL,
    [CANGCT] NVARCHAR(50) NULL,
    [CANGDEN] NVARCHAR(50) NULL,
    [GIAO] NVARCHAR(100) NULL,
    [NHAN] NVARCHAR(100) NULL,
    [DGS_CLASS] NVARCHAR(50) NULL,
    [GHICHU] NVARCHAR(1000) NULL,
    [ENTRY_VOY_NO] NVARCHAR(50) NULL,
    [ENTRY_VES_NAME] NVARCHAR(100) NULL,
    [EXIT_VOY_NO] NVARCHAR(50) NULL,
    [EXIT_VES_NAME] NVARCHAR(100) NULL,
    [ENTRY_TRUCK_ID] NVARCHAR(50) NULL,
    [EXIT_TRUCK_ID] NVARCHAR(50) NULL,
    [SOSEAL] NVARCHAR(50) NULL,
    [STORAGEDAY] INT NULL,
    [DateImport] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_5_Cang_VICT_DateImport] DEFAULT SYSUTCDATETIME(),
    [UserImport] NVARCHAR(100) NULL,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_5_Cang_VICT_CreatedAt] DEFAULT SYSUTCDATETIME()
);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_5_Cang_VICT_SOCONT]
    ON dbo.[8_3_5_Cang_VICT] ([SOCONT]);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_5_Cang_VICT_DepotId]
    ON dbo.[8_3_5_Cang_VICT] ([DepotId]);
GO
