-- 8.3.9 Depot Hai Phong
-- Chay bang tai khoan DBA (CREATE TABLE).
-- Mapping menu <-> Excel <-> table:
--   8.3.9.1  NAM DINH VU STOCK.xlsx           -> dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]
--   8.3.9.2  NAM DINH VU REPORT.xlsx          -> dbo.[8_3_9_2_Nam_Dinh_Vu_Report]
--   8.3.9.3  ICD HAI PHONG ( TCHP).XLS        -> dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]
--   8.3.9.4  ICD NAM HAI _STOCK.xlsx          -> dbo.[8_3_9_4_ICD_Nam_Hai_Stock]
--   8.3.9.5  SAO A DEPOT.xlsx                 -> dbo.[8_3_9_5_Sao_A_Depot]
--   8.3.9.6  HAI AN MOVEMENT REPORT.xls       -> dbo.[8_3_9_6_Hai_An_Movement]
--   8.3.9.7  HAI AN STOCK REPORT.xls          -> dbo.[8_3_9_7_Hai_An_Stock]
--   8.3.9.8  ICD NAM HAI_MOVEMENT.xlsx        -> dbo.[8_3_9_8_ICD_Nam_Hai_Movement]
--   8.3.9.9  GFT DEPO.xls                     -> dbo.[8_3_9_9_GFT_Depot]
--   8.3.9.10 HICT.XLS                         -> dbo.[8_3_9_10_HICT]
--
-- Moi table co: Id, Depot, DepotId, SOURCE_FILE, SHEET_NAME, SECTION_NAME,
-- EXCEL_ROW, ContainerNo, ExtraJson, ROW_SIGNATURE, DATE_IMPORT, USER_IMPORT, CREATED_AT
-- + cac cot nghiep vu theo header Excel.
-- Xoa theo file import dung SOURCE_FILE + DATE_IMPORT.

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_1_Nam_Dinh_Vu_Stock];
GO

CREATE TABLE dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_1_Nam_Dinh_Vu_Stock PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_1_Nam_Dinh_Vu_Stock_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_1_Nam_Dinh_Vu_Stock_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [Seq] NVARCHAR(400) NULL,
    [Container_No] NVARCHAR(400) NULL,
    [SzTp] NVARCHAR(400) NULL,
    [OPR] NVARCHAR(400) NULL,
    [Export_Seal] NVARCHAR(400) NULL,
    [Carrier_Seal] NVARCHAR(400) NULL,
    [BL_No] NVARCHAR(400) NULL,
    [Booking_No] NVARCHAR(400) NULL,
    [FE] NVARCHAR(400) NULL,
    [Vessel_Name] NVARCHAR(400) NULL,
    [User_Voyage] NVARCHAR(400) NULL,
    [In_Date] NVARCHAR(400) NULL,
    [Stack_Days] NVARCHAR(400) NULL,
    [Truck_No_In] NVARCHAR(400) NULL,
    [Consignee_Name] NVARCHAR(400) NULL,
    [WGT] NVARCHAR(400) NULL,
    [Remark] NVARCHAR(2000) NULL,
    [SzTp2] NVARCHAR(400) NULL,
    [Mode] NVARCHAR(400) NULL,
    [SO_No] NVARCHAR(400) NULL,
    [Status] NVARCHAR(400) NULL,
    [Block] NVARCHAR(400) NULL,
    [Bay] NVARCHAR(400) NULL,
    [Row] NVARCHAR(400) NULL,
    [Tier] NVARCHAR(400) NULL,
    [Area] NVARCHAR(400) NULL,
    [Vessel_Code] NVARCHAR(400) NULL,
    [Calling_Year] NVARCHAR(400) NULL,
    [Calling_Seq] NVARCHAR(400) NULL,
    [ATB] NVARCHAR(400) NULL,
    [In_Voyage] NVARCHAR(400) NULL,
    [Out_Voyage] NVARCHAR(400) NULL,
    [Second_Vessel] NVARCHAR(400) NULL,
    [Second_User_Voyage] NVARCHAR(400) NULL,
    [Private_SzTp] NVARCHAR(400) NULL,
    [Cntr_Len] NVARCHAR(400) NULL,
    [Cntr_H_W] NVARCHAR(400) NULL,
    [Cntr_Type] NVARCHAR(400) NULL,
    [Weight_Group] NVARCHAR(400) NULL,
    [Billing_OPR] NVARCHAR(400) NULL,
    [Loading_Confirm_Status] NVARCHAR(400) NULL,
    [Return_Cancel_Reason] NVARCHAR(400) NULL,
    [BL_Location] NVARCHAR(400) NULL,
    [Ship_Loc_D] NVARCHAR(400) NULL,
    [Discharging_Hold_Deck] NVARCHAR(400) NULL,
    [Discharging_Hatch_Index] NVARCHAR(400) NULL,
    [Ship_Loc_L] NVARCHAR(400) NULL,
    [Loading_Hold_Deck] NVARCHAR(400) NULL,
    [Loading_Hatch_Index] NVARCHAR(400) NULL,
    [Delivery] NVARCHAR(400) NULL,
    [Trans_Type_In] NVARCHAR(400) NULL,
    [Trans_Type_Out] NVARCHAR(400) NULL,
    [POR] NVARCHAR(400) NULL,
    [POL] NVARCHAR(400) NULL,
    [POD] NVARCHAR(400) NULL,
    [FPOD] NVARCHAR(400) NULL,
    [FDEST] NVARCHAR(400) NULL,
    [COD] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [VGM_Check] NVARCHAR(400) NULL,
    [Cargo_Type] NVARCHAR(400) NULL,
    [Temp_C] NVARCHAR(400) NULL,
    [Temp_F] NVARCHAR(400) NULL,
    [IMDG] NVARCHAR(400) NULL,
    [UNNo] NVARCHAR(400) NULL,
    [Packing_Group] NVARCHAR(400) NULL,
    [Handling_Inst_S] NVARCHAR(400) NULL,
    [AbsoluteConst_S] NVARCHAR(400) NULL,
    [Handling_Inst_Y] NVARCHAR(400) NULL,
    [Dispatch_Mode_In] NVARCHAR(400) NULL,
    [Dispatch_Mode_Out] NVARCHAR(400) NULL,
    [Customs_Seal] NVARCHAR(400) NULL,
    [Job_Order_No_In] NVARCHAR(400) NULL,
    [Job_Order_No_Out] NVARCHAR(400) NULL,
    [Shifting_Time] NVARCHAR(400) NULL,
    [Shifting_Type] NVARCHAR(400) NULL,
    [Shifting_RSN] NVARCHAR(400) NULL,
    [Container_Condition] NVARCHAR(400) NULL,
    [Defective_Code] NVARCHAR(400) NULL,
    [Damage_Condition] NVARCHAR(400) NULL,
    [Clean_Code] NVARCHAR(400) NULL,
    [Complete_Clean_Date] NVARCHAR(400) NULL,
    [Complete_Repair_Date] NVARCHAR(400) NULL,
    [Power_Code] NVARCHAR(400) NULL,
    [Customs_Hold] NVARCHAR(400) NULL,
    [Terminal_Hold] NVARCHAR(400) NULL,
    [Damage_Check] NVARCHAR(400) NULL,
    [Stuff_Check] NVARCHAR(400) NULL,
    [DG_Check] NVARCHAR(400) NULL,
    [Overland_Check] NVARCHAR(400) NULL,
    [Release_Check] NVARCHAR(400) NULL,
    [Empty_Check] NVARCHAR(400) NULL,
    [Inspection_Check] NVARCHAR(400) NULL,
    [Discharging_EQU_No] NVARCHAR(400) NULL,
    [Loading_EQU_No] NVARCHAR(400) NULL,
    [Trucker_In] NVARCHAR(400) NULL,
    [Trucker_Out] NVARCHAR(400) NULL,
    [Truck_No_Out] NVARCHAR(400) NULL,
    [Train_Voyage_In] NVARCHAR(400) NULL,
    [Train_Voyage_Out] NVARCHAR(400) NULL,
    [Shipper_Consignee] NVARCHAR(400) NULL,
    [Forwarder] NVARCHAR(400) NULL,
    [Commodity] NVARCHAR(400) NULL,
    [Commodity_Desc] NVARCHAR(2000) NULL,
    [Storage_Code] NVARCHAR(400) NULL,
    [In_Lane] NVARCHAR(400) NULL,
    [Out_Lane] NVARCHAR(400) NULL,
    [Terminal_In_Date] NVARCHAR(400) NULL,
    [Out_Date] NVARCHAR(400) NULL,
    [Customs_Approval_Type] NVARCHAR(400) NULL,
    [Domestic_Check] NVARCHAR(400) NULL,
    [Customer_Reference_Number] NVARCHAR(400) NULL,
    [Customer_Name] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_1_Nam_Dinh_Vu_Stock_SIGNATURE] ON dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_1_Nam_Dinh_Vu_Stock_ContainerNo] ON dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_1_Nam_Dinh_Vu_Stock_SOURCE_FILE] ON dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_1_Nam_Dinh_Vu_Stock_DepotId] ON dbo.[8_3_9_1_Nam_Dinh_Vu_Stock]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_2_Nam_Dinh_Vu_Report]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_2_Nam_Dinh_Vu_Report];
GO

CREATE TABLE dbo.[8_3_9_2_Nam_Dinh_Vu_Report]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_2_Nam_Dinh_Vu_Report PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_2_Nam_Dinh_Vu_Report_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_2_Nam_Dinh_Vu_Report_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [Container_No] NVARCHAR(400) NULL,
    [SZTP] NVARCHAR(400) NULL,
    [F_E] NVARCHAR(400) NULL,
    [Move_Type] NVARCHAR(400) NULL,
    [Move_Date] NVARCHAR(400) NULL,
    [BL_No] NVARCHAR(400) NULL,
    [Booking_No] NVARCHAR(400) NULL,
    [Consignee] NVARCHAR(400) NULL,
    [Vessel_Name] NVARCHAR(400) NULL,
    [In_Voyage] NVARCHAR(400) NULL,
    [Out_Voyage] NVARCHAR(400) NULL,
    [Partner_Code] NVARCHAR(400) NULL,
    [Dispatch_Mode] NVARCHAR(400) NULL,
    [Truck_In] NVARCHAR(400) NULL,
    [Truck_Out] NVARCHAR(400) NULL,
    [Carrier_Seal] NVARCHAR(400) NULL,
    [Export_Seal] NVARCHAR(400) NULL,
    [Weight] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [Remark] NVARCHAR(2000) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_2_Nam_Dinh_Vu_Report_SIGNATURE] ON dbo.[8_3_9_2_Nam_Dinh_Vu_Report]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_2_Nam_Dinh_Vu_Report_ContainerNo] ON dbo.[8_3_9_2_Nam_Dinh_Vu_Report]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_2_Nam_Dinh_Vu_Report_SOURCE_FILE] ON dbo.[8_3_9_2_Nam_Dinh_Vu_Report]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_2_Nam_Dinh_Vu_Report_DepotId] ON dbo.[8_3_9_2_Nam_Dinh_Vu_Report]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_3_ICD_Hai_Phong_TCHP];
GO

CREATE TABLE dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_3_ICD_Hai_Phong_TCHP PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_3_ICD_Hai_Phong_TCHP_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_3_ICD_Hai_Phong_TCHP_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [METHOD] NVARCHAR(400) NULL,
    [OPERATION_METHOD] NVARCHAR(400) NULL,
    [EXEC_TS] NVARCHAR(400) NULL,
    [LINE] NVARCHAR(400) NULL,
    [AGENT] NVARCHAR(400) NULL,
    [ITEM_KEY] NVARCHAR(400) NULL,
    [SOCONT] NVARCHAR(400) NULL,
    [KICHCO] NVARCHAR(400) NULL,
    [PORT_GRADE] NVARCHAR(400) NULL,
    [LINE_GRADE] NVARCHAR(400) NULL,
    [TRANGTHAI] NVARCHAR(400) NULL,
    [TRONGLUONG] NVARCHAR(400) NULL,
    [TRONGLUONG_VGM] NVARCHAR(400) NULL,
    [BL_NO] NVARCHAR(400) NULL,
    [BOOK_NO] NVARCHAR(400) NULL,
    [RELEASE_NO] NVARCHAR(400) NULL,
    [HUONG] NVARCHAR(400) NULL,
    [HUONG1] NVARCHAR(400) NULL,
    [CANGCT] NVARCHAR(400) NULL,
    [CANGDEN] NVARCHAR(400) NULL,
    [GIAO] NVARCHAR(400) NULL,
    [NHAN] NVARCHAR(400) NULL,
    [DGS_CLASS] NVARCHAR(400) NULL,
    [GHICHU] NVARCHAR(2000) NULL,
    [ENTRY_VOY_NO] NVARCHAR(400) NULL,
    [ENTRY_VES_NAME] NVARCHAR(400) NULL,
    [EXIT_VOY_NO] NVARCHAR(400) NULL,
    [EXIT_VES_NAME] NVARCHAR(400) NULL,
    [ENTRY_TRUCK_ID] NVARCHAR(400) NULL,
    [EXIT_TRUCK_ID] NVARCHAR(400) NULL,
    [SOSEAL] NVARCHAR(400) NULL,
    [ORG_METHOD] NVARCHAR(400) NULL,
    [CUR_METHOD] NVARCHAR(400) NULL,
    [FUTURE_METHOD] NVARCHAR(400) NULL,
    [ITEM_NO] NVARCHAR(400) NULL,
    [ISO] NVARCHAR(400) NULL,
    [FEL] NVARCHAR(400) NULL,
    [TEMP] NVARCHAR(400) NULL,
    [WEIGHT] NVARCHAR(400) NULL,
    [BILL_OF_LADING] NVARCHAR(400) NULL,
    [LOCATION] NVARCHAR(400) NULL,
    [CATEGORY] NVARCHAR(400) NULL,
    [ARR_BY] NVARCHAR(400) NULL,
    [ARR_CAR] NVARCHAR(400) NULL,
    [ARR_VES_NAME] NVARCHAR(400) NULL,
    [ARR_TS] NVARCHAR(400) NULL,
    [DEP_BY] NVARCHAR(400) NULL,
    [DEP_CAR] NVARCHAR(400) NULL,
    [DEP_VES_NAME] NVARCHAR(400) NULL,
    [DEP_TS] NVARCHAR(400) NULL,
    [DISCH_PORT] NVARCHAR(400) NULL,
    [FINAL_DISCH_PORT] NVARCHAR(400) NULL,
    [PLACE_OF_RECEIPT] NVARCHAR(400) NULL,
    [PLACE_OF_DELIVERY] NVARCHAR(400) NULL,
    [CUSTOM_CLEARANCE] NVARCHAR(400) NULL,
    [CC_TS] NVARCHAR(400) NULL,
    [UN_NO] NVARCHAR(400) NULL,
    [DAM] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_3_ICD_Hai_Phong_TCHP_SIGNATURE] ON dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_3_ICD_Hai_Phong_TCHP_ContainerNo] ON dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_3_ICD_Hai_Phong_TCHP_SOURCE_FILE] ON dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_3_ICD_Hai_Phong_TCHP_DepotId] ON dbo.[8_3_9_3_ICD_Hai_Phong_TCHP]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_4_ICD_Nam_Hai_Stock]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_4_ICD_Nam_Hai_Stock];
GO

CREATE TABLE dbo.[8_3_9_4_ICD_Nam_Hai_Stock]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_4_ICD_Nam_Hai_Stock PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_4_ICD_Nam_Hai_Stock_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_4_ICD_Nam_Hai_Stock_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [Hang_khai_thac] NVARCHAR(400) NULL,
    [Container] NVARCHAR(400) NULL,
    [Kich_co] NVARCHAR(400) NULL,
    [Kich_co_ISO] NVARCHAR(400) NULL,
    [Ghi_chu] NVARCHAR(2000) NULL,
    [Ghi_chu_noi_bo] NVARCHAR(2000) NULL,
    [Tinh_trang_vo] NVARCHAR(400) NULL,
    [Nam_san_xuat] NVARCHAR(400) NULL,
    [So_ngay_luu_bai] NVARCHAR(400) NULL,
    [Lich_trinh_tau] NVARCHAR(400) NULL,
    [Ten_tau] NVARCHAR(400) NULL,
    [Chuyen_nhap] NVARCHAR(400) NULL,
    [Chuyen_xuat] NVARCHAR(400) NULL,
    [Huong] NVARCHAR(400) NULL,
    [Trang_thai] NVARCHAR(400) NULL,
    [F_E] NVARCHAR(400) NULL,
    [Phuong_an] NVARCHAR(400) NULL,
    [Vi_tri_tren_bai] NVARCHAR(400) NULL,
    [Cang_xep] NVARCHAR(400) NULL,
    [Cang_do] NVARCHAR(400) NULL,
    [Cang_dich] NVARCHAR(400) NULL,
    [Ngay_nhap_bai] NVARCHAR(400) NULL,
    [Ngay_ra_bai] NVARCHAR(400) NULL,
    [Loai_Hang] NVARCHAR(400) NULL,
    [Hang_Hoa] NVARCHAR(2000) NULL,
    [Trong_Luong] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [Nhiet_do] NVARCHAR(400) NULL,
    [CLASS] NVARCHAR(400) NULL,
    [UNNO] NVARCHAR(400) NULL,
    [Chu_hang] NVARCHAR(400) NULL,
    [So_Booking] NVARCHAR(400) NULL,
    [So_Van_Don] NVARCHAR(400) NULL,
    [So_niem_chi] NVARCHAR(400) NULL,
    [So_niem_chi_1] NVARCHAR(400) NULL,
    [So_niem_chi_2] NVARCHAR(400) NULL,
    [Thanh_Ly_Hai_Quan] NVARCHAR(400) NULL,
    [So_to_khai] NVARCHAR(400) NULL,
    [Hang_noi_ngoai] NVARCHAR(400) NULL,
    [Cang_chuyen] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_4_ICD_Nam_Hai_Stock_SIGNATURE] ON dbo.[8_3_9_4_ICD_Nam_Hai_Stock]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_4_ICD_Nam_Hai_Stock_ContainerNo] ON dbo.[8_3_9_4_ICD_Nam_Hai_Stock]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_4_ICD_Nam_Hai_Stock_SOURCE_FILE] ON dbo.[8_3_9_4_ICD_Nam_Hai_Stock]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_4_ICD_Nam_Hai_Stock_DepotId] ON dbo.[8_3_9_4_ICD_Nam_Hai_Stock]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_5_Sao_A_Depot]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_5_Sao_A_Depot];
GO

CREATE TABLE dbo.[8_3_9_5_Sao_A_Depot]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_5_Sao_A_Depot PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_5_Sao_A_Depot_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_5_Sao_A_Depot_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [Seq] NVARCHAR(400) NULL,
    [EIR] NVARCHAR(400) NULL,
    [Date_in] NVARCHAR(400) NULL,
    [Time] NVARCHAR(400) NULL,
    [Container] NVARCHAR(400) NULL,
    [Type] NVARCHAR(400) NULL,
    [ISO_SZTP] NVARCHAR(400) NULL,
    [Opt] NVARCHAR(400) NULL,
    [F_E] NVARCHAR(400) NULL,
    [Move] NVARCHAR(400) NULL,
    [Bill_of_lading] NVARCHAR(400) NULL,
    [Consignee] NVARCHAR(400) NULL,
    [Truck] NVARCHAR(400) NULL,
    [YOM] NVARCHAR(400) NULL,
    [Seal_No] NVARCHAR(400) NULL,
    [Seal_No1] NVARCHAR(400) NULL,
    [Seal_No2] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [Clean] NVARCHAR(400) NULL,
    [Max_gross] NVARCHAR(400) NULL,
    [Tare_weight] NVARCHAR(400) NULL,
    [Remark] NVARCHAR(2000) NULL,
    [Status] NVARCHAR(400) NULL,
    [Grade] NVARCHAR(400) NULL,
    [Note] NVARCHAR(2000) NULL,
    [Ins_Date] NVARCHAR(400) NULL,
    [Date_out] NVARCHAR(400) NULL,
    [Booking] NVARCHAR(400) NULL,
    [Vessel] NVARCHAR(400) NULL,
    [Voyage] NVARCHAR(400) NULL,
    [POL] NVARCHAR(400) NULL,
    [POD] NVARCHAR(400) NULL,
    [Shipper] NVARCHAR(400) NULL,
    [SealNo] NVARCHAR(400) NULL,
    [Note1] NVARCHAR(2000) NULL,
    [Required_Grade] NVARCHAR(400) NULL,
    [TruckNo] NVARCHAR(400) NULL,
    [TruckerPhone] NVARCHAR(400) NULL,
    [DateIn] NVARCHAR(400) NULL,
    [Days] NVARCHAR(400) NULL,
    [ISO_Type] NVARCHAR(400) NULL,
    [Opr] NVARCHAR(400) NULL,
    [Position] NVARCHAR(400) NULL,
    [Location] NVARCHAR(400) NULL,
    [Note2] NVARCHAR(2000) NULL,
    [Note3] NVARCHAR(2000) NULL,
    [Clean_Status] NVARCHAR(400) NULL,
    [PTI_date] NVARCHAR(400) NULL,
    [PTI_setting] NVARCHAR(400) NULL,
    [PTI_status] NVARCHAR(400) NULL,
    [Estimated_date] NVARCHAR(400) NULL,
    [Appoval_date] NVARCHAR(400) NULL,
    [Reject_date] NVARCHAR(400) NULL,
    [Repaired_date] NVARCHAR(400) NULL,
    [Registered_date] NVARCHAR(400) NULL,
    [Cash] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_5_Sao_A_Depot_SIGNATURE] ON dbo.[8_3_9_5_Sao_A_Depot]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_5_Sao_A_Depot_ContainerNo] ON dbo.[8_3_9_5_Sao_A_Depot]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_5_Sao_A_Depot_SOURCE_FILE] ON dbo.[8_3_9_5_Sao_A_Depot]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_5_Sao_A_Depot_DepotId] ON dbo.[8_3_9_5_Sao_A_Depot]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_6_Hai_An_Movement]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_6_Hai_An_Movement];
GO

CREATE TABLE dbo.[8_3_9_6_Hai_An_Movement]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_6_Hai_An_Movement PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_6_Hai_An_Movement_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_6_Hai_An_Movement_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [SQ] NVARCHAR(400) NULL,
    [SHIPPER] NVARCHAR(400) NULL,
    [CONTAINER] NVARCHAR(400) NULL,
    [SIZE] NVARCHAR(400) NULL,
    [LINE] NVARCHAR(400) NULL,
    [SEAL] NVARCHAR(400) NULL,
    [BL_BK] NVARCHAR(400) NULL,
    [F_E] NVARCHAR(400) NULL,
    [VESSEL_VOYAGE] NVARCHAR(400) NULL,
    [GATE_OUT] NVARCHAR(400) NULL,
    [GATE_IN] NVARCHAR(400) NULL,
    [TRUCK] NVARCHAR(400) NULL,
    [WEIGHT] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [REMARKS] NVARCHAR(2000) NULL,
    [IMP_DAYS] NVARCHAR(400) NULL,
    [UNSTUFF] NVARCHAR(400) NULL,
    [STUFF] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_6_Hai_An_Movement_SIGNATURE] ON dbo.[8_3_9_6_Hai_An_Movement]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_6_Hai_An_Movement_ContainerNo] ON dbo.[8_3_9_6_Hai_An_Movement]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_6_Hai_An_Movement_SOURCE_FILE] ON dbo.[8_3_9_6_Hai_An_Movement]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_6_Hai_An_Movement_DepotId] ON dbo.[8_3_9_6_Hai_An_Movement]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_7_Hai_An_Stock]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_7_Hai_An_Stock];
GO

CREATE TABLE dbo.[8_3_9_7_Hai_An_Stock]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_7_Hai_An_Stock PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_7_Hai_An_Stock_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_7_Hai_An_Stock_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [No] NVARCHAR(400) NULL,
    [Container] NVARCHAR(400) NULL,
    [Line] NVARCHAR(400) NULL,
    [Seal] NVARCHAR(400) NULL,
    [Size] NVARCHAR(400) NULL,
    [B_L_No] NVARCHAR(400) NULL,
    [BK_No] NVARCHAR(400) NULL,
    [Shipper] NVARCHAR(400) NULL,
    [Vessel_Voyage] NVARCHAR(400) NULL,
    [Fulimp] NVARCHAR(400) NULL,
    [Trimp] NVARCHAR(400) NULL,
    [Imp_Days] NVARCHAR(400) NULL,
    [Remarks] NVARCHAR(2000) NULL,
    [GW] NVARCHAR(400) NULL,
    [Location] NVARCHAR(400) NULL,
    [Noted] NVARCHAR(2000) NULL,
    [Shippers] NVARCHAR(400) NULL,
    [Date_In] NVARCHAR(400) NULL,
    [Date_Order] NVARCHAR(400) NULL,
    [Type] NVARCHAR(400) NULL,
    [Remark_AV_DM] NVARCHAR(2000) NULL,
    [DAO_CHUYEN] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_7_Hai_An_Stock_SIGNATURE] ON dbo.[8_3_9_7_Hai_An_Stock]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_7_Hai_An_Stock_ContainerNo] ON dbo.[8_3_9_7_Hai_An_Stock]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_7_Hai_An_Stock_SOURCE_FILE] ON dbo.[8_3_9_7_Hai_An_Stock]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_7_Hai_An_Stock_DepotId] ON dbo.[8_3_9_7_Hai_An_Stock]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_8_ICD_Nam_Hai_Movement]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_8_ICD_Nam_Hai_Movement];
GO

CREATE TABLE dbo.[8_3_9_8_ICD_Nam_Hai_Movement]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_8_ICD_Nam_Hai_Movement PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_8_ICD_Nam_Hai_Movement_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_8_ICD_Nam_Hai_Movement_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [So_Container] NVARCHAR(400) NULL,
    [So_lenh] NVARCHAR(400) NULL,
    [Lich_trinh_tau] NVARCHAR(400) NULL,
    [Hang_KT] NVARCHAR(400) NULL,
    [Kich_co_noi_bo] NVARCHAR(400) NULL,
    [Kich_co_ISO] NVARCHAR(400) NULL,
    [F_E] NVARCHAR(400) NULL,
    [Trong_luong] NVARCHAR(400) NULL,
    [VGM] NVARCHAR(400) NULL,
    [CLASS] NVARCHAR(400) NULL,
    [UNNO] NVARCHAR(400) NULL,
    [Nhiet_do] NVARCHAR(400) NULL,
    [Vent] NVARCHAR(400) NULL,
    [So_niem_chi] NVARCHAR(400) NULL,
    [So_niem_chi_1] NVARCHAR(400) NULL,
    [So_niem_chi_2] NVARCHAR(400) NULL,
    [Tinh_trang_Container] NVARCHAR(400) NULL,
    [Phuong_an_ve_sinh] NVARCHAR(400) NULL,
    [Vao_Ra] NVARCHAR(400) NULL,
    [Cong_vao] NVARCHAR(400) NULL,
    [Nam_san_xuat] NVARCHAR(400) NULL,
    [Xe_vao_cong] NVARCHAR(400) NULL,
    [Cong_ra] NVARCHAR(400) NULL,
    [Xe_ra_cong] NVARCHAR(400) NULL,
    [Container_vao_bai] NVARCHAR(400) NULL,
    [Container_ra_bai] NVARCHAR(400) NULL,
    [So_ngay_luu_bai] NVARCHAR(400) NULL,
    [Phuong_tien] NVARCHAR(400) NULL,
    [So_xe_Sa_lan] NVARCHAR(400) NULL,
    [So_romooc] NVARCHAR(400) NULL,
    [Vi_tri_bai] NVARCHAR(400) NULL,
    [Phuong_an] NVARCHAR(400) NULL,
    [PTGN] NVARCHAR(400) NULL,
    [Chu_hang] NVARCHAR(400) NULL,
    [DTTT] NVARCHAR(400) NULL,
    [HTTT] NVARCHAR(400) NULL,
    [So_hoa_don] NVARCHAR(400) NULL,
    [Loai_hang] NVARCHAR(400) NULL,
    [Hang_hoa] NVARCHAR(2000) NULL,
    [So_BILL] NVARCHAR(400) NULL,
    [So_Booking] NVARCHAR(400) NULL,
    [Hang_noi_ngoai] NVARCHAR(400) NULL,
    [Cang_chuyen] NVARCHAR(400) NULL,
    [Cang_giao_nhan] NVARCHAR(400) NULL,
    [Ghi_chu] NVARCHAR(2000) NULL,
    [TLHQ] NVARCHAR(400) NULL,
    [Giao_qua_han_lenh] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_8_ICD_Nam_Hai_Movement_SIGNATURE] ON dbo.[8_3_9_8_ICD_Nam_Hai_Movement]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_8_ICD_Nam_Hai_Movement_ContainerNo] ON dbo.[8_3_9_8_ICD_Nam_Hai_Movement]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_8_ICD_Nam_Hai_Movement_SOURCE_FILE] ON dbo.[8_3_9_8_ICD_Nam_Hai_Movement]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_8_ICD_Nam_Hai_Movement_DepotId] ON dbo.[8_3_9_8_ICD_Nam_Hai_Movement]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_9_GFT_Depot]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_9_GFT_Depot];
GO

CREATE TABLE dbo.[8_3_9_9_GFT_Depot]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_9_GFT_Depot PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_9_GFT_Depot_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_9_GFT_Depot_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [SEQ] NVARCHAR(400) NULL,
    [CONTAINER_NO] NVARCHAR(400) NULL,
    [TYPE] NVARCHAR(400) NULL,
    [STATUS] NVARCHAR(400) NULL,
    [IN_DATE] NVARCHAR(400) NULL,
    [TIME] NVARCHAR(400) NULL,
    [Location] NVARCHAR(400) NULL,
    [TRUCK_NO] NVARCHAR(400) NULL,
    [ORDER_NO] NVARCHAR(400) NULL,
    [From] NVARCHAR(400) NULL,
    [Cont_Type] NVARCHAR(400) NULL,
    [Machine] NVARCHAR(400) NULL,
    [MFY] NVARCHAR(400) NULL,
    [IN_USER] NVARCHAR(400) NULL,
    [VESS] NVARCHAR(400) NULL,
    [VOY] NVARCHAR(400) NULL,
    [RMK] NVARCHAR(400) NULL,
    [OUT_DATE] NVARCHAR(400) NULL,
    [VSL] NVARCHAR(400) NULL,
    [OUT_USER] NVARCHAR(400) NULL,
    [REPAIR_DATE] NVARCHAR(400) NULL,
    [GRADE] NVARCHAR(400) NULL,
    [STAY_DAYS] NVARCHAR(400) NULL,
    [PTI_STATUS] NVARCHAR(400) NULL,
    [BOOK_NO_AT] NVARCHAR(400) NULL,
    [PLAN_NO_IN] NVARCHAR(400) NULL,
    [CASH] NVARCHAR(400) NULL,
    [REMARK] NVARCHAR(2000) NULL,
    [Place] NVARCHAR(400) NULL,
    [DEPOT_NAME] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_9_GFT_Depot_SIGNATURE] ON dbo.[8_3_9_9_GFT_Depot]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_9_GFT_Depot_ContainerNo] ON dbo.[8_3_9_9_GFT_Depot]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_9_GFT_Depot_SOURCE_FILE] ON dbo.[8_3_9_9_GFT_Depot]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_9_GFT_Depot_DepotId] ON dbo.[8_3_9_9_GFT_Depot]([DepotId]);
GO

IF OBJECT_ID(N'dbo.[8_3_9_10_HICT]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_9_10_HICT];
GO

CREATE TABLE dbo.[8_3_9_10_HICT]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_9_10_HICT PRIMARY KEY DEFAULT NEWID(),
    [Depot] NVARCHAR(150) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [SOURCE_FILE] NVARCHAR(260) NULL,
    [SHEET_NAME] NVARCHAR(100) NULL,
    [SECTION_NAME] NVARCHAR(100) NULL,
    [EXCEL_ROW] INT NULL,
    [ContainerNo] NVARCHAR(50) NULL,
    [ExtraJson] NVARCHAR(MAX) NULL,
    [ROW_SIGNATURE] CHAR(64) NOT NULL,
    [DATE_IMPORT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_10_HICT_DATE_IMPORT DEFAULT SYSUTCDATETIME(),
    [USER_IMPORT] NVARCHAR(100) NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT DF_8_3_9_10_HICT_CREATED_AT DEFAULT SYSUTCDATETIME(),
    [METHOD] NVARCHAR(400) NULL,
    [PHUONGAN] NVARCHAR(400) NULL,
    [LINE] NVARCHAR(400) NULL,
    [AGENT] NVARCHAR(400) NULL,
    [ITEM_KEY] NVARCHAR(400) NULL,
    [SOCONT] NVARCHAR(400) NULL,
    [KICHCO] NVARCHAR(400) NULL,
    [TRANGTHAI] NVARCHAR(400) NULL,
    [BOOK_NO] NVARCHAR(400) NULL,
    [RELEASE_NO] NVARCHAR(400) NULL,
    [SOSEAL] NVARCHAR(400) NULL,
    [NGAYNHAPBAI] NVARCHAR(400) NULL,
    [NGAYTHUCHIEN] NVARCHAR(400) NULL,
    [HUONG] NVARCHAR(400) NULL,
    [CANGCT] NVARCHAR(400) NULL,
    [CANGDEN] NVARCHAR(400) NULL,
    [GIAO] NVARCHAR(400) NULL,
    [NHAN] NVARCHAR(400) NULL,
    [DGS_CLASS] NVARCHAR(400) NULL,
    [GHICHU] NVARCHAR(2000) NULL,
    [CHIDINHCONTAINER] NVARCHAR(400) NULL,
    [TAUNHAP] NVARCHAR(400) NULL,
    [CHUYENNHAP] NVARCHAR(400) NULL,
    [TAUXUAT] NVARCHAR(400) NULL,
    [CHUYENXUAT] NVARCHAR(400) NULL,
    [TAUXUATDUKIEN] NVARCHAR(400) NULL,
    [CHUYENXUATDUKIEN] NVARCHAR(400) NULL,
    [XEVAO] NVARCHAR(400) NULL,
    [XERA] NVARCHAR(400) NULL,
    [TRONGLUONG_HANGHOA] NVARCHAR(400) NULL,
    [TRONGLUONG_VO] NVARCHAR(400) NULL,
    [TRONGLUONG_TONG] NVARCHAR(400) NULL,
    [TRONGLUONG_VGM] NVARCHAR(400) NULL,
    [TRONGLUONG_VGM_LOADLIST] NVARCHAR(400) NULL,
    [PHANLOAI] NVARCHAR(400) NULL,
    [TG_CAMDIEN] NVARCHAR(400) NULL,
    [TG_RUTDIEN] NVARCHAR(400) NULL,
    [ISO] NVARCHAR(400) NULL,
    [NHIETDO] NVARCHAR(400) NULL,
    [PTI_OK] NVARCHAR(400) NULL,
    [TRONGLUONG] NVARCHAR(400) NULL,
    [TRONGLUONG_VGM_LOATLIST] NVARCHAR(400) NULL,
    [BILL_OF_LADING] NVARCHAR(400) NULL,
    [VITRI] NVARCHAR(400) NULL,
    [KHUVUC] NVARCHAR(400) NULL,
    [LOAIPHUONGTIEN_VAO] NVARCHAR(400) NULL,
    [PHUONGTIEN_VAO] NVARCHAR(400) NULL,
    [LOAIPHUONGTIEN_RA] NVARCHAR(400) NULL,
    [PHUONGTIEN_RA] NVARCHAR(400) NULL,
    [NGAYROIBAI] NVARCHAR(400) NULL,
    [CANGCHUYENTAI] NVARCHAR(400) NULL,
    [CANGDICH] NVARCHAR(400) NULL,
    [TLHQ] NVARCHAR(400) NULL,
    [UN_NO] NVARCHAR(400) NULL,
    [DAM] NVARCHAR(400) NULL
);
GO

CREATE UNIQUE INDEX [UX_8_3_9_10_HICT_SIGNATURE] ON dbo.[8_3_9_10_HICT]([ROW_SIGNATURE]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_10_HICT_ContainerNo] ON dbo.[8_3_9_10_HICT]([ContainerNo]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_10_HICT_SOURCE_FILE] ON dbo.[8_3_9_10_HICT]([SOURCE_FILE], [DATE_IMPORT]);
GO
CREATE NONCLUSTERED INDEX [IX_8_3_9_10_HICT_DepotId] ON dbo.[8_3_9_10_HICT]([DepotId]);
GO
