-- 8.3.6 Macstar Thủ Đức
-- Drop old APS test tables used by StockInOutImportPro and recreate with Macstar_Thu_Duc names.
-- Data is discarded on purpose.

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.M_8_3_6_YARD_APS_GATEIN', N'U') IS NOT NULL DROP TABLE dbo.M_8_3_6_YARD_APS_GATEIN;
IF OBJECT_ID(N'dbo.M_8_3_6_YARD_APS_GATEOUT', N'U') IS NOT NULL DROP TABLE dbo.M_8_3_6_YARD_APS_GATEOUT;
IF OBJECT_ID(N'dbo.M_8_3_6_YARD_APS_STOCK', N'U') IS NOT NULL DROP TABLE dbo.M_8_3_6_YARD_APS_STOCK;
IF OBJECT_ID(N'dbo.M_8_3_6_YARD_APS_GENERAL', N'U') IS NOT NULL DROP TABLE dbo.M_8_3_6_YARD_APS_GENERAL;
IF OBJECT_ID(N'dbo.M_8_3_6_YARD_APS_GENERAL_STATUS', N'U') IS NOT NULL DROP TABLE dbo.M_8_3_6_YARD_APS_GENERAL_STATUS;
GO

IF OBJECT_ID(N'dbo.[8_3_6_Macstar_Thu_Duc_GATEIN]', N'U') IS NOT NULL DROP TABLE dbo.[8_3_6_Macstar_Thu_Duc_GATEIN];
IF OBJECT_ID(N'dbo.[8_3_6_Macstar_Thu_Duc_GATEOUT]', N'U') IS NOT NULL DROP TABLE dbo.[8_3_6_Macstar_Thu_Duc_GATEOUT];
IF OBJECT_ID(N'dbo.[8_3_6_Macstar_Thu_Duc_STOCK]', N'U') IS NOT NULL DROP TABLE dbo.[8_3_6_Macstar_Thu_Duc_STOCK];
IF OBJECT_ID(N'dbo.[8_3_6_Macstar_Thu_Duc_GENERAL]', N'U') IS NOT NULL DROP TABLE dbo.[8_3_6_Macstar_Thu_Duc_GENERAL];
IF OBJECT_ID(N'dbo.[8_3_6_Macstar_Thu_Duc_GENERAL_STATUS]', N'U') IS NOT NULL DROP TABLE dbo.[8_3_6_Macstar_Thu_Duc_GENERAL_STATUS];
GO

CREATE TABLE dbo.[8_3_6_Macstar_Thu_Duc_GATEIN](
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_6_Macstar_Thu_Duc_GATEIN PRIMARY KEY,
    DEPOT NVARCHAR(100) NULL, DepotId UNIQUEIDENTIFIER NULL, SOURCE_FILE NVARCHAR(260) NULL, SHEET_NAME NVARCHAR(100) NULL, EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL, REPORT_TO DATETIME2 NULL, REPORT_DATE DATETIME2 NULL,
    SEQ DECIMAL(18,4) NULL, EIR NVARCHAR(100) NULL, DATE_IN DATETIME2 NULL, TIME_IN NVARCHAR(50) NULL,
    CONTAINER NVARCHAR(50) NULL, CONTAINER_TYPE NVARCHAR(50) NULL, ISO_SZTP NVARCHAR(50) NULL, OPT NVARCHAR(50) NULL, FE NVARCHAR(20) NULL, MOVE NVARCHAR(50) NULL,
    LOCATION NVARCHAR(200) NULL, BILL_OF_LADING NVARCHAR(200) NULL, CONSIGNEE NVARCHAR(300) NULL, TRUCK NVARCHAR(100) NULL, YOM NVARCHAR(50) NULL,
    SEAL_NO NVARCHAR(100) NULL, SEAL_NO1 NVARCHAR(100) NULL, SEAL_NO2 NVARCHAR(100) NULL, VGM DECIMAL(18,4) NULL, CLEAN NVARCHAR(100) NULL,
    MAX_GROSS DECIMAL(18,4) NULL, TARE_WEIGHT DECIMAL(18,4) NULL, REMARK NVARCHAR(1000) NULL, STATUS NVARCHAR(100) NULL, GRADE NVARCHAR(50) NULL, NOTE NVARCHAR(1000) NULL,
    INS_DATE DATETIME2 NULL, RAW_JSON NVARCHAR(MAX) NULL, ROW_SIGNATURE NVARCHAR(64) NOT NULL, DATE_IMPORT DATETIME2 NULL, USER_IMPORT NVARCHAR(100) NULL, CREATED_AT DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_8_3_6_Macstar_Thu_Duc_GATEIN_SIG ON dbo.[8_3_6_Macstar_Thu_Duc_GATEIN](ROW_SIGNATURE);
CREATE NONCLUSTERED INDEX IX_8_3_6_Macstar_Thu_Duc_GATEIN_DepotId ON dbo.[8_3_6_Macstar_Thu_Duc_GATEIN](DepotId);
GO

CREATE TABLE dbo.[8_3_6_Macstar_Thu_Duc_GATEOUT](
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_6_Macstar_Thu_Duc_GATEOUT PRIMARY KEY,
    DEPOT NVARCHAR(100) NULL, DepotId UNIQUEIDENTIFIER NULL, SOURCE_FILE NVARCHAR(260) NULL, SHEET_NAME NVARCHAR(100) NULL, EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL, REPORT_TO DATETIME2 NULL, REPORT_DATE DATETIME2 NULL,
    SEQ DECIMAL(18,4) NULL, EIR NVARCHAR(100) NULL, DATE_IN DATETIME2 NULL, TIME_IN NVARCHAR(50) NULL,
    CONTAINER NVARCHAR(50) NULL, CONTAINER_TYPE NVARCHAR(50) NULL, ISO_SZTP NVARCHAR(50) NULL, OPT NVARCHAR(50) NULL, FE NVARCHAR(20) NULL, MOVE NVARCHAR(50) NULL,
    LOCATION NVARCHAR(200) NULL, BOOKING NVARCHAR(200) NULL, VESSEL NVARCHAR(200) NULL, VOYAGE NVARCHAR(100) NULL, POL NVARCHAR(100) NULL, POD NVARCHAR(100) NULL,
    SHIPPER NVARCHAR(300) NULL, YOM NVARCHAR(50) NULL, SEAL_NO NVARCHAR(100) NULL, NOTE1 NVARCHAR(1000) NULL, REQUIRED_GRADE NVARCHAR(100) NULL, VGM DECIMAL(18,4) NULL,
    TRUCK_NO NVARCHAR(100) NULL, TRUCKER_PHONE NVARCHAR(100) NULL, GRADE NVARCHAR(50) NULL, DATE_OUT DATETIME2 NULL, DAYS DECIMAL(18,4) NULL, REMARK NVARCHAR(1000) NULL,
    RAW_JSON NVARCHAR(MAX) NULL, ROW_SIGNATURE NVARCHAR(64) NOT NULL, DATE_IMPORT DATETIME2 NULL, USER_IMPORT NVARCHAR(100) NULL, CREATED_AT DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_8_3_6_Macstar_Thu_Duc_GATEOUT_SIG ON dbo.[8_3_6_Macstar_Thu_Duc_GATEOUT](ROW_SIGNATURE);
CREATE NONCLUSTERED INDEX IX_8_3_6_Macstar_Thu_Duc_GATEOUT_DepotId ON dbo.[8_3_6_Macstar_Thu_Duc_GATEOUT](DepotId);
GO

CREATE TABLE dbo.[8_3_6_Macstar_Thu_Duc_STOCK](
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_6_Macstar_Thu_Duc_STOCK PRIMARY KEY,
    DEPOT NVARCHAR(100) NULL, DepotId UNIQUEIDENTIFIER NULL, SOURCE_FILE NVARCHAR(260) NULL, SHEET_NAME NVARCHAR(100) NULL, EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL, REPORT_TO DATETIME2 NULL, REPORT_DATE DATETIME2 NULL,
    SEQ DECIMAL(18,4) NULL, CONTAINER NVARCHAR(50) NULL, CONTAINER_TYPE NVARCHAR(50) NULL, ISO_TYPE NVARCHAR(50) NULL, OPR NVARCHAR(50) NULL, FE NVARCHAR(20) NULL, MOVE NVARCHAR(50) NULL,
    DATE_IN DATETIME2 NULL, TIME_IN NVARCHAR(50) NULL, CONSIGNEE NVARCHAR(300) NULL, POSITION NVARCHAR(100) NULL, DAYS DECIMAL(18,4) NULL, LOCATION NVARCHAR(200) NULL,
    YOM NVARCHAR(50) NULL, TARE_WEIGHT DECIMAL(18,4) NULL, SEAL_NO NVARCHAR(100) NULL, NOTE2 NVARCHAR(1000) NULL, NOTE3 NVARCHAR(1000) NULL, VGM DECIMAL(18,4) NULL,
    MAX_GROSS DECIMAL(18,4) NULL, REMARK NVARCHAR(1000) NULL, STATUS NVARCHAR(100) NULL, GRADE NVARCHAR(50) NULL, CLEAN_METHOD NVARCHAR(100) NULL, CLEAN_STATUS NVARCHAR(100) NULL,
    PTI_DATE DATETIME2 NULL, PTI_SETTING NVARCHAR(100) NULL, PTI_STATUS NVARCHAR(100) NULL, ESTIMATED_DATE DATETIME2 NULL, APPROVAL_DATE DATETIME2 NULL, REJECT_DATE DATETIME2 NULL,
    REPAIRED_DATE DATETIME2 NULL, REGISTERED_DATE DATETIME2 NULL, SHIPPER NVARCHAR(300) NULL, BOOKING NVARCHAR(200) NULL,
    RAW_JSON NVARCHAR(MAX) NULL, ROW_SIGNATURE NVARCHAR(64) NOT NULL, DATE_IMPORT DATETIME2 NULL, USER_IMPORT NVARCHAR(100) NULL, CREATED_AT DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_8_3_6_Macstar_Thu_Duc_STOCK_SIG ON dbo.[8_3_6_Macstar_Thu_Duc_STOCK](ROW_SIGNATURE);
CREATE NONCLUSTERED INDEX IX_8_3_6_Macstar_Thu_Duc_STOCK_DepotId ON dbo.[8_3_6_Macstar_Thu_Duc_STOCK](DepotId);
GO

CREATE TABLE dbo.[8_3_6_Macstar_Thu_Duc_GENERAL](
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_6_Macstar_Thu_Duc_GENERAL PRIMARY KEY,
    DEPOT NVARCHAR(100) NULL, DepotId UNIQUEIDENTIFIER NULL, SOURCE_FILE NVARCHAR(260) NULL, SHEET_NAME NVARCHAR(100) NULL, EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL, REPORT_TO DATETIME2 NULL, REPORT_DATE DATETIME2 NULL,
    SECTION NVARCHAR(100) NULL, ROW_TYPE NVARCHAR(50) NULL, OPERATOR NVARCHAR(100) NULL, CONTAINER_TYPE NVARCHAR(100) NULL, QUANTITY_CONT DECIMAL(18,4) NULL, TEU DECIMAL(18,4) NULL,
    RAW_JSON NVARCHAR(MAX) NULL, ROW_SIGNATURE NVARCHAR(64) NOT NULL, DATE_IMPORT DATETIME2 NULL, USER_IMPORT NVARCHAR(100) NULL, CREATED_AT DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_8_3_6_Macstar_Thu_Duc_GENERAL_SIG ON dbo.[8_3_6_Macstar_Thu_Duc_GENERAL](ROW_SIGNATURE);
CREATE NONCLUSTERED INDEX IX_8_3_6_Macstar_Thu_Duc_GENERAL_DepotId ON dbo.[8_3_6_Macstar_Thu_Duc_GENERAL](DepotId);
GO

CREATE TABLE dbo.[8_3_6_Macstar_Thu_Duc_GENERAL_STATUS](
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_8_3_6_Macstar_Thu_Duc_GENERAL_STATUS PRIMARY KEY,
    DEPOT NVARCHAR(100) NULL, DepotId UNIQUEIDENTIFIER NULL, SOURCE_FILE NVARCHAR(260) NULL, SHEET_NAME NVARCHAR(100) NULL, EXCEL_ROW INT NULL,
    REPORT_FROM DATETIME2 NULL, REPORT_TO DATETIME2 NULL, REPORT_DATE DATETIME2 NULL,
    OPR NVARCHAR(100) NULL, GRADE NVARCHAR(50) NULL, STATUS NVARCHAR(100) NULL,
    C20_DC DECIMAL(18,4) NULL, C20_RF DECIMAL(18,4) NULL, C20_FR DECIMAL(18,4) NULL, C20_OT DECIMAL(18,4) NULL, C20_TK DECIMAL(18,4) NULL,
    C40_DC DECIMAL(18,4) NULL, C40_RF DECIMAL(18,4) NULL, C40_FR DECIMAL(18,4) NULL, C40_OT DECIMAL(18,4) NULL, C40_TK DECIMAL(18,4) NULL,
    C40HC_DC DECIMAL(18,4) NULL, C40HC_RF DECIMAL(18,4) NULL, C40HC_FR DECIMAL(18,4) NULL, C40HC_OT DECIMAL(18,4) NULL, C40HC_TK DECIMAL(18,4) NULL,
    C45_DC DECIMAL(18,4) NULL, C45_RF DECIMAL(18,4) NULL, TOTAL_20 DECIMAL(18,4) NULL, TOTAL_40 DECIMAL(18,4) NULL, CONT DECIMAL(18,4) NULL, TEUS DECIMAL(18,4) NULL,
    RAW_JSON NVARCHAR(MAX) NULL, ROW_SIGNATURE NVARCHAR(64) NOT NULL, DATE_IMPORT DATETIME2 NULL, USER_IMPORT NVARCHAR(100) NULL, CREATED_AT DATETIME2 NULL
);
CREATE UNIQUE INDEX UX_8_3_6_Macstar_Thu_Duc_GENERAL_STATUS_SIG ON dbo.[8_3_6_Macstar_Thu_Duc_GENERAL_STATUS](ROW_SIGNATURE);
CREATE NONCLUSTERED INDEX IX_8_3_6_Macstar_Thu_Duc_GENERAL_STATUS_DepotId ON dbo.[8_3_6_Macstar_Thu_Duc_GENERAL_STATUS](DepotId);
GO
