SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* 1) BAO CAO HDS     TU 6H-16H NGAY 08042026-TAN VU.xlsx */
IF OBJECT_ID(N'dbo.StockGateOut_HDS_08042026', N'U') IS NOT NULL
    DROP TABLE dbo.StockGateOut_HDS_08042026;
GO

CREATE TABLE dbo.StockGateOut_HDS_08042026 (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [ChuHang] NVARCHAR(100) NULL,
    [TenTau] NVARCHAR(100) NULL,
    [NgayCapBen] DATETIME2 NULL,
    [ChuyenNhap] NVARCHAR(100) NULL,
    [ChuyenXuat] NVARCHAR(100) NULL,
    [SoCont] NVARCHAR(50) NULL,
    [KichCo] NVARCHAR(20) NULL,
    [KichCoISO] NVARCHAR(20) NULL,
    [SoNiemChi] NVARCHAR(50) NULL,
    [SoNiemChi01] NVARCHAR(50) NULL,
    [SoNiemChi02] NVARCHAR(50) NULL,
    [HangKhaiThac] NVARCHAR(100) NULL,
    [HKTTau] NVARCHAR(100) NULL,
    [FE] NVARCHAR(10) NULL,
    [TrongLuong] DECIMAL(18,4) NULL,
    [VGM] DECIMAL(18,4) NULL,
    [ContVaoBai] DATETIME2 NULL,
    [ContRaBai] DATETIME2 NULL,
    [XeVaoCong] DATETIME2 NULL,
    [XeRaCong] DATETIME2 NULL,
    [NgayHoanTat] DATETIME2 NULL,
    [SoNgayLuuBai] INT NULL,
    [SoXe] NVARCHAR(50) NULL,
    [SoRomooc] NVARCHAR(50) NULL,
    [PhuongAn] NVARCHAR(100) NULL,
    [PhuongThucGiaoNhan] NVARCHAR(100) NULL,
    [SoBooking] NVARCHAR(100) NULL,
    [SoBL] NVARCHAR(100) NULL,
    [GhiChu] NVARCHAR(1000) NULL,
    [GhiChuCont] NVARCHAR(1000) NULL,
    [GhiChuTaiCong] NVARCHAR(1000) NULL,
    [GhiChuTaiCauTau] NVARCHAR(1000) NULL,
    [MaDTTT] NVARCHAR(50) NULL,
    [DoiTuongThanhToan] NVARCHAR(255) NULL,
    [ChuyenCang] NVARCHAR(100) NULL,
    [CangGiaoNhan] NVARCHAR(100) NULL,
    [TTHaiQuan] NVARCHAR(100) NULL,
    [LoaiHang] NVARCHAR(50) NULL,
    [HangNgoaiNoi] NVARCHAR(50) NULL,
    [ContainerStatus] NVARCHAR(50) NULL,
    [TinhTrangVo] NVARCHAR(50) NULL,
    [ContQuaCan] NVARCHAR(20) NULL,
    [SoLenh] NVARCHAR(100) NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* 2) AG_2026040307.xls (gop du lieu nhieu sheet vao 1 bang, co cot SourceSheet) */
IF OBJECT_ID(N'dbo.YardReport_AG_2026040307', N'U') IS NOT NULL
    DROP TABLE dbo.YardReport_AG_2026040307;
GO

CREATE TABLE dbo.YardReport_AG_2026040307 (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [SourceSheet] NVARCHAR(50) NOT NULL,
    [SQ] INT NULL,
    [CNTRNO] NVARCHAR(50) NULL,
    [SZ] NVARCHAR(10) NULL,
    [TP] NVARCHAR(20) NULL,
    [ST] NVARCHAR(20) NULL,
    [SealNo] NVARCHAR(50) NULL,
    [WD] DECIMAL(18,4) NULL,
    [WN] DECIMAL(18,4) NULL,
    [CC] NVARCHAR(20) NULL,
    [Location] NVARCHAR(100) NULL,
    [DoBkNo] NVARCHAR(100) NULL,
    [POD_FDest] NVARCHAR(100) NULL,
    [Days] INT NULL,
    [Customer] NVARCHAR(255) NULL,
    [Payment] NVARCHAR(50) NULL,
    [TruckNo] NVARCHAR(50) NULL,
    [VslVoy] NVARCHAR(100) NULL,
    [DT] DATETIME2 NULL,
    [PlugIn] NVARCHAR(50) NULL,
    [Cargo] NVARCHAR(255) NULL,
    [Remarks] NVARCHAR(1000) NULL,
    [LEN] NVARCHAR(10) NULL,
    [TY] NVARCHAR(20) NULL,
    [Cond] NVARCHAR(50) NULL,
    [ShipCons] NVARCHAR(255) NULL,
    [BKDO] NVARCHAR(100) NULL,
    [DISC_VV] NVARCHAR(100) NULL,
    [LOAD_VV] NVARCHAR(100) NULL,
    [UNSDT] DATETIME2 NULL,
    [CCDT] DATETIME2 NULL,
    [STUDT] DATETIME2 NULL,
    [JOB] NVARCHAR(100) NULL,
    [SrvCode] NVARCHAR(50) NULL,
    [MODE] NVARCHAR(50) NULL,
    [STV] NVARCHAR(50) NULL,
    [Type] NVARCHAR(20) NULL,
    [Condition] NVARCHAR(50) NULL,
    [POL] NVARCHAR(50) NULL,
    [LoadVV] NVARCHAR(100) NULL,
    [POD] NVARCHAR(50) NULL,
    [DischVV] NVARCHAR(100) NULL,
    [DayStatus] NVARCHAR(50) NULL,
    [DayStorage] INT NULL,
    [DisArrDate] DATETIME2 NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* 3) DLRP_VSS_26040808.XLS (sheet IN-OUT_YARD__Imp/Exp) */
IF OBJECT_ID(N'dbo.YardMovement_VSS_26040808', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_VSS_26040808;
GO

CREATE TABLE dbo.YardMovement_VSS_26040808 (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [SourceSheet] NVARCHAR(50) NOT NULL,
    [METHOD] NVARCHAR(50) NULL,
    [OPERATION_METHOD] NVARCHAR(50) NULL,
    [EXEC_TS] DATETIME2 NULL,
    [LINE] NVARCHAR(50) NULL,
    [AGENT] NVARCHAR(50) NULL,
    [KHACHHANG] NVARCHAR(255) NULL,
    [ITEM_KEY] NVARCHAR(50) NULL,
    [SOCONT] NVARCHAR(50) NULL,
    [KICHCO] NVARCHAR(20) NULL,
    [PORT_GRADE] NVARCHAR(20) NULL,
    [LINE_GRADE] NVARCHAR(20) NULL,
    [TRANGTHAI] NVARCHAR(20) NULL,
    [TRONGLUONG] DECIMAL(18,4) NULL,
    [TRONGLUONG_VGM] DECIMAL(18,4) NULL,
    [BL_NO] NVARCHAR(100) NULL,
    [BOOK_NO] NVARCHAR(100) NULL,
    [RELEASE_NO] NVARCHAR(100) NULL,
    [HUONG] NVARCHAR(50) NULL,
    [HUONG1] NVARCHAR(50) NULL,
    [CANGCT] NVARCHAR(50) NULL,
    [CANGDEN] NVARCHAR(50) NULL,
    [GIAO] NVARCHAR(100) NULL,
    [NHAN] NVARCHAR(100) NULL,
    [DGS_CLASS] NVARCHAR(50) NULL,
    [GHICHU] NVARCHAR(1000) NULL,
    [ENTRY_VOY_NO] NVARCHAR(50) NULL,
    [ENTRY_VES_NAME] NVARCHAR(100) NULL,
    [EXIT_VOY_NO] NVARCHAR(50) NULL,
    [EXIT_VES_NAME] NVARCHAR(100) NULL,
    [ENTRY_TRUCK_ID] NVARCHAR(50) NULL,
    [EXIT_TRUCK_ID] NVARCHAR(50) NULL,
    [SOSEAL] NVARCHAR(50) NULL,
    [STORAGEDAY] INT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* 4) DLRP_AMS26040816.XLS (XML Spreadsheet) */
IF OBJECT_ID(N'dbo.YardMovement_AMS_26040816', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_AMS_26040816;
GO

CREATE TABLE dbo.YardMovement_AMS_26040816 (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [METHOD] NVARCHAR(50) NULL,
    [EXEC_TS] DATETIME2 NULL,
    [LINE] NVARCHAR(50) NULL,
    [ITEM_KEY] NVARCHAR(50) NULL,
    [SOCONT] NVARCHAR(50) NULL,
    [KICHCO] NVARCHAR(20) NULL,
    [TRANGTHAI] NVARCHAR(20) NULL,
    [TRONGLUONG] DECIMAL(18,4) NULL,
    [TRONGLUONG_VGM] DECIMAL(18,4) NULL,
    [BL_NO] NVARCHAR(100) NULL,
    [BOOK_NO] NVARCHAR(100) NULL,
    [RELEASE_NO] NVARCHAR(100) NULL,
    [HUONG] NVARCHAR(50) NULL,
    [HUONG1] NVARCHAR(50) NULL,
    [CANGCT] NVARCHAR(50) NULL,
    [CANGDEN] NVARCHAR(50) NULL,
    [GIAO] NVARCHAR(100) NULL,
    [NHAN] NVARCHAR(100) NULL,
    [DGS_CLASS] NVARCHAR(50) NULL,
    [GHICHU] NVARCHAR(1000) NULL,
    [ENTRY_VOY_NO] NVARCHAR(50) NULL,
    [ENTRY_VES_NAME] NVARCHAR(100) NULL,
    [EXIT_VOY_NO] NVARCHAR(50) NULL,
    [EXIT_VES_NAME] NVARCHAR(100) NULL,
    [ENTRY_TRUCK_ID] NVARCHAR(50) NULL,
    [EXIT_TRUCK_ID] NVARCHAR(50) NULL,
    [SOSEAL] NVARCHAR(50) NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
