-- 8.3.4 Import Yard Movement CatLai
-- Drop old AMS test tables and recreate with names that match menu 8.3.4.
-- Data is discarded on purpose.

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.YardMovement_AMS_26040816_Current_In_Yard2', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_AMS_26040816_Current_In_Yard2;
GO

IF OBJECT_ID(N'dbo.YardMovement_AMS_26040816_Imp', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_AMS_26040816_Imp;
GO

IF OBJECT_ID(N'dbo.YardMovement_AMS_26040816_Exp', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_AMS_26040816_Exp;
GO

IF OBJECT_ID(N'dbo.YardMovement_AMS_26040816', N'U') IS NOT NULL
    DROP TABLE dbo.YardMovement_AMS_26040816;
GO

IF OBJECT_ID(N'dbo.M_YardMovement_AMS_26040816_Current_In_Yard2', N'U') IS NOT NULL
    DROP TABLE dbo.M_YardMovement_AMS_26040816_Current_In_Yard2;
GO

IF OBJECT_ID(N'dbo.M_8_3_IN_OUT_YARD_1', N'U') IS NOT NULL
    DROP TABLE dbo.M_8_3_IN_OUT_YARD_1;
GO

IF OBJECT_ID(N'dbo.[8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard];
GO

IF OBJECT_ID(N'dbo.[8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard]', N'U') IS NOT NULL
    DROP TABLE dbo.[8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard];
GO

CREATE TABLE dbo.[8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard] PRIMARY KEY DEFAULT NEWID(),
    [DEPOT] NVARCHAR(100) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [AGENT] NVARCHAR(100) NULL,
    [LINE] NVARCHAR(50) NULL,
    [ITEM_KEY] NVARCHAR(50) NULL,
    [ITEM_NO] NVARCHAR(50) NULL,
    [ISO] NVARCHAR(20) NULL,
    [FEL] NVARCHAR(20) NULL,
    [TEMP] DECIMAL(18,4) NULL,
    [WEIGHT] DECIMAL(18,4) NULL,
    [VGM_WEIGHT] DECIMAL(18,4) NULL,
    [BOOK_NO] NVARCHAR(100) NULL,
    [BILL_OF_LADING] NVARCHAR(100) NULL,
    [LOCATION] NVARCHAR(200) NULL,
    [CATEGORY] NVARCHAR(50) NULL,
    [ARR_BY] NVARCHAR(50) NULL,
    [ARR_CAR] NVARCHAR(100) NULL,
    [ARR_VES_NAME] NVARCHAR(100) NULL,
    [ARR_TS] DATETIME2 NULL,
    [DEP_BY] NVARCHAR(50) NULL,
    [DEP_CAR] NVARCHAR(100) NULL,
    [DEP_VES_NAME] NVARCHAR(100) NULL,
    [DEP_TS] DATETIME2 NULL,
    [DISCH_PORT] NVARCHAR(50) NULL,
    [FINAL_DISCH_PORT] NVARCHAR(50) NULL,
    [PLACE_OF_RECEIPT] NVARCHAR(100) NULL,
    [PLACE_OF_DELIVERY] NVARCHAR(100) NULL,
    [CUSTOM_CLEARANCE] NVARCHAR(100) NULL,
    [CC_TS] DATETIME2 NULL,
    [DGS_CLASS] NVARCHAR(50) NULL,
    [UN_NO] NVARCHAR(50) NULL,
    [DAM] NVARCHAR(100) NULL,
    [GHICHU] NVARCHAR(1000) NULL,
    [SOSEAL] NVARCHAR(50) NULL,
    [DateImport] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_4_CatLai_Current_In_Yard_DateImport] DEFAULT SYSUTCDATETIME(),
    [UserImport] NVARCHAR(100) NULL,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_4_CatLai_Current_In_Yard_CreatedAt] DEFAULT SYSUTCDATETIME()
);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_4_CatLai_Current_In_Yard_ITEM_NO]
    ON dbo.[8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard] ([ITEM_NO]);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_4_CatLai_Current_In_Yard_DepotId]
    ON dbo.[8_3_4_Import_Yard_Movement_CatLai_Current_In_Yard] ([DepotId]);
GO

CREATE TABLE dbo.[8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [PK_8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard] PRIMARY KEY DEFAULT NEWID(),
    [DEPOT] NVARCHAR(100) NULL,
    [DepotId] UNIQUEIDENTIFIER NULL,
    [METHOD] NVARCHAR(50) NULL,
    [EXEC_TS] DATETIME2 NULL,
    [LINE] NVARCHAR(50) NULL,
    [ITEM_KEY] NVARCHAR(50) NULL,
    [SOCONT] NVARCHAR(50) NULL,
    [KICHCO] NVARCHAR(20) NULL,
    [TRANGTHAI] NVARCHAR(20) NULL,
    [TRONGLUONG] DECIMAL(18,4) NULL,
    [TRONGLUONG_VGM] DECIMAL(18,4) NULL,
    [BL_NO] NVARCHAR(100) NULL,
    [BOOK_NO] NVARCHAR(100) NULL,
    [RELEASE_NO] NVARCHAR(100) NULL,
    [HUONG] NVARCHAR(50) NULL,
    [HUONG1] NVARCHAR(50) NULL,
    [CANGCT] NVARCHAR(50) NULL,
    [CANGDEN] NVARCHAR(50) NULL,
    [GIAO] NVARCHAR(100) NULL,
    [NHAN] NVARCHAR(100) NULL,
    [DGS_CLASS] NVARCHAR(50) NULL,
    [GHICHU] NVARCHAR(1000) NULL,
    [ENTRY_VOY_NO] NVARCHAR(50) NULL,
    [ENTRY_VES_NAME] NVARCHAR(100) NULL,
    [EXIT_VOY_NO] NVARCHAR(50) NULL,
    [EXIT_VES_NAME] NVARCHAR(100) NULL,
    [ENTRY_TRUCK_ID] NVARCHAR(50) NULL,
    [EXIT_TRUCK_ID] NVARCHAR(50) NULL,
    [SOSEAL] NVARCHAR(50) NULL,
    [DateImport] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_4_CatLai_In_Out_Yard_DateImport] DEFAULT SYSUTCDATETIME(),
    [UserImport] NVARCHAR(100) NULL,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [DF_8_3_4_CatLai_In_Out_Yard_CreatedAt] DEFAULT SYSUTCDATETIME()
);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_4_CatLai_In_Out_Yard_SOCONT]
    ON dbo.[8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard] ([SOCONT]);
GO

CREATE NONCLUSTERED INDEX [IX_8_3_4_CatLai_In_Out_Yard_DepotId]
    ON dbo.[8_3_4_Import_Yard_Movement_CatLai_In_Out_Yard] ([DepotId]);
GO
