/*
  Add localization resources for Accounting Period Add/Edit UI updates
  Components:
    - AccountingPeriod_Index.razor (PeriodCode column title)
    - AccountingPeriod_AddEditDialog.razor (labels/helper/status options)
  Cultures: vi-VN, en-US, zh-CN
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

;WITH src AS (
    SELECT N'AccountingPeriod.PeriodCode' AS ResourceKey, N'vi-VN' AS Culture, N'Mã kỳ' AS Value UNION ALL
    SELECT N'AccountingPeriod.PeriodCode', N'en-US', N'Period Code' UNION ALL
    SELECT N'AccountingPeriod.PeriodCode', N'zh-CN', N'期间编码' UNION ALL

    SELECT N'AccountingPeriod.PeriodCodeAutoGenerated', N'vi-VN', N'Tự động tăng, không chỉnh sửa.' UNION ALL
    SELECT N'AccountingPeriod.PeriodCodeAutoGenerated', N'en-US', N'Auto-incremented, cannot be edited.' UNION ALL
    SELECT N'AccountingPeriod.PeriodCodeAutoGenerated', N'zh-CN', N'自动递增，不可编辑。' UNION ALL

    SELECT N'AccountingPeriod.Status.Open', N'vi-VN', N'Mở' UNION ALL
    SELECT N'AccountingPeriod.Status.Open', N'en-US', N'Open' UNION ALL
    SELECT N'AccountingPeriod.Status.Open', N'zh-CN', N'打开' UNION ALL

    SELECT N'AccountingPeriod.Status.Closed', N'vi-VN', N'Đóng' UNION ALL
    SELECT N'AccountingPeriod.Status.Closed', N'en-US', N'Closed' UNION ALL
    SELECT N'AccountingPeriod.Status.Closed', N'zh-CN', N'关闭' UNION ALL

    SELECT N'AccountingPeriod.Status.Locked', N'vi-VN', N'Khóa' UNION ALL
    SELECT N'AccountingPeriod.Status.Locked', N'en-US', N'Locked' UNION ALL
    SELECT N'AccountingPeriod.Status.Locked', N'zh-CN', N'锁定'
)
MERGE dbo.LocalizationResources AS tgt
USING src
ON tgt.ResourceKey = src.ResourceKey AND tgt.Culture = src.Culture
WHEN MATCHED THEN
    UPDATE SET Value = src.Value
WHEN NOT MATCHED BY TARGET THEN
    INSERT (ResourceKey, Culture, Value)
    VALUES (src.ResourceKey, src.Culture, src.Value);

COMMIT TRANSACTION;
PRINT N'ImportAccountingPeriod_588_AddEdit_LocalizationResources: done.';
