-- Import CHARGE from DANH MUC PHI.xlsx (from row 8)
-- Mapping: CHARGE_CODE=D, CHARGE=unit=C, DVT=B, APPROVE=CONTINUED=EDITABLE=1
SET NOCOUNT ON;
BEGIN TRAN;

INSERT INTO [dbo].[CHARGE] (
    [CHARGE_ID], [stt], [CHARGE_CODE], [CHARGE], [unit], [DVT],
    [APPROVE], [CONTINUED], [EDITABLE], [UPDATETIME]
)
VALUES
    (NEWID(), 1, N'S_ATHC', N'Phí xếp dỡ hàng', N'Phí xếp dỡ hàng', N'THC fee', 1, 1, 1, GETDATE()),
    (NEWID(), 2, N'S_ACIC', N'Phí Cân bằng container', N'Phí Cân bằng container', N'CIC fee', 1, 1, 1, GETDATE()),
    (NEWID(), 3, N'S_PSS', N'PSS FEE/PHỤ PHÍ', N'PSS FEE/PHỤ PHÍ', N'PSS', 1, 1, 1, GETDATE()),
    (NEWID(), 4, N'S_STORAGE', N'PHÍ LƯU KHO(CUS-STORAGE CHARGE)', N'PHÍ LƯU KHO(CUS-STORAGE CHARGE)', N'CUS-STORAGE CHARGE', 1, 1, 1, GETDATE()),
    (NEWID(), 5, N'B_AGENT FEE', N'PHI DAI LY', N'PHI DAI LY', N'AGENT FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 6, N'B_LOCAL', N'Phí local charge', N'Phí local charge', N'LOCAL CHARGE', 1, 1, 1, GETDATE()),
    (NEWID(), 7, N'S_ASLOT', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'Slot Fee', 1, 1, 1, GETDATE()),
    (NEWID(), 8, N'B_ASLOT', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'Slot fee', 1, 1, 1, GETDATE()),
    (NEWID(), 9, N'B_OF', N'CƯỚC VẬN TẢI QUỐC TẾ', N'CƯỚC VẬN TẢI QUỐC TẾ', N'Ocean freight', 1, 1, 1, GETDATE()),
    (NEWID(), 10, N'S_EBS', N'Phụ phí xăng dầu', N'Phụ phí xăng dầu', N'EBS', 1, 1, 1, GETDATE()),
    (NEWID(), 11, N'S_AFCT', N'Foreign Cooperate IncomeTax', N'Foreign Cooperate IncomeTax', N'Foreign Cooperate IncomeTax', 1, 1, 1, GETDATE()),
    (NEWID(), 12, N'B_AOF/THC', N'Ocean Freight Include THC', N'Ocean Freight Include THC', N'Ocean Freight Include THC', 1, 1, 1, GETDATE()),
    (NEWID(), 13, N'S_ASLOT', N'Slot fee', N'Slot fee', N'Slot fee', 1, 1, 1, GETDATE()),
    (NEWID(), 14, N'S_ACOM', N'Agent commission', N'Agent commission', N'Agent commission', 1, 1, 1, GETDATE()),
    (NEWID(), 15, N'S_AHDL', N'Phí dịch vụ', N'Phí dịch vụ', N'Handling fee', 1, 1, 1, GETDATE()),
    (NEWID(), 16, N'S_OFTHC', N'THU HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'THU HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'OF/ THC', 1, 1, 1, GETDATE()),
    (NEWID(), 17, N'S_TELEX', N'Phí Điện giao hàng', N'Phí Điện giao hàng', N'TELEX', 1, 1, 1, GETDATE()),
    (NEWID(), 18, N'S_OF', N'Cước vận tải quốc tế', N'Cước vận tải quốc tế', N'Ocean Freight', 1, 1, 1, GETDATE()),
    (NEWID(), 19, N'B_AOF', N'Cước vận tải quốc tế', N'Cước vận tải quốc tế', N'Ocean freight', 1, 1, 1, GETDATE()),
    (NEWID(), 20, N'S_ASEAL', N'Phí niêm chì', N'Phí niêm chì', N'Seal Fee', 1, 1, 1, GETDATE()),
    (NEWID(), 21, N'B_ASEAL', N'phí niêm chì', N'phí niêm chì', N'Seal Fee', 1, 1, 1, GETDATE()),
    (NEWID(), 22, N'S_BILL', N'Phí chứng từ hàng xuất', N'Phí chứng từ hàng xuất', N'BILL FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 23, N'B_BILL', N'Phí chứng từ hàng xuất', N'Phí chứng từ hàng xuất', N'BILL FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 24, N'S_TRUCKING', N'Cước vận chuyển nội địa', N'Cước vận chuyển nội địa', N'TRUCKING', 1, 1, 1, GETDATE()),
    (NEWID(), 25, N'B_TRUCKING', N'Cước vận chuyển nội địa', N'Cước vận chuyển nội địa', N'TRUCKING', 1, 1, 1, GETDATE()),
    (NEWID(), 26, N'S_CUS', N'Phí khai báo hải quan', N'Phí khai báo hải quan', N'CUSTOMS', 1, 1, 1, GETDATE()),
    (NEWID(), 27, N'B_ CUS', N'Phí khai báo hải quan', N'Phí khai báo hải quan', N'CUSTOMS', 1, 1, 1, GETDATE()),
    (NEWID(), 28, N'S_CLEAN', N'Vệ Sinh cont', N'Vệ Sinh cont', N'CLEAN FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 29, N'B_ATHC', N'Phí xếp dỡ', N'Phí xếp dỡ', N'THC', 1, 1, 1, GETDATE()),
    (NEWID(), 30, N'B_ACIC', N'Thu hộ phí Cân bằng container', N'Thu hộ phí Cân bằng container', N'CIC', 1, 1, 1, GETDATE()),
    (NEWID(), 31, N'S_FUMI', N'Phí hun trùng', N'Phí hun trùng', N'FUMI', 1, 1, 1, GETDATE()),
    (NEWID(), 32, N'B_FUMI', N'Phí hun trùng', N'Phí hun trùng', N'FUMI', 1, 1, 1, GETDATE()),
    (NEWID(), 33, N'S_PHYTO', N'phí kiểm dịch', N'phí kiểm dịch', N'PHYTO', 1, 1, 1, GETDATE()),
    (NEWID(), 34, N'B_PHYTO', N'Phí kiểm dịch', N'Phí kiểm dịch', N'PHYTO', 1, 1, 1, GETDATE()),
    (NEWID(), 35, N'S_BH', N'Phí bảo hiểm', N'Phí bảo hiểm', N'BH', 1, 1, 1, GETDATE()),
    (NEWID(), 36, N'B_BH', N'Phí bảo hiểm', N'Phí bảo hiểm', N'BH', 1, 1, 1, GETDATE()),
    (NEWID(), 37, N'S_C/O', N'Phí C/O', N'Phí C/O', N'C/O', 1, 1, 1, GETDATE()),
    (NEWID(), 38, N'B_ C/O', N'Phí C/O', N'Phí C/O', N'C/O', 1, 1, 1, GETDATE()),
    (NEWID(), 39, N'S_tlex', N'Phí Điện giao hàng', N'Phí Điện giao hàng', N'TELEX', 1, 1, 1, GETDATE()),
    (NEWID(), 40, N'B_Tlex', N'Phí điện giao hàng', N'Phí điện giao hàng', N'TELEX', 1, 1, 1, GETDATE()),
    (NEWID(), 41, N'S_HL', N'Phí đại lý', N'Phí đại lý', N'Phí đại lý', 1, 1, 1, GETDATE()),
    (NEWID(), 42, N'S_DO', N'Phí chứng từ hàng nhập', N'Phí chứng từ hàng nhập', N'Phí chứng từ hàng nhập', 1, 1, 1, GETDATE()),
    (NEWID(), 43, N'B_CFS', N'Phí bốc xếp', N'Phí bốc xếp', N'CFS', 1, 1, 1, GETDATE()),
    (NEWID(), 44, N'S_THC2', N'Thu hộ Phí làm hàng tại cảng', N'Thu hộ Phí làm hàng tại cảng', N'THC fee', 1, 1, 1, GETDATE()),
    (NEWID(), 45, N'S_CIC', N'Thu hộ Phí cân bằng cont', N'Thu hộ Phí cân bằng cont', N'CIC fee', 1, 1, 1, GETDATE()),
    (NEWID(), 46, N'B_DO', N'Phí chứng từ hàng nhập', N'Phí chứng từ hàng nhập', N'Phí chứng từ hàng nhập', 1, 1, 1, GETDATE()),
    (NEWID(), 47, N'S_VS', N'Phí vệ sinh cont', N'Phí vệ sinh cont', N'Phí vệ sinh cont', 1, 1, 1, GETDATE()),
    (NEWID(), 48, N'S_LOLO', N'Phí nâng hạ cont', N'Phí nâng hạ cont', N'LOLO', 1, 1, 1, GETDATE()),
    (NEWID(), 49, N'B_LOLO', N'Phí nâng ha cont', N'Phí nâng ha cont', N'LOLO', 1, 1, 1, GETDATE()),
    (NEWID(), 50, N'B_VGM', N'Phí cân cont', N'Phí cân cont', N'VGM', 1, 1, 1, GETDATE()),
    (NEWID(), 51, N'S_VGM', N'Phí cân cont', N'Phí cân cont', N'VGM', 1, 1, 1, GETDATE()),
    (NEWID(), 52, N'S_CFS', N'Phí bốc xếp', N'Phí bốc xếp', N'CFS', 1, 1, 1, GETDATE()),
    (NEWID(), 53, N'B_EXW', N'Cước Ex-work đầu nước ngoài', N'Cước Ex-work đầu nước ngoài', N'EX-WORK', 1, 1, 1, GETDATE()),
    (NEWID(), 54, N'S_Exw', N'Cước Ex-work đầu nước ngoài', N'Cước Ex-work đầu nước ngoài', N'Ex-WORK', 1, 1, 1, GETDATE()),
    (NEWID(), 55, N'S_CUOC', N'CƯỢC CONTAINER', N'CƯỢC CONTAINER', N'CƯỢC CONTAINER', 1, 1, 1, GETDATE()),
    (NEWID(), 56, N'B_CUOC', N'TRẢ CƯỢC CONT', N'TRẢ CƯỢC CONT', N'TRẢ CƯỢC CONT', 1, 1, 1, GETDATE()),
    (NEWID(), 57, N'S_GN', N'Thủ tục Hải Quan', N'Thủ tục Hải Quan', N'CUSTOMS CLEARNCE', 1, 1, 1, GETDATE()),
    (NEWID(), 58, N'B_AFR', N'Phí khai báo Hải Quan', N'Phí khai báo Hải Quan', N'AFR', 1, 1, 1, GETDATE()),
    (NEWID(), 59, N'S_ Cuoc', N'Cước VCQT', N'Cước VCQT', N'OF', 1, 1, 1, GETDATE()),
    (NEWID(), 60, N'S_ÐLY', N'PROFIT SHARE', N'PROFIT SHARE', N'PROFIT SHARE', 1, 1, 1, GETDATE()),
    (NEWID(), 61, N'S_ACE', N'Phí khai hải quan', N'Phí khai hải quan', N'ACE', 1, 1, 1, GETDATE()),
    (NEWID(), 62, N'S_Deposit', N'Phí cược cont', N'Phí cược cont', N'DEPOSIT', 1, 1, 1, GETDATE()),
    (NEWID(), 63, N'B_DEPOSIT', N'Trả cược cont', N'Trả cược cont', N'DEPOSIT', 1, 1, 1, GETDATE()),
    (NEWID(), 64, N'B_COMCUS', N'Hoa Hồng Khách Hàng', N'Hoa Hồng Khách Hàng', N'Com', 1, 1, 1, GETDATE()),
    (NEWID(), 65, N'S_DMR', N'Thu hộ phí lưu cont', N'Thu hộ phí lưu cont', N'Thu hộ phí lưu cont', 1, 1, 1, GETDATE()),
    (NEWID(), 66, N'B_EBS', N'Phụ phí xăng dầu', N'Phụ phí xăng dầu', N'EBS', 1, 1, 1, GETDATE()),
    (NEWID(), 67, N'S_KH', N'Phí kiểm hóa', N'Phí kiểm hóa', N'Kiểm hóa', 1, 1, 1, GETDATE()),
    (NEWID(), 68, N'B_KH', N'Phí kiểm hóa', N'Phí kiểm hóa', N'Kiểm hóa', 1, 1, 1, GETDATE()),
    (NEWID(), 69, N'S_GN', N'Phí dịch vụ giao nhận', N'Phí dịch vụ giao nhận', N'GN', 1, 1, 1, GETDATE()),
    (NEWID(), 70, N'S_HCIC', N'Phí cân bằng cont', N'Phí cân bằng cont', N'CIC', 1, 1, 1, GETDATE()),
    (NEWID(), 71, N'B_HCIC', N'Phí cân bằng cont', N'Phí cân bằng cont', N'CIC', 1, 1, 1, GETDATE()),
    (NEWID(), 72, N'B_PPKC', N'PHỤ PHÍ KẸT CẢNG', N'PHỤ PHÍ KẸT CẢNG', N'PPHI', 1, 1, 1, GETDATE()),
    (NEWID(), 73, N'S_DTT', N'Thu hộ phí lưu vỏ', N'Thu hộ phí lưu vỏ', N'Thu hộ phí lưu vỏ', 1, 1, 1, GETDATE()),
    (NEWID(), 74, N'S_RP', N'RP- Phí Sửa chữa cont', N'RP- Phí Sửa chữa cont', N'REPAIR', 1, 1, 1, GETDATE()),
    (NEWID(), 75, N'B_RP', N'RP- Phí  Sửa chữa cont', N'RP- Phí  Sửa chữa cont', N'REPAIR', 1, 1, 1, GETDATE()),
    (NEWID(), 76, N'S_AFR', N'Phí khai báo Hải Quan', N'Phí khai báo Hải Quan', N'AFR', 1, 1, 1, GETDATE()),
    (NEWID(), 77, N'S_ASTORAGE', N'Phí lưu tại cảng', N'Phí lưu tại cảng', N'Storage charges', 1, 1, 1, GETDATE()),
    (NEWID(), 78, N'S_AF', N'Cước VCQT  hàng không', N'Cước VCQT  hàng không', N'Air Freight', 1, 1, 1, GETDATE()),
    (NEWID(), 79, N'S_AN', N'Phí an ninh tàu và cảng', N'Phí an ninh tàu và cảng', N'PHÍ AN NINH', 1, 1, 1, GETDATE()),
    (NEWID(), 80, N'B_AN', N'Phí an ninh tàu và cảng', N'Phí an ninh tàu và cảng', N'PHÍ AN NINH', 1, 1, 1, GETDATE()),
    (NEWID(), 81, N'S_ADEM', N'Demurrage', N'Demurrage', N'Demurrage', 1, 1, 1, GETDATE()),
    (NEWID(), 82, N'S_ADET', N'Detention', N'Detention', N'Detention', 1, 1, 1, GETDATE()),
    (NEWID(), 83, N'S_ACFDD', N'Commission for Dem/Det', N'Commission for Dem/Det', N'Commission DEM/DET', 1, 1, 1, GETDATE()),
    (NEWID(), 84, N'S_AMEND', N'Phí chỉnh sửa bill', N'Phí chỉnh sửa bill', N'Amend charges', 1, 1, 1, GETDATE()),
    (NEWID(), 85, N'S_HL', N'Phí đại lý', N'Phí đại lý', N'Phí đại lý', 1, 1, 1, GETDATE()),
    (NEWID(), 86, N'S_PLH', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', 1, 1, 1, GETDATE()),
    (NEWID(), 87, N'B_THC2', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', 1, 1, 1, GETDATE()),
    (NEWID(), 88, N'FD1709017', N'Cước vận chuyển air', N'Cước vận chuyển air', N'AIR', 1, 1, 1, GETDATE()),
    (NEWID(), 89, N'B_VS', N'Phí vệ sinh', N'Phí vệ sinh', N'Phí vệ sinh', 1, 1, 1, GETDATE()),
    (NEWID(), 90, N'B_AOFCIC', N'Ocean freight inlude CIC', N'Ocean freight inlude CIC', N'Ocean freight inlude CIC', 1, 1, 1, GETDATE()),
    (NEWID(), 91, N'S_RF', N'REFUND SALE HÃNG TÀU', N'REFUND SALE HÃNG TÀU', N'REFUND SALE HÃNG TÀU', 1, 1, 1, GETDATE()),
    (NEWID(), 92, N'B_RF', N'REFUND SALE HÃNG TÀU', N'REFUND SALE HÃNG TÀU', N'REFUND SALE HÃNG TÀU', 1, 1, 1, GETDATE()),
    (NEWID(), 93, N'B_ACOM', N'Agent commission', N'Agent commission', N'Agent commission', 1, 1, 1, GETDATE()),
    (NEWID(), 94, N'B_BILL(2)', N'Phụ phí chỉnh sửa vận đơn', N'Phụ phí chỉnh sửa vận đơn', N'Phụ phí chỉnh sửa vận đơn', 1, 1, 1, GETDATE()),
    (NEWID(), 95, N'B_CIC', N'phí cân bằng Cont', N'phí cân bằng Cont', N'CIC Fee', 1, 1, 1, GETDATE()),
    (NEWID(), 96, N'B_ADEM', N'Demurrage', N'Demurrage', N'Demurrage', 1, 1, 1, GETDATE()),
    (NEWID(), 97, N'B_ADET', N'Detention', N'Detention', N'Detention', 1, 1, 1, GETDATE()),
    (NEWID(), 98, N'B_APCS', N'PCS fee', N'PCS fee', N'PCS fee', 1, 1, 1, GETDATE()),
    (NEWID(), 99, N'B_LUU BAI', N'Phí lưu bãi', N'Phí lưu bãi', N'Storage charge', 1, 1, 1, GETDATE()),
    (NEWID(), 100, N'B_H/L', N'HANDING FEE', N'HANDING FEE', N'handling fee', 1, 1, 1, GETDATE()),
    (NEWID(), 101, N'S_THCTH', N'Thu hộ Phụ phí dịch vụ xếp dỡ container (THC)', N'Thu hộ Phụ phí dịch vụ xếp dỡ container (THC)', N'Thu hộ Phụ phí dịch vụ xếp dỡ container (THC)', 1, 1, 1, GETDATE()),
    (NEWID(), 102, N'S_CICTH', N'Thu hộ Phụ phí mất cân bằng container', N'Thu hộ Phụ phí mất cân bằng container', N'Thu hộ Phí cân bằng cont', 1, 1, 1, GETDATE()),
    (NEWID(), 103, N'S_SB', N'SWITCH BILL', N'SWITCH BILL', N'SWITCH BILL', 1, 1, 1, GETDATE()),
    (NEWID(), 104, N'B_TELEX', N'Phí điện giao hàng', N'Phí điện giao hàng', N'TELEX', 1, 1, 1, GETDATE()),
    (NEWID(), 105, N'B_DMR', N'Phí lưu cont', N'Phí lưu cont', N'DMR', 1, 1, 1, GETDATE()),
    (NEWID(), 106, N'S_QN', N'Cước vận chuyển quốc nội', N'Cước vận chuyển quốc nội', N'CVQN/Cước Chuyển quốc nội', 1, 1, 1, GETDATE()),
    (NEWID(), 107, N'S_X-RAY', N'PHÍ SOI', N'PHÍ SOI', N'X - RAY', 1, 1, 1, GETDATE()),
    (NEWID(), 108, N'S_AMS', N'Phí khai HQ AMS', N'Phí khai HQ AMS', N'AMS', 1, 1, 1, GETDATE()),
    (NEWID(), 109, N'B_OF QN', N'Cước vận chuyển quốc nội', N'Cước vận chuyển quốc nội', N'OF Quốc Nội', 1, 1, 1, GETDATE()),
    (NEWID(), 110, N'S_AIR', N'Phí chứng từ hàng AIR', N'Phí chứng từ hàng AIR', N'AWB', 1, 1, 1, GETDATE()),
    (NEWID(), 111, N'B_AIR', N'Phí tách bill Air', N'Phí tách bill Air', N'PHÍ TÁCH BILL AIR', 1, 1, 1, GETDATE()),
    (NEWID(), 112, N'S_PCS', N'Phí tắc nghẽn', N'Phí tắc nghẽn', N'Phí tắc nghẽn', 1, 1, 1, GETDATE()),
    (NEWID(), 113, N'B_PCS', N'Phí tắc nghẽn', N'Phí tắc nghẽn', N'Phí tắc nghẽn', 1, 1, 1, GETDATE()),
    (NEWID(), 114, N'S_POWER', N'Phí cắm điện', N'Phí cắm điện', N'Phí cắm điện', 1, 1, 1, GETDATE()),
    (NEWID(), 115, N'B_AIR', N'Phí khai AMS', N'Phí khai AMS', N'AMS FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 116, N'B_AIR', N'Phí khai hàng DG', N'Phí khai hàng DG', N'DG FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 117, N'B_AIR', N'Thùng DG', N'Thùng DG', N'UNI BOX', 1, 1, 1, GETDATE()),
    (NEWID(), 118, N'S_TRP', N'Tạm thu sửa chữa', N'Tạm thu sửa chữa', N'TAM THU SUA CHUA', 1, 1, 1, GETDATE()),
    (NEWID(), 119, N'B_TRP', N'Trả lại tạm thu sửa chữa', N'Trả lại tạm thu sửa chữa', N'SUA CHUA', 1, 1, 1, GETDATE()),
    (NEWID(), 120, N'FD1801001', N'Thu hộ phí Salan', N'Thu hộ phí Salan', N'Thu hộ phí Salan', 1, 1, 1, GETDATE()),
    (NEWID(), 121, N'B_AEMP', N'Chi hộ cước VCQT', N'Chi hộ cước VCQT', N'EMPTY REPO', 1, 1, 1, GETDATE()),
    (NEWID(), 122, N'S_AEmpty', N'Empty Repo', N'Empty Repo', N'Empty Repo', 1, 1, 1, GETDATE()),
    (NEWID(), 123, N'S_ERC', N'Phụ phí rủi ro hàng nhập', N'Phụ phí rủi ro hàng nhập', N'ERC', 1, 1, 1, GETDATE()),
    (NEWID(), 124, N'S_THCCOC', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', N'Phí làm hàng tại cảng', 1, 1, 1, GETDATE()),
    (NEWID(), 125, N'S_CICCOC', N'Phí cân bằng cont', N'Phí cân bằng cont', N'Phí cân bằng cont', 1, 1, 1, GETDATE()),
    (NEWID(), 126, N'S_ACUSTOMS', N'Customs fee', N'Customs fee', N'Customs fee', 1, 1, 1, GETDATE()),
    (NEWID(), 127, N'S_APO', N'Phí cắm điện', N'Phí cắm điện', N'Plugin Cost', 1, 1, 1, GETDATE()),
    (NEWID(), 128, N'S_BUC', N'Phụ phí cước tàu', N'Phụ phí cước tàu', N'BUC', 1, 1, 1, GETDATE()),
    (NEWID(), 129, N'B_BUC', N'Phụ phí cước tàu', N'Phụ phí cước tàu', N'BUC', 1, 1, 1, GETDATE()),
    (NEWID(), 130, N'S_OFT', N'Thu hộ cước vận chuyển quốc tế', N'Thu hộ cước vận chuyển quốc tế', N'Thu hộ cước vận chuyển quốc tế', 1, 1, 1, GETDATE()),
    (NEWID(), 131, N'B_OFT', N'Thu hộ cước vận chuyển quốc tế', N'Thu hộ cước vận chuyển quốc tế', N'Thu hộ cước vận chuyển quốc tế', 1, 1, 1, GETDATE()),
    (NEWID(), 132, N'S_ALeasing', N'Leasing fee', N'Leasing fee', N'Leasing fee', 1, 1, 1, GETDATE()),
    (NEWID(), 133, N'S_ATHCPORT', N'Stevedore charge', N'Stevedore charge', N'Stevedore charge', 1, 1, 1, GETDATE()),
    (NEWID(), 134, N'B_AMEND', N'Phí chỉnh sửa bill', N'Phí chỉnh sửa bill', N'AMEND', 1, 1, 1, GETDATE()),
    (NEWID(), 135, N'FD1807003', N'Phí ecrs', N'Phí ecrs', N'ECRS', 1, 1, 1, GETDATE()),
    (NEWID(), 136, N'S_ARP', N'Phí sửa chữa', N'Phí sửa chữa', N'Repair fee', 1, 1, 1, GETDATE()),
    (NEWID(), 137, N'S_RMS', N'Phí bảo trì cont lạnh', N'Phí bảo trì cont lạnh', N'Phí bảo trì cont lạnh', 1, 1, 1, GETDATE()),
    (NEWID(), 138, N'S_EBS', N'Phụ phí xăng dầu', N'Phụ phí xăng dầu', N'Phụ phí xăng dầu', 1, 1, 1, GETDATE()),
    (NEWID(), 139, N'B_AVS', N'Phí vệ sinh', N'Phí vệ sinh', N'Cleaning fee', 1, 1, 1, GETDATE()),
    (NEWID(), 140, N'S_BCLEANING', N'Phí vệ sinh', N'Phí vệ sinh', N'Cleaning fee', 1, 1, 1, GETDATE()),
    (NEWID(), 141, N'S_CRC', N'Thu hộ Phụ phí hàng nhập', N'Thu hộ Phụ phí hàng nhập', N'Thu hộ Phụ phí hàng nhập', 1, 1, 1, GETDATE()),
    (NEWID(), 142, N'FD1810002', N'Locally fee', N'Locally fee', N'Locally fee', 1, 1, 1, GETDATE()),
    (NEWID(), 143, N'S_TALLY', N'Phí kiểm đếm', N'Phí kiểm đếm', N'Phí kiểm đếm', 1, 1, 1, GETDATE()),
    (NEWID(), 144, N'B_FM', N'Phí hun trùng', N'Phí hun trùng', N'HUN TRUNG', 1, 1, 1, GETDATE()),
    (NEWID(), 145, N'S_FM', N'Phí hun trùng', N'Phí hun trùng', N'HUN TRUNG', 1, 1, 1, GETDATE()),
    (NEWID(), 146, N'B_Phyto', N'Phí kiểm dịch', N'Phí kiểm dịch', N'KIEM DICH', 1, 1, 1, GETDATE()),
    (NEWID(), 147, N'S_Phyto', N'Phí kiểm dịch', N'Phí kiểm dịch', N'KIEM DICH', 1, 1, 1, GETDATE()),
    (NEWID(), 148, N'B_INS', N'Phí bảo hiểm', N'Phí bảo hiểm', N'BAO HIEM', 1, 1, 1, GETDATE()),
    (NEWID(), 149, N'S_INS', N'Phí bảo hiểm', N'Phí bảo hiểm', N'BAO HIEM', 1, 1, 1, GETDATE()),
    (NEWID(), 150, N'B_CO', N'Phí C/O', N'Phí C/O', N'C/O', 1, 1, 1, GETDATE()),
    (NEWID(), 151, N'S_ CO', N'Phí C/O', N'Phí C/O', N'C/O', 1, 1, 1, GETDATE()),
    (NEWID(), 152, N'B_ HQ', N'Phí hải quan', N'Phí hải quan', N'HAI QUAN', 1, 1, 1, GETDATE()),
    (NEWID(), 153, N'S_ HQ', N'Phí hải quan', N'Phí hải quan', N'HAI QUAN', 1, 1, 1, GETDATE()),
    (NEWID(), 154, N'B_RF', N'REFUND', N'REFUND', N'REFUND', 1, 1, 1, GETDATE()),
    (NEWID(), 155, N'S_RF', N'REFUND', N'REFUND', N'REFUND', 1, 1, 1, GETDATE()),
    (NEWID(), 156, N'S_APTI', N'PreTrip Inspection Cost', N'PreTrip Inspection Cost', N'PTI', 1, 1, 1, GETDATE()),
    (NEWID(), 157, N'B_CERT', N'Certificate Issuance Fee', N'Certificate Issuance Fee', N'CERT', 1, 1, 1, GETDATE()),
    (NEWID(), 158, N'S_CERT', N'Certificate Issuance Fee', N'Certificate Issuance Fee', N'CERT', 1, 1, 1, GETDATE()),
    (NEWID(), 159, N'B_CN', N'Phí in chứng nhận tuổi tầu', N'Phí in chứng nhận tuổi tầu', N'chứng nhận', 1, 1, 1, GETDATE()),
    (NEWID(), 160, N'S_CN', N'Phí in chứng nhận tuổi tầu', N'Phí in chứng nhận tuổi tầu', N'Chứng nhận', 1, 1, 1, GETDATE()),
    (NEWID(), 161, N'S_BEQ', NULL, NULL, N'EQUPMENT MAINTANENCE', 1, 1, 1, GETDATE()),
    (NEWID(), 162, N'S_AVS', N'Phí vệ sinh', N'Phí vệ sinh', N'Cleaning fee', 1, 1, 1, GETDATE()),
    (NEWID(), 163, N'B_SEC', N'Special Equipment charge', N'Special Equipment charge', N'Special Equipment charge', 1, 1, 1, GETDATE()),
    (NEWID(), 164, N'B_ASEC', N'PHI ISPS', N'PHI ISPS', N'ISPS', 1, 1, 1, GETDATE()),
    (NEWID(), 165, N'B_Asec', N'PHI Adim', N'PHI Adim', N'ADMIN', 1, 1, 1, GETDATE()),
    (NEWID(), 166, N'B_Asec', N'PHI CMC', N'PHI CMC', N'CMC', 1, 1, 1, GETDATE()),
    (NEWID(), 167, N'B - BAF', N'PHỤ PHÍ NHIÊN LIÊU', N'PHỤ PHÍ NHIÊN LIÊU', N'SLOT - BAF', 1, 1, 1, GETDATE()),
    (NEWID(), 168, N'B_BK', N'Phí nhiên liệu', N'Phí nhiên liệu', N'BK', 1, 1, 1, GETDATE()),
    (NEWID(), 169, N'S_ANBK', N'Phí nhiên liệu', N'Phí nhiên liệu', N'New Bunker Charge', 1, 1, 1, GETDATE()),
    (NEWID(), 170, N'B_BNBK', N'Phí nhiên liệu', N'Phí nhiên liệu', N'New Bunker Charge', 1, 1, 1, GETDATE()),
    (NEWID(), 171, N'S_ALSS', N'Phí nhiên liệu', N'Phí nhiên liệu', N'Low Sulphur Surcharges', 1, 1, 1, GETDATE()),
    (NEWID(), 172, N'B_LSS', N'Phụ phí nhiên liệu', N'Phụ phí nhiên liệu', N'LSS', 1, 1, 1, GETDATE()),
    (NEWID(), 173, N'B_ASLOT', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'CHI HỘ CƯỚC VẬN TẢI QUỐC TẾ', N'SLOT+ BAF', 1, 1, 1, GETDATE()),
    (NEWID(), 174, N'B_SCC', N'PHỤ PHÍ SCC', N'PHỤ PHÍ SCC', N'SCC FEE', 1, 1, 1, GETDATE()),
    (NEWID(), 175, N'B_POW', N'Phí cắm điện', N'Phí cắm điện', N'Phí cắm điện', 1, 1, 1, GETDATE()),
    (NEWID(), 176, N'S_PTI', N'Phí PTI container', N'Phí PTI container', N'PTI', 1, 1, 1, GETDATE()),
    (NEWID(), 177, N'B_PTI', N'Phí PTI container', N'Phí PTI container', N'PTI', 1, 1, 1, GETDATE()),
    (NEWID(), 178, N'B_CERT', N'Phí chứng nhận (Cert)', N'Phí chứng nhận (Cert)', N'Phi chung nhan', 1, 1, 1, GETDATE()),
    (NEWID(), 179, N'S_CERT', N'Phí chứng nhận (Cert)', N'Phí chứng nhận (Cert)', N'Phi chung nhan', 1, 1, 1, GETDATE()),
    (NEWID(), 180, N'B_MONITORING', N'Phí vận hành cont lạnh', N'Phí vận hành cont lạnh', N'MONITORING', 1, 1, 1, GETDATE()),
    (NEWID(), 181, N'B_NANG VO', N'Phí nâng vỏ', N'Phí nâng vỏ', N'Phí nâng vỏ', 1, 1, 1, GETDATE()),
    (NEWID(), 182, N'B_Shipside', N'Phí shipside', N'Phí shipside', N'Phí shipside', 1, 1, 1, GETDATE());

-- Imported 182 rows, skipped empty: 0
COMMIT;
-- ROLLBACK; -- dung de test, comment COMMIT o tren neu can rollback