-- Menu 5: Payment (Shipment 5.0, DNTT, Reports, Invoice, Accounting)
BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    'NothingToSearch','NothingToFind','NothingToExport','SelectOneData','SelectSearchCondition',
    'CreditApproved','InvoiceApproved','SelectAtLeastOneInvoiceRow','CustomerGroupMismatch',
    'DNTT_Shipping_Create','DNTT_Shipping_Edit','DNTT_Shipping_Duplicate',
    'DNTT_VendorOther_Create','DNTT_VendorOther_Edit','DNTT_VendorOther_Duplicate',
    'FromToDate','THCN_Subtitle','PaymentReport_Subtitle','Shipment5_Subtitle',
    'MblApproved','HblApproved','DebitApproved','SelectOneHbl','SelectOneRowHbl','SelectOneRowMbl',
    'GeneralJournal_Title','GeneralJournal_Subtitle','FromDate','ToDate','FilterData',
    'GeneralJournal_TotalRows','GeneralJournal_TotalDebit','GeneralJournal_TotalCredit','GeneralJournal_Difference',
    'GeneralJournal_PostingDate','GeneralJournal_VoucherDate','GeneralJournal_VoucherNo','GeneralJournal_TransactionType',
    'GeneralJournal_Description','GeneralJournal_Object','GeneralJournal_DebitAccount','GeneralJournal_CreditAccount',
    'GeneralJournal_ForeignAmount','GeneralJournal_AmountVnd','GeneralJournal_UpdatedBy','GeneralJournal_UpdatedDate',
    'GeneralJournal_StatusDraft','GeneralJournal_StatusPosted','GeneralJournal_StatusCancelled','GeneralJournal_StatusUnknown',
    'GeneralJournal_LoadedRows',
    'Viettel_Subtitle','Viettel_UseDefaultJson','Configuration','DateTimeRange','Viettel_InvoiceActions',
    'Viettel_CreateDraftInvoice','Viettel_CreateInvoice','Viettel_DownloadPdf','SearchConditions','Apply','Exit',
    'Viettel_FormNo','Viettel_InvoiceSeries','Viettel_EnterTaxCode','SelectAtLeastOneRow',
    'Viettel_AlreadyHasInvoiceNo','Viettel_RequireInternalInvoiceNo','Viettel_SameInternalInvoiceNo',
    'Viettel_AccessTokenFailed','Viettel_ApiError','Viettel_DraftCreatedSuccess','Viettel_ConfigLoginRequired'
);

INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('NothingToSearch','en-US',N'Nothing to search.'),('NothingToSearch','vi-VN',N'Không có gì để tìm.'),('NothingToSearch','zh-CN',N'没有可搜索的内容。'),
('NothingToFind','en-US',N'Nothing found.'),('NothingToFind','vi-VN',N'Không tìm thấy.'),('NothingToFind','zh-CN',N'未找到结果。'),
('NothingToExport','en-US',N'Nothing to export.'),('NothingToExport','vi-VN',N'Không có gì để xuất.'),('NothingToExport','zh-CN',N'没有可导出的内容。'),
('SelectOneData','en-US',N'You must select one record.'),('SelectOneData','vi-VN',N'Bạn phải chọn 1 dòng dữ liệu.'),('SelectOneData','zh-CN',N'请选择一条记录。'),
('SelectSearchCondition','en-US',N'Please select a search condition.'),('SelectSearchCondition','vi-VN',N'Chọn điều kiện search.'),('SelectSearchCondition','zh-CN',N'请选择搜索条件。'),
('CreditApproved','en-US',N'This credit is approved.'),('CreditApproved','vi-VN',N'Credit đã được approve.'),('CreditApproved','zh-CN',N'此贷记已审批。'),
('InvoiceApproved','en-US',N'This invoice is approved.'),('InvoiceApproved','vi-VN',N'Invoice đã được approve.'),('InvoiceApproved','zh-CN',N'此发票已审批。'),
('SelectAtLeastOneInvoiceRow','en-US',N'Please select at least one invoice row.'),('SelectAtLeastOneInvoiceRow','vi-VN',N'Bạn phải chọn ít nhất một dòng hóa đơn!'),('SelectAtLeastOneInvoiceRow','zh-CN',N'请至少选择一行发票。'),
('CustomerGroupMismatch','en-US',N'Customer group mismatch in selection.'),('CustomerGroupMismatch','vi-VN',N'Có sự khác biệt trong nhóm Customer.'),('CustomerGroupMismatch','zh-CN',N'所选客户分组不一致。'),
('DNTT_Shipping_Create','en-US',N'Payment Request — Create'),('DNTT_Shipping_Create','vi-VN',N'Payment Request — Tạo mới'),('DNTT_Shipping_Create','zh-CN',N'付款申请 — 新建'),
('DNTT_Shipping_Edit','en-US',N'Payment Request — Edit'),('DNTT_Shipping_Edit','vi-VN',N'Payment Request — Sửa'),('DNTT_Shipping_Edit','zh-CN',N'付款申请 — 编辑'),
('DNTT_Shipping_Duplicate','en-US',N'Payment Request — Duplicate'),('DNTT_Shipping_Duplicate','vi-VN',N'Payment Request — Nhân bản'),('DNTT_Shipping_Duplicate','zh-CN',N'付款申请 — 复制'),
('DNTT_VendorOther_Create','en-US',N'Payment Request (Other Vendor) — Create'),('DNTT_VendorOther_Create','vi-VN',N'Payment Request To Vendor Other — Tạo mới'),('DNTT_VendorOther_Create','zh-CN',N'其他供应商付款申请 — 新建'),
('DNTT_VendorOther_Edit','en-US',N'Payment Request (Other Vendor) — Edit'),('DNTT_VendorOther_Edit','vi-VN',N'Payment Request To Vendor Other — Sửa'),('DNTT_VendorOther_Edit','zh-CN',N'其他供应商付款申请 — 编辑'),
('DNTT_VendorOther_Duplicate','en-US',N'Payment Request (Other) — Duplicate'),('DNTT_VendorOther_Duplicate','vi-VN',N'Payment Request Other — Nhân bản'),('DNTT_VendorOther_Duplicate','zh-CN',N'其他付款申请 — 复制'),
('FromToDate','en-US',N'From — To date'),('FromToDate','vi-VN',N'Từ — Đến ngày'),('FromToDate','zh-CN',N'起止日期'),
('THCN_Subtitle','en-US',N'Outstanding balances by HBL / invoice'),('THCN_Subtitle','vi-VN',N'Công nợ theo HBL / invoice'),('THCN_Subtitle','zh-CN',N'按 HBL/发票的未结余额'),
('PaymentReport_Subtitle','en-US',N'AR / payment status & aging'),('PaymentReport_Subtitle','vi-VN',N'Báo cáo công nợ & aging'),('PaymentReport_Subtitle','zh-CN',N'应收/账龄报告'),
('Shipment5_Subtitle','en-US',N'Manage jobs, MBL/HBL, payment and charges on one screen.'),('Shipment5_Subtitle','vi-VN',N'Quản lý job, MBL/HBL, payment và charges trong cùng một màn hình.'),('Shipment5_Subtitle','zh-CN',N'在同一屏幕管理作业、MBL/HBL、付款和费用。'),
('MblApproved','en-US',N'This MBL is approved.'),('MblApproved','vi-VN',N'MBL này đã được approve.'),('MblApproved','zh-CN',N'此 MBL 已审批。'),
('HblApproved','en-US',N'This HBL is approved.'),('HblApproved','vi-VN',N'HBL này đã được approve.'),('HblApproved','zh-CN',N'此 HBL 已审批。'),
('DebitApproved','en-US',N'This debit is approved.'),('DebitApproved','vi-VN',N'Debit này đã được approve.'),('DebitApproved','zh-CN',N'此借记已审批。'),
('SelectOneHbl','en-US',N'You must select one HBL.'),('SelectOneHbl','vi-VN',N'Bạn phải chọn 1 HBL.'),('SelectOneHbl','zh-CN',N'请选择一个 HBL。'),
('SelectOneRowHbl','en-US',N'Please select one HBL row.'),('SelectOneRowHbl','vi-VN',N'Vui lòng chọn 1 dòng HBL.'),('SelectOneRowHbl','zh-CN',N'请选择一行 HBL。'),
('SelectOneRowMbl','en-US',N'Please select one MBL row.'),('SelectOneRowMbl','vi-VN',N'Vui lòng chọn 1 dòng MBL.'),('SelectOneRowMbl','zh-CN',N'请选择一行 MBL。'),
('GeneralJournal_Title','en-US',N'General Journal'),('GeneralJournal_Title','vi-VN',N'Sổ Nhật Ký Chung'),('GeneralJournal_Title','zh-CN',N'总账日记账'),
('GeneralJournal_Subtitle','en-US',N'Track debit/credit accounting entries'),('GeneralJournal_Subtitle','vi-VN',N'Theo dõi bút toán kế toán Nợ / Có'),('GeneralJournal_Subtitle','zh-CN',N'跟踪借贷会计分录'),
('FromDate','en-US',N'From date'),('FromDate','vi-VN',N'Từ ngày'),('FromDate','zh-CN',N'起始日期'),
('ToDate','en-US',N'To date'),('ToDate','vi-VN',N'Đến ngày'),('ToDate','zh-CN',N'结束日期'),
('FilterData','en-US',N'Filter data'),('FilterData','vi-VN',N'Lọc dữ liệu'),('FilterData','zh-CN',N'筛选数据'),
('GeneralJournal_TotalRows','en-US',N'Total rows'),('GeneralJournal_TotalRows','vi-VN',N'Tổng dòng'),('GeneralJournal_TotalRows','zh-CN',N'总行数'),
('GeneralJournal_TotalDebit','en-US',N'Total debit'),('GeneralJournal_TotalDebit','vi-VN',N'Tổng Nợ'),('GeneralJournal_TotalDebit','zh-CN',N'借方合计'),
('GeneralJournal_TotalCredit','en-US',N'Total credit'),('GeneralJournal_TotalCredit','vi-VN',N'Tổng Có'),('GeneralJournal_TotalCredit','zh-CN',N'贷方合计'),
('GeneralJournal_Difference','en-US',N'Difference'),('GeneralJournal_Difference','vi-VN',N'Chênh lệch'),('GeneralJournal_Difference','zh-CN',N'差额'),
('GeneralJournal_PostingDate','en-US',N'Posting date'),('GeneralJournal_PostingDate','vi-VN',N'Ngày hạch toán'),('GeneralJournal_PostingDate','zh-CN',N'记账日期'),
('GeneralJournal_VoucherDate','en-US',N'Voucher date'),('GeneralJournal_VoucherDate','vi-VN',N'Ngày chứng từ'),('GeneralJournal_VoucherDate','zh-CN',N'凭证日期'),
('GeneralJournal_VoucherNo','en-US',N'Voucher no.'),('GeneralJournal_VoucherNo','vi-VN',N'Số chứng từ'),('GeneralJournal_VoucherNo','zh-CN',N'凭证号'),
('GeneralJournal_TransactionType','en-US',N'Trans. type'),('GeneralJournal_TransactionType','vi-VN',N'Loại CT'),('GeneralJournal_TransactionType','zh-CN',N'交易类型'),
('GeneralJournal_Description','en-US',N'Description'),('GeneralJournal_Description','vi-VN',N'Diễn giải'),('GeneralJournal_Description','zh-CN',N'摘要'),
('GeneralJournal_Object','en-US',N'Object'),('GeneralJournal_Object','vi-VN',N'Đối tượng'),('GeneralJournal_Object','zh-CN',N'对象'),
('GeneralJournal_DebitAccount','en-US',N'Debit account'),('GeneralJournal_DebitAccount','vi-VN',N'TK Nợ'),('GeneralJournal_DebitAccount','zh-CN',N'借方科目'),
('GeneralJournal_CreditAccount','en-US',N'Credit account'),('GeneralJournal_CreditAccount','vi-VN',N'TK Có'),('GeneralJournal_CreditAccount','zh-CN',N'贷方科目'),
('GeneralJournal_ForeignAmount','en-US',N'Foreign amount'),('GeneralJournal_ForeignAmount','vi-VN',N'Số tiền nguyên tệ'),('GeneralJournal_ForeignAmount','zh-CN',N'原币金额'),
('GeneralJournal_AmountVnd','en-US',N'Amount VND'),('GeneralJournal_AmountVnd','vi-VN',N'Số tiền VND'),('GeneralJournal_AmountVnd','zh-CN',N'VND 金额'),
('GeneralJournal_UpdatedBy','en-US',N'Updated by'),('GeneralJournal_UpdatedBy','vi-VN',N'User tạo/sửa'),('GeneralJournal_UpdatedBy','zh-CN',N'更新人'),
('GeneralJournal_UpdatedDate','en-US',N'Updated date'),('GeneralJournal_UpdatedDate','vi-VN',N'Ngày cập nhật'),('GeneralJournal_UpdatedDate','zh-CN',N'更新日期'),
('GeneralJournal_StatusDraft','en-US',N'Draft'),('GeneralJournal_StatusDraft','vi-VN',N'Nháp'),('GeneralJournal_StatusDraft','zh-CN',N'草稿'),
('GeneralJournal_StatusPosted','en-US',N'Posted'),('GeneralJournal_StatusPosted','vi-VN',N'Đã ghi sổ'),('GeneralJournal_StatusPosted','zh-CN',N'已过账'),
('GeneralJournal_StatusCancelled','en-US',N'Cancelled'),('GeneralJournal_StatusCancelled','vi-VN',N'Đã hủy'),('GeneralJournal_StatusCancelled','zh-CN',N'已取消'),
('GeneralJournal_StatusUnknown','en-US',N'Unknown'),('GeneralJournal_StatusUnknown','vi-VN',N'Không xác định'),('GeneralJournal_StatusUnknown','zh-CN',N'未知'),
('GeneralJournal_LoadedRows','en-US',N'Loaded {0:N0} row(s).'),('GeneralJournal_LoadedRows','vi-VN',N'Đã tải {0:N0} dòng dữ liệu'),('GeneralJournal_LoadedRows','zh-CN',N'已加载 {0:N0} 行。'),
('Viettel_Subtitle','en-US',N'E-invoice management · search and export'),('Viettel_Subtitle','vi-VN',N'Quản lý hóa đơn điện tử · tìm kiếm và xuất'),('Viettel_Subtitle','zh-CN',N'电子发票管理 · 搜索与导出'),
('Viettel_UseDefaultJson','en-US',N'Use default JSON values'),('Viettel_UseDefaultJson','vi-VN',N'Lấy giá trị Json mặc định'),('Viettel_UseDefaultJson','zh-CN',N'使用默认 JSON 值'),
('Configuration','en-US',N'Configuration'),('Configuration','vi-VN',N'Cấu hình'),('Configuration','zh-CN',N'配置'),
('DateTimeRange','en-US',N'Date range'),('DateTimeRange','vi-VN',N'Khoảng thời gian'),('DateTimeRange','zh-CN',N'时间范围'),
('Viettel_InvoiceActions','en-US',N'Invoice actions'),('Viettel_InvoiceActions','vi-VN',N'Thao tác hóa đơn'),('Viettel_InvoiceActions','zh-CN',N'发票操作'),
('Viettel_CreateDraftInvoice','en-US',N'Create draft invoice'),('Viettel_CreateDraftInvoice','vi-VN',N'Lập hóa đơn nháp'),('Viettel_CreateDraftInvoice','zh-CN',N'创建草稿发票'),
('Viettel_CreateInvoice','en-US',N'Create invoice'),('Viettel_CreateInvoice','vi-VN',N'Lập hóa đơn'),('Viettel_CreateInvoice','zh-CN',N'创建发票'),
('Viettel_DownloadPdf','en-US',N'Download invoice PDF'),('Viettel_DownloadPdf','vi-VN',N'Tải file PDF hóa đơn'),('Viettel_DownloadPdf','zh-CN',N'下载发票 PDF'),
('SearchConditions','en-US',N'Search conditions'),('SearchConditions','vi-VN',N'Điều kiện tìm kiếm'),('SearchConditions','zh-CN',N'搜索条件'),
('Apply','en-US',N'Apply'),('Apply','vi-VN',N'Áp dụng'),('Apply','zh-CN',N'应用'),
('Exit','en-US',N'Exit'),('Exit','vi-VN',N'Thoát'),('Exit','zh-CN',N'退出'),
('Viettel_FormNo','en-US',N'Form no.'),('Viettel_FormNo','vi-VN',N'Mẫu số'),('Viettel_FormNo','zh-CN',N'表格编号'),
('Viettel_InvoiceSeries','en-US',N'Invoice series'),('Viettel_InvoiceSeries','vi-VN',N'Ký hiệu hóa đơn'),('Viettel_InvoiceSeries','zh-CN',N'发票系列'),
('Viettel_EnterTaxCode','en-US',N'Please enter tax code.'),('Viettel_EnterTaxCode','vi-VN',N'Vui lòng nhập Mã Số Thuế!'),('Viettel_EnterTaxCode','zh-CN',N'请输入税号。'),
('SelectAtLeastOneRow','en-US',N'Please select at least one row.'),('SelectAtLeastOneRow','vi-VN',N'Vui lòng chọn ít nhất một dòng dữ liệu!'),('SelectAtLeastOneRow','zh-CN',N'请至少选择一行。'),
('Viettel_AlreadyHasInvoiceNo','en-US',N'Selected data already has Viettel invoice number.'),('Viettel_AlreadyHasInvoiceNo','vi-VN',N'Xuất hiện dữ liệu đã có Số Hóa Đơn Viettel!'),('Viettel_AlreadyHasInvoiceNo','zh-CN',N'所选数据已有 Viettel 发票号。'),
('Viettel_RequireInternalInvoiceNo','en-US',N'Selected invoices must have internal invoice number.'),('Viettel_RequireInternalInvoiceNo','vi-VN',N'Các hóa đơn đã chọn phải có số hóa đơn nội bộ!'),('Viettel_RequireInternalInvoiceNo','zh-CN',N'所选发票必须有内部发票号。'),
('Viettel_SameInternalInvoiceNo','en-US',N'Selected rows must share the same internal invoice number.'),('Viettel_SameInternalInvoiceNo','vi-VN',N'Các dòng đã chọn phải có chung một số hóa đơn nội bộ!'),('Viettel_SameInternalInvoiceNo','zh-CN',N'所选行必须有相同的内部发票号。'),
('Viettel_AccessTokenFailed','en-US',N'Cannot get access token. Check login credentials.'),('Viettel_AccessTokenFailed','vi-VN',N'Không thể lấy Access Token. Vui lòng kiểm tra lại thông tin đăng nhập!'),('Viettel_AccessTokenFailed','zh-CN',N'无法获取访问令牌，请检查登录信息。'),
('Viettel_ApiError','en-US',N'Viettel API error.'),('Viettel_ApiError','vi-VN',N'Lỗi khi gọi API Viettel!'),('Viettel_ApiError','zh-CN',N'Viettel API 错误。'),
('Viettel_DraftCreatedSuccess','en-US',N'Draft invoice created successfully.'),('Viettel_DraftCreatedSuccess','vi-VN',N'Tạo hóa đơn nháp thành công!'),('Viettel_DraftCreatedSuccess','zh-CN',N'草稿发票创建成功。'),
('Viettel_ConfigLoginRequired','en-US',N'Please configure Viettel login credentials.'),('Viettel_ConfigLoginRequired','vi-VN',N'Vui lòng cấu hình thông tin đăng nhập Viettel!'),('Viettel_ConfigLoginRequired','zh-CN',N'请配置 Viettel 登录信息。');

COMMIT;
