SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.LocalizationResources', N'U') IS NULL
BEGIN
    THROW 50001, 'Table dbo.LocalizationResources does not exist.', 1;
END;
GO

DECLARE @Resources TABLE
(
    ResourceKey nvarchar(500) NOT NULL,
    Culture nvarchar(10) NOT NULL,
    Value nvarchar(max) NOT NULL,
    PRIMARY KEY (ResourceKey, Culture)
);

INSERT INTO @Resources (ResourceKey, Culture, Value)
VALUES
(N'BkavInvoice.Menu', N'en-US', N'Invoice BKAV'),
(N'BkavInvoice.Menu', N'vi-VN', N'Hóa đơn BKAV'),
(N'BkavInvoice.Menu', N'zh-CN', N'Invoice BKAV'),
(N'BkavInvoice.Title', N'en-US', N'Invoice BKAV'),
(N'BkavInvoice.Title', N'vi-VN', N'Hóa đơn BKAV'),
(N'BkavInvoice.Title', N'zh-CN', N'Invoice BKAV'),
(N'BkavInvoice.Subtitle', N'en-US', N'HoaDonDauRa grouped by internal invoice and customer'),
(N'BkavInvoice.Subtitle', N'vi-VN', N'Hóa đơn đầu ra được nhóm theo số nội bộ và khách hàng'),
(N'BkavInvoice.Subtitle', N'zh-CN', N'HoaDonDauRa grouped by internal invoice and customer'),
(N'BkavInvoice.ConfigMissing', N'en-US', N'Missing BKAV configuration: ServiceUrl, PartnerGuid or PartnerToken.'),
(N'BkavInvoice.ConfigMissing', N'vi-VN', N'Thiếu cấu hình BKAV: ServiceUrl, PartnerGuid hoặc PartnerToken.'),
(N'BkavInvoice.ConfigMissing', N'zh-CN', N'Missing BKAV configuration: ServiceUrl, PartnerGuid or PartnerToken.'),

(N'BkavInvoice.Tooltip.Help', N'en-US', N'User guide'),
(N'BkavInvoice.Tooltip.Help', N'vi-VN', N'Hướng dẫn sử dụng'),
(N'BkavInvoice.Tooltip.Help', N'zh-CN', N'User guide'),
(N'BkavInvoice.Tooltip.Issue', N'en-US', N'Issue invoice 100/101/110/111'),
(N'BkavInvoice.Tooltip.Issue', N'vi-VN', N'Phát hành hóa đơn 100/101/110/111'),
(N'BkavInvoice.Tooltip.Issue', N'zh-CN', N'Issue invoice 100/101/110/111'),
(N'BkavInvoice.Tooltip.Update200', N'en-US', N'Update invoice by PartnerInvoiceID 200'),
(N'BkavInvoice.Tooltip.Update200', N'vi-VN', N'Cập nhật hóa đơn theo PartnerInvoiceID 200'),
(N'BkavInvoice.Tooltip.Update200', N'zh-CN', N'Update invoice by PartnerInvoiceID 200'),
(N'BkavInvoice.Tooltip.Update204', N'en-US', N'Update invoice by InvoiceGUID 204'),
(N'BkavInvoice.Tooltip.Update204', N'vi-VN', N'Cập nhật hóa đơn theo InvoiceGUID 204'),
(N'BkavInvoice.Tooltip.Update204', N'zh-CN', N'Update invoice by InvoiceGUID 204'),
(N'BkavInvoice.Tooltip.Replace120', N'en-US', N'Replace invoice 120'),
(N'BkavInvoice.Tooltip.Replace120', N'vi-VN', N'Thay thế hóa đơn 120'),
(N'BkavInvoice.Tooltip.Replace120', N'zh-CN', N'Replace invoice 120'),
(N'BkavInvoice.Tooltip.Adjust121', N'en-US', N'Adjust invoice 121'),
(N'BkavInvoice.Tooltip.Adjust121', N'vi-VN', N'Điều chỉnh hóa đơn 121'),
(N'BkavInvoice.Tooltip.Adjust121', N'zh-CN', N'Adjust invoice 121'),
(N'BkavInvoice.Tooltip.Cancel201', N'en-US', N'Cancel invoice by InvoiceGUID 201'),
(N'BkavInvoice.Tooltip.Cancel201', N'vi-VN', N'Hủy hóa đơn theo InvoiceGUID 201'),
(N'BkavInvoice.Tooltip.Cancel201', N'zh-CN', N'Cancel invoice by InvoiceGUID 201'),
(N'BkavInvoice.Tooltip.Cancel202', N'en-US', N'Cancel invoice by PartnerInvoiceID 202'),
(N'BkavInvoice.Tooltip.Cancel202', N'vi-VN', N'Hủy hóa đơn theo PartnerInvoiceID 202'),
(N'BkavInvoice.Tooltip.Cancel202', N'zh-CN', N'Cancel invoice by PartnerInvoiceID 202'),
(N'BkavInvoice.Tooltip.Delete303', N'en-US', N'Delete unissued invoice by InvoiceGUID 303'),
(N'BkavInvoice.Tooltip.Delete303', N'vi-VN', N'Xóa hóa đơn chưa phát hành theo InvoiceGUID 303'),
(N'BkavInvoice.Tooltip.Delete303', N'zh-CN', N'Delete unissued invoice by InvoiceGUID 303'),
(N'BkavInvoice.Tooltip.Delete301', N'en-US', N'Delete unissued invoice by PartnerInvoiceID 301'),
(N'BkavInvoice.Tooltip.Delete301', N'vi-VN', N'Xóa hóa đơn chưa phát hành theo PartnerInvoiceID 301'),
(N'BkavInvoice.Tooltip.Delete301', N'zh-CN', N'Delete unissued invoice by PartnerInvoiceID 301'),
(N'BkavInvoice.Tooltip.Info800', N'en-US', N'Get invoice information 800'),
(N'BkavInvoice.Tooltip.Info800', N'vi-VN', N'Lấy thông tin hóa đơn 800'),
(N'BkavInvoice.Tooltip.Info800', N'zh-CN', N'Get invoice information 800'),
(N'BkavInvoice.Tooltip.Status801', N'en-US', N'Refresh invoice status 801'),
(N'BkavInvoice.Tooltip.Status801', N'vi-VN', N'Cập nhật trạng thái hóa đơn 801'),
(N'BkavInvoice.Tooltip.Status801', N'zh-CN', N'Refresh invoice status 801'),
(N'BkavInvoice.Tooltip.History802', N'en-US', N'Get invoice history 802'),
(N'BkavInvoice.Tooltip.History802', N'vi-VN', N'Lấy lịch sử hóa đơn 802'),
(N'BkavInvoice.Tooltip.History802', N'zh-CN', N'Get invoice history 802'),
(N'BkavInvoice.Tooltip.Link804', N'en-US', N'Get invoice link 804'),
(N'BkavInvoice.Tooltip.Link804', N'vi-VN', N'Lấy link hóa đơn 804'),
(N'BkavInvoice.Tooltip.Link804', N'zh-CN', N'Get invoice link 804'),
(N'BkavInvoice.Tooltip.Pdf808', N'en-US', N'Download PDF 808'),
(N'BkavInvoice.Tooltip.Pdf808', N'vi-VN', N'Tải PDF 808'),
(N'BkavInvoice.Tooltip.Pdf808', N'zh-CN', N'Download PDF 808'),
(N'BkavInvoice.Tooltip.Xml809', N'en-US', N'Download XML 809'),
(N'BkavInvoice.Tooltip.Xml809', N'vi-VN', N'Tải XML 809'),
(N'BkavInvoice.Tooltip.Xml809', N'zh-CN', N'Download XML 809'),
(N'BkavInvoice.Tooltip.Tax904', N'en-US', N'Look up tax code 904'),
(N'BkavInvoice.Tooltip.Tax904', N'vi-VN', N'Tra cứu mã số thuế 904'),
(N'BkavInvoice.Tooltip.Tax904', N'zh-CN', N'Look up tax code 904'),
(N'BkavInvoice.Tooltip.Account902', N'en-US', N'Create demo account 902'),
(N'BkavInvoice.Tooltip.Account902', N'vi-VN', N'Tạo tài khoản demo 902'),
(N'BkavInvoice.Tooltip.Account902', N'zh-CN', N'Create demo account 902'),
(N'BkavInvoice.Tooltip.Dll1001', N'en-US', N'Download DLL 1001'),
(N'BkavInvoice.Tooltip.Dll1001', N'vi-VN', N'Tải DLL 1001'),
(N'BkavInvoice.Tooltip.Dll1001', N'zh-CN', N'Download DLL 1001'),

(N'BkavInvoice.Filter.Invoice', N'en-US', N'Internal/e-invoice'),
(N'BkavInvoice.Filter.Invoice', N'vi-VN', N'Số nội bộ/điện tử'),
(N'BkavInvoice.Filter.Invoice', N'zh-CN', N'Internal/e-invoice'),
(N'BkavInvoice.Status.Open', N'en-US', N'Not issued'),
(N'BkavInvoice.Status.Open', N'vi-VN', N'Chưa phát hành'),
(N'BkavInvoice.Status.Open', N'zh-CN', N'Not issued'),
(N'BkavInvoice.Status.Issued', N'en-US', N'Issued'),
(N'BkavInvoice.Status.Issued', N'vi-VN', N'Đã phát hành'),
(N'BkavInvoice.Status.Issued', N'zh-CN', N'Issued'),
(N'BkavInvoice.Input.Command', N'en-US', N'Command'),
(N'BkavInvoice.Input.Command', N'vi-VN', N'Lệnh'),
(N'BkavInvoice.Input.Command', N'zh-CN', N'Command'),
(N'BkavInvoice.Input.Pay', N'en-US', N'Pay'),
(N'BkavInvoice.Input.Pay', N'vi-VN', N'Thanh toán'),
(N'BkavInvoice.Input.Pay', N'zh-CN', N'Pay'),
(N'BkavInvoice.Input.Form', N'en-US', N'Form'),
(N'BkavInvoice.Input.Form', N'vi-VN', N'Mẫu số'),
(N'BkavInvoice.Input.Form', N'zh-CN', N'Form'),
(N'BkavInvoice.Input.Serial', N'en-US', N'Serial'),
(N'BkavInvoice.Input.Serial', N'vi-VN', N'Ký hiệu'),
(N'BkavInvoice.Input.Serial', N'zh-CN', N'Serial'),
(N'BkavInvoice.Input.No', N'en-US', N'No'),
(N'BkavInvoice.Input.No', N'vi-VN', N'Số HĐ'),
(N'BkavInvoice.Input.No', N'zh-CN', N'No'),
(N'BkavInvoice.Input.OriginalIdentify', N'en-US', N'Original identify'),
(N'BkavInvoice.Input.OriginalIdentify', N'vi-VN', N'Định danh hóa đơn gốc'),
(N'BkavInvoice.Input.OriginalIdentify', N'zh-CN', N'Original identify'),
(N'BkavInvoice.Input.TaxCode', N'en-US', N'Tax code'),
(N'BkavInvoice.Input.TaxCode', N'vi-VN', N'Mã số thuế'),
(N'BkavInvoice.Input.TaxCode', N'zh-CN', N'Tax code'),
(N'BkavInvoice.Pay.Cash', N'en-US', N'Cash'),
(N'BkavInvoice.Pay.Cash', N'vi-VN', N'TM'),
(N'BkavInvoice.Pay.Cash', N'zh-CN', N'Cash'),
(N'BkavInvoice.Pay.Transfer', N'en-US', N'Transfer'),
(N'BkavInvoice.Pay.Transfer', N'vi-VN', N'CK'),
(N'BkavInvoice.Pay.Transfer', N'zh-CN', N'Transfer'),
(N'BkavInvoice.Pay.CashTransfer', N'en-US', N'Cash/Transfer'),
(N'BkavInvoice.Pay.CashTransfer', N'vi-VN', N'TM/CK'),
(N'BkavInvoice.Pay.CashTransfer', N'zh-CN', N'Cash/Transfer'),

(N'BkavInvoice.Action.Reload', N'en-US', N'Reload'),
(N'BkavInvoice.Action.Reload', N'vi-VN', N'Tải lại'),
(N'BkavInvoice.Action.Reload', N'zh-CN', N'Reload'),
(N'BkavInvoice.Action.Issue', N'en-US', N'Issue BKAV'),
(N'BkavInvoice.Action.Issue', N'vi-VN', N'Phát hành BKAV'),
(N'BkavInvoice.Action.Issue', N'zh-CN', N'Issue BKAV'),
(N'BkavInvoice.Action.Update200', N'en-US', N'Update 200'),
(N'BkavInvoice.Action.Update200', N'vi-VN', N'Cập nhật 200'),
(N'BkavInvoice.Action.Update200', N'zh-CN', N'Update 200'),
(N'BkavInvoice.Action.Update204', N'en-US', N'Update 204'),
(N'BkavInvoice.Action.Update204', N'vi-VN', N'Cập nhật 204'),
(N'BkavInvoice.Action.Update204', N'zh-CN', N'Update 204'),
(N'BkavInvoice.Action.Replace120', N'en-US', N'Replace 120'),
(N'BkavInvoice.Action.Replace120', N'vi-VN', N'Thay thế 120'),
(N'BkavInvoice.Action.Replace120', N'zh-CN', N'Replace 120'),
(N'BkavInvoice.Action.Adjust121', N'en-US', N'Adjust 121'),
(N'BkavInvoice.Action.Adjust121', N'vi-VN', N'Điều chỉnh 121'),
(N'BkavInvoice.Action.Adjust121', N'zh-CN', N'Adjust 121'),
(N'BkavInvoice.Action.Cancel201', N'en-US', N'Cancel 201'),
(N'BkavInvoice.Action.Cancel201', N'vi-VN', N'Hủy 201'),
(N'BkavInvoice.Action.Cancel201', N'zh-CN', N'Cancel 201'),
(N'BkavInvoice.Action.Cancel202', N'en-US', N'Cancel 202'),
(N'BkavInvoice.Action.Cancel202', N'vi-VN', N'Hủy 202'),
(N'BkavInvoice.Action.Cancel202', N'zh-CN', N'Cancel 202'),
(N'BkavInvoice.Action.Delete303', N'en-US', N'Delete 303'),
(N'BkavInvoice.Action.Delete303', N'vi-VN', N'Xóa 303'),
(N'BkavInvoice.Action.Delete303', N'zh-CN', N'Delete 303'),
(N'BkavInvoice.Action.Delete301', N'en-US', N'Delete 301'),
(N'BkavInvoice.Action.Delete301', N'vi-VN', N'Xóa 301'),
(N'BkavInvoice.Action.Delete301', N'zh-CN', N'Delete 301'),
(N'BkavInvoice.Action.Info800', N'en-US', N'Info 800'),
(N'BkavInvoice.Action.Info800', N'vi-VN', N'Thông tin 800'),
(N'BkavInvoice.Action.Info800', N'zh-CN', N'Info 800'),
(N'BkavInvoice.Action.Status801', N'en-US', N'Status 801'),
(N'BkavInvoice.Action.Status801', N'vi-VN', N'Trạng thái 801'),
(N'BkavInvoice.Action.Status801', N'zh-CN', N'Status 801'),
(N'BkavInvoice.Action.Status', N'en-US', N'Status'),
(N'BkavInvoice.Action.Status', N'vi-VN', N'Trạng thái'),
(N'BkavInvoice.Action.Status', N'zh-CN', N'Status'),
(N'BkavInvoice.Action.History802', N'en-US', N'History 802'),
(N'BkavInvoice.Action.History802', N'vi-VN', N'Lịch sử 802'),
(N'BkavInvoice.Action.History802', N'zh-CN', N'History 802'),
(N'BkavInvoice.Action.Link804', N'en-US', N'Link 804'),
(N'BkavInvoice.Action.Link804', N'vi-VN', N'Link 804'),
(N'BkavInvoice.Action.Link804', N'zh-CN', N'Link 804'),
(N'BkavInvoice.Action.Link', N'en-US', N'Link'),
(N'BkavInvoice.Action.Link', N'vi-VN', N'Link'),
(N'BkavInvoice.Action.Link', N'zh-CN', N'Link'),
(N'BkavInvoice.Action.Pdf808', N'en-US', N'PDF 808'),
(N'BkavInvoice.Action.Pdf808', N'vi-VN', N'PDF 808'),
(N'BkavInvoice.Action.Pdf808', N'zh-CN', N'PDF 808'),
(N'BkavInvoice.Action.Pdf', N'en-US', N'PDF'),
(N'BkavInvoice.Action.Pdf', N'vi-VN', N'PDF'),
(N'BkavInvoice.Action.Pdf', N'zh-CN', N'PDF'),
(N'BkavInvoice.Action.Xml809', N'en-US', N'XML 809'),
(N'BkavInvoice.Action.Xml809', N'vi-VN', N'XML 809'),
(N'BkavInvoice.Action.Xml809', N'zh-CN', N'XML 809'),
(N'BkavInvoice.Action.Xml', N'en-US', N'XML'),
(N'BkavInvoice.Action.Xml', N'vi-VN', N'XML'),
(N'BkavInvoice.Action.Xml', N'zh-CN', N'XML'),
(N'BkavInvoice.Action.Tax904', N'en-US', N'Tax lookup 904'),
(N'BkavInvoice.Action.Tax904', N'vi-VN', N'Tra cứu MST 904'),
(N'BkavInvoice.Action.Tax904', N'zh-CN', N'Tax lookup 904'),
(N'BkavInvoice.Action.Account902', N'en-US', N'Account 902'),
(N'BkavInvoice.Action.Account902', N'vi-VN', N'Tài khoản 902'),
(N'BkavInvoice.Action.Account902', N'zh-CN', N'Account 902'),
(N'BkavInvoice.Action.Dll1001', N'en-US', N'DLL 1001'),
(N'BkavInvoice.Action.Dll1001', N'vi-VN', N'DLL 1001'),
(N'BkavInvoice.Action.Dll1001', N'zh-CN', N'DLL 1001'),

(N'BkavInvoice.Column.Bkav', N'en-US', N'BKAV'),
(N'BkavInvoice.Column.Bkav', N'vi-VN', N'BKAV'),
(N'BkavInvoice.Column.Bkav', N'zh-CN', N'BKAV'),
(N'BkavInvoice.Column.InternalNo', N'en-US', N'Internal No'),
(N'BkavInvoice.Column.InternalNo', N'vi-VN', N'Số nội bộ'),
(N'BkavInvoice.Column.InternalNo', N'zh-CN', N'Internal No'),
(N'BkavInvoice.Column.EInvoiceNo', N'en-US', N'E-Invoice No'),
(N'BkavInvoice.Column.EInvoiceNo', N'vi-VN', N'Số HĐ điện tử'),
(N'BkavInvoice.Column.EInvoiceNo', N'zh-CN', N'E-Invoice No'),
(N'BkavInvoice.Column.Lines', N'en-US', N'Lines'),
(N'BkavInvoice.Column.Lines', N'vi-VN', N'Dòng'),
(N'BkavInvoice.Column.Lines', N'zh-CN', N'Lines'),
(N'BkavInvoice.Column.IssueDate', N'en-US', N'Issue Date'),
(N'BkavInvoice.Column.IssueDate', N'vi-VN', N'Ngày phát hành'),
(N'BkavInvoice.Column.IssueDate', N'zh-CN', N'Issue Date'),
(N'BkavInvoice.Column.BeforeVat', N'en-US', N'Before VAT'),
(N'BkavInvoice.Column.BeforeVat', N'vi-VN', N'Trước thuế'),
(N'BkavInvoice.Column.BeforeVat', N'zh-CN', N'Before VAT'),
(N'BkavInvoice.Column.AfterVat', N'en-US', N'After VAT'),
(N'BkavInvoice.Column.AfterVat', N'vi-VN', N'Sau thuế'),
(N'BkavInvoice.Column.AfterVat', N'zh-CN', N'After VAT'),
(N'BkavInvoice.Column.PartnerId', N'en-US', N'Partner ID'),
(N'BkavInvoice.Column.PartnerId', N'vi-VN', N'Partner ID'),
(N'BkavInvoice.Column.PartnerId', N'zh-CN', N'Partner ID'),
(N'BkavInvoice.Column.Guid', N'en-US', N'GUID'),
(N'BkavInvoice.Column.Guid', N'vi-VN', N'GUID'),
(N'BkavInvoice.Column.Guid', N'zh-CN', N'GUID'),
(N'BkavInvoice.Column.Form', N'en-US', N'Form'),
(N'BkavInvoice.Column.Form', N'vi-VN', N'Mẫu số'),
(N'BkavInvoice.Column.Form', N'zh-CN', N'Form'),
(N'BkavInvoice.Column.Serial', N'en-US', N'Serial'),
(N'BkavInvoice.Column.Serial', N'vi-VN', N'Ký hiệu'),
(N'BkavInvoice.Column.Serial', N'zh-CN', N'Serial'),
(N'BkavInvoice.Column.BkavNo', N'en-US', N'BKAV No'),
(N'BkavInvoice.Column.BkavNo', N'vi-VN', N'Số BKAV'),
(N'BkavInvoice.Column.BkavNo', N'zh-CN', N'BKAV No'),
(N'BkavInvoice.Column.StatusId', N'en-US', N'Status ID'),
(N'BkavInvoice.Column.StatusId', N'vi-VN', N'Mã trạng thái'),
(N'BkavInvoice.Column.StatusId', N'zh-CN', N'Status ID'),
(N'BkavInvoice.Column.Files', N'en-US', N'Files'),
(N'BkavInvoice.Column.Files', N'vi-VN', N'Tệp'),
(N'BkavInvoice.Column.Files', N'zh-CN', N'Files'),
(N'BkavInvoice.Column.Message', N'en-US', N'Message'),
(N'BkavInvoice.Column.Message', N'vi-VN', N'Thông báo'),
(N'BkavInvoice.Column.Message', N'zh-CN', N'Message'),
(N'BkavInvoice.File.Link', N'en-US', N'Link'),
(N'BkavInvoice.File.Link', N'vi-VN', N'Link'),
(N'BkavInvoice.File.Link', N'zh-CN', N'Link'),
(N'BkavInvoice.File.Pdf', N'en-US', N'PDF'),
(N'BkavInvoice.File.Pdf', N'vi-VN', N'PDF'),
(N'BkavInvoice.File.Pdf', N'zh-CN', N'PDF'),
(N'BkavInvoice.File.Xml', N'en-US', N'XML'),
(N'BkavInvoice.File.Xml', N'vi-VN', N'XML'),
(N'BkavInvoice.File.Xml', N'zh-CN', N'XML'),

(N'BkavInvoice.Line.No', N'en-US', N'No'),
(N'BkavInvoice.Line.No', N'vi-VN', N'STT'),
(N'BkavInvoice.Line.No', N'zh-CN', N'No'),
(N'BkavInvoice.Line.Item', N'en-US', N'Item'),
(N'BkavInvoice.Line.Item', N'vi-VN', N'Mã phí'),
(N'BkavInvoice.Line.Item', N'zh-CN', N'Item'),
(N'BkavInvoice.Line.Note', N'en-US', N'Note'),
(N'BkavInvoice.Line.Note', N'vi-VN', N'Ghi chú'),
(N'BkavInvoice.Line.Note', N'zh-CN', N'Note'),
(N'BkavInvoice.Line.Rate', N'en-US', N'Rate'),
(N'BkavInvoice.Line.Rate', N'vi-VN', N'Tỷ giá'),
(N'BkavInvoice.Line.Rate', N'zh-CN', N'Rate'),
(N'BkavInvoice.Line.Qty', N'en-US', N'Qty'),
(N'BkavInvoice.Line.Qty', N'vi-VN', N'Số lượng'),
(N'BkavInvoice.Line.Qty', N'zh-CN', N'Qty'),
(N'BkavInvoice.Line.Price', N'en-US', N'Price'),
(N'BkavInvoice.Line.Price', N'vi-VN', N'Đơn giá'),
(N'BkavInvoice.Line.Price', N'zh-CN', N'Price'),
(N'BkavInvoice.Line.Amount', N'en-US', N'Amount'),
(N'BkavInvoice.Line.Amount', N'vi-VN', N'Thành tiền'),
(N'BkavInvoice.Line.Amount', N'zh-CN', N'Amount'),
(N'BkavInvoice.Line.VatPercent', N'en-US', N'VAT %'),
(N'BkavInvoice.Line.VatPercent', N'vi-VN', N'Thuế %'),
(N'BkavInvoice.Line.VatPercent', N'zh-CN', N'VAT %'),
(N'BkavInvoice.Line.AfterVat', N'en-US', N'After VAT'),
(N'BkavInvoice.Line.AfterVat', N'vi-VN', N'Sau thuế'),
(N'BkavInvoice.Line.AfterVat', N'zh-CN', N'After VAT'),

(N'BkavInvoice.Result', N'en-US', N'BKAV Result'),
(N'BkavInvoice.Result', N'vi-VN', N'Kết quả BKAV'),
(N'BkavInvoice.Result', N'zh-CN', N'BKAV Result'),
(N'BkavInvoice.LoadFailed', N'en-US', N'Cannot load BKAV invoice groups: {0}'),
(N'BkavInvoice.LoadFailed', N'vi-VN', N'Không tải được danh sách hóa đơn BKAV: {0}'),
(N'BkavInvoice.LoadFailed', N'zh-CN', N'Cannot load BKAV invoice groups: {0}'),
(N'BkavInvoice.SelectGroupRequired', N'en-US', N'Please select at least one invoice group.'),
(N'BkavInvoice.SelectGroupRequired', N'vi-VN', N'Vui lòng chọn ít nhất một nhóm hóa đơn.'),
(N'BkavInvoice.SelectGroupRequired', N'zh-CN', N'Please select at least one invoice group.'),
(N'BkavInvoice.ActionSummary', N'en-US', N'{0}: {1} success, {2} failed. {3}'),
(N'BkavInvoice.ActionSummary', N'vi-VN', N'{0}: {1} thành công, {2} lỗi. {3}'),
(N'BkavInvoice.ActionSummary', N'zh-CN', N'{0}: {1} success, {2} failed. {3}'),
(N'BkavInvoice.ToolSummary', N'en-US', N'{0}: {1}'),
(N'BkavInvoice.ToolSummary', N'vi-VN', N'{0}: {1}'),
(N'BkavInvoice.ToolSummary', N'zh-CN', N'{0}: {1}'),
(N'BkavInvoice.ActionFailed', N'en-US', N'{0} failed: {1}'),
(N'BkavInvoice.ActionFailed', N'vi-VN', N'{0} lỗi: {1}'),
(N'BkavInvoice.ActionFailed', N'zh-CN', N'{0} failed: {1}'),

(N'BkavInvoice.Help.Title', N'en-US', N'Invoice BKAV user guide'),
(N'BkavInvoice.Help.Title', N'vi-VN', N'Hướng dẫn sử dụng Invoice BKAV'),
(N'BkavInvoice.Help.Title', N'zh-CN', N'Invoice BKAV user guide'),
(N'BkavInvoice.Help.FlowTitle', N'en-US', N'Basic workflow'),
(N'BkavInvoice.Help.FlowTitle', N'vi-VN', N'Quy trình cơ bản'),
(N'BkavInvoice.Help.FlowTitle', N'zh-CN', N'Basic workflow'),
(N'BkavInvoice.Help.Flow1', N'en-US', N'Filter and select one or more invoice groups. One BKAV invoice equals one sohoadonNoibo plus customer group.'),
(N'BkavInvoice.Help.Flow1', N'vi-VN', N'Lọc và chọn một hoặc nhiều nhóm hóa đơn. Một hóa đơn BKAV tương ứng một nhóm sohoadonNoibo cộng khách hàng.'),
(N'BkavInvoice.Help.Flow1', N'zh-CN', N'Filter and select one or more invoice groups. One BKAV invoice equals one sohoadonNoibo plus customer group.'),
(N'BkavInvoice.Help.Flow2', N'en-US', N'Expand the row to review HoaDonDauRa lines, amount, VAT and currency before sending.'),
(N'BkavInvoice.Help.Flow2', N'vi-VN', N'Mở rộng dòng để kiểm tra các dòng HoaDonDauRa, thành tiền, thuế và tiền tệ trước khi gửi.'),
(N'BkavInvoice.Help.Flow2', N'zh-CN', N'Expand the row to review HoaDonDauRa lines, amount, VAT and currency before sending.'),
(N'BkavInvoice.Help.Flow3', N'en-US', N'Choose the create command and fill Form, Serial or No when the selected command requires them.'),
(N'BkavInvoice.Help.Flow3', N'vi-VN', N'Chọn lệnh tạo hóa đơn và nhập Mẫu số, Ký hiệu hoặc Số hóa đơn khi lệnh yêu cầu.'),
(N'BkavInvoice.Help.Flow3', N'zh-CN', N'Choose the create command and fill Form, Serial or No when the selected command requires them.'),
(N'BkavInvoice.Help.Flow4', N'en-US', N'Send to BKAV, then refresh status or download link, PDF and XML as needed.'),
(N'BkavInvoice.Help.Flow4', N'vi-VN', N'Gửi BKAV, sau đó cập nhật trạng thái hoặc tải link, PDF và XML khi cần.'),
(N'BkavInvoice.Help.Flow4', N'zh-CN', N'Send to BKAV, then refresh status or download link, PDF and XML as needed.'),
(N'BkavInvoice.Help.InputTitle', N'en-US', N'Input fields'),
(N'BkavInvoice.Help.InputTitle', N'vi-VN', N'Các ô nhập liệu'),
(N'BkavInvoice.Help.InputTitle', N'zh-CN', N'Input fields'),
(N'BkavInvoice.Help.InputCommand', N'en-US', N'Command: 100 and 101 let BKAV allocate form, serial and number; 110 requires Form and Serial; 111 also requires No.'),
(N'BkavInvoice.Help.InputCommand', N'vi-VN', N'Lệnh: 100 và 101 để BKAV cấp mẫu, ký hiệu và số; 110 cần Mẫu số và Ký hiệu; 111 cần thêm Số hóa đơn.'),
(N'BkavInvoice.Help.InputCommand', N'zh-CN', N'Command: 100 and 101 let BKAV allocate form, serial and number; 110 requires Form and Serial; 111 also requires No.'),
(N'BkavInvoice.Help.InputPay', N'en-US', N'Pay: payment method sent to BKAV, including cash, transfer or cash/transfer.'),
(N'BkavInvoice.Help.InputPay', N'vi-VN', N'Thanh toán: hình thức thanh toán gửi sang BKAV, gồm tiền mặt, chuyển khoản hoặc tiền mặt/chuyển khoản.'),
(N'BkavInvoice.Help.InputPay', N'zh-CN', N'Pay: payment method sent to BKAV, including cash, transfer or cash/transfer.'),
(N'BkavInvoice.Help.InputFormSerialNo', N'en-US', N'Form, Serial and No: used for create commands 110/111 and special operations where BKAV requires explicit invoice identifiers.'),
(N'BkavInvoice.Help.InputFormSerialNo', N'vi-VN', N'Mẫu số, Ký hiệu và Số HĐ: dùng cho lệnh tạo 110/111 và các nghiệp vụ cần định danh hóa đơn rõ ràng.'),
(N'BkavInvoice.Help.InputFormSerialNo', N'zh-CN', N'Form, Serial and No: used for create commands 110/111 and special operations where BKAV requires explicit invoice identifiers.'),
(N'BkavInvoice.Help.InputOriginal', N'en-US', N'Original identify: required for replace 120 and adjust 121, in the format [Form]_[Serial]_[InvoiceNo].'),
(N'BkavInvoice.Help.InputOriginal', N'vi-VN', N'Định danh hóa đơn gốc: bắt buộc cho thay thế 120 và điều chỉnh 121, theo dạng [Mẫu số]_[Ký hiệu]_[Số HĐ].'),
(N'BkavInvoice.Help.InputOriginal', N'zh-CN', N'Original identify: required for replace 120 and adjust 121, in the format [Form]_[Serial]_[InvoiceNo].'),
(N'BkavInvoice.Help.InputTaxCode', N'en-US', N'Tax code: used by tax lookup 904 and DLL 1001.'),
(N'BkavInvoice.Help.InputTaxCode', N'vi-VN', N'Mã số thuế: dùng cho tra cứu MST 904 và tải DLL 1001.'),
(N'BkavInvoice.Help.InputTaxCode', N'zh-CN', N'Tax code: used by tax lookup 904 and DLL 1001.'),
(N'BkavInvoice.Help.ButtonTitle', N'en-US', N'Button functions'),
(N'BkavInvoice.Help.ButtonTitle', N'vi-VN', N'Chức năng từng nút'),
(N'BkavInvoice.Help.ButtonTitle', N'zh-CN', N'Button functions'),
(N'BkavInvoice.Help.ButtonColumn', N'en-US', N'Button'),
(N'BkavInvoice.Help.ButtonColumn', N'vi-VN', N'Nút'),
(N'BkavInvoice.Help.ButtonColumn', N'zh-CN', N'Button'),
(N'BkavInvoice.Help.FunctionColumn', N'en-US', N'Function'),
(N'BkavInvoice.Help.FunctionColumn', N'vi-VN', N'Chức năng'),
(N'BkavInvoice.Help.FunctionColumn', N'zh-CN', N'Function'),
(N'BkavInvoice.Help.NoteTitle', N'en-US', N'Business notes'),
(N'BkavInvoice.Help.NoteTitle', N'vi-VN', N'Lưu ý nghiệp vụ'),
(N'BkavInvoice.Help.NoteTitle', N'zh-CN', N'Business notes'),
(N'BkavInvoice.Help.NoteSelection', N'en-US', N'Group actions only run on selected invoice groups.'),
(N'BkavInvoice.Help.NoteSelection', N'vi-VN', N'Các thao tác theo nhóm chỉ chạy trên nhóm hóa đơn đã chọn.'),
(N'BkavInvoice.Help.NoteSelection', N'zh-CN', N'Group actions only run on selected invoice groups.'),
(N'BkavInvoice.Help.NoteCommand110111', N'en-US', N'Commands 110 and 111 require Form and Serial; command 111 also requires No.'),
(N'BkavInvoice.Help.NoteCommand110111', N'vi-VN', N'Lệnh 110 và 111 cần Mẫu số và Ký hiệu; lệnh 111 cần thêm Số HĐ.'),
(N'BkavInvoice.Help.NoteCommand110111', N'zh-CN', N'Commands 110 and 111 require Form and Serial; command 111 also requires No.'),
(N'BkavInvoice.Help.NoteReplaceAdjust', N'en-US', N'Replace and adjust require Original identify before sending.'),
(N'BkavInvoice.Help.NoteReplaceAdjust', N'vi-VN', N'Thay thế và điều chỉnh cần nhập Định danh hóa đơn gốc trước khi gửi.'),
(N'BkavInvoice.Help.NoteReplaceAdjust', N'zh-CN', N'Replace and adjust require Original identify before sending.'),
(N'BkavInvoice.Help.NoteFiles', N'en-US', N'PDF and XML files are saved under wwwroot/exports/bkav.'),
(N'BkavInvoice.Help.NoteFiles', N'vi-VN', N'File PDF và XML được lưu trong wwwroot/exports/bkav.'),
(N'BkavInvoice.Help.NoteFiles', N'zh-CN', N'PDF and XML files are saved under wwwroot/exports/bkav.'),

(N'BkavInvoice.Help.ButtonReload', N'en-US', N'Reload invoice groups from HoaDonDauRa.'),
(N'BkavInvoice.Help.ButtonReload', N'vi-VN', N'Tải lại các nhóm hóa đơn từ HoaDonDauRa.'),
(N'BkavInvoice.Help.ButtonReload', N'zh-CN', N'Reload invoice groups from HoaDonDauRa.'),
(N'BkavInvoice.Help.ButtonIssue', N'en-US', N'Create and send selected invoice groups to BKAV with command 100, 101, 110 or 111.'),
(N'BkavInvoice.Help.ButtonIssue', N'vi-VN', N'Tạo và gửi nhóm hóa đơn đã chọn sang BKAV bằng lệnh 100, 101, 110 hoặc 111.'),
(N'BkavInvoice.Help.ButtonIssue', N'zh-CN', N'Create and send selected invoice groups to BKAV with command 100, 101, 110 or 111.'),
(N'BkavInvoice.Help.ButtonUpdate200', N'en-US', N'Update an existing BKAV invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonUpdate200', N'vi-VN', N'Cập nhật hóa đơn BKAV hiện có theo PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonUpdate200', N'zh-CN', N'Update an existing BKAV invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonUpdate204', N'en-US', N'Update an existing BKAV invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonUpdate204', N'vi-VN', N'Cập nhật hóa đơn BKAV hiện có theo InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonUpdate204', N'zh-CN', N'Update an existing BKAV invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonReplace120', N'en-US', N'Create a replacement invoice for the original invoice.'),
(N'BkavInvoice.Help.ButtonReplace120', N'vi-VN', N'Tạo hóa đơn thay thế cho hóa đơn gốc.'),
(N'BkavInvoice.Help.ButtonReplace120', N'zh-CN', N'Create a replacement invoice for the original invoice.'),
(N'BkavInvoice.Help.ButtonAdjust121', N'en-US', N'Create an adjustment invoice for the original invoice.'),
(N'BkavInvoice.Help.ButtonAdjust121', N'vi-VN', N'Tạo hóa đơn điều chỉnh cho hóa đơn gốc.'),
(N'BkavInvoice.Help.ButtonAdjust121', N'zh-CN', N'Create an adjustment invoice for the original invoice.'),
(N'BkavInvoice.Help.ButtonCancel201', N'en-US', N'Cancel the invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonCancel201', N'vi-VN', N'Hủy hóa đơn theo InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonCancel201', N'zh-CN', N'Cancel the invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonCancel202', N'en-US', N'Cancel the invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonCancel202', N'vi-VN', N'Hủy hóa đơn theo PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonCancel202', N'zh-CN', N'Cancel the invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonDelete303', N'en-US', N'Delete an unissued invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonDelete303', N'vi-VN', N'Xóa hóa đơn chưa phát hành theo InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonDelete303', N'zh-CN', N'Delete an unissued invoice by InvoiceGUID.'),
(N'BkavInvoice.Help.ButtonDelete301', N'en-US', N'Delete an unissued invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonDelete301', N'vi-VN', N'Xóa hóa đơn chưa phát hành theo PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonDelete301', N'zh-CN', N'Delete an unissued invoice by PartnerInvoiceID.'),
(N'BkavInvoice.Help.ButtonInfo800', N'en-US', N'Get invoice information from BKAV and refresh stored invoice identifiers.'),
(N'BkavInvoice.Help.ButtonInfo800', N'vi-VN', N'Lấy thông tin hóa đơn từ BKAV và cập nhật các định danh đã lưu.'),
(N'BkavInvoice.Help.ButtonInfo800', N'zh-CN', N'Get invoice information from BKAV and refresh stored invoice identifiers.'),
(N'BkavInvoice.Help.ButtonStatus801', N'en-US', N'Get the current BKAV status ID.'),
(N'BkavInvoice.Help.ButtonStatus801', N'vi-VN', N'Lấy mã trạng thái hiện tại từ BKAV.'),
(N'BkavInvoice.Help.ButtonStatus801', N'zh-CN', N'Get the current BKAV status ID.'),
(N'BkavInvoice.Help.ButtonHistory802', N'en-US', N'Get the BKAV change history for the invoice.'),
(N'BkavInvoice.Help.ButtonHistory802', N'vi-VN', N'Lấy lịch sử thay đổi hóa đơn từ BKAV.'),
(N'BkavInvoice.Help.ButtonHistory802', N'zh-CN', N'Get the BKAV change history for the invoice.'),
(N'BkavInvoice.Help.ButtonLink804', N'en-US', N'Get the public invoice link and save it to the group.'),
(N'BkavInvoice.Help.ButtonLink804', N'vi-VN', N'Lấy link hóa đơn và lưu vào nhóm.'),
(N'BkavInvoice.Help.ButtonLink804', N'zh-CN', N'Get the public invoice link and save it to the group.'),
(N'BkavInvoice.Help.ButtonPdf808', N'en-US', N'Download the PDF file and save the path to the group.'),
(N'BkavInvoice.Help.ButtonPdf808', N'vi-VN', N'Tải file PDF và lưu đường dẫn vào nhóm.'),
(N'BkavInvoice.Help.ButtonPdf808', N'zh-CN', N'Download the PDF file and save the path to the group.'),
(N'BkavInvoice.Help.ButtonXml809', N'en-US', N'Download the XML file and save the path to the group.'),
(N'BkavInvoice.Help.ButtonXml809', N'vi-VN', N'Tải file XML và lưu đường dẫn vào nhóm.'),
(N'BkavInvoice.Help.ButtonXml809', N'zh-CN', N'Download the XML file and save the path to the group.'),
(N'BkavInvoice.Help.ButtonTax904', N'en-US', N'Look up business information by tax code.'),
(N'BkavInvoice.Help.ButtonTax904', N'vi-VN', N'Tra cứu thông tin doanh nghiệp theo mã số thuế.'),
(N'BkavInvoice.Help.ButtonTax904', N'zh-CN', N'Look up business information by tax code.'),
(N'BkavInvoice.Help.ButtonAccount902', N'en-US', N'Create a BKAV demo account using demo information.'),
(N'BkavInvoice.Help.ButtonAccount902', N'vi-VN', N'Tạo tài khoản demo BKAV bằng thông tin mẫu.'),
(N'BkavInvoice.Help.ButtonAccount902', N'zh-CN', N'Create a BKAV demo account using demo information.'),
(N'BkavInvoice.Help.ButtonDll1001', N'en-US', N'Download BKAV DLL content by tax code.'),
(N'BkavInvoice.Help.ButtonDll1001', N'vi-VN', N'Tải nội dung DLL BKAV theo mã số thuế.'),
(N'BkavInvoice.Help.ButtonDll1001', N'zh-CN', N'Download BKAV DLL content by tax code.'),

(N'BkavInvoice.Credential.Title', N'en-US', N'BKAV credentials'),
(N'BkavInvoice.Credential.Title', N'vi-VN', N'Cấu hình BKAV'),
(N'BkavInvoice.Credential.Title', N'zh-CN', N'BKAV credentials'),
(N'BkavInvoice.Credential.LocalStorageNote', N'en-US', N'PartnerGuid and PartnerToken are saved in this browser only. Clear the browser cache entry when this computer should no longer issue BKAV invoices.'),
(N'BkavInvoice.Credential.LocalStorageNote', N'vi-VN', N'PartnerGuid và PartnerToken chỉ được lưu trong trình duyệt này. Hãy xóa cache khi máy này không còn dùng để phát hành hóa đơn BKAV.'),
(N'BkavInvoice.Credential.LocalStorageNote', N'zh-CN', N'PartnerGuid and PartnerToken are saved in this browser only. Clear the browser cache entry when this computer should no longer issue BKAV invoices.'),
(N'BkavInvoice.Credential.ServerFallback', N'en-US', N'Server BKAV credentials are configured and will be used when browser credentials are empty.'),
(N'BkavInvoice.Credential.ServerFallback', N'vi-VN', N'Server đã có cấu hình BKAV và sẽ được dùng khi credential trên trình duyệt trống.'),
(N'BkavInvoice.Credential.ServerFallback', N'zh-CN', N'Server BKAV credentials are configured and will be used when browser credentials are empty.'),
(N'BkavInvoice.Credential.PartnerGuid', N'en-US', N'PartnerGuid'),
(N'BkavInvoice.Credential.PartnerGuid', N'vi-VN', N'PartnerGuid'),
(N'BkavInvoice.Credential.PartnerGuid', N'zh-CN', N'PartnerGuid'),
(N'BkavInvoice.Credential.PartnerToken', N'en-US', N'PartnerToken'),
(N'BkavInvoice.Credential.PartnerToken', N'vi-VN', N'PartnerToken'),
(N'BkavInvoice.Credential.PartnerToken', N'zh-CN', N'PartnerToken'),
(N'BkavInvoice.Credential.Save', N'en-US', N'Save to browser'),
(N'BkavInvoice.Credential.Save', N'vi-VN', N'Lưu vào trình duyệt'),
(N'BkavInvoice.Credential.Save', N'zh-CN', N'Save to browser'),
(N'BkavInvoice.Credential.Clear', N'en-US', N'Clear cache'),
(N'BkavInvoice.Credential.Clear', N'vi-VN', N'Xóa cache'),
(N'BkavInvoice.Credential.Clear', N'zh-CN', N'Clear cache'),
(N'BkavInvoice.Credential.Saved', N'en-US', N'BKAV credentials saved in this browser.'),
(N'BkavInvoice.Credential.Saved', N'vi-VN', N'Đã lưu cấu hình BKAV trong trình duyệt này.'),
(N'BkavInvoice.Credential.Saved', N'zh-CN', N'BKAV credentials saved in this browser.'),
(N'BkavInvoice.Credential.Cleared', N'en-US', N'BKAV browser credential cache cleared.'),
(N'BkavInvoice.Credential.Cleared', N'vi-VN', N'Đã xóa cache cấu hình BKAV trên trình duyệt.'),
(N'BkavInvoice.Credential.Cleared', N'zh-CN', N'BKAV browser credential cache cleared.'),
(N'BkavInvoice.Credential.Required', N'en-US', N'PartnerGuid and PartnerToken are required.'),
(N'BkavInvoice.Credential.Required', N'vi-VN', N'Cần nhập đủ PartnerGuid và PartnerToken.'),
(N'BkavInvoice.Credential.Required', N'zh-CN', N'PartnerGuid and PartnerToken are required.'),
(N'BkavInvoice.Credential.SavedAt', N'en-US', N'Saved at: {0}'),
(N'BkavInvoice.Credential.SavedAt', N'vi-VN', N'Đã lưu lúc: {0}'),
(N'BkavInvoice.Credential.SavedAt', N'zh-CN', N'Saved at: {0}');

UPDATE target
SET target.Value = source.Value
FROM dbo.LocalizationResources AS target
INNER JOIN @Resources AS source
    ON source.ResourceKey = target.ResourceKey
   AND source.Culture = target.Culture;

INSERT INTO dbo.LocalizationResources (ResourceKey, Culture, Value)
SELECT source.ResourceKey, source.Culture, source.Value
FROM @Resources AS source
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.LocalizationResources AS target
    WHERE target.ResourceKey = source.ResourceKey
      AND target.Culture = source.Culture
);

SELECT ResourceKey, Culture, Value
FROM dbo.LocalizationResources
WHERE ResourceKey LIKE N'BkavInvoice.%'
ORDER BY ResourceKey, Culture;
GO
