-- Localization cho 5.15 Hóa Đơn Đầu Vào (import XML)
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.LocalizationResources', N'U') IS NULL
BEGIN
    THROW 50001, 'Table dbo.LocalizationResources does not exist.', 1;
END;
GO

DECLARE @Resources TABLE
(
    ResourceKey nvarchar(500) NOT NULL,
    Culture nvarchar(10) NOT NULL,
    Value nvarchar(max) NOT NULL,
    PRIMARY KEY (ResourceKey, Culture)
);

INSERT INTO @Resources (ResourceKey, Culture, Value)
VALUES
(N'HDDVXml.Menu', N'en-US', N'Input Invoices'),
(N'HDDVXml.Menu', N'vi-VN', N'Hóa Đơn Đầu Vào'),
(N'HDDVXml.Menu', N'zh-CN', N'Input Invoices'),
(N'HDDVXml.Title', N'en-US', N'Input Invoices'),
(N'HDDVXml.Title', N'vi-VN', N'Hóa Đơn Đầu Vào'),
(N'HDDVXml.Title', N'zh-CN', N'Input Invoices'),
(N'HDDVXml.Subtitle', N'en-US', N'Import e-invoice XML files, auto-link to HBL/MBL by bill number'),
(N'HDDVXml.Subtitle', N'vi-VN', N'Import file XML hóa đơn điện tử, tự gắn HBL/MBL theo số vận đơn'),
(N'HDDVXml.Subtitle', N'zh-CN', N'Import e-invoice XML files, auto-link to HBL/MBL by bill number'),
(N'HDDVXml.ImportXml', N'en-US', N'Import XML'),
(N'HDDVXml.ImportXml', N'vi-VN', N'Import XML'),
(N'HDDVXml.ImportXml', N'zh-CN', N'Import XML'),
(N'HDDVXml.Importing', N'en-US', N'Importing...'),
(N'HDDVXml.Importing', N'vi-VN', N'Đang import...'),
(N'HDDVXml.Importing', N'zh-CN', N'Importing...'),
(N'HDDVXml.Filter.FromDate', N'en-US', N'From date'),
(N'HDDVXml.Filter.FromDate', N'vi-VN', N'Từ ngày'),
(N'HDDVXml.Filter.FromDate', N'zh-CN', N'From date'),
(N'HDDVXml.Filter.ToDate', N'en-US', N'To date'),
(N'HDDVXml.Filter.ToDate', N'vi-VN', N'Đến ngày'),
(N'HDDVXml.Filter.ToDate', N'zh-CN', N'To date'),
(N'HDDVXml.Filter.All', N'en-US', N'All'),
(N'HDDVXml.Filter.All', N'vi-VN', N'Tất cả'),
(N'HDDVXml.Filter.All', N'zh-CN', N'All'),
(N'HDDVXml.Filter.Manual', N'en-US', N'Manual entry'),
(N'HDDVXml.Filter.Manual', N'vi-VN', N'Nhập tay'),
(N'HDDVXml.Filter.Manual', N'zh-CN', N'Manual entry'),
(N'HDDVXml.Filter.Search', N'en-US', N'Search'),
(N'HDDVXml.Filter.Search', N'vi-VN', N'Tìm kiếm'),
(N'HDDVXml.Filter.Search', N'zh-CN', N'Search'),
(N'HDDVXml.Filter.SearchHelp', N'en-US', N'Invoice no, serial, tax code, name, bill...'),
(N'HDDVXml.Filter.SearchHelp', N'vi-VN', N'Số HĐ, ký hiệu, MST, tên, số bill...'),
(N'HDDVXml.Filter.SearchHelp', N'zh-CN', N'Invoice no, serial, tax code, name, bill...'),
(N'HDDVXml.Col.Date', N'en-US', N'Invoice date'),
(N'HDDVXml.Col.Date', N'vi-VN', N'Ngày HĐ'),
(N'HDDVXml.Col.Date', N'zh-CN', N'Invoice date'),
(N'HDDVXml.Col.Serial', N'en-US', N'Serial'),
(N'HDDVXml.Col.Serial', N'vi-VN', N'Ký hiệu'),
(N'HDDVXml.Col.Serial', N'zh-CN', N'Serial'),
(N'HDDVXml.Col.InvoiceNo', N'en-US', N'Invoice no'),
(N'HDDVXml.Col.InvoiceNo', N'vi-VN', N'Số HĐ'),
(N'HDDVXml.Col.InvoiceNo', N'zh-CN', N'Invoice no'),
(N'HDDVXml.Col.Seller', N'en-US', N'Seller'),
(N'HDDVXml.Col.Seller', N'vi-VN', N'Người bán'),
(N'HDDVXml.Col.Seller', N'zh-CN', N'Seller'),
(N'HDDVXml.Col.Buyer', N'en-US', N'Buyer'),
(N'HDDVXml.Col.Buyer', N'vi-VN', N'Người mua'),
(N'HDDVXml.Col.Buyer', N'zh-CN', N'Buyer'),
(N'HDDVXml.Col.Partner', N'en-US', N'Partner'),
(N'HDDVXml.Col.Partner', N'vi-VN', N'Đối tác'),
(N'HDDVXml.Col.Partner', N'zh-CN', N'Partner'),
(N'HDDVXml.Col.Shipment', N'en-US', N'Shipment'),
(N'HDDVXml.Col.Shipment', N'vi-VN', N'Lô hàng'),
(N'HDDVXml.Col.Shipment', N'zh-CN', N'Shipment'),
(N'HDDVXml.Col.BeforeTax', N'en-US', N'Amount before tax'),
(N'HDDVXml.Col.BeforeTax', N'vi-VN', N'Tiền trước thuế'),
(N'HDDVXml.Col.BeforeTax', N'zh-CN', N'Amount before tax'),
(N'HDDVXml.Col.TaxAmount', N'en-US', N'Tax amount'),
(N'HDDVXml.Col.TaxAmount', N'vi-VN', N'Tiền thuế'),
(N'HDDVXml.Col.TaxAmount', N'zh-CN', N'Tax amount'),
(N'HDDVXml.Col.Source', N'en-US', N'Source'),
(N'HDDVXml.Col.Source', N'vi-VN', N'Nguồn'),
(N'HDDVXml.Col.Source', N'zh-CN', N'Source'),
(N'HDDVXml.CreateDebt', N'en-US', N'Create debt'),
(N'HDDVXml.CreateDebt', N'vi-VN', N'Tạo công nợ'),
(N'HDDVXml.CreateDebt', N'zh-CN', N'Create debt'),
(N'HDDVXml.LinkShipment', N'en-US', N'Link shipment'),
(N'HDDVXml.LinkShipment', N'vi-VN', N'Gắn lô hàng'),
(N'HDDVXml.LinkShipment', N'zh-CN', N'Link shipment'),
(N'HDDVXml.NotLinked', N'en-US', N'Not linked'),
(N'HDDVXml.NotLinked', N'vi-VN', N'Chưa gắn'),
(N'HDDVXml.NotLinked', N'zh-CN', N'Not linked'),
(N'HDDVXml.BillOnInvoice', N'en-US', N'Bill on invoice'),
(N'HDDVXml.BillOnInvoice', N'vi-VN', N'Số bill trên hóa đơn'),
(N'HDDVXml.BillOnInvoice', N'zh-CN', N'Bill on invoice'),
(N'HDDVXml.SearchBill', N'en-US', N'Search HBL/MBL number'),
(N'HDDVXml.SearchBill', N'vi-VN', N'Tìm số HBL/MBL'),
(N'HDDVXml.SearchBill', N'zh-CN', N'Search HBL/MBL number'),
(N'HDDVXml.Unlink', N'en-US', N'Unlink'),
(N'HDDVXml.Unlink', N'vi-VN', N'Bỏ gắn'),
(N'HDDVXml.Unlink', N'zh-CN', N'Unlink'),
(N'HDDVXml.Detail.General', N'en-US', N'General information'),
(N'HDDVXml.Detail.General', N'vi-VN', N'Thông tin chung'),
(N'HDDVXml.Detail.General', N'zh-CN', N'General information'),
(N'HDDVXml.Detail.Name', N'en-US', N'Goods/Services'),
(N'HDDVXml.Detail.Name', N'vi-VN', N'Tên hàng hóa, dịch vụ'),
(N'HDDVXml.Detail.Name', N'zh-CN', N'Goods/Services'),
(N'HDDVXml.Detail.Unit', N'en-US', N'Unit'),
(N'HDDVXml.Detail.Unit', N'vi-VN', N'ĐVT'),
(N'HDDVXml.Detail.Unit', N'zh-CN', N'Unit'),
(N'HDDVXml.Detail.TaxRate', N'en-US', N'Tax rate'),
(N'HDDVXml.Detail.TaxRate', N'vi-VN', N'Thuế suất'),
(N'HDDVXml.Detail.TaxRate', N'zh-CN', N'Tax rate'),
(N'HDDVXml.Detail.NoLines', N'en-US', N'No line details (not imported from XML).'),
(N'HDDVXml.Detail.NoLines', N'vi-VN', N'Không có chi tiết dòng hàng (không import từ XML).'),
(N'HDDVXml.Detail.NoLines', N'zh-CN', N'No line details (not imported from XML).'),
(N'HDDVXml.Msg.TooManyFiles', N'en-US', N'You can import at most {0} files at a time.'),
(N'HDDVXml.Msg.TooManyFiles', N'vi-VN', N'Chỉ được import tối đa {0} file mỗi lần.'),
(N'HDDVXml.Msg.TooManyFiles', N'zh-CN', N'You can import at most {0} files at a time.'),
(N'HDDVXml.Msg.InvalidFormat', N'en-US', N'Invalid file format. Please select an XML file.'),
(N'HDDVXml.Msg.InvalidFormat', N'vi-VN', N'Sai định dạng. Vui lòng chọn file XML.'),
(N'HDDVXml.Msg.InvalidFormat', N'zh-CN', N'Invalid file format. Please select an XML file.'),
(N'HDDVXml.Msg.EmptyFile', N'en-US', N'The file is empty.'),
(N'HDDVXml.Msg.EmptyFile', N'vi-VN', N'File rỗng.'),
(N'HDDVXml.Msg.EmptyFile', N'zh-CN', N'The file is empty.'),
(N'HDDVXml.Msg.FileTooLarge', N'en-US', N'The file exceeds the limit of {0}MB.'),
(N'HDDVXml.Msg.FileTooLarge', N'vi-VN', N'File vượt quá giới hạn {0}MB.'),
(N'HDDVXml.Msg.FileTooLarge', N'zh-CN', N'The file exceeds the limit of {0}MB.'),
(N'HDDVXml.Msg.Duplicate', N'en-US', N'Invoice {0} has already been imported. Skipped.'),
(N'HDDVXml.Msg.Duplicate', N'vi-VN', N'Hóa đơn {0} đã được import trước đó. Bỏ qua.'),
(N'HDDVXml.Msg.Duplicate', N'zh-CN', N'Invoice {0} has already been imported. Skipped.'),
(N'HDDVXml.Msg.CannotRead', N'en-US', N'Cannot read file: {0}'),
(N'HDDVXml.Msg.CannotRead', N'vi-VN', N'Không đọc được file: {0}'),
(N'HDDVXml.Msg.CannotRead', N'zh-CN', N'Cannot read file: {0}'),
(N'HDDVXml.Msg.Summary', N'en-US', N'Import finished: {0} created, {1} duplicated, {2} failed.'),
(N'HDDVXml.Msg.Summary', N'vi-VN', N'Import xong: {0} thành công, {1} trùng, {2} lỗi.'),
(N'HDDVXml.Msg.Summary', N'zh-CN', N'Import finished: {0} created, {1} duplicated, {2} failed.'),
(N'The file is not an e-invoice XML (HDon).', N'en-US', N'The file is not an e-invoice XML (HDon).'),
(N'The file is not an e-invoice XML (HDon).', N'vi-VN', N'File không phải XML hóa đơn điện tử (HDon).'),
(N'The file is not an e-invoice XML (HDon).', N'zh-CN', N'The file is not an e-invoice XML (HDon).'),
(N'Cannot read invoice number.', N'en-US', N'Cannot read invoice number.'),
(N'Cannot read invoice number.', N'vi-VN', N'Không đọc được số hóa đơn.'),
(N'Cannot read invoice number.', N'zh-CN', N'Cannot read invoice number.'),
(N'Cannot read seller tax code.', N'en-US', N'Cannot read seller tax code.'),
(N'Cannot read seller tax code.', N'vi-VN', N'Không đọc được MST người bán.'),
(N'Cannot read seller tax code.', N'zh-CN', N'Cannot read seller tax code.'),
(N'Cannot read buyer tax code.', N'en-US', N'Cannot read buyer tax code.'),
(N'Cannot read buyer tax code.', N'vi-VN', N'Không đọc được MST người mua.'),
(N'Cannot read buyer tax code.', N'zh-CN', N'Cannot read buyer tax code.');

MERGE dbo.LocalizationResources AS target
USING @Resources AS source
    ON target.ResourceKey = source.ResourceKey
   AND target.Culture = source.Culture
WHEN MATCHED THEN
    UPDATE SET Value = source.Value
WHEN NOT MATCHED THEN
    INSERT (ResourceKey, Culture, Value)
    VALUES (source.ResourceKey, source.Culture, source.Value);
GO
