-- Menu 6: Task (Shipment 6.0, Booking, Export HBL/AN/DO, Lenh Dieu Xe, TKHQ, Trucking, CO, LCCR, Container, Quan Ly Cont/Tau)
-- Depends on: Localization_GroupC_System.sql, Localization_Group2_Menu.sql, Localization_Group3_Menu.sql, Localization_Group5_Menu.sql (SelectOneHbl, HblApproved, MblApproved, Apply)
BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    'SelectOneBooking','CommitItemError','CommitHblError','RenderError','SendSuccess',
    'RecordNotFound','DeleteSuccess','SaveFailed','DeleteFailed','LoadDataFailed',
    'HouseTruckingNoEmpty','ShipmentGridColorsUpdated','NoEditFormForJobType','HblNumberEmpty',
    'LoadParamWeightFailed','SelectOneRowToEdit','SelectOneRowToDelete','SelectOneRowToExport','DataNotFoundToDelete',
    'EnterBothAddresses','DistanceCalcError',
    'BookingRequest_Create','BookingRequest_Edit','BookingRequest_Subtitle',
    'LenhDieuXe_Create','LenhDieuXe_Edit','LenhDieuXe_Subtitle',
    'TKHQ_Create','TKHQ_Edit','TKHQ_AddDetails','TKHQ_Subtitle',
    'TruckingReq_Create','TruckingReq_Edit','TruckingReq_Subtitle',
    'COConsult_Create','COConsult_Edit','COConsult_Subtitle','COResponse_Create',
    'Shipment6_Title','Shipment6_Subtitle',
    'Shipment_GridColors','Shipment_GridHeaderRow','Shipment_GridSelectedRow','Shipment_GridTabToolbar',
    'ExportHBL_Subtitle','ExportDO_Subtitle','ExportAN_Subtitle',
    'ParamWeight_Subtitle','LCCR_Subtitle','CamKet_Subtitle',
    'LCCR_RowAlreadyExportedNoEdit','LCCR_SelectContType','LCCR_QuantityMinOne','LCCR_OldOrdersNeedUpdate',
    'LCCR_BookingNotFoundForStock','LCCR_AlreadyExported','LCCR_InvalidBookingIdExport',
    'LCCR_ExportDateDataNotFound','LCCR_UpdateExportDateFailed',
    'QuanLyCont_Title','QuanLyCont_Subtitle','QuanLyTau_Title','QuanLyTau_Subtitle',
    'ContainerTracking_Subtitle','Reset','delete','cancel',
    'BindError','BookingNumberExhausted','RefInvNumberExhausted',
    'Shipment_Colors','Color','CBM','Size','Status','Collect','Invoice','Rate','Qty','DebitCreditFor',
    'QuanLyCont_Container','QuanLyCont_Principal','QuanLyCont_Owner','QuanLyCont_GateOut','QuanLyCont_EmptyReturn','QuanLyCont_Yard',
    'QuanLyTau_EstHours','QuanLyTau_Items','QuanLyTau_BasedOn','QuanLyTau_TurnTime',
    'CamKet_No','CamKet_PrivateWarehouse','CamKet_ReturnLocation',
    'sendnotification','BookingUpdatedNotify','BookingEmptyValue','BookingMoreChanges',
    'BookingHandleAdded','BookingHandleRemoved','Shipment_CheckListHblBooking'
);

INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('SelectOneBooking','en-US',N'You must select one booking.'),('SelectOneBooking','vi-VN',N'Bạn phải chọn 1 Booking.'),('SelectOneBooking','zh-CN',N'请选择一个订舱。'),
('CommitItemError','en-US',N'Error while saving item: {0}'),('CommitItemError','vi-VN',N'Lỗi khi lưu item: {0}'),('CommitItemError','zh-CN',N'保存项目时出错：{0}'),
('CommitHblError','en-US',N'Error while saving HBL: {0}'),('CommitHblError','vi-VN',N'Lỗi khi lưu HBL: {0}'),('CommitHblError','zh-CN',N'保存 HBL 时出错：{0}'),
('RenderError','en-US',N'Error while rendering: {0}'),('RenderError','vi-VN',N'Lỗi khi render: {0}'),('RenderError','zh-CN',N'渲染时出错：{0}'),
('SendSuccess','en-US',N'Sent successfully.'),('SendSuccess','vi-VN',N'Gửi thành công!'),('SendSuccess','zh-CN',N'发送成功。'),
('RecordNotFound','en-US',N'Record not found.'),('RecordNotFound','vi-VN',N'Không tìm thấy bản ghi.'),('RecordNotFound','zh-CN',N'未找到记录。'),
('DeleteSuccess','en-US',N'Deleted successfully.'),('DeleteSuccess','vi-VN',N'Đã xóa.'),('DeleteSuccess','zh-CN',N'删除成功。'),
('SaveFailed','en-US',N'Save failed: {0}'),('SaveFailed','vi-VN',N'Không lưu được: {0}'),('SaveFailed','zh-CN',N'保存失败：{0}'),
('DeleteFailed','en-US',N'Delete failed: {0}'),('DeleteFailed','vi-VN',N'Không xóa được: {0}'),('DeleteFailed','zh-CN',N'删除失败：{0}'),
('LoadDataFailed','en-US',N'Failed to load data: {0}'),('LoadDataFailed','vi-VN',N'Không tải được dữ liệu: {0}'),('LoadDataFailed','zh-CN',N'加载数据失败：{0}'),
('HouseTruckingNoEmpty','en-US',N'House trucking number is empty.'),('HouseTruckingNoEmpty','vi-VN',N'Số House Trucking trống.'),('HouseTruckingNoEmpty','zh-CN',N'House trucking 编号为空。'),
('ShipmentGridColorsUpdated','en-US',N'Shipment grid colors updated.'),('ShipmentGridColorsUpdated','vi-VN',N'Đã cập nhật màu lưới Shipment.'),('ShipmentGridColorsUpdated','zh-CN',N'已更新货运网格颜色。'),
('NoEditFormForJobType','en-US',N'No edit form for this job type.'),('NoEditFormForJobType','vi-VN',N'Chưa có form edit cho loại Job này!'),('NoEditFormForJobType','zh-CN',N'此作业类型暂无编辑表单。'),
('HblNumberEmpty','en-US',N'HBL number is empty.'),('HblNumberEmpty','vi-VN',N'Số HBL trống.'),('HblNumberEmpty','zh-CN',N'HBL 编号为空。'),
('LoadParamWeightFailed','en-US',N'Cannot load container weight parameters: {0}'),('LoadParamWeightFailed','vi-VN',N'Không tải được ParamTrongLuongCont: {0}'),('LoadParamWeightFailed','zh-CN',N'无法加载集装箱重量参数：{0}'),
('SelectOneRowToEdit','en-US',N'Please select one row to edit.'),('SelectOneRowToEdit','vi-VN',N'Vui lòng chọn 1 dòng để sửa.'),('SelectOneRowToEdit','zh-CN',N'请选择一行进行编辑。'),
('SelectOneRowToDelete','en-US',N'Please select one row to delete.'),('SelectOneRowToDelete','vi-VN',N'Vui lòng chọn 1 dòng để xoá.'),('SelectOneRowToDelete','zh-CN',N'请选择一行进行删除。'),
('SelectOneRowToExport','en-US',N'Please select one row to export.'),('SelectOneRowToExport','vi-VN',N'Vui lòng chọn 1 dòng để export.'),('SelectOneRowToExport','zh-CN',N'请选择一行进行导出。'),
('DataNotFoundToDelete','en-US',N'Data not found to delete.'),('DataNotFoundToDelete','vi-VN',N'Không tìm thấy dữ liệu để xoá.'),('DataNotFoundToDelete','zh-CN',N'未找到可删除的数据。'),
('EnterBothAddresses','en-US',N'Please enter both addresses.'),('EnterBothAddresses','vi-VN',N'Vui lòng nhập đủ 2 địa chỉ.'),('EnterBothAddresses','zh-CN',N'请输入两个地址。'),
('DistanceCalcError','en-US',N'Error calculating distance: {0}'),('DistanceCalcError','vi-VN',N'Có lỗi khi tính khoảng cách: {0}'),('DistanceCalcError','zh-CN',N'计算距离时出错：{0}'),
('BookingRequest_Create','en-US',N'Booking Request — Create'),('BookingRequest_Create','vi-VN',N'Booking Request — Tạo mới'),('BookingRequest_Create','zh-CN',N'订舱申请 — 新建'),
('BookingRequest_Edit','en-US',N'Booking Request — Edit'),('BookingRequest_Edit','vi-VN',N'Booking Request — Sửa'),('BookingRequest_Edit','zh-CN',N'订舱申请 — 编辑'),
('BookingRequest_Subtitle','en-US',N'Manage booking requests, status and shipment information'),('BookingRequest_Subtitle','vi-VN',N'Quản lý yêu cầu booking, trạng thái và thông tin shipment'),('BookingRequest_Subtitle','zh-CN',N'管理订舱申请、状态及货运信息'),
('LenhDieuXe_Create','en-US',N'Dispatch Order — Create'),('LenhDieuXe_Create','vi-VN',N'Lệnh Điều Xe — Tạo mới'),('LenhDieuXe_Create','zh-CN',N'调车令 — 新建'),
('LenhDieuXe_Edit','en-US',N'Dispatch Order — Edit'),('LenhDieuXe_Edit','vi-VN',N'Lệnh Điều Xe — Sửa'),('LenhDieuXe_Edit','zh-CN',N'调车令 — 编辑'),
('LenhDieuXe_Subtitle','en-US',N'Dispatch / trucking orders'),('LenhDieuXe_Subtitle','vi-VN',N'Lệnh điều xe / trucking'),('LenhDieuXe_Subtitle','zh-CN',N'调车/拖车指令'),
('TKHQ_Create','en-US',N'Customs Clearance — Create'),('TKHQ_Create','vi-VN',N'TKHQ — Tạo mới'),('TKHQ_Create','zh-CN',N'报关 — 新建'),
('TKHQ_Edit','en-US',N'Customs Clearance — Edit'),('TKHQ_Edit','vi-VN',N'TKHQ — Sửa'),('TKHQ_Edit','zh-CN',N'报关 — 编辑'),
('TKHQ_AddDetails','en-US',N'Customs Clearance — Details'),('TKHQ_AddDetails','vi-VN',N'TKHQ — Chi tiết'),('TKHQ_AddDetails','zh-CN',N'报关 — 明细'),
('TKHQ_Subtitle','en-US',N'Customs clearance requests'),('TKHQ_Subtitle','vi-VN',N'Yêu cầu thông quan'),('TKHQ_Subtitle','zh-CN',N'报关申请'),
('TruckingReq_Create','en-US',N'Trucking Requirements — Create'),('TruckingReq_Create','vi-VN',N'Yêu cầu Trucking — Tạo mới'),('TruckingReq_Create','zh-CN',N'拖车需求 — 新建'),
('TruckingReq_Edit','en-US',N'Trucking Requirements — Edit'),('TruckingReq_Edit','vi-VN',N'Yêu cầu Trucking — Sửa'),('TruckingReq_Edit','zh-CN',N'拖车需求 — 编辑'),
('TruckingReq_Subtitle','en-US',N'Trucking requests · distance estimate'),('TruckingReq_Subtitle','vi-VN',N'Yêu cầu trucking · ước tính khoảng cách'),('TruckingReq_Subtitle','zh-CN',N'拖车申请 · 距离估算'),
('COConsult_Create','en-US',N'Customs C/O Consultation — Create'),('COConsult_Create','vi-VN',N'Tư vấn thủ tục HQ C/O — Tạo mới'),('COConsult_Create','zh-CN',N'C/O 报关咨询 — 新建'),
('COConsult_Edit','en-US',N'Customs C/O Consultation — Edit'),('COConsult_Edit','vi-VN',N'Tư vấn thủ tục HQ C/O — Sửa'),('COConsult_Edit','zh-CN',N'C/O 报关咨询 — 编辑'),
('COConsult_Subtitle','en-US',N'Customs consultation C/O requests'),('COConsult_Subtitle','vi-VN',N'Yêu cầu tư vấn thủ tục HQ C/O'),('COConsult_Subtitle','zh-CN',N'C/O 报关咨询申请'),
('COResponse_Create','en-US',N'C/O Customs Response — Create'),('COResponse_Create','vi-VN',N'Phản hồi yêu cầu C/O — Tạo mới'),('COResponse_Create','zh-CN',N'C/O 报关回复 — 新建'),
('Shipment6_Title','en-US',N'Shipment Management'),('Shipment6_Title','vi-VN',N'Quản lý Shipment'),('Shipment6_Title','zh-CN',N'货运管理'),
('Shipment6_Subtitle','en-US',N'Manage jobs, MBL/HBL, trucking and customs in one workspace.'),('Shipment6_Subtitle','vi-VN',N'Quản lý job, MBL/HBL, trucking và thông quan trong cùng một màn hình.'),('Shipment6_Subtitle','zh-CN',N'在同一工作区管理作业、MBL/HBL、拖车及报关。'),
('Shipment_GridColors','en-US',N'Shipment grid colors'),('Shipment_GridColors','vi-VN',N'Màu lưới Shipment'),('Shipment_GridColors','zh-CN',N'货运网格颜色'),
('Shipment_GridHeaderRow','en-US',N'Header row'),('Shipment_GridHeaderRow','vi-VN',N'Hàng tiêu đề'),('Shipment_GridHeaderRow','zh-CN',N'标题行'),
('Shipment_GridSelectedRow','en-US',N'Selected row'),('Shipment_GridSelectedRow','vi-VN',N'Dòng đang chọn'),('Shipment_GridSelectedRow','zh-CN',N'选中行'),
('Shipment_GridTabToolbar','en-US',N'Tab toolbar'),('Shipment_GridTabToolbar','vi-VN',N'Thanh công cụ tab'),('Shipment_GridTabToolbar','zh-CN',N'选项卡工具栏'),
('ExportHBL_Subtitle','en-US',N'HBL list export'),('ExportHBL_Subtitle','vi-VN',N'Xuất danh sách HBL'),('ExportHBL_Subtitle','zh-CN',N'HBL 列表导出'),
('ExportDO_Subtitle','en-US',N'Delivery order export'),('ExportDO_Subtitle','vi-VN',N'Xuất Delivery Order'),('ExportDO_Subtitle','zh-CN',N'提货单导出'),
('ExportAN_Subtitle','en-US',N'Arrival notice export'),('ExportAN_Subtitle','vi-VN',N'Xuất Arrival Notice'),('ExportAN_Subtitle','zh-CN',N'到货通知导出'),
('ParamWeight_Subtitle','en-US',N'Max weight parameters by container type'),('ParamWeight_Subtitle','vi-VN',N'Tham số trọng lượng tối đa theo loại container'),('ParamWeight_Subtitle','zh-CN',N'按箱型的最大重量参数'),
('LCCR_Subtitle','en-US',N'Empty container release orders'),('LCCR_Subtitle','vi-VN',N'Lệnh cấp container rỗng'),('LCCR_Subtitle','zh-CN',N'空箱放箱指令'),
('CamKet_Subtitle','en-US',N'Empty return container commitments'),('CamKet_Subtitle','vi-VN',N'Cam kết mượn cont trả rỗng'),('CamKet_Subtitle','zh-CN',N'借箱还空承诺'),
('LCCR_RowAlreadyExportedNoEdit','en-US',N'This row is already exported and cannot be edited.'),('LCCR_RowAlreadyExportedNoEdit','vi-VN',N'Dòng này đã được export, không thể sửa.'),('LCCR_RowAlreadyExportedNoEdit','zh-CN',N'此行已导出，无法编辑。'),
('LCCR_SelectContType','en-US',N'Please select container type.'),('LCCR_SelectContType','vi-VN',N'Vui lòng chọn Cont Type.'),('LCCR_SelectContType','zh-CN',N'请选择箱型。'),
('LCCR_QuantityMinOne','en-US',N'Quantity must be at least 1.'),('LCCR_QuantityMinOne','vi-VN',N'Quantity phải >= 1.'),('LCCR_QuantityMinOne','zh-CN',N'数量必须 >= 1。'),
('LCCR_OldOrdersNeedUpdate','en-US',N'This booking has old orders without Cont Type/Quantity. Please edit them before creating a new order.'),('LCCR_OldOrdersNeedUpdate','vi-VN',N'Booking này đang có lệnh cũ chưa cập nhật Cont Type/Quantity. Vui lòng Edit các lệnh cũ trước khi tạo/sửa lệnh mới.'),('LCCR_OldOrdersNeedUpdate','zh-CN',N'此订舱有未更新箱型/数量的旧指令，请先编辑后再新建。'),
('LCCR_BookingNotFoundForStock','en-US',N'Booking not found for stock calculation.'),('LCCR_BookingNotFoundForStock','vi-VN',N'Không tìm thấy Booking để tính tồn.'),('LCCR_BookingNotFoundForStock','zh-CN',N'未找到用于计算库存的订舱。'),
('LCCR_AlreadyExported','en-US',N'This row is already exported.'),('LCCR_AlreadyExported','vi-VN',N'Dòng này đã được export rồi.'),('LCCR_AlreadyExported','zh-CN',N'此行已导出。'),
('LCCR_InvalidBookingIdExport','en-US',N'Invalid BookingId for export.'),('LCCR_InvalidBookingIdExport','vi-VN',N'BookingId không hợp lệ để export.'),('LCCR_InvalidBookingIdExport','zh-CN',N'导出用的 BookingId 无效。'),
('LCCR_ExportDateDataNotFound','en-US',N'Data not found to update export date.'),('LCCR_ExportDateDataNotFound','vi-VN',N'Không tìm thấy dữ liệu để cập nhật ExportDate.'),('LCCR_ExportDateDataNotFound','zh-CN',N'未找到可更新导出日期的数据。'),
('LCCR_UpdateExportDateFailed','en-US',N'Failed to update ExportDate/UserExport: {0}'),('LCCR_UpdateExportDateFailed','vi-VN',N'Không thể cập nhật ExportDate/UserExport: {0}'),('LCCR_UpdateExportDateFailed','zh-CN',N'更新 ExportDate/UserExport 失败：{0}'),
('QuanLyCont_Title','en-US',N'6.13 Container management'),('QuanLyCont_Title','vi-VN',N'6.13 Quản lý container'),('QuanLyCont_Title','zh-CN',N'6.13 集装箱管理'),
('QuanLyCont_Subtitle','en-US',N'Sheet VNSGN — QUAN LY CONT'),('QuanLyCont_Subtitle','vi-VN',N'Sheet VNSGN — QUAN LY CONT'),('QuanLyCont_Subtitle','zh-CN',N'工作表 VNSGN — 集装箱管理'),
('QuanLyTau_Title','en-US',N'6.14 Vessel / PDA management'),('QuanLyTau_Title','vi-VN',N'6.14 Quản lý tàu / PDA'),('QuanLyTau_Title','zh-CN',N'6.14 船舶/PDA 管理'),
('QuanLyTau_Subtitle','en-US',N'Sheet PDA — QUAN LY TAU'),('QuanLyTau_Subtitle','vi-VN',N'Sheet PDA — QUAN LY TAU'),('QuanLyTau_Subtitle','zh-CN',N'工作表 PDA — 船舶管理'),
('ContainerTracking_Subtitle','en-US',N'Track containers by MBL / HBL'),('ContainerTracking_Subtitle','vi-VN',N'Theo dõi container theo MBL / HBL'),('ContainerTracking_Subtitle','zh-CN',N'按 MBL/HBL 跟踪集装箱'),
('Reset','en-US',N'Reset'),('Reset','vi-VN',N'Đặt lại'),('Reset','zh-CN',N'重置'),
('delete','en-US',N'Delete'),('delete','vi-VN',N'Xóa'),('delete','zh-CN',N'删除'),
('cancel','en-US',N'Cancel'),('cancel','vi-VN',N'Hủy'),('cancel','zh-CN',N'取消'),
('BindError','en-US',N'Error while binding: {0}'),('BindError','vi-VN',N'Lỗi khi bind: {0}'),('BindError','zh-CN',N'绑定时出错：{0}'),
('BookingNumberExhausted','en-US',N'Booking number exhausted. Please contact admin.'),('BookingNumberExhausted','vi-VN',N'Hết Số Booking. Liên hệ Admin.'),('BookingNumberExhausted','zh-CN',N'订舱号已用完，请联系管理员。'),
('RefInvNumberExhausted','en-US',N'Ref INV number exhausted. Please contact admin.'),('RefInvNumberExhausted','vi-VN',N'Hết Số Ref INV. Liên hệ Admin.'),('RefInvNumberExhausted','zh-CN',N'Ref INV 号已用完，请联系管理员。'),
('Shipment_Colors','en-US',N'Colors'),('Shipment_Colors','vi-VN',N'Màu sắc'),('Shipment_Colors','zh-CN',N'颜色'),
('Color','en-US',N'Color'),('Color','vi-VN',N'Màu'),('Color','zh-CN',N'颜色'),
('CBM','en-US',N'CBM'),('CBM','vi-VN',N'CBM'),('CBM','zh-CN',N'CBM'),
('Size','en-US',N'Size'),('Size','vi-VN',N'Size'),('Size','zh-CN',N'尺寸'),
('Status','en-US',N'Status'),('Status','vi-VN',N'Trạng thái'),('Status','zh-CN',N'状态'),
('Collect','en-US',N'Collect'),('Collect','vi-VN',N'Collect'),('Collect','zh-CN',N'Collect'),
('Invoice','en-US',N'Invoice'),('Invoice','vi-VN',N'Hóa đơn'),('Invoice','zh-CN',N'发票'),
('Rate','en-US',N'Rate'),('Rate','vi-VN',N'Rate'),('Rate','zh-CN',N'费率'),
('Qty','en-US',N'Qty'),('Qty','vi-VN',N'Qty'),('Qty','zh-CN',N'数量'),
('DebitCreditFor','en-US',N'Debit / Credit — {0}'),('DebitCreditFor','vi-VN',N'Debit / Credit — {0}'),('DebitCreditFor','zh-CN',N'借记/贷记 — {0}'),
('QuanLyCont_Container','en-US',N'Container'),('QuanLyCont_Container','vi-VN',N'Container'),('QuanLyCont_Container','zh-CN',N'集装箱'),
('QuanLyCont_Principal','en-US',N'Principal'),('QuanLyCont_Principal','vi-VN',N'Principal'),('QuanLyCont_Principal','zh-CN',N'Principal'),
('QuanLyCont_Owner','en-US',N'Container owner'),('QuanLyCont_Owner','vi-VN',N'Chủ cont'),('QuanLyCont_Owner','zh-CN',N'箱主'),
('QuanLyCont_GateOut','en-US',N'Gate out'),('QuanLyCont_GateOut','vi-VN',N'Gate out'),('QuanLyCont_GateOut','zh-CN',N'出闸'),
('QuanLyCont_EmptyReturn','en-US',N'Empty return'),('QuanLyCont_EmptyReturn','vi-VN',N'Trả rỗng'),('QuanLyCont_EmptyReturn','zh-CN',N'还空'),
('QuanLyCont_Yard','en-US',N'Yard'),('QuanLyCont_Yard','vi-VN',N'Bãi'),('QuanLyCont_Yard','zh-CN',N'堆场'),
('QuanLyTau_EstHours','en-US',N'Est. hours'),('QuanLyTau_EstHours','vi-VN',N'Est. giờ'),('QuanLyTau_EstHours','zh-CN',N'预估小时'),
('QuanLyTau_Items','en-US',N'Items'),('QuanLyTau_Items','vi-VN',N'Khoản mục'),('QuanLyTau_Items','zh-CN',N'项目'),
('QuanLyTau_BasedOn','en-US',N'Based on'),('QuanLyTau_BasedOn','vi-VN',N'Cơ sở'),('QuanLyTau_BasedOn','zh-CN',N'依据'),
('QuanLyTau_TurnTime','en-US',N'Turn/Time'),('QuanLyTau_TurnTime','vi-VN',N'Turn/Time'),('QuanLyTau_TurnTime','zh-CN',N'Turn/Time'),
('CamKet_No','en-US',N'Commitment no.'),('CamKet_No','vi-VN',N'Số cam kết'),('CamKet_No','zh-CN',N'承诺编号'),
('CamKet_PrivateWarehouse','en-US',N'Private warehouse'),('CamKet_PrivateWarehouse','vi-VN',N'Kho riêng'),('CamKet_PrivateWarehouse','zh-CN',N'专用仓库'),
('CamKet_ReturnLocation','en-US',N'Empty return location'),('CamKet_ReturnLocation','vi-VN',N'Nơi trả rỗng'),('CamKet_ReturnLocation','zh-CN',N'还空地点'),
('sendnotification','en-US',N'Send notification'),('sendnotification','vi-VN',N'Gửi thông báo'),('sendnotification','zh-CN',N'发送通知'),
('BookingUpdatedNotify','en-US',N'Booking {0} updated by {1}.'),('BookingUpdatedNotify','vi-VN',N'Booking {0} đã được cập nhật bởi {1}.'),('BookingUpdatedNotify','zh-CN',N'订舱 {0} 已由 {1} 更新。'),
('BookingEmptyValue','en-US',N'(empty)'),('BookingEmptyValue','vi-VN',N'(trống)'),('BookingEmptyValue','zh-CN',N'(空)'),
('BookingMoreChanges','en-US',N'... and {0} more change(s).'),('BookingMoreChanges','vi-VN',N'... và {0} thay đổi khác.'),('BookingMoreChanges','zh-CN',N'... 以及其他 {0} 项更改。'),
('BookingHandleAdded','en-US',N'User handle added: {0}'),('BookingHandleAdded','vi-VN',N'User handle thêm: {0}'),('BookingHandleAdded','zh-CN',N'新增经办人：{0}'),
('BookingHandleRemoved','en-US',N'User handle removed: {0}'),('BookingHandleRemoved','vi-VN',N'User handle gỡ: {0}'),('BookingHandleRemoved','zh-CN',N'移除经办人：{0}'),
('Shipment_CheckListHblBooking','en-US',N'Check List HBL-Booking'),('Shipment_CheckListHblBooking','vi-VN',N'Check List HBL-Booking'),('Shipment_CheckListHblBooking','zh-CN',N'HBL-订舱核对清单');

COMMIT;
-- After run: DbStringLocalizerFactory.ClearCache() or restart app.
