-- Menu 7: Statistical Report (7.1–7.7)
-- Depends on: Group C, Group 2 (NoData, Processing, SearchCustomers, FromToDate, Total, Type, Customer, etc.), Group 6 (CBM, Qty, Rate, Note)
BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    'NoPermission_ViewReport','EnterContainerNo','LoadReportFailed','ExportError',
    'SelectFromToDate','NoHblInRange',
    'Export','ExportCostReport','Search','Date','Debit','Credit','Branch','Department','Job No',
    'ShipStat_Subtitle','ShipStat_InvoiceNo','ShipStat_PickupDate','ShipStat_ImportExport',
    'ShipStat_PickupLocation','ShipStat_EmptyContLocation','ShipStat_DeliveryLocation',
    'ShipStat_FreightCharge','ShipStat_Surcharge','ShipStat_InvoiceTotal',
    'ShipStat_LiftOnFee','ShipStat_LiftOnInvoiceNo','ShipStat_LiftOffFee','ShipStat_LiftOffInvoiceNo',
    'ShipStat_WeighFee','ShipStat_Stevedoring','ShipStat_OtherFee','ShipStat_TotalFee',
    'HBLReports_Subtitle','HBLReports_ModeNet','HBLReports_FilterHbl',
    'TruckingReport_Subtitle','TruckingReport_Export','TruckingReport_TruckReqNo','TruckingReport_LenhNo',
    'TruckingReport_Pickup','TruckingReport_Dropoff','TruckingReport_QtyPkgsCont','TruckingReport_TruckNo',
    'TruckingReport_DomesticFreight','TruckingReport_LiftOnFee','TruckingReport_LiftOffFee',
    'TruckingReport_LocalCharge','TruckingReport_IntlFreight','TruckingReport_OtherFee',
    'TruckingReport_Vat8','TruckingReport_Subtotal','TruckingReport_InvoiceNos',
    'AgentReport_Subtitle','AgentReport_Export','AgentReport_JobFileNo','AgentReport_AgentName',
    'AgentReport_Carrier','AgentReport_MBL','AgentReport_Client',
    'DebtReport_Subtitle','DebtReport_SelectType','DebtReport_MainCustomer','DebtReport_Unit',
    'DebtReport_TotalDebit','DebtReport_TotalCredit','DebtReport_TotalOutputInvoice',
    'DebtReport_TotalInputInvoice','DebtReport_InvoiceNo',
    'ContainerDetail_Subtitle','ContainerDetail_Active','ContainerDetail_Decommissioned',
    'ContainerDetail_IsoCode','ContainerDetail_OwnerType','ContainerDetail_Owner','ContainerDetail_StatusCont',
    'ContainerDetail_Condition','ContainerDetail_Seal','ContainerDetail_GrossWeight','ContainerDetail_NetWeight',
    'ContainerDetail_Pkgs','ContainerDetail_InDepot','ContainerDetail_InPort','ContainerDetail_NvoccStatus',
    'ContainerDetail_Decommission',
    'ContainerProfit_Subtitle','ContainerProfit_EnterContainer','ContainerProfit_TotalDebitUsd',
    'ContainerProfit_TotalCreditUsd','ContainerProfit_ProfitUsd','ContainerProfit_TotalDebitVnd',
    'ContainerProfit_TotalCreditVnd','ContainerProfit_ProfitVnd','ContainerProfit_Source',
    'ContainerProfit_Charge','ContainerProfit_OriginalAmount','ContainerProfit_AmountUsd','ContainerProfit_AmountVnd'
);

INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('NoPermission_ViewReport','en-US',N'You do not have permission to view this report.'),('NoPermission_ViewReport','vi-VN',N'Bạn không có quyền xem báo cáo này.'),('NoPermission_ViewReport','zh-CN',N'您没有查看此报告的权限。'),
('EnterContainerNo','en-US',N'Please enter container number.'),('EnterContainerNo','vi-VN',N'Vui lòng nhập Container No.'),('EnterContainerNo','zh-CN',N'请输入集装箱号。'),
('LoadReportFailed','en-US',N'Cannot load report: {0}'),('LoadReportFailed','vi-VN',N'Không tải được báo cáo: {0}'),('LoadReportFailed','zh-CN',N'无法加载报告：{0}'),
('ExportError','en-US',N'Export error: {0}'),('ExportError','vi-VN',N'Lỗi export: {0}'),('ExportError','zh-CN',N'导出错误：{0}'),
('SelectFromToDate','en-US',N'Please select from/to date.'),('SelectFromToDate','vi-VN',N'Vui lòng chọn từ/đến ngày.'),('SelectFromToDate','zh-CN',N'请选择起止日期。'),
('NoHblInRange','en-US',N'No HBL found in selected range.'),('NoHblInRange','vi-VN',N'Không tìm thấy HBL trong khoảng thời gian.'),('NoHblInRange','zh-CN',N'所选时间范围内未找到 HBL。'),
('Export','en-US',N'Export'),('Export','vi-VN',N'Xuất'),('Export','zh-CN',N'导出'),
('ExportCostReport','en-US',N'Export cost report'),('ExportCostReport','vi-VN',N'Xuất báo cáo chi phí'),('ExportCostReport','zh-CN',N'导出成本报告'),
('Search','en-US',N'Search'),('Search','vi-VN',N'Tìm'),('Search','zh-CN',N'搜索'),
('Date','en-US',N'Date'),('Date','vi-VN',N'Ngày'),('Date','zh-CN',N'日期'),
('Debit','en-US',N'Debit'),('Debit','vi-VN',N'Debit'),('Debit','zh-CN',N'借记'),
('Credit','en-US',N'Credit'),('Credit','vi-VN',N'Credit'),('Credit','zh-CN',N'贷记'),
('Branch','en-US',N'Branch'),('Branch','vi-VN',N'Chi nhánh'),('Branch','zh-CN',N'分支'),
('Department','en-US',N'Department'),('Department','vi-VN',N'Phòng ban'),('Department','zh-CN',N'部门'),
('Job No','en-US',N'Job No'),('Job No','vi-VN',N'Job No'),('Job No','zh-CN',N'作业号'),
('ShipStat_Subtitle','en-US',N'7.1 · Shipment KPI and export'),('ShipStat_Subtitle','vi-VN',N'7.1 · KPI shipment và xuất báo cáo'),('ShipStat_Subtitle','zh-CN',N'7.1 · 货运 KPI 与导出'),
('ShipStat_InvoiceNo','en-US',N'Invoice no.'),('ShipStat_InvoiceNo','vi-VN',N'Số HĐ'),('ShipStat_InvoiceNo','zh-CN',N'发票号'),
('ShipStat_PickupDate','en-US',N'Pickup date'),('ShipStat_PickupDate','vi-VN',N'Ngày lấy hàng'),('ShipStat_PickupDate','zh-CN',N'提货日期'),
('ShipStat_ImportExport','en-US',N'Import/Export'),('ShipStat_ImportExport','vi-VN',N'Xuất/Nhập'),('ShipStat_ImportExport','zh-CN',N'进/出口'),
('ShipStat_PickupLocation','en-US',N'Pickup location'),('ShipStat_PickupLocation','vi-VN',N'Địa điểm nhận hàng'),('ShipStat_PickupLocation','zh-CN',N'收货地点'),
('ShipStat_EmptyContLocation','en-US',N'Empty container location'),('ShipStat_EmptyContLocation','vi-VN',N'Vị trí cont rỗng'),('ShipStat_EmptyContLocation','zh-CN',N'空箱位置'),
('ShipStat_DeliveryLocation','en-US',N'Delivery location'),('ShipStat_DeliveryLocation','vi-VN',N'Địa điểm trả hàng'),('ShipStat_DeliveryLocation','zh-CN',N'交货地点'),
('ShipStat_FreightCharge','en-US',N'Freight charge'),('ShipStat_FreightCharge','vi-VN',N'Cước vận chuyển'),('ShipStat_FreightCharge','zh-CN',N'运费'),
('ShipStat_Surcharge','en-US',N'Surcharge'),('ShipStat_Surcharge','vi-VN',N'Phụ thu'),('ShipStat_Surcharge','zh-CN',N'附加费'),
('ShipStat_InvoiceTotal','en-US',N'Invoice total'),('ShipStat_InvoiceTotal','vi-VN',N'Tổng tiền HĐ'),('ShipStat_InvoiceTotal','zh-CN',N'发票总额'),
('ShipStat_LiftOnFee','en-US',N'Lift-on fee'),('ShipStat_LiftOnFee','vi-VN',N'Phí nâng'),('ShipStat_LiftOnFee','zh-CN',N'吊上费'),
('ShipStat_LiftOnInvoiceNo','en-US',N'Lift-on invoice no.'),('ShipStat_LiftOnInvoiceNo','vi-VN',N'Số HĐ nâng'),('ShipStat_LiftOnInvoiceNo','zh-CN',N'吊上发票号'),
('ShipStat_LiftOffFee','en-US',N'Lift-off fee'),('ShipStat_LiftOffFee','vi-VN',N'Phí hạ'),('ShipStat_LiftOffFee','zh-CN',N'吊下费'),
('ShipStat_LiftOffInvoiceNo','en-US',N'Lift-off invoice no.'),('ShipStat_LiftOffInvoiceNo','vi-VN',N'Số HĐ hạ'),('ShipStat_LiftOffInvoiceNo','zh-CN',N'吊下发票号'),
('ShipStat_WeighFee','en-US',N'Weighing fee'),('ShipStat_WeighFee','vi-VN',N'Phí cân'),('ShipStat_WeighFee','zh-CN',N'过磅费'),
('ShipStat_Stevedoring','en-US',N'Stevedoring'),('ShipStat_Stevedoring','vi-VN',N'Bốc xếp'),('ShipStat_Stevedoring','zh-CN',N'装卸费'),
('ShipStat_OtherFee','en-US',N'Other fees'),('ShipStat_OtherFee','vi-VN',N'Phí khác'),('ShipStat_OtherFee','zh-CN',N'其他费用'),
('ShipStat_TotalFee','en-US',N'Total fees'),('ShipStat_TotalFee','vi-VN',N'Tổng phí'),('ShipStat_TotalFee','zh-CN',N'费用合计'),
('HBLReports_Subtitle','en-US',N'7.2 · Charge and net/debit/credit matrix'),('HBLReports_Subtitle','vi-VN',N'7.2 · Ma trận phí và net/debit/credit'),('HBLReports_Subtitle','zh-CN',N'7.2 · 费用与 net/借贷矩阵'),
('HBLReports_ModeNet','en-US',N'Net (Debit - Credit)'),('HBLReports_ModeNet','vi-VN',N'Net (Debit - Credit)'),('HBLReports_ModeNet','zh-CN',N'净额 (Debit - Credit)'),
('HBLReports_FilterHbl','en-US',N'Filter HBL...'),('HBLReports_FilterHbl','vi-VN',N'Lọc HBL...'),('HBLReports_FilterHbl','zh-CN',N'筛选 HBL...'),
('TruckingReport_Subtitle','en-US',N'Trucking operations and cost summary'),('TruckingReport_Subtitle','vi-VN',N'Tổng hợp vận hành và chi phí trucking'),('TruckingReport_Subtitle','zh-CN',N'拖车运营与成本汇总'),
('TruckingReport_Export','en-US',N'Export 7.3'),('TruckingReport_Export','vi-VN',N'Xuất 7.3'),('TruckingReport_Export','zh-CN',N'导出 7.3'),
('TruckingReport_TruckReqNo','en-US',N'Truck req. no.'),('TruckingReport_TruckReqNo','vi-VN',N'Truck Req No'),('TruckingReport_TruckReqNo','zh-CN',N'拖车申请号'),
('TruckingReport_LenhNo','en-US',N'Dispatch no.'),('TruckingReport_LenhNo','vi-VN',N'Lenh No'),('TruckingReport_LenhNo','zh-CN',N'调车令号'),
('TruckingReport_Pickup','en-US',N'Pickup'),('TruckingReport_Pickup','vi-VN',N'Pickup'),('TruckingReport_Pickup','zh-CN',N'提货'),
('TruckingReport_Dropoff','en-US',N'Dropoff'),('TruckingReport_Dropoff','vi-VN',N'Dropoff'),('TruckingReport_Dropoff','zh-CN',N'卸货'),
('TruckingReport_QtyPkgsCont','en-US',N'Qty (pkgs/cont)'),('TruckingReport_QtyPkgsCont','vi-VN',N'Qty (Pkgs/Cont)'),('TruckingReport_QtyPkgsCont','zh-CN',N'数量 (件/箱)'),
('TruckingReport_TruckNo','en-US',N'Truck no.'),('TruckingReport_TruckNo','vi-VN',N'Truck No'),('TruckingReport_TruckNo','zh-CN',N'车牌号'),
('TruckingReport_DomesticFreight','en-US',N'Domestic freight'),('TruckingReport_DomesticFreight','vi-VN',N'Cước VC nội địa'),('TruckingReport_DomesticFreight','zh-CN',N'国内运费'),
('TruckingReport_LiftOnFee','en-US',N'Lift-on fee'),('TruckingReport_LiftOnFee','vi-VN',N'Phí nâng'),('TruckingReport_LiftOnFee','zh-CN',N'吊上费'),
('TruckingReport_LiftOffFee','en-US',N'Lift-off fee'),('TruckingReport_LiftOffFee','vi-VN',N'Phí hạ'),('TruckingReport_LiftOffFee','zh-CN',N'吊下费'),
('TruckingReport_LocalCharge','en-US',N'Local charge'),('TruckingReport_LocalCharge','vi-VN',N'Local Charge'),('TruckingReport_LocalCharge','zh-CN',N'本地费用'),
('TruckingReport_IntlFreight','en-US',N'International freight'),('TruckingReport_IntlFreight','vi-VN',N'Cước VC quốc tế'),('TruckingReport_IntlFreight','zh-CN',N'国际运费'),
('TruckingReport_OtherFee','en-US',N'Other cost'),('TruckingReport_OtherFee','vi-VN',N'Chi phí khác'),('TruckingReport_OtherFee','zh-CN',N'其他费用'),
('TruckingReport_Vat8','en-US',N'VAT 8%'),('TruckingReport_Vat8','vi-VN',N'VAT 8%'),('TruckingReport_Vat8','zh-CN',N'VAT 8%'),
('TruckingReport_Subtotal','en-US',N'Subtotal'),('TruckingReport_Subtotal','vi-VN',N'Thành tiền'),('TruckingReport_Subtotal','zh-CN',N'小计'),
('TruckingReport_InvoiceNos','en-US',N'Invoice nos.'),('TruckingReport_InvoiceNos','vi-VN',N'Invoice Nos'),('TruckingReport_InvoiceNos','zh-CN',N'发票号'),
('AgentReport_Subtitle','en-US',N'Agent amount summary by job / BL'),('AgentReport_Subtitle','vi-VN',N'Tổng hợp số tiền agent theo job / BL'),('AgentReport_Subtitle','zh-CN',N'按作业/BL 的代理金额汇总'),
('AgentReport_Export','en-US',N'Export 7.4'),('AgentReport_Export','vi-VN',N'Xuất 7.4'),('AgentReport_Export','zh-CN',N'导出 7.4'),
('AgentReport_JobFileNo','en-US',N'Job file no.'),('AgentReport_JobFileNo','vi-VN',N'JOB FILE NO'),('AgentReport_JobFileNo','zh-CN',N'作业档案号'),
('AgentReport_AgentName','en-US',N'Agent name'),('AgentReport_AgentName','vi-VN',N'AGENT Name'),('AgentReport_AgentName','zh-CN',N'代理名称'),
('AgentReport_Carrier','en-US',N'Carrier'),('AgentReport_Carrier','vi-VN',N'CARRIER'),('AgentReport_Carrier','zh-CN',N'承运人'),
('AgentReport_MBL','en-US',N'MB/L'),('AgentReport_MBL','vi-VN',N'MB/L'),('AgentReport_MBL','zh-CN',N'MB/L'),
('AgentReport_Client','en-US',N'Client'),('AgentReport_Client','vi-VN',N'CLIENT'),('AgentReport_Client','zh-CN',N'客户'),
('DebtReport_Subtitle','en-US',N'7.5 · Agent debit / credit by HBL and invoice'),('DebtReport_Subtitle','vi-VN',N'7.5 · Debit/credit agent theo HBL và invoice'),('DebtReport_Subtitle','zh-CN',N'7.5 · 按 HBL/发票的代理借贷'),
('DebtReport_SelectType','en-US',N'Select report type'),('DebtReport_SelectType','vi-VN',N'Chọn loại báo cáo'),('DebtReport_SelectType','zh-CN',N'选择报告类型'),
('DebtReport_MainCustomer','en-US',N'Main customer'),('DebtReport_MainCustomer','vi-VN',N'MAIN CUSTOMER'),('DebtReport_MainCustomer','zh-CN',N'主客户'),
('DebtReport_Unit','en-US',N'Unit'),('DebtReport_Unit','vi-VN',N'UNIT'),('DebtReport_Unit','zh-CN',N'单位'),
('DebtReport_TotalDebit','en-US',N'Total debit'),('DebtReport_TotalDebit','vi-VN',N'TOTAL DEBIT'),('DebtReport_TotalDebit','zh-CN',N'借记合计'),
('DebtReport_TotalCredit','en-US',N'Total credit'),('DebtReport_TotalCredit','vi-VN',N'TOTAL CREDIT'),('DebtReport_TotalCredit','zh-CN',N'贷记合计'),
('DebtReport_TotalOutputInvoice','en-US',N'Total output invoice'),('DebtReport_TotalOutputInvoice','vi-VN',N'TOTAL HÓA ĐƠN ĐẦU RA'),('DebtReport_TotalOutputInvoice','zh-CN',N'销项发票合计'),
('DebtReport_TotalInputInvoice','en-US',N'Total input invoice'),('DebtReport_TotalInputInvoice','vi-VN',N'TOTAL HÓA ĐƠN ĐẦU VÀO'),('DebtReport_TotalInputInvoice','zh-CN',N'进项发票合计'),
('DebtReport_InvoiceNo','en-US',N'Invoice no.'),('DebtReport_InvoiceNo','vi-VN',N'INVOICE NO'),('DebtReport_InvoiceNo','zh-CN',N'发票号'),
('ContainerDetail_Subtitle','en-US',N'Container lifecycle details'),('ContainerDetail_Subtitle','vi-VN',N'Chi tiết vòng đời container'),('ContainerDetail_Subtitle','zh-CN',N'集装箱生命周期明细'),
('ContainerDetail_Active','en-US',N'Active'),('ContainerDetail_Active','vi-VN',N'Đang hoạt động'),('ContainerDetail_Active','zh-CN',N'在用'),
('ContainerDetail_Decommissioned','en-US',N'Decommissioned'),('ContainerDetail_Decommissioned','vi-VN',N'Đã ngừng sử dụng'),('ContainerDetail_Decommissioned','zh-CN',N'已停用'),
('ContainerDetail_IsoCode','en-US',N'ISO code'),('ContainerDetail_IsoCode','vi-VN',N'ISO Code'),('ContainerDetail_IsoCode','zh-CN',N'ISO 代码'),
('ContainerDetail_OwnerType','en-US',N'Owner type'),('ContainerDetail_OwnerType','vi-VN',N'Owner Type'),('ContainerDetail_OwnerType','zh-CN',N'箱主类型'),
('ContainerDetail_Owner','en-US',N'Owner'),('ContainerDetail_Owner','vi-VN',N'Owner'),('ContainerDetail_Owner','zh-CN',N'箱主'),
('ContainerDetail_StatusCont','en-US',N'Container status'),('ContainerDetail_StatusCont','vi-VN',N'Status Cont'),('ContainerDetail_StatusCont','zh-CN',N'箱状态'),
('ContainerDetail_Condition','en-US',N'Condition'),('ContainerDetail_Condition','vi-VN',N'Condition'),('ContainerDetail_Condition','zh-CN',N'状况'),
('ContainerDetail_Seal','en-US',N'Seal'),('ContainerDetail_Seal','vi-VN',N'Seal'),('ContainerDetail_Seal','zh-CN',N'铅封'),
('ContainerDetail_GrossWeight','en-US',N'Gross weight'),('ContainerDetail_GrossWeight','vi-VN',N'Gross Weight'),('ContainerDetail_GrossWeight','zh-CN',N'毛重'),
('ContainerDetail_NetWeight','en-US',N'Net weight'),('ContainerDetail_NetWeight','vi-VN',N'Net Weight'),('ContainerDetail_NetWeight','zh-CN',N'净重'),
('ContainerDetail_Pkgs','en-US',N'Packages'),('ContainerDetail_Pkgs','vi-VN',N'Pkgs'),('ContainerDetail_Pkgs','zh-CN',N'件数'),
('ContainerDetail_InDepot','en-US',N'In depot'),('ContainerDetail_InDepot','vi-VN',N'In Depot'),('ContainerDetail_InDepot','zh-CN',N'在堆场'),
('ContainerDetail_InPort','en-US',N'In port'),('ContainerDetail_InPort','vi-VN',N'In Port'),('ContainerDetail_InPort','zh-CN',N'在港'),
('ContainerDetail_NvoccStatus','en-US',N'NVOCC status'),('ContainerDetail_NvoccStatus','vi-VN',N'NVOCC Status'),('ContainerDetail_NvoccStatus','zh-CN',N'NVOCC 状态'),
('ContainerDetail_Decommission','en-US',N'Decommission'),('ContainerDetail_Decommission','vi-VN',N'Decommission'),('ContainerDetail_Decommission','zh-CN',N'停用'),
('ContainerProfit_Subtitle','en-US',N'Debit, credit and profit by container'),('ContainerProfit_Subtitle','vi-VN',N'Debit, credit và lợi nhuận theo container'),('ContainerProfit_Subtitle','zh-CN',N'按集装箱的借贷与利润'),
('ContainerProfit_EnterContainer','en-US',N'Enter or select container number'),('ContainerProfit_EnterContainer','vi-VN',N'Nhập hoặc chọn số container'),('ContainerProfit_EnterContainer','zh-CN',N'输入或选择集装箱号'),
('ContainerProfit_TotalDebitUsd','en-US',N'Total debit (USD)'),('ContainerProfit_TotalDebitUsd','vi-VN',N'Total Debit (USD)'),('ContainerProfit_TotalDebitUsd','zh-CN',N'借记合计 (USD)'),
('ContainerProfit_TotalCreditUsd','en-US',N'Total credit (USD)'),('ContainerProfit_TotalCreditUsd','vi-VN',N'Total Credit (USD)'),('ContainerProfit_TotalCreditUsd','zh-CN',N'贷记合计 (USD)'),
('ContainerProfit_ProfitUsd','en-US',N'Profit (USD)'),('ContainerProfit_ProfitUsd','vi-VN',N'Profit (USD)'),('ContainerProfit_ProfitUsd','zh-CN',N'利润 (USD)'),
('ContainerProfit_TotalDebitVnd','en-US',N'Total debit (VND)'),('ContainerProfit_TotalDebitVnd','vi-VN',N'Total Debit (VND)'),('ContainerProfit_TotalDebitVnd','zh-CN',N'借记合计 (VND)'),
('ContainerProfit_TotalCreditVnd','en-US',N'Total credit (VND)'),('ContainerProfit_TotalCreditVnd','vi-VN',N'Total Credit (VND)'),('ContainerProfit_TotalCreditVnd','zh-CN',N'贷记合计 (VND)'),
('ContainerProfit_ProfitVnd','en-US',N'Profit (VND)'),('ContainerProfit_ProfitVnd','vi-VN',N'Profit (VND)'),('ContainerProfit_ProfitVnd','zh-CN',N'利润 (VND)'),
('ContainerProfit_Source','en-US',N'Source'),('ContainerProfit_Source','vi-VN',N'Nguồn'),('ContainerProfit_Source','zh-CN',N'来源'),
('ContainerProfit_Charge','en-US',N'Charge'),('ContainerProfit_Charge','vi-VN',N'Phí'),('ContainerProfit_Charge','zh-CN',N'费用'),
('ContainerProfit_OriginalAmount','en-US',N'Original amount'),('ContainerProfit_OriginalAmount','vi-VN',N'Original Amount'),('ContainerProfit_OriginalAmount','zh-CN',N'原始金额'),
('ContainerProfit_AmountUsd','en-US',N'Amount USD'),('ContainerProfit_AmountUsd','vi-VN',N'Amount USD'),('ContainerProfit_AmountUsd','zh-CN',N'USD 金额'),
('ContainerProfit_AmountVnd','en-US',N'Amount VND'),('ContainerProfit_AmountVnd','vi-VN',N'Amount VND'),('ContainerProfit_AmountVnd','zh-CN',N'VND 金额');

COMMIT;
-- After run: DbStringLocalizerFactory.ClearCache() or restart app.
