-- Menu 2: Shipment, Client, Profit, Reports, Quotation
BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    'Shipment_Subtitle','Shipment_ViewDocument','Shipment_ShowAll','Shipment_Workspace','Shipment_WorkspaceCaption',
    'Shipment_TotalJobs','Shipment_AdvancedSearch','Shipment_AdvancedSearchCaption','Shipment_SearchFromHBL',
    'Shipment_HideSummarySearch','Shipment_ShowSummarySearch','Template','Shipment_HblMbl',
    'InternalInvoiceNo','ElectronicInvoiceNo','DebitNo','ContainerNo','PKGs','PKGsCode','GrossWT','Notify',
    'ShowChart','OnTimeDelivery','LateDelivery','Pending','Delivered','Cancelled','Processing',
    'InvIssued','DebitReceived','SpentCredit','RcvSpentAgent','SearchCustomers',
    'SearchBySales','SearchPOLPlaceholder','SearchPODPlaceholder','SearchJobMblHbl','Total',
    'ChargeReport_Subtitle','ChargeReport_ToggleFilters','ClearFilter','Print','ExportExcel',
    'ChargeReport_ChargeLabel','ChargeReport_ChargePlaceholder','AgentOnly','ChargeReport_RowCount',
    'ChargeReport_FilteredOfTotal','ChargeReport_TotalDebitAfterTax','ChargeReport_TotalCreditAfterTax',
    'ChargeReport_TotalVndDebit','ChargeReport_TotalVndCredit','ChargeReport_TotalUsdDebit','ChargeReport_TotalUsdCredit',
    'ChargeReport_PrintTitle','Keyword','PrintDate','ChargeReport_RowCountLabel','All',
    'ChargeReport_RowType','ChargeReport_ChargeCode','ChargeReport_ChargeName','BKNo','UnitPrice','Quantity',
    'Currency','Amount','Tax','AmountAfterTax','CollectPayOnBehalf','DebitDNTT','Note','Vessel','Voy','DVT',
    'Group','ExchangeRate','InvoiceExchangeRate','AccountSelling','AccountBuying','Locked','Printed','IssuedInvoice',
    'ChargeReport_NoFilterMatch','ChargeReport_NoDataHint','FilterPlaceholder',
    'ChargeReport_SelectChargeFirst','ChargeReport_ChargeNotFound','ChargeReport_FoundRows','ChargeReport_NoDebitCredit',
    'ChargeReport_LoadError','ChargeReport_PrintError','ChargeReport_ExportError','ChargeReport_SheetName',
    'SelectCustomerPlease','NoPermission_Move','CannotEditNomi','NothingToDelete',
    'Customer_DuplicateTitle','Customer_EditTitle','Customer_CreateTitle',    'ImportExcel','PreviewData','DeleteError',
    'SearchContent','SearchBy','InvoiceName','DebitName','EnterSearchConditions',
    'ImportPartnerListExcel','NoValidExcelData','PreviewImportPartnerList','ImportSkippedRows','ImportResult',
    'NoPermission_View','NoPermission_Edit','NoPermission_Add','NoPermission_Delete','NoPermission_Approve',
    'Warning','DeleteConfirmBody',
    'PleaseSelectData','DataAlreadyApproved','SelectOneQuotation',
    'EmailSentSuccess','EmailSentFailed','EmailCustomerEmpty',
    'FromMonth','FromYear','ToMonth','ToYear',
    'NoInfo','SelectSaleName','SelectDateTimeRange',
    'SelectType','SelectItem','NoData',
    'SaveSuccess','Shipment_DebitCreditTemplateTitle','Shipment_NoMatchingBatch',
    'UserUpdate','DateUpdate','Type',
    'PleaseSlowDown','SomethingWentWrong','Error_Message',
    'SelectOneRow','SelectOneJob','CannotDeleteApprovedJob','JobApproved','DataNotFound'
);

INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('Shipment_Subtitle','en-US',N'Payment & charges'),('Shipment_Subtitle','vi-VN',N'Thanh toán & phí'),('Shipment_Subtitle','zh-CN',N'付款与费用'),
('Shipment_ViewDocument','en-US',N'View Document'),('Shipment_ViewDocument','vi-VN',N'Xem tài liệu'),('Shipment_ViewDocument','zh-CN',N'查看文档'),
('Shipment_ShowAll','en-US',N'Show all'),('Shipment_ShowAll','vi-VN',N'Hiện tất cả'),('Shipment_ShowAll','zh-CN',N'显示全部'),
('Shipment_Workspace','en-US',N'Shipment Workspace'),('Shipment_Workspace','vi-VN',N'Không gian Shipment'),('Shipment_Workspace','zh-CN',N'货运工作区'),
('Shipment_WorkspaceCaption','en-US',N'Manage jobs, MBL/HBL, debit/credit templates and reports in one screen.'),('Shipment_WorkspaceCaption','vi-VN',N'Quản lý job, MBL/HBL, debit/credit template và báo cáo trong cùng một màn hình.'),('Shipment_WorkspaceCaption','zh-CN',N'在同一屏幕管理作业、MBL/HBL、借贷模板和报告。'),
('Shipment_TotalJobs','en-US',N'Total Jobs'),('Shipment_TotalJobs','vi-VN',N'Tổng Job'),('Shipment_TotalJobs','zh-CN',N'作业总数'),
('Shipment_AdvancedSearch','en-US',N'Advanced Search'),('Shipment_AdvancedSearch','vi-VN',N'Tìm kiếm nâng cao'),('Shipment_AdvancedSearch','zh-CN',N'高级搜索'),
('Shipment_AdvancedSearchCaption','en-US',N'Filter by HBL, invoice, debit, port, customer or container.'),('Shipment_AdvancedSearchCaption','vi-VN',N'Lọc theo HBL, invoice, debit, port, customer hoặc container.'),('Shipment_AdvancedSearchCaption','zh-CN',N'按 HBL、发票、借贷、港口、客户或集装箱筛选。'),
('Shipment_SearchFromHBL','en-US',N'Searching data from HBL'),('Shipment_SearchFromHBL','vi-VN',N'Tìm dữ liệu từ HBL'),('Shipment_SearchFromHBL','zh-CN',N'从 HBL 搜索数据'),
('Shipment_HideSummarySearch','en-US',N'Hide summary & search'),('Shipment_HideSummarySearch','vi-VN',N'Ẩn thống kê & tìm kiếm'),('Shipment_HideSummarySearch','zh-CN',N'隐藏统计与搜索'),
('Shipment_ShowSummarySearch','en-US',N'Show summary & search'),('Shipment_ShowSummarySearch','vi-VN',N'Hiện thống kê & tìm kiếm'),('Shipment_ShowSummarySearch','zh-CN',N'显示统计与搜索'),
('Template','en-US',N'Template'),('Template','vi-VN',N'Template'),('Template','zh-CN',N'模板'),
('Shipment_HblMbl','en-US',N'HBL / MBL'),('Shipment_HblMbl','vi-VN',N'HBL / MBL'),('Shipment_HblMbl','zh-CN',N'HBL / MBL'),
('InternalInvoiceNo','en-US',N'Internal invoice no.'),('InternalInvoiceNo','vi-VN',N'Số hóa đơn nội bộ'),('InternalInvoiceNo','zh-CN',N'内部发票号'),
('ElectronicInvoiceNo','en-US',N'E-invoice no.'),('ElectronicInvoiceNo','vi-VN',N'Số hóa đơn điện tử'),('ElectronicInvoiceNo','zh-CN',N'电子发票号'),
('DebitNo','en-US',N'Debit no.'),('DebitNo','vi-VN',N'Số Debit'),('DebitNo','zh-CN',N'借记单号'),
('ContainerNo','en-US',N'Container No'),('ContainerNo','vi-VN',N'Số container'),('ContainerNo','zh-CN',N'集装箱号'),
('PKGs','en-US',N'PKGs'),('PKGs','vi-VN',N'PKGs'),('PKGs','zh-CN',N'PKGs'),
('PKGsCode','en-US',N'PKGs Code'),('PKGsCode','vi-VN',N'Mã PKGs'),('PKGsCode','zh-CN',N'PKGs 代码'),
('GrossWT','en-US',N'Gross WT.'),('GrossWT','vi-VN',N'Gross WT.'),('GrossWT','zh-CN',N'毛重'),
('Notify','en-US',N'Notify'),('Notify','vi-VN',N'Notify'),('Notify','zh-CN',N'通知方'),
('ShowChart','en-US',N'Show Chart'),('ShowChart','vi-VN',N'Hiện biểu đồ'),('ShowChart','zh-CN',N'显示图表'),
('OnTimeDelivery','en-US',N'On-time delivery'),('OnTimeDelivery','vi-VN',N'Giao đúng hạn'),('OnTimeDelivery','zh-CN',N'准时交付'),
('LateDelivery','en-US',N'Late delivery'),('LateDelivery','vi-VN',N'Giao trễ hạn'),('LateDelivery','zh-CN',N'延迟交付'),
('Pending','en-US',N'Pending'),('Pending','vi-VN',N'Pending'),('Pending','zh-CN',N'待处理'),
('Delivered','en-US',N'Delivered'),('Delivered','vi-VN',N'Delivered'),('Delivered','zh-CN',N'已交付'),
('Cancelled','en-US',N'Cancelled'),('Cancelled','vi-VN',N'Cancelled'),('Cancelled','zh-CN',N'已取消'),
('Processing','en-US',N'Processing'),('Processing','vi-VN',N'Đang xử lý'),('Processing','zh-CN',N'处理中'),
('InvIssued','en-US',N'Inv. Issued'),('InvIssued','vi-VN',N'Đã xuất HĐ'),('InvIssued','zh-CN',N'已开发票'),
('DebitReceived','en-US',N'Debit Rcv'),('DebitReceived','vi-VN',N'Đã thu Debit'),('DebitReceived','zh-CN',N'已收借记'),
('SpentCredit','en-US',N'Spent Credit'),('SpentCredit','vi-VN',N'Đã chi Credit'),('SpentCredit','zh-CN',N'已付贷记'),
('RcvSpentAgent','en-US',N'Rcv&Spent Agent'),('RcvSpentAgent','vi-VN',N'Thu/Chi Agent'),('RcvSpentAgent','zh-CN',N'代理收付'),
('SearchCustomers','en-US',N'Search Customers'),('SearchCustomers','vi-VN',N'Tìm khách hàng'),('SearchCustomers','zh-CN',N'搜索客户'),
('SearchBySales','en-US',N'Search By Sales'),('SearchBySales','vi-VN',N'Tìm theo Sale'),('SearchBySales','zh-CN',N'按销售搜索'),
('SearchPOLPlaceholder','en-US',N'Type to search POL...'),('SearchPOLPlaceholder','vi-VN',N'Nhập tìm POL...'),('SearchPOLPlaceholder','zh-CN',N'输入搜索 POL...'),
('SearchPODPlaceholder','en-US',N'Type to search POD...'),('SearchPODPlaceholder','vi-VN',N'Nhập tìm POD...'),('SearchPODPlaceholder','zh-CN',N'输入搜索 POD...'),
('SearchJobMblHbl','en-US',N'Search By JobNo, MBL, HBL'),('SearchJobMblHbl','vi-VN',N'Tìm theo JobNo, MBL, HBL'),('SearchJobMblHbl','zh-CN',N'按 JobNo、MBL、HBL 搜索'),
('Total','en-US',N'Total'),('Total','vi-VN',N'Tổng'),('Total','zh-CN',N'合计'),
('ChargeReport_Subtitle','en-US',N'Select charge name or code to find all Debit/Credit by HBL.'),('ChargeReport_Subtitle','vi-VN',N'Chọn tên phí hoặc mã phí để tìm toàn bộ Debit/Credit theo HBL.'),('ChargeReport_Subtitle','zh-CN',N'选择费用名称或代码以按 HBL 查找所有借贷。'),
('ChargeReport_ToggleFilters','en-US',N'Toggle column filters'),('ChargeReport_ToggleFilters','vi-VN',N'Bật/tắt bộ lọc trên đầu mỗi cột'),('ChargeReport_ToggleFilters','zh-CN',N'切换列筛选'),
('ClearFilter','en-US',N'Clear filter'),('ClearFilter','vi-VN',N'Xóa filter'),('ClearFilter','zh-CN',N'清除筛选'),
('Print','en-US',N'Print'),('Print','vi-VN',N'In'),('Print','zh-CN',N'打印'),
('ExportExcel','en-US',N'Export Excel'),('ExportExcel','vi-VN',N'Xuất Excel'),('ExportExcel','zh-CN',N'导出 Excel'),
('ChargeReport_ChargeLabel','en-US',N'Charge name / code'),('ChargeReport_ChargeLabel','vi-VN',N'Tên phí / mã phí'),('ChargeReport_ChargeLabel','zh-CN',N'费用名称/代码'),
('ChargeReport_ChargePlaceholder','en-US',N'E.g. THC, LOCAL CHARGE, DOC FEE...'),('ChargeReport_ChargePlaceholder','vi-VN',N'VD: THC, LOCAL CHARGE, DOC FEE...'),('ChargeReport_ChargePlaceholder','zh-CN',N'例如：THC、LOCAL CHARGE、DOC FEE...'),
('AgentOnly','en-US',N'Agent only'),('AgentOnly','vi-VN',N'Đại Lý/Agent'),('AgentOnly','zh-CN',N'仅代理'),
('ChargeReport_RowCount','en-US',N'Rows {0}'),('ChargeReport_RowCount','vi-VN',N'Số dòng {0}'),('ChargeReport_RowCount','zh-CN',N'行数 {0}'),
('ChargeReport_FilteredOfTotal','en-US',N'(filtered / total {0})'),('ChargeReport_FilteredOfTotal','vi-VN',N'(lọc / tổng {0})'),('ChargeReport_FilteredOfTotal','zh-CN',N'（筛选/总计 {0}）'),
('ChargeReport_TotalDebitAfterTax','en-US',N'Total Debit (after tax)'),('ChargeReport_TotalDebitAfterTax','vi-VN',N'Tổng Debit (sau thuế)'),('ChargeReport_TotalDebitAfterTax','zh-CN',N'借记合计（税后）'),
('ChargeReport_TotalCreditAfterTax','en-US',N'Total Credit (after tax)'),('ChargeReport_TotalCreditAfterTax','vi-VN',N'Tổng Credit (sau thuế)'),('ChargeReport_TotalCreditAfterTax','zh-CN',N'贷记合计（税后）'),
('ChargeReport_TotalVndDebit','en-US',N'Total VND — Debit'),('ChargeReport_TotalVndDebit','vi-VN',N'Tổng VND — Debit'),('ChargeReport_TotalVndDebit','zh-CN',N'VND 合计 — 借记'),
('ChargeReport_TotalVndCredit','en-US',N'Total VND — Credit'),('ChargeReport_TotalVndCredit','vi-VN',N'Tổng VND — Credit'),('ChargeReport_TotalVndCredit','zh-CN',N'VND 合计 — 贷记'),
('ChargeReport_TotalUsdDebit','en-US',N'Total USD — Debit'),('ChargeReport_TotalUsdDebit','vi-VN',N'Tổng USD — Debit'),('ChargeReport_TotalUsdDebit','zh-CN',N'USD 合计 — 借记'),
('ChargeReport_TotalUsdCredit','en-US',N'Total USD — Credit'),('ChargeReport_TotalUsdCredit','vi-VN',N'Tổng USD — Credit'),('ChargeReport_TotalUsdCredit','zh-CN',N'USD 合计 — 贷记'),
('ChargeReport_PrintTitle','en-US',N'CHARGE DETAIL REPORT'),('ChargeReport_PrintTitle','vi-VN',N'BÁO CÁO CHI TIẾT THEO TÊN PHÍ'),('ChargeReport_PrintTitle','zh-CN',N'费用明细报告'),
('Keyword','en-US',N'Keyword'),('Keyword','vi-VN',N'Từ khóa'),('Keyword','zh-CN',N'关键词'),
('PrintDate','en-US',N'Print date'),('PrintDate','vi-VN',N'Ngày in'),('PrintDate','zh-CN',N'打印日期'),
('ChargeReport_RowCountLabel','en-US',N'Rows'),('ChargeReport_RowCountLabel','vi-VN',N'Số dòng'),('ChargeReport_RowCountLabel','zh-CN',N'行数'),
('All','en-US',N'All'),('All','vi-VN',N'Tất cả'),('All','zh-CN',N'全部'),
('ChargeReport_RowType','en-US',N'Type'),('ChargeReport_RowType','vi-VN',N'Loại'),('ChargeReport_RowType','zh-CN',N'类型'),
('ChargeReport_ChargeCode','en-US',N'Charge code'),('ChargeReport_ChargeCode','vi-VN',N'Mã phí'),('ChargeReport_ChargeCode','zh-CN',N'费用代码'),
('ChargeReport_ChargeName','en-US',N'Charge name'),('ChargeReport_ChargeName','vi-VN',N'Tên phí'),('ChargeReport_ChargeName','zh-CN',N'费用名称'),
('BKNo','en-US',N'BK No'),('BKNo','vi-VN',N'BK No'),('BKNo','zh-CN',N'BK 号'),
('UnitPrice','en-US',N'Unit price'),('UnitPrice','vi-VN',N'Đơn giá'),('UnitPrice','zh-CN',N'单价'),
('Quantity','en-US',N'Qty'),('Quantity','vi-VN',N'SL'),('Quantity','zh-CN',N'数量'),
('Currency','en-US',N'Currency'),('Currency','vi-VN',N'Tiền tệ'),('Currency','zh-CN',N'币种'),
('Amount','en-US',N'Amount'),('Amount','vi-VN',N'Thành tiền'),('Amount','zh-CN',N'金额'),
('Tax','en-US',N'Tax'),('Tax','vi-VN',N'Thuế'),('Tax','zh-CN',N'税'),
('AmountAfterTax','en-US',N'After tax'),('AmountAfterTax','vi-VN',N'Sau thuế'),('AmountAfterTax','zh-CN',N'税后'),
('CollectPayOnBehalf','en-US',N'Collect/Pay on behalf'),('CollectPayOnBehalf','vi-VN',N'Thu/Chi hộ'),('CollectPayOnBehalf','zh-CN',N'代收/代付'),
('DebitDNTT','en-US',N'Debit/DNTT'),('DebitDNTT','vi-VN',N'Debit/DNTT'),('DebitDNTT','zh-CN',N'借记/DNTT'),
('Note','en-US',N'Note'),('Note','vi-VN',N'Ghi chú'),('Note','zh-CN',N'备注'),
('Vessel','en-US',N'Vessel'),('Vessel','vi-VN',N'Vessel'),('Vessel','zh-CN',N'船名'),
('Voy','en-US',N'Voy'),('Voy','vi-VN',N'Voy'),('Voy','zh-CN',N'航次'),
('DVT','en-US',N'UOM'),('DVT','vi-VN',N'DVT'),('DVT','zh-CN',N'单位'),
('Group','en-US',N'Group'),('Group','vi-VN',N'Nhóm'),('Group','zh-CN',N'组'),
('ExchangeRate','en-US',N'Exchange rate'),('ExchangeRate','vi-VN',N'Tỷ giá'),('ExchangeRate','zh-CN',N'汇率'),
('InvoiceExchangeRate','en-US',N'Invoice rate'),('InvoiceExchangeRate','vi-VN',N'Tỷ giá HĐ'),('InvoiceExchangeRate','zh-CN',N'发票汇率'),
('AccountSelling','en-US',N'Selling account'),('AccountSelling','vi-VN',N'TK bán'),('AccountSelling','zh-CN',N'销售科目'),
('AccountBuying','en-US',N'Buying account'),('AccountBuying','vi-VN',N'TK mua'),('AccountBuying','zh-CN',N'采购科目'),
('Locked','en-US',N'Locked'),('Locked','vi-VN',N'Khóa'),('Locked','zh-CN',N'锁定'),
('Printed','en-US',N'Printed'),('Printed','vi-VN',N'Đã in'),('Printed','zh-CN',N'已打印'),
('IssuedInvoice','en-US',N'Invoice issued'),('IssuedInvoice','vi-VN',N'Đã xuất HĐ'),('IssuedInvoice','zh-CN',N'已开发票'),
('ChargeReport_NoFilterMatch','en-US',N'No rows match the filter.'),('ChargeReport_NoFilterMatch','vi-VN',N'Không có dòng nào khớp bộ lọc.'),('ChargeReport_NoFilterMatch','zh-CN',N'没有匹配筛选的行。'),
('ChargeReport_NoDataHint','en-US',N'No data yet. Enter a charge name and click Search.'),('ChargeReport_NoDataHint','vi-VN',N'Chưa có dữ liệu. Nhập tên phí rồi bấm Tìm.'),('ChargeReport_NoDataHint','zh-CN',N'暂无数据。输入费用名称后点击搜索。'),
('FilterPlaceholder','en-US',N'Filter...'),('FilterPlaceholder','vi-VN',N'Lọc...'),('FilterPlaceholder','zh-CN',N'筛选...'),
('ChargeReport_SelectChargeFirst','en-US',N'Please select a charge name or code before searching.'),('ChargeReport_SelectChargeFirst','vi-VN',N'Chọn tên phí hoặc mã phí trước khi tìm.'),('ChargeReport_SelectChargeFirst','zh-CN',N'搜索前请选择费用名称或代码。'),
('ChargeReport_ChargeNotFound','en-US',N'Charge not found in ChargeModel.'),('ChargeReport_ChargeNotFound','vi-VN',N'Không tìm thấy mã phí/tên phí trong ChargeModel.'),('ChargeReport_ChargeNotFound','zh-CN',N'在 ChargeModel 中未找到费用。'),
('ChargeReport_FoundRows','en-US',N'Found {0:N0} charge detail row(s).'),('ChargeReport_FoundRows','vi-VN',N'Tìm thấy {0:N0} dòng chi tiết theo phí.'),('ChargeReport_FoundRows','zh-CN',N'找到 {0:N0} 条费用明细。'),
('ChargeReport_NoDebitCredit','en-US',N'Charge exists but no Debit/Credit transactions found.'),('ChargeReport_NoDebitCredit','vi-VN',N'Có mã phí trong ChargeModel nhưng chưa phát sinh Debit/Credit.'),('ChargeReport_NoDebitCredit','zh-CN',N'费用存在但未产生借贷记录。'),
('ChargeReport_LoadError','en-US',N'Load error: {0}'),('ChargeReport_LoadError','vi-VN',N'Lỗi load dữ liệu: {0}'),('ChargeReport_LoadError','zh-CN',N'加载错误：{0}'),
('ChargeReport_PrintError','en-US',N'Print error: {0}'),('ChargeReport_PrintError','vi-VN',N'Lỗi in báo cáo: {0}'),('ChargeReport_PrintError','zh-CN',N'打印错误：{0}'),
('ChargeReport_ExportError','en-US',N'Export error: {0}'),('ChargeReport_ExportError','vi-VN',N'Lỗi xuất Excel: {0}'),('ChargeReport_ExportError','zh-CN',N'导出错误：{0}'),
('ChargeReport_SheetName','en-US',N'Charge detail'),('ChargeReport_SheetName','vi-VN',N'Chi tiet phi'),('ChargeReport_SheetName','zh-CN',N'费用明细'),
('SelectCustomerPlease','en-US',N'Please select a customer.'),('SelectCustomerPlease','vi-VN',N'Vui lòng chọn khách hàng.'),('SelectCustomerPlease','zh-CN',N'请选择客户。'),
('NoPermission_Move','en-US',N'You do not have permission to move.'),('NoPermission_Move','vi-VN',N'Bạn không có quyền Move.'),('NoPermission_Move','zh-CN',N'您没有移动权限。'),
('CannotEditNomi','en-US',N'You cannot edit Sale Name ''NOMI''. Move the customer and try again.'),('CannotEditNomi','vi-VN',N'Không thể sửa Sale Name ''NOMI''. Hãy Move Customer rồi thử lại.'),('CannotEditNomi','zh-CN',N'无法编辑 Sale Name ''NOMI''。请移动客户后重试。'),
('NothingToDelete','en-US',N'Nothing to delete.'),('NothingToDelete','vi-VN',N'Không có gì để xóa.'),('NothingToDelete','zh-CN',N'没有可删除的内容。'),
('Customer_DuplicateTitle','en-US',N'Customer - Duplicate {0}'),('Customer_DuplicateTitle','vi-VN',N'Customer - Duplicate {0}'),('Customer_DuplicateTitle','zh-CN',N'客户 - 复制 {0}'),
('Customer_EditTitle','en-US',N'Customer - Edit {0}'),('Customer_EditTitle','vi-VN',N'Customer - Edit {0}'),('Customer_EditTitle','zh-CN',N'客户 - 编辑 {0}'),
('Customer_CreateTitle','en-US',N'Customer - Create'),('Customer_CreateTitle','vi-VN',N'Customer - Create'),('Customer_CreateTitle','zh-CN',N'客户 - 新建'),
('ImportExcel','en-US',N'Import Excel'),('ImportExcel','vi-VN',N'Import Excel'),('ImportExcel','zh-CN',N'导入 Excel'),
('PreviewData','en-US',N'Preview Data'),('PreviewData','vi-VN',N'Xem trước dữ liệu'),('PreviewData','zh-CN',N'预览数据'),
('DeleteError','en-US',N'Delete error: {0}'),('DeleteError','vi-VN',N'Lỗi xóa: {0}'),('DeleteError','zh-CN',N'删除错误：{0}'),
('SearchContent','en-US',N'Search content'),('SearchContent','vi-VN',N'Nội dung tìm kiếm'),('SearchContent','zh-CN',N'搜索内容'),
('SearchBy','en-US',N'Search by'),('SearchBy','vi-VN',N'Tìm theo'),('SearchBy','zh-CN',N'搜索方式'),
('InvoiceName','en-US',N'Invoice name'),('InvoiceName','vi-VN',N'Tên Invoice'),('InvoiceName','zh-CN',N'发票名称'),
('DebitName','en-US',N'Debit name'),('DebitName','vi-VN',N'Tên Debit'),('DebitName','zh-CN',N'借记名称'),
('EnterSearchConditions','en-US',N'Enter search conditions.'),('EnterSearchConditions','vi-VN',N'Nhập điều kiện tìm kiếm.'),('EnterSearchConditions','zh-CN',N'请输入搜索条件。'),
('ImportPartnerListExcel','en-US',N'Import Partner List Excel'),('ImportPartnerListExcel','vi-VN',N'Import Partner List Excel'),('ImportPartnerListExcel','zh-CN',N'导入合作伙伴列表 Excel'),
('NoValidExcelData','en-US',N'No valid data in Excel file (data from row 8).'),('NoValidExcelData','vi-VN',N'Không có dữ liệu hợp lệ trong file Excel (data từ dòng 8).'),('NoValidExcelData','zh-CN',N'Excel 文件中无有效数据（从第 8 行起）。'),
('PreviewImportPartnerList','en-US',N'Preview Import Partner List'),('PreviewImportPartnerList','vi-VN',N'Xem trước Import Partner List'),('PreviewImportPartnerList','zh-CN',N'预览导入合作伙伴列表'),
('ImportSkippedRows','en-US',N' Skipped {0} existing row(s): '),('ImportSkippedRows','vi-VN',N' Bỏ qua {0} dòng đã tồn tại: '),('ImportSkippedRows','zh-CN',N' 跳过 {0} 条已存在行：'),
('ImportResult','en-US',N'Import result'),('ImportResult','vi-VN',N'Kết quả Import'),('ImportResult','zh-CN',N'导入结果'),
('NoPermission_View','en-US',N'You do not have permission to view.'),('NoPermission_View','vi-VN',N'Bạn không có quyền xem.'),('NoPermission_View','zh-CN',N'您没有查看权限。'),
('NoPermission_Edit','en-US',N'You do not have permission to edit.'),('NoPermission_Edit','vi-VN',N'Bạn không có quyền sửa.'),('NoPermission_Edit','zh-CN',N'您没有编辑权限。'),
('NoPermission_Add','en-US',N'You do not have permission to add.'),('NoPermission_Add','vi-VN',N'Bạn không có quyền thêm.'),('NoPermission_Add','zh-CN',N'您没有添加权限。'),
('NoPermission_Delete','en-US',N'You do not have permission to delete.'),('NoPermission_Delete','vi-VN',N'Bạn không có quyền xóa.'),('NoPermission_Delete','zh-CN',N'您没有删除权限。'),
('NoPermission_Approve','en-US',N'You do not have permission to approve.'),('NoPermission_Approve','vi-VN',N'Bạn không có quyền Approve.'),('NoPermission_Approve','zh-CN',N'您没有审批权限。'),
('Warning','en-US',N'Warning'),('Warning','vi-VN',N'Cảnh báo'),('Warning','zh-CN',N'警告'),
('DeleteConfirmBody','en-US',N'Deleting cannot be undone!'),('DeleteConfirmBody','vi-VN',N'Xóa không thể hoàn tác!'),('DeleteConfirmBody','zh-CN',N'删除后无法撤销！'),
('PleaseSelectData','en-US',N'Please select data.'),('PleaseSelectData','vi-VN',N'Vui lòng chọn dữ liệu.'),('PleaseSelectData','zh-CN',N'请选择数据。'),
('DataAlreadyApproved','en-US',N'Data is already approved. Please un-approve first.'),('DataAlreadyApproved','vi-VN',N'Data đã được Approve!!! , vui lòng bỏ Approve'),('DataAlreadyApproved','zh-CN',N'数据已审批，请先取消审批。'),
('SelectOneQuotation','en-US',N'You must select one quotation.'),('SelectOneQuotation','vi-VN',N'Bạn phải chọn 1 Quotation.'),('SelectOneQuotation','zh-CN',N'请选择一条报价。'),
('EmailSentSuccess','en-US',N'Email sent successfully.'),('EmailSentSuccess','vi-VN',N'Email đã gửi thành công!'),('EmailSentSuccess','zh-CN',N'邮件发送成功。'),
('EmailSentFailed','en-US',N'Email failed to send.'),('EmailSentFailed','vi-VN',N'Email đã gửi thất bại!'),('EmailSentFailed','zh-CN',N'邮件发送失败。'),
('EmailCustomerEmpty','en-US',N'Customer email is empty.'),('EmailCustomerEmpty','vi-VN',N'Email Cus trống!!!'),('EmailCustomerEmpty','zh-CN',N'客户邮箱为空。'),
('FromMonth','en-US',N'From month'),('FromMonth','vi-VN',N'Từ tháng'),('FromMonth','zh-CN',N'起始月份'),
('FromYear','en-US',N'From year'),('FromYear','vi-VN',N'Từ năm'),('FromYear','zh-CN',N'起始年份'),
('ToMonth','en-US',N'To month'),('ToMonth','vi-VN',N'Đến tháng'),('ToMonth','zh-CN',N'结束月份'),
('ToYear','en-US',N'To year'),('ToYear','vi-VN',N'Đến năm'),('ToYear','zh-CN',N'结束年份'),
('NoInfo','en-US',N'No information.'),('NoInfo','vi-VN',N'Không có thông tin.'),('NoInfo','zh-CN',N'无信息。'),
('SelectSaleName','en-US',N'Please select a sale name.'),('SelectSaleName','vi-VN',N'Vui lòng chọn Sale Name.'),('SelectSaleName','zh-CN',N'请选择销售名称。'),
('SelectDateTimeRange','en-US',N'Please select a date/time range.'),('SelectDateTimeRange','vi-VN',N'Vui lòng chọn khoảng thời gian.'),('SelectDateTimeRange','zh-CN',N'请选择日期时间范围。'),
('SelectType','en-US',N'Please select a type.'),('SelectType','vi-VN',N'Vui lòng chọn loại.'),('SelectType','zh-CN',N'请选择类型。'),
('SelectItem','en-US',N'Please select an item.'),('SelectItem','vi-VN',N'Vui lòng chọn mục.'),('SelectItem','zh-CN',N'请选择项目。'),
('NoData','en-US',N'No data.'),('NoData','vi-VN',N'Không có dữ liệu.'),('NoData','zh-CN',N'无数据。'),
('SaveSuccess','en-US',N'Saved successfully.'),('SaveSuccess','vi-VN',N'Lưu thành công'),('SaveSuccess','zh-CN',N'保存成功。'),
('Shipment_DebitCreditTemplateTitle','en-US',N'Manage default Debit/Credit charges'),('Shipment_DebitCreditTemplateTitle','vi-VN',N'Quản lý các phí Debit Credit mặc định'),('Shipment_DebitCreditTemplateTitle','zh-CN',N'管理默认借贷费用'),
('Shipment_NoMatchingBatch','en-US',N'No matching batch found: {0}'),('Shipment_NoMatchingBatch','vi-VN',N'Không tìm thấy lô khớp: {0}'),('Shipment_NoMatchingBatch','zh-CN',N'未找到匹配批次：{0}'),
('UserUpdate','en-US',N'User update'),('UserUpdate','vi-VN',N'User update'),('UserUpdate','zh-CN',N'更新用户'),
('DateUpdate','en-US',N'Date update'),('DateUpdate','vi-VN',N'Date update'),('DateUpdate','zh-CN',N'更新日期'),
('Type','en-US',N'Type'),('Type','vi-VN',N'Loại'),('Type','zh-CN',N'类型'),
('PleaseSlowDown','en-US',N'Please slow down!'),('PleaseSlowDown','vi-VN',N'Vui lòng thao tác chậm lại!'),('PleaseSlowDown','zh-CN',N'请慢一些操作！'),
('SomethingWentWrong','en-US',N'Something went wrong: {0}'),('SomethingWentWrong','vi-VN',N'Đã xảy ra lỗi: {0}'),('SomethingWentWrong','zh-CN',N'发生错误：{0}'),
('Error_Message','en-US',N'Error: {0}'),('Error_Message','vi-VN',N'Lỗi: {0}'),('Error_Message','zh-CN',N'错误：{0}'),
('SelectOneRow','en-US',N'You must select one row.'),('SelectOneRow','vi-VN',N'Bạn phải chọn 1 dòng.'),('SelectOneRow','zh-CN',N'请选择一行。'),
('SelectOneJob','en-US',N'You must select one job.'),('SelectOneJob','vi-VN',N'Bạn phải chọn 1 Job.'),('SelectOneJob','zh-CN',N'请选择一个作业。'),
('CannotDeleteApprovedJob','en-US',N'You cannot delete an approved job.'),('CannotDeleteApprovedJob','vi-VN',N'Không thể xóa Job đã approve.'),('CannotDeleteApprovedJob','zh-CN',N'无法删除已审批的作业。'),
('JobApproved','en-US',N'This job is approved.'),('JobApproved','vi-VN',N'Job này đã được approve.'),('JobApproved','zh-CN',N'此作业已审批。'),
('DataNotFound','en-US',N'Data not found.'),('DataNotFound','vi-VN',N'Không tìm thấy dữ liệu.'),('DataNotFound','zh-CN',N'未找到数据。');

COMMIT;
