-- Group C: WordDocument, CompanyInformation, BillSeaLayoutEditor, Home (Dashboard)
-- Run then clear cache: DbStringLocalizerFactory.ClearCache() or restart app

BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    -- WordDocument
    'WordDocument_Title','WordDocument_UploadNew','WordDocument_ChooseFile','WordDocument_FileSelected',
    'WordDocument_NoFileSelected','Description_Optional','WordDocument_Uploading','WordDocument_UploadDocument',
    'WordDocument_List','WordDocument_SearchHint','SortBy','FileName','UploadDate','FileSize','SortOrder',
    'Ascending','Descending','WordDocument_ShowingResults','WordDocument_ShowingResultsKeyword','Description',
    'Actions','NoDescription','View','Download','WordDocument_EmptyList','WordDocument_LoadListError',
    'WordDocument_SelectFilePlease','WordDocument_DescriptionMaxLength','WordDocument_OnlyDocx',
    'WordDocument_FileTooLarge','WordDocument_CannotReadContent','WordDocument_UploadSuccess',
    'WordDocument_UploadError','WordDocument_ViewDocumentTitle','WordDocument_DownloadSuccess',
    'WordDocument_FileNotOnServer','WordDocument_DownloadError','WordDocument_DeleteConfirmTitle',
    'WordDocument_DeleteSuccess','WordDocument_NotFoundToDelete','WordDocument_DeleteError',
    -- CompanyInformation (tab/grid keys added in Group C)
    'CompanyInformation_Tab','PrefixTab','CompanyOther_Tab','CompanyLogo','NoLogoYet','ChooseLogo',
    'RemoveLogo','NotificationEmail','NotificationEmailPassword','SmtpServer','SmtpPort',
    'ApprovalEmailList','EmailListHelper','AccountName','BankName','AccountNo','Deposit','Transit',
    'CustomerSupportPhone','Company','BankAddress','IbanCode','Branches','LogoMaxSize','LogoReadError',
    'SaveError','DeleteConfirmItem',
    -- BillSeaLayoutEditor
    'LayoutEditor_Title','LayoutEditor_Page2','LayoutEditor_SelectForm','LayoutEditor_FormCustomized',
    'LayoutEditor_CreateForm','LayoutEditor_DeleteForm','LayoutEditor_ReloadList','LayoutEditor_MainForm',
    'LayoutEditor_AttachForm','LayoutEditor_CreateAttachForm','LayoutEditor_DeleteAttachForm',
    'LayoutEditor_Help_An','LayoutEditor_Help_Do','LayoutEditor_Help_Booking','LayoutEditor_Help_Quotation','LayoutEditor_Help_Bill',
    'LayoutEditor_NoAttachForm','LayoutEditor_NoForm','LayoutEditor_LoadError','LayoutEditor_LoadFormsError',
    'LayoutEditor_CreateFormTitle','LayoutEditor_CreateFormDialog','LayoutEditor_FormCreated',
    'LayoutEditor_DeleteFormTitle','LayoutEditor_DeleteFormBody','LayoutEditor_DeleteFormAttachNote',
    'LayoutEditor_FormDeleted','LayoutEditor_AttachFormCreated','LayoutEditor_DeleteAttachFormTitle',
    'LayoutEditor_DeleteAttachFormBody','LayoutEditor_AttachFormDeleted',
    -- Home / Dashboard
    'Dashboard_Subtitle','Dashboard_ProfitMonth','Dashboard_ProfitCaption','Dashboard_QuoteRequest',
    'Dashboard_QuoteCaption','Dashboard_OverdueDebt','Dashboard_DebtCaption','Dashboard_ProfitReport',
    'Dashboard_ShipmentReport','Dashboard_MapTracking','Dashboard_HideMap','Dashboard_ShowMap',
    'Dashboard_HBLInputLabel','Dashboard_HBLPlaceholder','Dashboard_ClosePopup','Dashboard_Selected',
    'Dashboard_TrackingMap','Dashboard_MapStyle','Dashboard_MapStyle_Roadmap','Dashboard_MapStyle_Satellite',
    'Dashboard_MapStyle_Terrain','Dashboard_MapStyle_Hybrid','Dashboard_MapStyle_Traffic','Dashboard_Traffic',
    'Dashboard_ProfitUSD','Dashboard_Debt_Overdue','Dashboard_Debt_NotDue','Dashboard_EnterHBL',
    'Dashboard_SearchingHBL','Dashboard_InvalidHBL','Dashboard_NoLocationForHBLs',
    'Dashboard_FoundHBLWithLocations','Dashboard_SearchError','Dashboard_SelectHBLBeforeReload',
    'Dashboard_FoundLocationsForHBL','Dashboard_NoLocationForTheseHBL','Dashboard_LoadDataError',
    'Dashboard_MapCleared','Dashboard_ClearMapError','Dashboard_PopupsClosed','Dashboard_ClosePopupError',
    'Dashboard_NoLocationData','Dashboard_NoValidCoordinates','Dashboard_ShowingValidLocations',
    'Dashboard_LoadedLocationsOnMap','Dashboard_LoadMapError'
);

-- ========== WordDocument ==========
INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('WordDocument_Title','en-US',N'Word Document Management'),
('WordDocument_Title','vi-VN',N'Quản lý tài liệu Word'),
('WordDocument_Title','zh-CN',N'Word文档管理'),
('WordDocument_UploadNew','en-US',N'Upload new document'),
('WordDocument_UploadNew','vi-VN',N'Tải lên tài liệu mới'),
('WordDocument_UploadNew','zh-CN',N'上传新文档'),
('WordDocument_ChooseFile','en-US',N'Choose file'),
('WordDocument_ChooseFile','vi-VN',N'Chọn file'),
('WordDocument_ChooseFile','zh-CN',N'选择文件'),
('WordDocument_FileSelected','en-US',N'Selected: {0} ({1} KB)'),
('WordDocument_FileSelected','vi-VN',N'Đã chọn: {0} ({1} KB)'),
('WordDocument_FileSelected','zh-CN',N'已选择：{0}（{1} KB）'),
('WordDocument_NoFileSelected','en-US',N'No file selected'),
('WordDocument_NoFileSelected','vi-VN',N'Chưa chọn file'),
('WordDocument_NoFileSelected','zh-CN',N'未选择文件'),
('Description_Optional','en-US',N'Description (optional)'),
('Description_Optional','vi-VN',N'Mô tả (tùy chọn)'),
('Description_Optional','zh-CN',N'描述（可选）'),
('WordDocument_Uploading','en-US',N'Uploading...'),
('WordDocument_Uploading','vi-VN',N'Đang tải lên...'),
('WordDocument_Uploading','zh-CN',N'上传中...'),
('WordDocument_UploadDocument','en-US',N'Upload document'),
('WordDocument_UploadDocument','vi-VN',N'Tải lên tài liệu'),
('WordDocument_UploadDocument','zh-CN',N'上传文档'),
('WordDocument_List','en-US',N'Document list'),
('WordDocument_List','vi-VN',N'Danh sách tài liệu'),
('WordDocument_List','zh-CN',N'文档列表'),
('WordDocument_SearchHint','en-US',N'Search by file name or description...'),
('WordDocument_SearchHint','vi-VN',N'Tìm theo tên file hoặc mô tả...'),
('WordDocument_SearchHint','zh-CN',N'按文件名或描述搜索...'),
('SortBy','en-US',N'Sort by'),
('SortBy','vi-VN',N'Sắp xếp theo'),
('SortBy','zh-CN',N'排序方式'),
('FileName','en-US',N'File name'),
('FileName','vi-VN',N'Tên file'),
('FileName','zh-CN',N'文件名'),
('UploadDate','en-US',N'Upload date'),
('UploadDate','vi-VN',N'Ngày tải lên'),
('UploadDate','zh-CN',N'上传日期'),
('FileSize','en-US',N'File size'),
('FileSize','vi-VN',N'Kích thước'),
('FileSize','zh-CN',N'文件大小'),
('SortOrder','en-US',N'Sort order'),
('SortOrder','vi-VN',N'Thứ tự'),
('SortOrder','zh-CN',N'排序顺序'),
('Ascending','en-US',N'Ascending'),
('Ascending','vi-VN',N'Tăng dần'),
('Ascending','zh-CN',N'升序'),
('Descending','en-US',N'Descending'),
('Descending','vi-VN',N'Giảm dần'),
('Descending','zh-CN',N'降序'),
('WordDocument_ShowingResults','en-US',N'Showing {0} of {1} documents'),
('WordDocument_ShowingResults','vi-VN',N'Hiển thị {0}/{1} tài liệu'),
('WordDocument_ShowingResults','zh-CN',N'显示 {0}/{1} 个文档'),
('WordDocument_ShowingResultsKeyword','en-US',N' (keyword: "{0}")'),
('WordDocument_ShowingResultsKeyword','vi-VN',N' (từ khóa: "{0}")'),
('WordDocument_ShowingResultsKeyword','zh-CN',N'（关键词：“{0}”）'),
('Description','en-US',N'Description'),
('Description','vi-VN',N'Mô tả'),
('Description','zh-CN',N'描述'),
('Actions','en-US',N'Actions'),
('Actions','vi-VN',N'Thao tác'),
('Actions','zh-CN',N'操作'),
('NoDescription','en-US',N'No description'),
('NoDescription','vi-VN',N'Không có mô tả'),
('NoDescription','zh-CN',N'无描述'),
('View','en-US',N'View'),
('View','vi-VN',N'Xem'),
('View','zh-CN',N'查看'),
('Download','en-US',N'Download'),
('Download','vi-VN',N'Tải xuống'),
('Download','zh-CN',N'下载'),
('WordDocument_EmptyList','en-US',N'No documents yet. Upload your first document above.'),
('WordDocument_EmptyList','vi-VN',N'Chưa có tài liệu. Hãy tải lên tài liệu đầu tiên ở trên.'),
('WordDocument_EmptyList','zh-CN',N'暂无文档。请在上方上传第一个文档。'),
('WordDocument_LoadListError','en-US',N'Failed to load document list: {0}'),
('WordDocument_LoadListError','vi-VN',N'Không tải được danh sách: {0}'),
('WordDocument_LoadListError','zh-CN',N'加载文档列表失败：{0}'),
('WordDocument_SelectFilePlease','en-US',N'Please select a file to upload'),
('WordDocument_SelectFilePlease','vi-VN',N'Vui lòng chọn file để tải lên'),
('WordDocument_SelectFilePlease','zh-CN',N'请选择要上传的文件'),
('WordDocument_DescriptionMaxLength','en-US',N'Description must not exceed 1000 characters'),
('WordDocument_DescriptionMaxLength','vi-VN',N'Mô tả không được vượt quá 1000 ký tự'),
('WordDocument_DescriptionMaxLength','zh-CN',N'描述不得超过1000个字符'),
('WordDocument_OnlyDocx','en-US',N'Only .docx files are allowed'),
('WordDocument_OnlyDocx','vi-VN',N'Chỉ chấp nhận file .docx'),
('WordDocument_OnlyDocx','zh-CN',N'仅允许 .docx 文件'),
('WordDocument_FileTooLarge','en-US',N'File size exceeds the maximum limit (10 MB)'),
('WordDocument_FileTooLarge','vi-VN',N'File vượt quá giới hạn (10 MB)'),
('WordDocument_FileTooLarge','zh-CN',N'文件超过大小限制（10 MB）'),
('WordDocument_CannotReadContent','en-US',N'Cannot read file content'),
('WordDocument_CannotReadContent','vi-VN',N'Không đọc được nội dung file'),
('WordDocument_CannotReadContent','zh-CN',N'无法读取文件内容'),
('WordDocument_UploadSuccess','en-US',N'Document uploaded successfully'),
('WordDocument_UploadSuccess','vi-VN',N'Tải lên tài liệu thành công'),
('WordDocument_UploadSuccess','zh-CN',N'文档上传成功'),
('WordDocument_UploadError','en-US',N'Upload failed: {0}'),
('WordDocument_UploadError','vi-VN',N'Tải lên thất bại: {0}'),
('WordDocument_UploadError','zh-CN',N'上传失败：{0}'),
('WordDocument_ViewDocumentTitle','en-US',N'{0} (ID: {1}...)'),
('WordDocument_ViewDocumentTitle','vi-VN',N'{0} (ID: {1}...)'),
('WordDocument_ViewDocumentTitle','zh-CN',N'{0}（ID：{1}...）'),
('WordDocument_DownloadSuccess','en-US',N'Download started'),
('WordDocument_DownloadSuccess','vi-VN',N'Đã bắt đầu tải xuống'),
('WordDocument_DownloadSuccess','zh-CN',N'开始下载'),
('WordDocument_FileNotOnServer','en-US',N'File not found on server'),
('WordDocument_FileNotOnServer','vi-VN',N'Không tìm thấy file trên server'),
('WordDocument_FileNotOnServer','zh-CN',N'服务器上未找到文件'),
('WordDocument_DownloadError','en-US',N'Download failed: {0}'),
('WordDocument_DownloadError','vi-VN',N'Tải xuống thất bại: {0}'),
('WordDocument_DownloadError','zh-CN',N'下载失败：{0}'),
('WordDocument_DeleteConfirmTitle','en-US',N'Delete document'),
('WordDocument_DeleteConfirmTitle','vi-VN',N'Xóa tài liệu'),
('WordDocument_DeleteConfirmTitle','zh-CN',N'删除文档'),
('WordDocument_DeleteSuccess','en-US',N'Deleted: {0}'),
('WordDocument_DeleteSuccess','vi-VN',N'Đã xóa: {0}'),
('WordDocument_DeleteSuccess','zh-CN',N'已删除：{0}'),
('WordDocument_NotFoundToDelete','en-US',N'Document not found or already deleted'),
('WordDocument_NotFoundToDelete','vi-VN',N'Không tìm thấy tài liệu hoặc đã bị xóa'),
('WordDocument_NotFoundToDelete','zh-CN',N'未找到文档或已删除'),
('WordDocument_DeleteError','en-US',N'Delete failed: {0}'),
('WordDocument_DeleteError','vi-VN',N'Xóa thất bại: {0}'),
('WordDocument_DeleteError','zh-CN',N'删除失败：{0}');

-- ========== CompanyInformation ==========
INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('CompanyInformation_Tab','en-US',N'Company information'),
('CompanyInformation_Tab','vi-VN',N'Thông tin công ty'),
('CompanyInformation_Tab','zh-CN',N'公司信息'),
('PrefixTab','en-US',N'Prefix'),
('PrefixTab','vi-VN',N'Hằng số'),
('PrefixTab','zh-CN',N'前缀'),
('CompanyOther_Tab','en-US',N'Other company info'),
('CompanyOther_Tab','vi-VN',N'Thông tin khác'),
('CompanyOther_Tab','zh-CN',N'其他公司信息'),
('CompanyLogo','en-US',N'Company logo'),
('CompanyLogo','vi-VN',N'Logo công ty'),
('CompanyLogo','zh-CN',N'公司标志'),
('NoLogoYet','en-US',N'No logo yet'),
('NoLogoYet','vi-VN',N'Chưa có logo'),
('NoLogoYet','zh-CN',N'暂无标志'),
('ChooseLogo','en-US',N'Choose logo'),
('ChooseLogo','vi-VN',N'Chọn logo'),
('ChooseLogo','zh-CN',N'选择标志'),
('RemoveLogo','en-US',N'Remove logo'),
('RemoveLogo','vi-VN',N'Xóa logo'),
('RemoveLogo','zh-CN',N'移除标志'),
('NotificationEmail','en-US',N'Notification email'),
('NotificationEmail','vi-VN',N'Email gửi thông báo'),
('NotificationEmail','zh-CN',N'通知邮箱'),
('NotificationEmailPassword','en-US',N'Notification email password'),
('NotificationEmailPassword','vi-VN',N'Mật khẩu email gửi thông báo'),
('NotificationEmailPassword','zh-CN',N'通知邮箱密码'),
('SmtpServer','en-US',N'SMTP server'),
('SmtpServer','vi-VN',N'SMTP server'),
('SmtpServer','zh-CN',N'SMTP服务器'),
('SmtpPort','en-US',N'SMTP port'),
('SmtpPort','vi-VN',N'Cổng SMTP'),
('SmtpPort','zh-CN',N'SMTP端口'),
('ApprovalEmailList','en-US',N'Approval email list'),
('ApprovalEmailList','vi-VN',N'Danh sách email duyệt'),
('ApprovalEmailList','zh-CN',N'审批邮箱列表'),
('EmailListHelper','en-US',N'Separate multiple emails with semicolons'),
('EmailListHelper','vi-VN',N'Phân cách nhiều email bằng dấu chấm phẩy'),
('EmailListHelper','zh-CN',N'多个邮箱用分号分隔'),
('AccountName','en-US',N'Account name'),
('AccountName','vi-VN',N'Tên tài khoản'),
('AccountName','zh-CN',N'账户名称'),
('BankName','en-US',N'Bank name'),
('BankName','vi-VN',N'Tên ngân hàng'),
('BankName','zh-CN',N'银行名称'),
('AccountNo','en-US',N'Account number'),
('AccountNo','vi-VN',N'Số tài khoản'),
('AccountNo','zh-CN',N'账号'),
('Deposit','en-US',N'Deposit'),
('Deposit','vi-VN',N'Ký quỹ'),
('Deposit','zh-CN',N'保证金'),
('Transit','en-US',N'Transit'),
('Transit','vi-VN',N'Quá cảnh'),
('Transit','zh-CN',N'中转'),
('CustomerSupportPhone','en-US',N'Customer support phone'),
('CustomerSupportPhone','vi-VN',N'SĐT hỗ trợ KH'),
('CustomerSupportPhone','zh-CN',N'客户支持电话'),
('Company','en-US',N'Company'),
('Company','vi-VN',N'Công ty'),
('Company','zh-CN',N'公司'),
('BankAddress','en-US',N'Bank address'),
('BankAddress','vi-VN',N'Địa chỉ ngân hàng'),
('BankAddress','zh-CN',N'银行地址'),
('IbanCode','en-US',N'IBAN code'),
('IbanCode','vi-VN',N'Mã IBAN'),
('IbanCode','zh-CN',N'IBAN代码'),
('Branches','en-US',N'Branches'),
('Branches','vi-VN',N'Chi nhánh'),
('Branches','zh-CN',N'分行'),
('LogoMaxSize','en-US',N'Logo file must not exceed 500 KB'),
('LogoMaxSize','vi-VN',N'Logo không được vượt quá 500 KB'),
('LogoMaxSize','zh-CN',N'标志文件不得超过500 KB'),
('LogoReadError','en-US',N'Failed to read logo: {0}'),
('LogoReadError','vi-VN',N'Không đọc được logo: {0}'),
('LogoReadError','zh-CN',N'读取标志失败：{0}'),
('SaveError','en-US',N'Save failed: {0}'),
('SaveError','vi-VN',N'Lưu thất bại: {0}'),
('SaveError','zh-CN',N'保存失败：{0}'),
('DeleteConfirmItem','en-US',N'Are you sure you want to delete {0} - {1}?'),
('DeleteConfirmItem','vi-VN',N'Bạn có chắc muốn xóa {0} - {1}?'),
('DeleteConfirmItem','zh-CN',N'确定要删除 {0} - {1} 吗？');

-- ========== BillSeaLayoutEditor ==========
INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('LayoutEditor_Title','en-US',N'Layout form editor'),
('LayoutEditor_Title','vi-VN',N'Chỉnh layout form'),
('LayoutEditor_Title','zh-CN',N'表单布局编辑器'),
('LayoutEditor_Page2','en-US',N'Page 2'),
('LayoutEditor_Page2','vi-VN',N'Trang 2'),
('LayoutEditor_Page2','zh-CN',N'第2页'),
('LayoutEditor_SelectForm','en-US',N'Select {0} form'),
('LayoutEditor_SelectForm','vi-VN',N'Chọn form {0}'),
('LayoutEditor_SelectForm','zh-CN',N'选择 {0} 表单'),
('LayoutEditor_FormCustomized','en-US',N' (customized)'),
('LayoutEditor_FormCustomized','vi-VN',N' (đã chỉnh)'),
('LayoutEditor_FormCustomized','zh-CN',N'（已自定义）'),
('LayoutEditor_CreateForm','en-US',N'Create new form'),
('LayoutEditor_CreateForm','vi-VN',N'Tạo form mới'),
('LayoutEditor_CreateForm','zh-CN',N'创建新表单'),
('LayoutEditor_DeleteForm','en-US',N'Delete form'),
('LayoutEditor_DeleteForm','vi-VN',N'Xóa form'),
('LayoutEditor_DeleteForm','zh-CN',N'删除表单'),
('LayoutEditor_ReloadList','en-US',N'Reload list'),
('LayoutEditor_ReloadList','vi-VN',N'Tải lại danh sách'),
('LayoutEditor_ReloadList','zh-CN',N'重新加载列表'),
('LayoutEditor_MainForm','en-US',N'Main form'),
('LayoutEditor_MainForm','vi-VN',N'Form chính'),
('LayoutEditor_MainForm','zh-CN',N'主表单'),
('LayoutEditor_AttachForm','en-US',N'Attach form'),
('LayoutEditor_AttachForm','vi-VN',N'Form Attach'),
('LayoutEditor_AttachForm','zh-CN',N'附件表单'),
('LayoutEditor_CreateAttachForm','en-US',N'Create attach form'),
('LayoutEditor_CreateAttachForm','vi-VN',N'Tạo form Attach'),
('LayoutEditor_CreateAttachForm','zh-CN',N'创建附件表单'),
('LayoutEditor_DeleteAttachForm','en-US',N'Delete attach form'),
('LayoutEditor_DeleteAttachForm','vi-VN',N'Xóa form Attach'),
('LayoutEditor_DeleteAttachForm','zh-CN',N'删除附件表单'),
('LayoutEditor_Help_An','en-US',N'<b>AN Sea</b> from <b>BillArrivalNoticeNVOCC.mrt</b>. <b>AN Air</b> from <b>BillArrivalNotice_Air.mrt</b>. Logo can be replaced.'),
('LayoutEditor_Help_An','vi-VN',N'<b>AN Sea</b> từ <b>BillArrivalNoticeNVOCC.mrt</b>. <b>AN Air</b> từ <b>BillArrivalNotice_Air.mrt</b>. Có thể chọn logo thay thế.'),
('LayoutEditor_Help_An','zh-CN',N'<b>AN Sea</b> 来自 <b>BillArrivalNoticeNVOCC.mrt</b>。<b>AN Air</b> 来自 <b>BillArrivalNotice_Air.mrt</b>。可替换 logo。'),
('LayoutEditor_Help_Do','en-US',N'<b>DO</b> from <b>BillDeliveryOrderNVOCC.mrt</b> (no Sea/Air split). Logo can be replaced.'),
('LayoutEditor_Help_Do','vi-VN',N'<b>DO</b> từ <b>BillDeliveryOrderNVOCC.mrt</b> (không tách Sea/Air). Có thể chọn logo thay thế.'),
('LayoutEditor_Help_Do','zh-CN',N'<b>DO</b> 来自 <b>BillDeliveryOrderNVOCC.mrt</b>（不分 Sea/Air）。可替换 logo。'),
('LayoutEditor_Help_Booking','en-US',N'<b>Booking</b> from <b>BookingRequestNVOCC.mrt</b> (no Sea/Air split). <b>Image1</b> uses <b>CompanyInfo.Logo</b>; connection string follows the active DB when exporting.'),
('LayoutEditor_Help_Booking','vi-VN',N'<b>Booking</b> từ <b>BookingRequestNVOCC.mrt</b> (không tách Sea/Air). <b>Image1</b> lấy logo từ <b>CompanyInfo.Logo</b>; connection string theo DB đang kết nối khi xuất.'),
('LayoutEditor_Help_Booking','zh-CN',N'<b>Booking</b> 来自 <b>BookingRequestNVOCC.mrt</b>（不分 Sea/Air）。<b>Image1</b> 使用 <b>CompanyInfo.Logo</b>；导出时连接字符串跟随当前数据库。'),
('LayoutEditor_Help_Quotation','en-US',N'<b>Quotation</b> from <b>Quotation.mrt</b> (no Sea/Air split). <b>Image1</b> uses <b>CompanyInfo.Logo</b>; connection string follows the active DB when exporting.'),
('LayoutEditor_Help_Quotation','vi-VN',N'<b>Quotation</b> từ <b>Quotation.mrt</b> (không tách Sea/Air). <b>Image1</b> lấy logo từ <b>CompanyInfo.Logo</b>; connection string theo DB đang kết nối khi xuất.'),
('LayoutEditor_Help_Quotation','zh-CN',N'<b>Quotation</b> 来自 <b>Quotation.mrt</b>（不分 Sea/Air）。<b>Image1</b> 使用 <b>CompanyInfo.Logo</b>；导出时连接字符串跟随当前数据库。'),
('LayoutEditor_Help_Bill','en-US',N'<b>Bill Sea</b> from <b>BillSea_NVOCC.mrt</b> (attach form, background image, remove lines). <b>Bill Air</b> from <b>BillAir.mrt</b> (background Image1, remove lines). <b>Page 2</b> from <b>BillTrang2.mrt</b> (full image or full text only).'),
('LayoutEditor_Help_Bill','vi-VN',N'<b>Bill Sea</b> từ <b>BillSea_NVOCC.mrt</b> (có thể tạo form Attach, thêm ảnh nền, bỏ line). <b>Bill Air</b> từ <b>BillAir.mrt</b> (ảnh nền Image1, bỏ line). <b>Trang 2</b> từ <b>BillTrang2.mrt</b> (chỉ ảnh full hoặc text full).'),
('LayoutEditor_Help_Bill','zh-CN',N'<b>Bill Sea</b> 来自 <b>BillSea_NVOCC.mrt</b>（可创建附件表单、背景图、删除线条）。<b>Bill Air</b> 来自 <b>BillAir.mrt</b>（背景 Image1，删除线条）。<b>第2页</b> 来自 <b>BillTrang2.mrt</b>（仅全图或全文本）。'),
('LayoutEditor_NoAttachForm','en-US',N'Form <b>{0}</b> has no attach form yet. Click <b>Create attach form</b> to create one from the current main form.'),
('LayoutEditor_NoAttachForm','vi-VN',N'Form <b>{0}</b> chưa có form Attach. Bấm <b>Tạo form Attach</b> để tạo từ form chính hiện tại.'),
('LayoutEditor_NoAttachForm','zh-CN',N'表单 <b>{0}</b> 尚无附件表单。点击 <b>创建附件表单</b> 从当前主表单创建。'),
('LayoutEditor_NoForm','en-US',N'No {0} form yet. Click <b>Create new form</b> to get started.'),
('LayoutEditor_NoForm','vi-VN',N'Chưa có form {0}. Bấm <b>Tạo form mới</b> để bắt đầu.'),
('LayoutEditor_NoForm','zh-CN',N'尚无 {0} 表单。点击 <b>创建新表单</b> 开始。'),
('LayoutEditor_LoadError','en-US',N'Failed to load data: {0}'),
('LayoutEditor_LoadError','vi-VN',N'Không tải được dữ liệu: {0}'),
('LayoutEditor_LoadError','zh-CN',N'加载数据失败：{0}'),
('LayoutEditor_LoadFormsError','en-US',N'Failed to load form list: {0}'),
('LayoutEditor_LoadFormsError','vi-VN',N'Không tải được danh sách form: {0}'),
('LayoutEditor_LoadFormsError','zh-CN',N'加载表单列表失败：{0}'),
('LayoutEditor_CreateFormTitle','en-US',N'Create new {0} form'),
('LayoutEditor_CreateFormTitle','vi-VN',N'Tạo form {0} mới'),
('LayoutEditor_CreateFormTitle','zh-CN',N'创建新 {0} 表单'),
('LayoutEditor_CreateFormDialog','en-US',N'Create new form'),
('LayoutEditor_CreateFormDialog','vi-VN',N'Tạo form mới'),
('LayoutEditor_CreateFormDialog','zh-CN',N'创建新表单'),
('LayoutEditor_FormCreated','en-US',N'Form ''{0}'' created.'),
('LayoutEditor_FormCreated','vi-VN',N'Đã tạo form ''{0}''.'),
('LayoutEditor_FormCreated','zh-CN',N'已创建表单 ''{0}''.'),
('LayoutEditor_DeleteFormTitle','en-US',N'Delete {0} form'),
('LayoutEditor_DeleteFormTitle','vi-VN',N'Xóa form {0}'),
('LayoutEditor_DeleteFormTitle','zh-CN',N'删除 {0} 表单'),
('LayoutEditor_DeleteFormBody','en-US',N'Are you sure you want to delete form ''{0}''?'),
('LayoutEditor_DeleteFormBody','vi-VN',N'Bạn có chắc muốn xóa form ''{0}''?'),
('LayoutEditor_DeleteFormBody','zh-CN',N'确定要删除表单 ''{0}'' 吗？'),
('LayoutEditor_DeleteFormAttachNote','en-US',N'

The attached form will also be deleted.'),
('LayoutEditor_DeleteFormAttachNote','vi-VN',N'

Form Attach đi kèm cũng sẽ bị xóa.'),
('LayoutEditor_DeleteFormAttachNote','zh-CN',N'

附件表单也将被删除。'),
('LayoutEditor_FormDeleted','en-US',N'Form deleted.'),
('LayoutEditor_FormDeleted','vi-VN',N'Đã xóa form.'),
('LayoutEditor_FormDeleted','zh-CN',N'表单已删除。'),
('LayoutEditor_AttachFormCreated','en-US',N'Attach form created for ''{0}''.'),
('LayoutEditor_AttachFormCreated','vi-VN',N'Đã tạo form Attach cho ''{0}''.'),
('LayoutEditor_AttachFormCreated','zh-CN',N'已为 ''{0}'' 创建附件表单。'),
('LayoutEditor_DeleteAttachFormTitle','en-US',N'Delete attach form'),
('LayoutEditor_DeleteAttachFormTitle','vi-VN',N'Xóa form Attach'),
('LayoutEditor_DeleteAttachFormTitle','zh-CN',N'删除附件表单'),
('LayoutEditor_DeleteAttachFormBody','en-US',N'Are you sure you want to delete the attach form of ''{0}''?'),
('LayoutEditor_DeleteAttachFormBody','vi-VN',N'Bạn có chắc muốn xóa form Attach của ''{0}''?'),
('LayoutEditor_DeleteAttachFormBody','zh-CN',N'确定要删除 ''{0}'' 的附件表单吗？'),
('LayoutEditor_AttachFormDeleted','en-US',N'Attach form deleted.'),
('LayoutEditor_AttachFormDeleted','vi-VN',N'Đã xóa form Attach.'),
('LayoutEditor_AttachFormDeleted','zh-CN',N'附件表单已删除。');

-- ========== Home / Dashboard ==========
INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('Dashboard_Subtitle','en-US',N'Overview of profit, quotations, debt and shipment status in {0}'),
('Dashboard_Subtitle','vi-VN',N'Tổng quan lợi nhuận, báo giá, công nợ và tình trạng lô hàng trong năm {0}'),
('Dashboard_Subtitle','zh-CN',N'{0} 年利润、报价、债务和货运状态概览'),
('Dashboard_ProfitMonth','en-US',N'Profit month {0}'),
('Dashboard_ProfitMonth','vi-VN',N'Profit tháng {0}'),
('Dashboard_ProfitMonth','zh-CN',N'{0} 月利润'),
('Dashboard_ProfitCaption','en-US',N'Current total profit'),
('Dashboard_ProfitCaption','vi-VN',N'Tổng lợi nhuận hiện tại'),
('Dashboard_ProfitCaption','zh-CN',N'当前总利润'),
('Dashboard_QuoteRequest','en-US',N'Quotation requests'),
('Dashboard_QuoteRequest','vi-VN',N'Yêu cầu báo giá'),
('Dashboard_QuoteRequest','zh-CN',N'报价请求'),
('Dashboard_QuoteCaption','en-US',N'By quotation status'),
('Dashboard_QuoteCaption','vi-VN',N'Theo trạng thái quotation'),
('Dashboard_QuoteCaption','zh-CN',N'按报价状态'),
('Dashboard_OverdueDebt','en-US',N'Overdue debt'),
('Dashboard_OverdueDebt','vi-VN',N'Công nợ quá hạn'),
('Dashboard_OverdueDebt','zh-CN',N'逾期债务'),
('Dashboard_DebtCaption','en-US',N'Customer debt status'),
('Dashboard_DebtCaption','vi-VN',N'Tình trạng công nợ khách hàng'),
('Dashboard_DebtCaption','zh-CN',N'客户债务状况'),
('Dashboard_ProfitReport','en-US',N'Profit report for {0}'),
('Dashboard_ProfitReport','vi-VN',N'Báo cáo lợi nhuận trong năm {0}'),
('Dashboard_ProfitReport','zh-CN',N'{0} 年利润报告'),
('Dashboard_ShipmentReport','en-US',N'Shipment report for {0}'),
('Dashboard_ShipmentReport','vi-VN',N'Báo cáo lô hàng trong năm {0}'),
('Dashboard_ShipmentReport','zh-CN',N'{0} 年货运报告'),
('Dashboard_MapTracking','en-US',N'Shipment location tracking'),
('Dashboard_MapTracking','vi-VN',N'Theo dõi vị trí lô hàng'),
('Dashboard_MapTracking','zh-CN',N'货运位置跟踪'),
('Dashboard_HideMap','en-US',N'Hide map'),
('Dashboard_HideMap','vi-VN',N'Ẩn bản đồ'),
('Dashboard_HideMap','zh-CN',N'隐藏地图'),
('Dashboard_ShowMap','en-US',N'Show map'),
('Dashboard_ShowMap','vi-VN',N'Hiện bản đồ'),
('Dashboard_ShowMap','zh-CN',N'显示地图'),
('Dashboard_HBLInputLabel','en-US',N'Enter HBL number(s)'),
('Dashboard_HBLInputLabel','vi-VN',N'Nhập HBL Number(s)'),
('Dashboard_HBLInputLabel','zh-CN',N'输入 HBL 编号'),
('Dashboard_HBLPlaceholder','en-US',N'E.g. HBL001 or HBL001,HBL002...'),
('Dashboard_HBLPlaceholder','vi-VN',N'VD: HBL001 hoặc HBL001,HBL002...'),
('Dashboard_HBLPlaceholder','zh-CN',N'例如：HBL001 或 HBL001,HBL002...'),
('Dashboard_ClosePopup','en-US',N'Close popups'),
('Dashboard_ClosePopup','vi-VN',N'Đóng popup'),
('Dashboard_ClosePopup','zh-CN',N'关闭弹窗'),
('Dashboard_Selected','en-US',N'Selected:'),
('Dashboard_Selected','vi-VN',N'Đã chọn:'),
('Dashboard_Selected','zh-CN',N'已选择：'),
('Dashboard_TrackingMap','en-US',N'Tracking map'),
('Dashboard_TrackingMap','vi-VN',N'Bản đồ theo dõi'),
('Dashboard_TrackingMap','zh-CN',N'跟踪地图'),
('Dashboard_MapStyle','en-US',N'Map style'),
('Dashboard_MapStyle','vi-VN',N'Kiểu bản đồ'),
('Dashboard_MapStyle','zh-CN',N'地图样式'),
('Dashboard_MapStyle_Roadmap','en-US',N'OpenStreetMap'),
('Dashboard_MapStyle_Roadmap','vi-VN',N'OpenStreetMap'),
('Dashboard_MapStyle_Roadmap','zh-CN',N'OpenStreetMap'),
('Dashboard_MapStyle_Satellite','en-US',N'Satellite'),
('Dashboard_MapStyle_Satellite','vi-VN',N'Vệ tinh'),
('Dashboard_MapStyle_Satellite','zh-CN',N'卫星'),
('Dashboard_MapStyle_Terrain','en-US',N'Terrain'),
('Dashboard_MapStyle_Terrain','vi-VN',N'Địa hình'),
('Dashboard_MapStyle_Terrain','zh-CN',N'地形'),
('Dashboard_MapStyle_Hybrid','en-US',N'Hybrid'),
('Dashboard_MapStyle_Hybrid','vi-VN',N'Lai'),
('Dashboard_MapStyle_Hybrid','zh-CN',N'混合'),
('Dashboard_MapStyle_Traffic','en-US',N'Traffic'),
('Dashboard_MapStyle_Traffic','vi-VN',N'Giao thông'),
('Dashboard_MapStyle_Traffic','zh-CN',N'交通'),
('Dashboard_Traffic','en-US',N'Traffic'),
('Dashboard_Traffic','vi-VN',N'Giao thông'),
('Dashboard_Traffic','zh-CN',N'交通'),
('Dashboard_ProfitUSD','en-US',N'Profit USD'),
('Dashboard_ProfitUSD','vi-VN',N'Profit USD'),
('Dashboard_ProfitUSD','zh-CN',N'利润 USD'),
('Dashboard_Debt_Overdue','en-US',N'Overdue'),
('Dashboard_Debt_Overdue','vi-VN',N'Quá hạn'),
('Dashboard_Debt_Overdue','zh-CN',N'逾期'),
('Dashboard_Debt_NotDue','en-US',N'Not yet due'),
('Dashboard_Debt_NotDue','vi-VN',N'Chưa đến hạn'),
('Dashboard_Debt_NotDue','zh-CN',N'未到期'),
('Dashboard_EnterHBL','en-US',N'Please enter HBL number'),
('Dashboard_EnterHBL','vi-VN',N'Vui lòng nhập HBL Number'),
('Dashboard_EnterHBL','zh-CN',N'请输入 HBL 编号'),
('Dashboard_SearchingHBL','en-US',N'Searching HBL...'),
('Dashboard_SearchingHBL','vi-VN',N'Đang tìm kiếm HBL...'),
('Dashboard_SearchingHBL','zh-CN',N'正在搜索 HBL...'),
('Dashboard_InvalidHBL','en-US',N'No valid HBL number found'),
('Dashboard_InvalidHBL','vi-VN',N'Không tìm thấy HBL number hợp lệ'),
('Dashboard_InvalidHBL','zh-CN',N'未找到有效的 HBL 编号'),
('Dashboard_NoLocationForHBLs','en-US',N'No location data found for {0} HBL(s)'),
('Dashboard_NoLocationForHBLs','vi-VN',N'Không tìm thấy dữ liệu vị trí cho {0} HBL'),
('Dashboard_NoLocationForHBLs','zh-CN',N'未找到 {0} 个 HBL 的位置数据'),
('Dashboard_FoundHBLWithLocations','en-US',N'Found {0}/{1} HBL(s) with {2} location(s)'),
('Dashboard_FoundHBLWithLocations','vi-VN',N'Đã tìm thấy {0}/{1} HBL với {2} vị trí'),
('Dashboard_FoundHBLWithLocations','zh-CN',N'找到 {0}/{1} 个 HBL，共 {2} 个位置'),
('Dashboard_SearchError','en-US',N'Search error: {0}'),
('Dashboard_SearchError','vi-VN',N'Có lỗi xảy ra khi tìm kiếm: {0}'),
('Dashboard_SearchError','zh-CN',N'搜索出错：{0}'),
('Dashboard_SelectHBLBeforeReload','en-US',N'Please select HBL before reload'),
('Dashboard_SelectHBLBeforeReload','vi-VN',N'Vui lòng chọn HBL trước khi reload'),
('Dashboard_SelectHBLBeforeReload','zh-CN',N'刷新前请先选择 HBL'),
('Dashboard_FoundLocationsForHBL','en-US',N'Found {0} location(s) for {1} HBL(s)'),
('Dashboard_FoundLocationsForHBL','vi-VN',N'Đã tìm thấy {0} vị trí cho {1} HBL'),
('Dashboard_FoundLocationsForHBL','zh-CN',N'找到 {0} 个位置，共 {1} 个 HBL'),
('Dashboard_NoLocationForTheseHBL','en-US',N'No location data found for these HBL(s)'),
('Dashboard_NoLocationForTheseHBL','vi-VN',N'Không tìm thấy dữ liệu vị trí cho các HBL này'),
('Dashboard_NoLocationForTheseHBL','zh-CN',N'未找到这些 HBL 的位置数据'),
('Dashboard_LoadDataError','en-US',N'Failed to load data: {0}'),
('Dashboard_LoadDataError','vi-VN',N'Có lỗi xảy ra khi load dữ liệu: {0}'),
('Dashboard_LoadDataError','zh-CN',N'加载数据失败：{0}'),
('Dashboard_MapCleared','en-US',N'All map data cleared'),
('Dashboard_MapCleared','vi-VN',N'Đã xóa tất cả dữ liệu map'),
('Dashboard_MapCleared','zh-CN',N'已清除所有地图数据'),
('Dashboard_ClearMapError','en-US',N'Failed to clear map: {0}'),
('Dashboard_ClearMapError','vi-VN',N'Có lỗi xảy ra khi xóa map: {0}'),
('Dashboard_ClearMapError','zh-CN',N'清除地图失败：{0}'),
('Dashboard_PopupsClosed','en-US',N'All map popups closed'),
('Dashboard_PopupsClosed','vi-VN',N'Đã đóng tất cả popup trên map'),
('Dashboard_PopupsClosed','zh-CN',N'已关闭地图上所有弹窗'),
('Dashboard_ClosePopupError','en-US',N'Failed to close popups: {0}'),
('Dashboard_ClosePopupError','vi-VN',N'Có lỗi xảy ra khi đóng popup: {0}'),
('Dashboard_ClosePopupError','zh-CN',N'关闭弹窗失败：{0}'),
('Dashboard_NoLocationData','en-US',N'No location data to display'),
('Dashboard_NoLocationData','vi-VN',N'Không có dữ liệu vị trí để hiển thị'),
('Dashboard_NoLocationData','zh-CN',N'没有可显示的位置数据'),
('Dashboard_NoValidCoordinates','en-US',N'No valid coordinates to display on map'),
('Dashboard_NoValidCoordinates','vi-VN',N'Không có tọa độ hợp lệ để hiển thị trên bản đồ'),
('Dashboard_NoValidCoordinates','zh-CN',N'没有可在地图上显示的有效坐标'),
('Dashboard_ShowingValidLocations','en-US',N'Showing {0}/{1} valid location(s)'),
('Dashboard_ShowingValidLocations','vi-VN',N'Hiển thị {0}/{1} vị trí hợp lệ'),
('Dashboard_ShowingValidLocations','zh-CN',N'显示 {0}/{1} 个有效位置'),
('Dashboard_LoadedLocationsOnMap','en-US',N'Loaded {0} location(s) on map'),
('Dashboard_LoadedLocationsOnMap','vi-VN',N'Đã tải {0} vị trí lên bản đồ'),
('Dashboard_LoadedLocationsOnMap','zh-CN',N'已在地图上加载 {0} 个位置'),
('Dashboard_LoadMapError','en-US',N'Map load error: {0}'),
('Dashboard_LoadMapError','vi-VN',N'Lỗi khi load map: {0}'),
('Dashboard_LoadMapError','zh-CN',N'地图加载错误：{0}');

COMMIT;
