-- Menu 8: EQ / Stock / Charge setup (8.1–8.8)
-- Depends on: Group C, Groups 2–7 (NoPermission_*, SelectOneRow, SaveFailed, etc.)
-- Also run module scripts if not yet applied:
--   ImportChargeTypeLocalizationResources.sql
--   ImportTariffHeaderLocalizationResources.sql
--   ImportTariffTierLocalizationResources.sql
--   ImportShipmentChargeContextLocalizationResources.sql
--   ImportYardMovementLocalizationResources.sql
BEGIN TRANSACTION;

DELETE FROM LocalizationResources WHERE ResourceKey IN (
    'EqControl_Subtitle','Eq_SelectContainer','Eq_LoadContainersError',
    'Eq_ContainerType','Eq_OwnershipType','Eq_Owner','Eq_CurrentLocation','Eq_CurrentDepot',
    'Eq_ManufactureDate','Eq_LastInspectionDate','Eq_GetTemplate','Eq_Import','Eq_Add',
    'Eq_ContainerNoRequired','Eq_ContainerNoHint','Eq_ConfirmDelete','Eq_TemplateDownloaded',
    'Eq_ImportSheetNotFound','Eq_ImportSuccess','Eq_ImportError',
    'Eq_SearchContainerError','Eq_SearchMblError','Eq_SearchHblError','Eq_SearchJobError',
    'Eq_SaveGateInError','Eq_SaveGateOutError','Eq_NoRowsForContainer','Eq_ImportGateSuccess',
    'Eq_ImportGateInOutError','Eq_LoadContainersFirst','Eq_ContainerNotSelected',
    'Eq_GateInSheetNotFound','Eq_GateOutSheetNotFound','Eq_ImportGateInError','Eq_ImportGateOutError',
    'Eq_ImportedGateInCount','Eq_ImportedGateOutCount',
    'Terminal_Subtitle','Terminal_Name','FreeStorage','ValidOrder','OrderReport','Continued','Editable','CodeNvocc','Tel','Capacity','Address','New','Code',
    'ChargeType_Subtitle','TariffHeader_Subtitle','TariffTier_Subtitle','Scc_Subtitle',
    'Scdm_PageTitle','Scdm_Title','Scdm_Subtitle','Scdm_SaveConfig','Scdm_InfoAlert','Scdm_TargetDate','Scdm_DataSource','Scdm_Enabled','Scdm_Saved','Scdm_SaveFailed',
    'Ci_PageTitle','Ci_Title','Ci_Subtitle','Ci_DataSource','Ci_Import834','Ci_Import835','Ci_Import836','Ci_Import837','Refresh',
    'StockImport_PageTitle834','StockImport_HeroTitle834','StockImport_HeroDesc834',
    'StockImport_PageTitle835','StockImport_HeroTitle835','StockImport_HeroDesc835',
    'StockImport_PageTitle836','StockImport_HeroTitle836','StockImport_HeroDesc836',
    'StockImport_PageTitle838','StockImport_HeroTitle838','StockImport_HeroDesc838','StockImport_DepotPlaceholder838',
    'StockImport_HeroTitle837','StockImport_HeroDesc837','StockImport_SpItcDepot',
    'StockImport_DepotName','StockImport_SelectDepotBeforePreview','StockImport_ChooseExcel','StockImport_ImportDb','StockImport_Reset','StockImport_Clear','StockImport_SaveImport',
    'StockImport_PreviewRows','StockImport_NewRows','StockImport_DuplicateRows',
    'StockImport_SelectDepotPreview','StockImport_SelectDepotImport','StockImport_XlsxOnly','StockImport_XlsXlsxOnly',
    'StockImport_NoFileSelected','StockImport_NoValidRows','StockImport_NoNewRowsAfterDupCheck','StockImport_NoPermissionVss','StockImport_NoPermissionInventory',
    'StockImport_PreviewSummary','StockImport_NothingImported','StockImport_YardMovementCompleted','StockImport_VssCompleted',
    'StockImport_ApsPreviewSummary','StockImport_ApsNothingImported','StockImport_ApsCompleted',
    'StockImport_AlpineSheetsNotFound','StockImport_AlpinePreviewSummary','StockImport_NoNewRows','StockImport_AlpineCompleted',
    'StockImport_PreviewDone','StockImport_PreviewError','StockImport_NoPreviewData','StockImport_AllDuplicate','StockImport_SpItcSaved',
    'EqGate_GateIn','EqGate_GateOut','EqGate_AddGateIn','EqGate_AddGateOut','EqGate_Seq','EqGate_EIR','EqGate_TimeIn',
    'EqGate_IsoSztp','EqGate_Opt','EqGate_FE','EqGate_Move','EqGate_Location','EqGate_BillOfLading','EqGate_Consignee','EqGate_Truck',
    'EqGate_YOM','EqGate_SealNo1','EqGate_SealNo2','EqGate_VGM','EqGate_Clean','EqGate_MaxGross','EqGate_Grade','EqGate_Voyage',
    'EqGate_Shipper','EqGate_Note1','EqGate_RequiredGrade','EqGate_TruckNo','EqGate_TruckerPhone','EqGate_Days',
    'Container','Remark','Booking','POL','POD','DateIn','DateOut','SealNo','Close','Search',
    'Ci_SearchPlaceholder','Ci_Source','Ci_Agent','Ci_Line','Ci_Depot','Ci_SizeType','Ci_LoadFE','Ci_Damage','Ci_HideDam',
    'Ci_DemFree','Ci_DetFree','Ci_DemMin','Ci_DetMin','Ci_Other','Ci_StatusInDepot','Ci_StatusWaitingPort','Ci_StatusArrivedPort','Ci_StatusInTransit',
    'Ci_LoadEmpty','Ci_LoadFull','Ci_LoadOther','Ci_DamageDamaged','Ci_Print',
    'Ci_SectionInDepot','Ci_SectionWaitingPort','Ci_SectionArrivedPort','Ci_SectionInTransit',
    'Ci_Col_ContainerType','Ci_Col_Empty','Ci_Col_Full','Ci_Col_OtherLoad','Ci_Col_Damaged',
    'Ci_ContainerDetail','Ci_RowsCount','Ci_DetailChip','Ci_HideDetailList','Ci_ShowDetailList',
    'Ci_Col_InOut','Ci_Col_LastEvent','Ci_Col_GateInDate','Ci_Col_GateOutDate','Ci_Col_DemDays','Ci_Col_DemBillable','Ci_Col_DetDays','Ci_Col_DetBillable',
    'Ci_Col_InsDate','Ci_Col_CustomsDate','Ci_Col_CleanMethod','Ci_Col_CleanStatus','Ci_Col_PtiDate','Ci_Col_PtiSetting','Ci_Col_PtiStatus',
    'Ci_Col_EstimatedDate','Ci_Col_ApprovalDate','Ci_Col_RejectDate','Ci_Col_RepairedDate','Ci_Col_RegisteredDate',
    'Ci_Col_CurrentLocation','Ci_Col_CurrentStatus','Ci_Col_IsoSize','Ci_Col_SizeGroup','Ci_Col_DamageStatus','Ci_Col_RawFel','Ci_Col_Weight',
    'Ci_Col_BillBooking','Ci_Col_BL','Ci_Col_Seal','Ci_Col_ImportSource','Ci_DetailHiddenAlert','Ci_EventDetailTitle','Ci_LatestStatusCaption',
    'Ci_HideEventList','Ci_ShowEventList','Ci_MiniContainerDepot','Ci_MiniMovementStatus','Ci_MiniBillSeal','Ci_MiniLocationDamage',
    'Ci_LoadedSuccess','Ci_Col_EventTime','Ci_Col_RawMethod','Ci_EventHiddenAlert'
);

INSERT INTO LocalizationResources (ResourceKey, Culture, Value) VALUES
('EqControl_Subtitle','en-US',N'8.1 · Container master and owner'),('EqControl_Subtitle','vi-VN',N'8.1 · Danh mục container và chủ container'),('EqControl_Subtitle','zh-CN',N'8.1 · 集装箱主数据与箱主'),
('Eq_ContainerType','en-US',N'Container Type'),('Eq_ContainerType','vi-VN',N'Loại container'),('Eq_ContainerType','zh-CN',N'箱型'),
('Eq_OwnershipType','en-US',N'Ownership Type'),('Eq_OwnershipType','vi-VN',N'Loại sở hữu'),('Eq_OwnershipType','zh-CN',N'所有权类型'),
('Eq_Owner','en-US',N'Owner'),('Eq_Owner','vi-VN',N'Chủ container'),('Eq_Owner','zh-CN',N'箱主'),
('Eq_CurrentLocation','en-US',N'Current Location'),('Eq_CurrentLocation','vi-VN',N'Vị trí hiện tại'),('Eq_CurrentLocation','zh-CN',N'当前位置'),
('Eq_CurrentDepot','en-US',N'Current Depot'),('Eq_CurrentDepot','vi-VN',N'Depot hiện tại'),('Eq_CurrentDepot','zh-CN',N'当前堆场'),
('Eq_ManufactureDate','en-US',N'Manufacture Date'),('Eq_ManufactureDate','vi-VN',N'Ngày sản xuất'),('Eq_ManufactureDate','zh-CN',N'生产日期'),
('Eq_LastInspectionDate','en-US',N'Last Inspection Date'),('Eq_LastInspectionDate','vi-VN',N'Ngày kiểm định'),('Eq_LastInspectionDate','zh-CN',N'最近检验日期'),
('Eq_GetTemplate','en-US',N'Get template import'),('Eq_GetTemplate','vi-VN',N'Tải mẫu import'),('Eq_GetTemplate','zh-CN',N'下载导入模板'),
('Eq_Import','en-US',N'Import'),('Eq_Import','vi-VN',N'Import'),('Eq_Import','zh-CN',N'导入'),
('Eq_Add','en-US',N'Add container'),('Eq_Add','vi-VN',N'Thêm container'),('Eq_Add','zh-CN',N'新增集装箱'),
('Eq_ContainerNoRequired','en-US',N'ContainerNo is required.'),('Eq_ContainerNoRequired','vi-VN',N'Bắt buộc nhập số container.'),('Eq_ContainerNoRequired','zh-CN',N'集装箱号为必填。'),
('Eq_ContainerNoHint','en-US',N'Search existing container no or type a new one.'),('Eq_ContainerNoHint','vi-VN',N'Tìm số container có sẵn hoặc nhập tay số mới.'),('Eq_ContainerNoHint','zh-CN',N'可搜索已有箱号或手动输入新箱号。'),
('Eq_ConfirmDelete','en-US',N'Delete container {0}?'),('Eq_ConfirmDelete','vi-VN',N'Xóa container {0}?'),('Eq_ConfirmDelete','zh-CN',N'删除集装箱 {0}？'),
('Eq_TemplateDownloaded','en-US',N'Import template downloaded.'),('Eq_TemplateDownloaded','vi-VN',N'Đã tải mẫu import.'),('Eq_TemplateDownloaded','zh-CN',N'导入模板已下载。'),
('Eq_ImportSheetNotFound','en-US',N'ContainerMaster sheet not found in Excel file.'),('Eq_ImportSheetNotFound','vi-VN',N'Không tìm thấy sheet ContainerMaster trong file Excel.'),('Eq_ImportSheetNotFound','zh-CN',N'Excel 文件中未找到 ContainerMaster 工作表。'),
('Eq_ImportSuccess','en-US',N'Imported {0} row(s). Skipped {1} empty row(s).'),('Eq_ImportSuccess','vi-VN',N'Đã import {0} dòng. Bỏ qua {1} dòng trống.'),('Eq_ImportSuccess','zh-CN',N'已导入 {0} 行，跳过 {1} 个空行。'),
('Eq_ImportError','en-US',N'Import error: {0}'),('Eq_ImportError','vi-VN',N'Lỗi import: {0}'),('Eq_ImportError','zh-CN',N'导入错误：{0}'),
('Eq_SelectContainer','en-US',N'Please select a container.'),('Eq_SelectContainer','vi-VN',N'Vui lòng chọn container.'),('Eq_SelectContainer','zh-CN',N'请选择集装箱。'),
('Eq_LoadContainersError','en-US',N'Error loading containers: {0}'),('Eq_LoadContainersError','vi-VN',N'Lỗi tải container: {0}'),('Eq_LoadContainersError','zh-CN',N'加载集装箱失败：{0}'),
('Eq_SearchContainerError','en-US',N'Container search error: {0}'),('Eq_SearchContainerError','vi-VN',N'Lỗi tìm container: {0}'),('Eq_SearchContainerError','zh-CN',N'集装箱搜索错误：{0}'),
('Eq_SearchMblError','en-US',N'MBL search error: {0}'),('Eq_SearchMblError','vi-VN',N'Lỗi tìm MBL: {0}'),('Eq_SearchMblError','zh-CN',N'MBL 搜索错误：{0}'),
('Eq_SearchHblError','en-US',N'HBL search error: {0}'),('Eq_SearchHblError','vi-VN',N'Lỗi tìm HBL: {0}'),('Eq_SearchHblError','zh-CN',N'HBL 搜索错误：{0}'),
('Eq_SearchJobError','en-US',N'Job search error: {0}'),('Eq_SearchJobError','vi-VN',N'Lỗi tìm job: {0}'),('Eq_SearchJobError','zh-CN',N'作业搜索错误：{0}'),
('Eq_SaveGateInError','en-US',N'Error saving Gate In Seq {0}: {1}'),('Eq_SaveGateInError','vi-VN',N'Lỗi lưu Gate In Seq {0}: {1}'),('Eq_SaveGateInError','zh-CN',N'保存 Gate In Seq {0} 失败：{1}'),
('Eq_SaveGateOutError','en-US',N'Error saving Gate Out Seq {0}: {1}'),('Eq_SaveGateOutError','vi-VN',N'Lỗi lưu Gate Out Seq {0}: {1}'),('Eq_SaveGateOutError','zh-CN',N'保存 Gate Out Seq {0} 失败：{1}'),
('Eq_NoRowsForContainer','en-US',N'No Gate In/Out rows found for this container.'),('Eq_NoRowsForContainer','vi-VN',N'Không có dòng Gate In/Out cho container này.'),('Eq_NoRowsForContainer','zh-CN',N'未找到此集装箱的 Gate In/Out 记录。'),
('Eq_ImportGateSuccess','en-US',N'Imported {0} Gate In and {1} Gate Out records.'),('Eq_ImportGateSuccess','vi-VN',N'Đã import {0} Gate In và {1} Gate Out.'),('Eq_ImportGateSuccess','zh-CN',N'已导入 {0} 条 Gate In 和 {1} 条 Gate Out。'),
('Eq_ImportGateInOutError','en-US',N'Gate In/Out import error: {0}'),('Eq_ImportGateInOutError','vi-VN',N'Lỗi import Gate In/Out: {0}'),('Eq_ImportGateInOutError','zh-CN',N'Gate In/Out 导入错误：{0}'),
('Eq_LoadContainersFirst','en-US',N'Please load containers first.'),('Eq_LoadContainersFirst','vi-VN',N'Vui lòng tải danh sách container trước.'),('Eq_LoadContainersFirst','zh-CN',N'请先加载集装箱列表。'),
('Eq_ContainerNotSelected','en-US',N'Container is not selected.'),('Eq_ContainerNotSelected','vi-VN',N'Chưa chọn container.'),('Eq_ContainerNotSelected','zh-CN',N'未选择集装箱。'),
('Eq_GateInSheetNotFound','en-US',N'GATEIN sheet not found in Excel file.'),('Eq_GateInSheetNotFound','vi-VN',N'Không tìm thấy sheet GATEIN trong file Excel.'),('Eq_GateInSheetNotFound','zh-CN',N'Excel 文件中未找到 GATEIN 工作表。'),
('Eq_GateOutSheetNotFound','en-US',N'GATEOUT sheet not found in Excel file.'),('Eq_GateOutSheetNotFound','vi-VN',N'Không tìm thấy sheet GATEOUT trong file Excel.'),('Eq_GateOutSheetNotFound','zh-CN',N'Excel 文件中未找到 GATEOUT 工作表。'),
('Eq_ImportGateInError','en-US',N'Gate In import error: {0}'),('Eq_ImportGateInError','vi-VN',N'Lỗi import Gate In: {0}'),('Eq_ImportGateInError','zh-CN',N'Gate In 导入错误：{0}'),
('Eq_ImportGateOutError','en-US',N'Gate Out import error: {0}'),('Eq_ImportGateOutError','vi-VN',N'Lỗi import Gate Out: {0}'),('Eq_ImportGateOutError','zh-CN',N'Gate Out 导入错误：{0}'),
('Eq_ImportedGateInCount','en-US',N'Imported {0} Gate In records from Excel.'),('Eq_ImportedGateInCount','vi-VN',N'Đã import {0} bản ghi Gate In từ Excel.'),('Eq_ImportedGateInCount','zh-CN',N'已从 Excel 导入 {0} 条 Gate In 记录。'),
('Eq_ImportedGateOutCount','en-US',N'Imported {0} Gate Out records from Excel.'),('Eq_ImportedGateOutCount','vi-VN',N'Đã import {0} bản ghi Gate Out từ Excel.'),('Eq_ImportedGateOutCount','zh-CN',N'已从 Excel 导入 {0} 条 Gate Out 记录。'),
('Terminal_Subtitle','en-US',N'8.2 · Terminal master data'),('Terminal_Subtitle','vi-VN',N'8.2 · Danh mục terminal'),('Terminal_Subtitle','zh-CN',N'8.2 · 码头主数据'),
('Terminal_Name','en-US',N'Terminal Name'),('Terminal_Name','vi-VN',N'Tên terminal'),('Terminal_Name','zh-CN',N'码头名称'),
('FreeStorage','en-US',N'Free Storage'),('FreeStorage','vi-VN',N'Lưu bãi miễn phí'),('FreeStorage','zh-CN',N'免费堆存'),
('ValidOrder','en-US',N'Valid Order'),('ValidOrder','vi-VN',N'Lệnh hợp lệ'),('ValidOrder','zh-CN',N'有效指令'),
('OrderReport','en-US',N'Order Report'),('OrderReport','vi-VN',N'Báo cáo lệnh'),('OrderReport','zh-CN',N'指令报告'),
('Continued','en-US',N'Continued'),('Continued','vi-VN',N'Tiếp tục'),('Continued','zh-CN',N'继续'),
('Editable','en-US',N'Editable'),('Editable','vi-VN',N'Cho phép sửa'),('Editable','zh-CN',N'可编辑'),
('CodeNvocc','en-US',N'Code NVOCC'),('CodeNvocc','vi-VN',N'Mã NVOCC'),('CodeNvocc','zh-CN',N'NVOCC 代码'),
('Tel','en-US',N'Tel'),('Tel','vi-VN',N'Điện thoại'),('Tel','zh-CN',N'电话'),
('Capacity','en-US',N'Capacity'),('Capacity','vi-VN',N'Sức chứa'),('Capacity','zh-CN',N'容量'),
('Address','en-US',N'Address'),('Address','vi-VN',N'Địa chỉ'),('Address','zh-CN',N'地址'),
('New','en-US',N'New'),('New','vi-VN',N'Thêm mới'),('New','zh-CN',N'新建'),
('Code','en-US',N'Code'),('Code','vi-VN',N'Mã'),('Code','zh-CN',N'代码'),
('ChargeType_Subtitle','en-US',N'Charge type setup'),('ChargeType_Subtitle','vi-VN',N'Thiết lập loại phí'),('ChargeType_Subtitle','zh-CN',N'费用类型设置'),
('TariffHeader_Subtitle','en-US',N'Tariff header setup'),('TariffHeader_Subtitle','vi-VN',N'Thiết lập header biểu phí'),('TariffHeader_Subtitle','zh-CN',N'运价头设置'),
('TariffTier_Subtitle','en-US',N'Tariff tier bands'),('TariffTier_Subtitle','vi-VN',N'Bậc biểu phí'),('TariffTier_Subtitle','zh-CN',N'运价档位'),
('Scc_Subtitle','en-US',N'Shipment charge context rules'),('Scc_Subtitle','vi-VN',N'Quy tắc ngữ cảnh tính phí lô hàng'),('Scc_Subtitle','zh-CN',N'货运计费上下文规则'),
('Scdm_PageTitle','en-US',N'8.8 Charge date mapping'),('Scdm_PageTitle','vi-VN',N'8.8 Mapping ngày tính cước'),('Scdm_PageTitle','zh-CN',N'8.8 计费日期映射'),
('Scdm_Title','en-US',N'8.8 Date mapping by container'),('Scdm_Title','vi-VN',N'8.8 Mapping ngày theo số cont'),('Scdm_Title','zh-CN',N'8.8 按箱号日期映射'),
('Scdm_Subtitle','en-US',N'Date source mapping for charge calculation'),('Scdm_Subtitle','vi-VN',N'Cấu hình nguồn ngày cho tính cước'),('Scdm_Subtitle','zh-CN',N'计费日期来源映射'),
('Scdm_SaveConfig','en-US',N'Save configuration'),('Scdm_SaveConfig','vi-VN',N'Lưu cấu hình'),('Scdm_SaveConfig','zh-CN',N'保存配置'),
('Scdm_InfoAlert','en-US',N'Select a date source for each date field on screen 8.7. When you click "Calculate Charge", the system will take dates by container from the configured source.'),('Scdm_InfoAlert','vi-VN',N'Chọn nguồn ngày cho từng trường ngày ở màn hình 8.7. Khi bấm "Tính Tiền", hệ thống sẽ tự lấy ngày theo số cont từ nguồn đã cấu hình.'),('Scdm_InfoAlert','zh-CN',N'为 8.7 屏幕上的每个日期字段选择日期来源。点击“计费”后，系统将按箱号从已配置来源取日期。'),
('Scdm_TargetDate','en-US',N'Target date (8.7)'),('Scdm_TargetDate','vi-VN',N'Ngày đích (8.7)'),('Scdm_TargetDate','zh-CN',N'目标日期 (8.7)'),
('Scdm_DataSource','en-US',N'Data source'),('Scdm_DataSource','vi-VN',N'Nguồn dữ liệu'),('Scdm_DataSource','zh-CN',N'数据来源'),
('Scdm_Enabled','en-US',N'Enabled'),('Scdm_Enabled','vi-VN',N'Bật'),('Scdm_Enabled','zh-CN',N'启用'),
('Scdm_Saved','en-US',N'Date mapping configuration saved.'),('Scdm_Saved','vi-VN',N'Đã lưu cấu hình map ngày.'),('Scdm_Saved','zh-CN',N'日期映射配置已保存。'),
('Scdm_SaveFailed','en-US',N'Failed to save configuration: {0}'),('Scdm_SaveFailed','vi-VN',N'Lưu cấu hình thất bại: {0}'),('Scdm_SaveFailed','zh-CN',N'保存配置失败：{0}'),
('Ci_PageTitle','en-US',N'8.3.3 Container Inventory'),('Ci_PageTitle','vi-VN',N'8.3.3 Tồn kho container'),('Ci_PageTitle','zh-CN',N'8.3.3 集装箱库存'),
('Ci_Title','en-US',N'8.3.3 Container Inventory'),('Ci_Title','vi-VN',N'8.3.3 Tồn kho container'),('Ci_Title','zh-CN',N'8.3.3 集装箱库存'),
('Ci_Subtitle','en-US',N'Statistics from all yard/import tables using one common inventory logic: Current In Yard + In/Out Yard + VSS import/export + APS Yard 8.3.6 + SP-ITC Yard 8.3.7 tables.'),('Ci_Subtitle','vi-VN',N'Thống kê từ tất cả bảng yard/import theo logic tồn kho chung: Current In Yard + In/Out Yard + VSS import/export + APS Yard 8.3.6 + SP-ITC Yard 8.3.7.'),('Ci_Subtitle','zh-CN',N'基于统一库存逻辑汇总所有堆场/导入表：Current In Yard + In/Out Yard + VSS 进出口 + APS Yard 8.3.6 + SP-ITC Yard 8.3.7。'),
('Ci_DataSource','en-US',N'Data source: {0}'),('Ci_DataSource','vi-VN',N'Nguồn dữ liệu: {0}'),('Ci_DataSource','zh-CN',N'数据来源：{0}'),
('Ci_Import834','en-US',N'8.3.4 Import'),('Ci_Import834','vi-VN',N'8.3.4 Import'),('Ci_Import834','zh-CN',N'8.3.4 导入'),
('Ci_Import835','en-US',N'8.3.5 Import'),('Ci_Import835','vi-VN',N'8.3.5 Import'),('Ci_Import835','zh-CN',N'8.3.5 导入'),
('Ci_Import836','en-US',N'8.3.6 Import'),('Ci_Import836','vi-VN',N'8.3.6 Import'),('Ci_Import836','zh-CN',N'8.3.6 导入'),
('Ci_Import837','en-US',N'8.3.7 SP-ITC'),('Ci_Import837','vi-VN',N'8.3.7 SP-ITC'),('Ci_Import837','zh-CN',N'8.3.7 SP-ITC'),
('Refresh','en-US',N'Refresh'),('Refresh','vi-VN',N'Tải lại'),('Refresh','zh-CN',N'刷新'),
('StockImport_PageTitle834','en-US',N'8.3.4 Import Yard Movement CAT LAI'),('StockImport_PageTitle834','vi-VN',N'8.3.4 Import Yard Movement CAT LAI'),('StockImport_PageTitle834','zh-CN',N'8.3.4 导入 CAT LAI 堆场动态'),
('StockImport_HeroTitle834','en-US',N'8.3.4 Import Container / Yard Movement CAT LAI'),('StockImport_HeroTitle834','vi-VN',N'8.3.4 Import Container / Yard Movement CAT LAI'),('StockImport_HeroTitle834','zh-CN',N'8.3.4 导入集装箱 / CAT LAI 堆场动态'),
('StockImport_HeroDesc834','en-US',N'Select depot → choose Excel → preview Sheet1/Sheet2 → check existing database rows by all business columns including DEPOT → import new rows only.'),('StockImport_HeroDesc834','vi-VN',N'Chọn depot → chọn Excel → preview Sheet1/Sheet2 → kiểm tra dòng đã có trong DB theo tất cả cột nghiệp vụ kể cả DEPOT → chỉ import dòng mới.'),('StockImport_HeroDesc834','zh-CN',N'选择 depot → 选择 Excel → 预览 Sheet1/Sheet2 → 按全部业务列（含 DEPOT）检查数据库已有行 → 仅导入新行。'),
('StockImport_PageTitle835','en-US',N'8.3.5 VSS In/Out Yard Import'),('StockImport_PageTitle835','vi-VN',N'8.3.5 Import VSS In/Out Yard'),('StockImport_PageTitle835','zh-CN',N'8.3.5 VSS 进出堆场导入'),
('StockImport_HeroTitle835','en-US',N'8.3.5 Import VSS In/Out Yard Movement'),('StockImport_HeroTitle835','vi-VN',N'8.3.5 Import VSS In/Out Yard Movement'),('StockImport_HeroTitle835','zh-CN',N'8.3.5 导入 VSS 进出堆场动态'),
('StockImport_HeroDesc835','en-US',N'Select depot → choose Excel → preview all sheets → check existing database rows by all business columns including DEPOT → import new rows only.'),('StockImport_HeroDesc835','vi-VN',N'Chọn depot → chọn Excel → preview tất cả sheet → kiểm tra dòng đã có trong DB theo tất cả cột nghiệp vụ kể cả DEPOT → chỉ import dòng mới.'),('StockImport_HeroDesc835','zh-CN',N'选择 depot → 选择 Excel → 预览全部 sheet → 按全部业务列（含 DEPOT）检查数据库已有行 → 仅导入新行。'),
('StockImport_PageTitle836','en-US',N'8.3.6 Import APS Stock / In-Out Excel'),('StockImport_PageTitle836','vi-VN',N'8.3.6 Import APS Stock / In-Out Excel'),('StockImport_PageTitle836','zh-CN',N'8.3.6 导入 APS 库存 / 进出 Excel'),
('StockImport_HeroTitle836','en-US',N'8.3.6 Import APS Stock / Gate In / Gate Out'),('StockImport_HeroTitle836','vi-VN',N'8.3.6 Import APS Stock / Gate In / Gate Out'),('StockImport_HeroTitle836','zh-CN',N'8.3.6 导入 APS 库存 / Gate In / Gate Out'),
('StockImport_HeroDesc836','en-US',N'Select depot → choose Excel → auto-detect GATEIN / GATEOUT / Stock / General / General_Status → preview → skip existing rows → import new rows only.'),('StockImport_HeroDesc836','vi-VN',N'Chọn depot → chọn Excel → tự nhận GATEIN / GATEOUT / Stock / General / General_Status → preview → bỏ dòng đã có → chỉ import dòng mới.'),('StockImport_HeroDesc836','zh-CN',N'选择 depot → 选择 Excel → 自动识别 GATEIN / GATEOUT / Stock / General / General_Status → 预览 → 跳过已有行 → 仅导入新行。'),
('StockImport_PageTitle838','en-US',N'8.3.8 Import YARD Alpine Inventory'),('StockImport_PageTitle838','vi-VN',N'8.3.8 Import YARD Alpine Inventory'),('StockImport_PageTitle838','zh-CN',N'8.3.8 导入 YARD Alpine 库存'),
('StockImport_HeroTitle838','en-US',N'8.3.8 Import YARD Alpine Inventory'),('StockImport_HeroTitle838','vi-VN',N'8.3.8 Import YARD Alpine Inventory'),('StockImport_HeroTitle838','zh-CN',N'8.3.8 导入 YARD Alpine 库存'),
('StockImport_HeroDesc838','en-US',N'Import ALPINE Inventory workbook: read GATE IN, GATE OUT and STOCK → preview → skip duplicates → write to <b>{0}</b>.'),('StockImport_HeroDesc838','vi-VN',N'Import workbook ALPINE Inventory: đọc GATE IN, GATE OUT và STOCK → preview → bỏ dòng trùng → ghi vào <b>{0}</b>.'),('StockImport_HeroDesc838','zh-CN',N'导入 ALPINE Inventory 工作簿：读取 GATE IN、GATE OUT 和 STOCK → 预览 → 跳过重复 → 写入 <b>{0}</b>。'),
('StockImport_DepotPlaceholder838','en-US',N'PHUONG DONG DEPOT'),('StockImport_DepotPlaceholder838','vi-VN',N'PHUONG DONG DEPOT'),('StockImport_DepotPlaceholder838','zh-CN',N'PHUONG DONG DEPOT'),
('StockImport_HeroTitle837','en-US',N'8.3.7 - Import SP-ITC Yard'),('StockImport_HeroTitle837','vi-VN',N'8.3.7 - Import SP-ITC Yard'),('StockImport_HeroTitle837','zh-CN',N'8.3.7 - 导入 SP-ITC 堆场'),
('StockImport_HeroDesc837','en-US',N'Read 4 sheets: IN-OUT, STUFF-UNSTUFF, YARD-FCL, YARD-MTY. Skip Summary. Import to dbo.M_8_3_7_YARD_SP_ITC.'),('StockImport_HeroDesc837','vi-VN',N'Đọc 4 sheet: IN-OUT, STUFF-UNSTUFF, YARD-FCL, YARD-MTY. Bỏ qua Summary. Import vào dbo.M_8_3_7_YARD_SP_ITC.'),('StockImport_HeroDesc837','zh-CN',N'读取 4 个工作表：IN-OUT、STUFF-UNSTUFF、YARD-FCL、YARD-MTY。跳过 Summary。导入 dbo.M_8_3_7_YARD_SP_ITC。'),
('StockImport_SpItcDepot','en-US',N'DEPOT: SP-ITC'),('StockImport_SpItcDepot','vi-VN',N'DEPOT: SP-ITC'),('StockImport_SpItcDepot','zh-CN',N'DEPOT: SP-ITC'),
('StockImport_DepotName','en-US',N'Depot name'),('StockImport_DepotName','vi-VN',N'Tên depot'),('StockImport_DepotName','zh-CN',N'Depot 名称'),
('StockImport_SelectDepotBeforePreview','en-US',N'Select depot before preview'),('StockImport_SelectDepotBeforePreview','vi-VN',N'Chọn depot trước khi preview'),('StockImport_SelectDepotBeforePreview','zh-CN',N'预览前请选择 depot'),
('StockImport_ChooseExcel','en-US',N'Choose Excel file'),('StockImport_ChooseExcel','vi-VN',N'Chọn file Excel'),('StockImport_ChooseExcel','zh-CN',N'选择 Excel 文件'),
('StockImport_ImportDb','en-US',N'Import DB'),('StockImport_ImportDb','vi-VN',N'Import DB'),('StockImport_ImportDb','zh-CN',N'导入数据库'),
('StockImport_Reset','en-US',N'Reset'),('StockImport_Reset','vi-VN',N'Đặt lại'),('StockImport_Reset','zh-CN',N'重置'),
('StockImport_Clear','en-US',N'Clear'),('StockImport_Clear','vi-VN',N'Xóa preview'),('StockImport_Clear','zh-CN',N'清除'),
('StockImport_SaveImport','en-US',N'Save Import'),('StockImport_SaveImport','vi-VN',N'Lưu import'),('StockImport_SaveImport','zh-CN',N'保存导入'),
('StockImport_PreviewRows','en-US',N'Preview rows'),('StockImport_PreviewRows','vi-VN',N'Dòng preview'),('StockImport_PreviewRows','zh-CN',N'预览行数'),
('StockImport_NewRows','en-US',N'New rows'),('StockImport_NewRows','vi-VN',N'Dòng mới'),('StockImport_NewRows','zh-CN',N'新行'),
('StockImport_DuplicateRows','en-US',N'Duplicate rows'),('StockImport_DuplicateRows','vi-VN',N'Dòng trùng'),('StockImport_DuplicateRows','zh-CN',N'重复行'),
('StockImport_SelectDepotPreview','en-US',N'Please select depot before preview.'),('StockImport_SelectDepotPreview','vi-VN',N'Vui lòng chọn depot trước khi preview.'),('StockImport_SelectDepotPreview','zh-CN',N'预览前请选择 depot。'),
('StockImport_SelectDepotImport','en-US',N'Please select depot before import.'),('StockImport_SelectDepotImport','vi-VN',N'Vui lòng chọn/nhập depot trước khi import.'),('StockImport_SelectDepotImport','zh-CN',N'导入前请选择 depot。'),
('StockImport_XlsxOnly','en-US',N'This feature supports .xlsx only.'),('StockImport_XlsxOnly','vi-VN',N'Chỉ hỗ trợ file .xlsx.'),('StockImport_XlsxOnly','zh-CN',N'仅支持 .xlsx 文件。'),
('StockImport_XlsXlsxOnly','en-US',N'This feature supports .xls and .xlsx only.'),('StockImport_XlsXlsxOnly','vi-VN',N'Chỉ hỗ trợ file .xls và .xlsx.'),('StockImport_XlsXlsxOnly','zh-CN',N'仅支持 .xls 和 .xlsx 文件。'),
('StockImport_NoFileSelected','en-US',N'No file selected for import.'),('StockImport_NoFileSelected','vi-VN',N'Chưa chọn file để import.'),('StockImport_NoFileSelected','zh-CN',N'未选择导入文件。'),
('StockImport_NoValidRows','en-US',N'No valid rows to import.'),('StockImport_NoValidRows','vi-VN',N'Không có dòng hợp lệ để import.'),('StockImport_NoValidRows','zh-CN',N'没有可导入的有效行。'),
('StockImport_NoNewRowsAfterDupCheck','en-US',N'No new rows after duplicate check.'),('StockImport_NoNewRowsAfterDupCheck','vi-VN',N'Không còn dòng mới sau khi kiểm tra trùng.'),('StockImport_NoNewRowsAfterDupCheck','zh-CN',N'去重后没有新行。'),
('StockImport_NoPermissionVss','en-US',N'You do not have permission to import VSS yard Excel.'),('StockImport_NoPermissionVss','vi-VN',N'Bạn không có quyền import Excel VSS yard.'),('StockImport_NoPermissionVss','zh-CN',N'您没有导入 VSS 堆场 Excel 的权限。'),
('StockImport_NoPermissionInventory','en-US',N'You do not have permission to import inventory Excel.'),('StockImport_NoPermissionInventory','vi-VN',N'Bạn không có quyền import Inventory Excel.'),('StockImport_NoPermissionInventory','zh-CN',N'您没有导入库存 Excel 的权限。'),
('StockImport_PreviewSummary','en-US',N'Previewed {0:N0} rows from {1:N0} sheet(s). New {2:N0}, existing DB {3:N0}, file duplicates {4:N0}.'),('StockImport_PreviewSummary','vi-VN',N'Preview {0:N0} dòng từ {1:N0} sheet. Mới {2:N0}, DB có sẵn {3:N0}, trùng file {4:N0}.'),('StockImport_PreviewSummary','zh-CN',N'已预览 {0:N0} 行，来自 {1:N0} 个工作表。新 {2:N0}，数据库已有 {3:N0}，文件重复 {4:N0}。'),
('StockImport_NothingImported','en-US',N'Nothing imported because there are no new rows. Existing database: {0:N0}; file duplicates: {1:N0}; errors: {2:N0}.'),('StockImport_NothingImported','vi-VN',N'Không import vì không có dòng mới. DB có sẵn: {0:N0}; trùng file: {1:N0}; lỗi: {2:N0}.'),('StockImport_NothingImported','zh-CN',N'无新行，未导入。数据库已有：{0:N0}；文件重复：{1:N0}；错误：{2:N0}。'),
('StockImport_YardMovementCompleted','en-US',N'Import completed: Current In Yard {0:N0} rows, In/Out Yard {1:N0} rows. Skipped: existing DB {2:N0}, file duplicates {3:N0}, errors {4:N0}.'),('StockImport_YardMovementCompleted','vi-VN',N'Import xong: Current In Yard {0:N0} dòng, In/Out Yard {1:N0} dòng. Bỏ qua: DB {2:N0}, trùng file {3:N0}, lỗi {4:N0}.'),('StockImport_YardMovementCompleted','zh-CN',N'导入完成：Current In Yard {0:N0} 行，In/Out Yard {1:N0} 行。跳过：数据库 {2:N0}，文件重复 {3:N0}，错误 {4:N0}。'),
('StockImport_VssCompleted','en-US',N'Import completed: {0:N0} new row(s). Skipped: existing DB {1:N0}, file duplicates {2:N0}, errors {3:N0}.'),('StockImport_VssCompleted','vi-VN',N'Import xong: {0:N0} dòng mới. Bỏ qua: DB {1:N0}, trùng file {2:N0}, lỗi {3:N0}.'),('StockImport_VssCompleted','zh-CN',N'导入完成：{0:N0} 条新行。跳过：数据库 {1:N0}，文件重复 {2:N0}，错误 {3:N0}。'),
('StockImport_ApsPreviewSummary','en-US',N'Previewed {0:N0} rows. New {1:N0}, existing {2:N0}, duplicates {3:N0}, errors {4:N0}.'),('StockImport_ApsPreviewSummary','vi-VN',N'Preview {0:N0} dòng. Mới {1:N0}, có sẵn {2:N0}, trùng {3:N0}, lỗi {4:N0}.'),('StockImport_ApsPreviewSummary','zh-CN',N'已预览 {0:N0} 行。新 {1:N0}，已有 {2:N0}，重复 {3:N0}，错误 {4:N0}。'),
('StockImport_ApsNothingImported','en-US',N'Nothing imported. Existing {0:N0}, duplicates {1:N0}, errors {2:N0}.'),('StockImport_ApsNothingImported','vi-VN',N'Không import. Có sẵn {0:N0}, trùng {1:N0}, lỗi {2:N0}.'),('StockImport_ApsNothingImported','zh-CN',N'未导入。已有 {0:N0}，重复 {1:N0}，错误 {2:N0}。'),
('StockImport_ApsCompleted','en-US',N'Import completed: {0:N0} rows. Skipped: existing {1:N0}, file duplicates {2:N0}, errors {3:N0}.'),('StockImport_ApsCompleted','vi-VN',N'Import xong: {0:N0} dòng. Bỏ qua: có sẵn {1:N0}, trùng file {2:N0}, lỗi {3:N0}.'),('StockImport_ApsCompleted','zh-CN',N'导入完成：{0:N0} 行。跳过：已有 {1:N0}，文件重复 {2:N0}，错误 {3:N0}。'),
('StockImport_AlpineSheetsNotFound','en-US',N'GATE IN, GATE OUT or STOCK sheet not found in file.'),('StockImport_AlpineSheetsNotFound','vi-VN',N'Không tìm thấy GATE IN, GATE OUT hoặc STOCK trong file.'),('StockImport_AlpineSheetsNotFound','zh-CN',N'文件中未找到 GATE IN、GATE OUT 或 STOCK 工作表。'),
('StockImport_AlpinePreviewSummary','en-US',N'Preview done: {0:N0} Gate In, {1:N0} Gate Out, {2:N0} Stock. New {3:N0}, existing {4:N0}.'),('StockImport_AlpinePreviewSummary','vi-VN',N'Preview xong: {0:N0} Gate In, {1:N0} Gate Out, {2:N0} Stock. Mới {3:N0}, có sẵn {4:N0}.'),('StockImport_AlpinePreviewSummary','zh-CN',N'预览完成：{0:N0} Gate In，{1:N0} Gate Out，{2:N0} Stock。新 {3:N0}，已有 {4:N0}。'),
('StockImport_NoNewRows','en-US',N'No new rows to import.'),('StockImport_NoNewRows','vi-VN',N'Không có dòng mới để import.'),('StockImport_NoNewRows','zh-CN',N'没有可导入的新行。'),
('StockImport_AlpineCompleted','en-US',N'Import succeeded: {0:N0} rows into dbo.{1}.'),('StockImport_AlpineCompleted','vi-VN',N'Import thành công {0:N0} dòng vào dbo.{1}.'),('StockImport_AlpineCompleted','zh-CN',N'导入成功：{0:N0} 行写入 dbo.{1}。'),
('StockImport_PreviewDone','en-US',N'Preview done: {0} rows, {1} new, {2} duplicates.'),('StockImport_PreviewDone','vi-VN',N'Preview xong: {0} dòng, {1} mới, {2} trùng.'),('StockImport_PreviewDone','zh-CN',N'预览完成：{0} 行，{1} 新，{2} 重复。'),
('StockImport_PreviewError','en-US',N'Preview error: {0}'),('StockImport_PreviewError','vi-VN',N'Lỗi preview: {0}'),('StockImport_PreviewError','zh-CN',N'预览错误：{0}'),
('StockImport_NoPreviewData','en-US',N'No preview data. Please choose an Excel file first.'),('StockImport_NoPreviewData','vi-VN',N'Chưa có dữ liệu preview. Vui lòng chọn file Excel trước.'),('StockImport_NoPreviewData','zh-CN',N'无预览数据，请先选择 Excel 文件。'),
('StockImport_AllDuplicate','en-US',N'All rows are duplicates. Nothing to import.'),('StockImport_AllDuplicate','vi-VN',N'Tất cả dòng đều trùng. Không có gì để import.'),('StockImport_AllDuplicate','zh-CN',N'全部为重复行，无需导入。'),
('StockImport_SpItcSaved','en-US',N'Saved {0} SP-ITC yard rows.'),('StockImport_SpItcSaved','vi-VN',N'Đã lưu {0} dòng SP-ITC yard.'),('StockImport_SpItcSaved','zh-CN',N'已保存 {0} 条 SP-ITC 堆场记录。'),
('EqGate_GateIn','en-US',N'Gate In'),('EqGate_GateIn','vi-VN',N'Gate In'),('EqGate_GateIn','zh-CN',N'进闸'),
('EqGate_GateOut','en-US',N'Gate Out'),('EqGate_GateOut','vi-VN',N'Gate Out'),('EqGate_GateOut','zh-CN',N'出闸'),
('EqGate_AddGateIn','en-US',N'Add Gate In'),('EqGate_AddGateIn','vi-VN',N'Thêm Gate In'),('EqGate_AddGateIn','zh-CN',N'添加进闸'),
('EqGate_AddGateOut','en-US',N'Add Gate Out'),('EqGate_AddGateOut','vi-VN',N'Thêm Gate Out'),('EqGate_AddGateOut','zh-CN',N'添加出闸'),
('EqGate_Seq','en-US',N'Seq'),('EqGate_Seq','vi-VN',N'Seq'),('EqGate_Seq','zh-CN',N'序号'),
('EqGate_EIR','en-US',N'EIR'),('EqGate_EIR','vi-VN',N'EIR'),('EqGate_EIR','zh-CN',N'EIR'),
('EqGate_TimeIn','en-US',N'Time In'),('EqGate_TimeIn','vi-VN',N'Giờ vào'),('EqGate_TimeIn','zh-CN',N'进闸时间'),
('EqGate_IsoSztp','en-US',N'ISO SZTP'),('EqGate_IsoSztp','vi-VN',N'ISO SZTP'),('EqGate_IsoSztp','zh-CN',N'ISO SZTP'),
('EqGate_Opt','en-US',N'Opt'),('EqGate_Opt','vi-VN',N'Opt'),('EqGate_Opt','zh-CN',N'Opt'),
('EqGate_FE','en-US',N'FE'),('EqGate_FE','vi-VN',N'FE'),('EqGate_FE','zh-CN',N'FE'),
('EqGate_Move','en-US',N'Move'),('EqGate_Move','vi-VN',N'Move'),('EqGate_Move','zh-CN',N'动态'),
('EqGate_Location','en-US',N'Location'),('EqGate_Location','vi-VN',N'Vị trí'),('EqGate_Location','zh-CN',N'位置'),
('EqGate_BillOfLading','en-US',N'Bill Of Lading'),('EqGate_BillOfLading','vi-VN',N'Bill Of Lading'),('EqGate_BillOfLading','zh-CN',N'提单'),
('EqGate_Consignee','en-US',N'Consignee'),('EqGate_Consignee','vi-VN',N'Consignee'),('EqGate_Consignee','zh-CN',N'收货人'),
('EqGate_Truck','en-US',N'Truck'),('EqGate_Truck','vi-VN',N'Xe'),('EqGate_Truck','zh-CN',N'卡车'),
('EqGate_YOM','en-US',N'YOM'),('EqGate_YOM','vi-VN',N'YOM'),('EqGate_YOM','zh-CN',N'YOM'),
('EqGate_SealNo1','en-US',N'Seal No 1'),('EqGate_SealNo1','vi-VN',N'Seal No 1'),('EqGate_SealNo1','zh-CN',N'封条号 1'),
('EqGate_SealNo2','en-US',N'Seal No 2'),('EqGate_SealNo2','vi-VN',N'Seal No 2'),('EqGate_SealNo2','zh-CN',N'封条号 2'),
('EqGate_VGM','en-US',N'VGM'),('EqGate_VGM','vi-VN',N'VGM'),('EqGate_VGM','zh-CN',N'VGM'),
('EqGate_Clean','en-US',N'Clean'),('EqGate_Clean','vi-VN',N'Clean'),('EqGate_Clean','zh-CN',N'清洁'),
('EqGate_MaxGross','en-US',N'Max Gross'),('EqGate_MaxGross','vi-VN',N'Max Gross'),('EqGate_MaxGross','zh-CN',N'最大毛重'),
('EqGate_Grade','en-US',N'Grade'),('EqGate_Grade','vi-VN',N'Grade'),('EqGate_Grade','zh-CN',N'等级'),
('EqGate_Voyage','en-US',N'Voyage'),('EqGate_Voyage','vi-VN',N'Chuyến'),('EqGate_Voyage','zh-CN',N'航次'),
('EqGate_Shipper','en-US',N'Shipper'),('EqGate_Shipper','vi-VN',N'Shipper'),('EqGate_Shipper','zh-CN',N'发货人'),
('EqGate_Note1','en-US',N'Note 1'),('EqGate_Note1','vi-VN',N'Ghi chú 1'),('EqGate_Note1','zh-CN',N'备注 1'),
('EqGate_RequiredGrade','en-US',N'Required Grade'),('EqGate_RequiredGrade','vi-VN',N'Grade yêu cầu'),('EqGate_RequiredGrade','zh-CN',N'要求等级'),
('EqGate_TruckNo','en-US',N'Truck No'),('EqGate_TruckNo','vi-VN',N'Số xe'),('EqGate_TruckNo','zh-CN',N'车号'),
('EqGate_TruckerPhone','en-US',N'Trucker Phone'),('EqGate_TruckerPhone','vi-VN',N'ĐT tài xế'),('EqGate_TruckerPhone','zh-CN',N'司机电话'),
('EqGate_Days','en-US',N'Days'),('EqGate_Days','vi-VN',N'Số ngày'),('EqGate_Days','zh-CN',N'天数'),
('Container','en-US',N'Container'),('Container','vi-VN',N'Container'),('Container','zh-CN',N'集装箱'),
('Remark','en-US',N'Remark'),('Remark','vi-VN',N'Ghi chú'),('Remark','zh-CN',N'备注'),
('Booking','en-US',N'Booking'),('Booking','vi-VN',N'Booking'),('Booking','zh-CN',N'订舱'),
('POL','en-US',N'POL'),('POL','vi-VN',N'POL'),('POL','zh-CN',N'POL'),
('POD','en-US',N'POD'),('POD','vi-VN',N'POD'),('POD','zh-CN',N'POD'),
('DateIn','en-US',N'Date In'),('DateIn','vi-VN',N'Ngày vào'),('DateIn','zh-CN',N'进闸日期'),
('DateOut','en-US',N'Date Out'),('DateOut','vi-VN',N'Ngày ra'),('DateOut','zh-CN',N'出闸日期'),
('SealNo','en-US',N'Seal No'),('SealNo','vi-VN',N'Seal No'),('SealNo','zh-CN',N'封条号'),
('Close','en-US',N'Close'),('Close','vi-VN',N'Đóng'),('Close','zh-CN',N'关闭'),
('Search','en-US',N'Search'),('Search','vi-VN',N'Tìm'),('Search','zh-CN',N'搜索'),
('Ci_SearchPlaceholder','en-US',N'Container, BOOK, BL, depot, port, vessel...'),('Ci_SearchPlaceholder','vi-VN',N'Container, BOOK, BL, depot, port, vessel...'),('Ci_SearchPlaceholder','zh-CN',N'集装箱、BOOK、BL、depot、港口、船名…'),
('Ci_Source','en-US',N'Source'),('Ci_Source','vi-VN',N'Nguồn'),('Ci_Source','zh-CN',N'来源'),
('Ci_Agent','en-US',N'AGENT'),('Ci_Agent','vi-VN',N'AGENT'),('Ci_Agent','zh-CN',N'AGENT'),
('Ci_Line','en-US',N'LINE'),('Ci_Line','vi-VN',N'LINE'),('Ci_Line','zh-CN',N'LINE'),
('Ci_Depot','en-US',N'DEPOT'),('Ci_Depot','vi-VN',N'DEPOT'),('Ci_Depot','zh-CN',N'DEPOT'),
('Ci_SizeType','en-US',N'Size/Type'),('Ci_SizeType','vi-VN',N'Size/Type'),('Ci_SizeType','zh-CN',N'尺寸/类型'),
('Ci_LoadFE','en-US',N'Load F/E'),('Ci_LoadFE','vi-VN',N'Load F/E'),('Ci_LoadFE','zh-CN',N'装载 F/E'),
('Ci_Damage','en-US',N'Damage'),('Ci_Damage','vi-VN',N'Hư hỏng'),('Ci_Damage','zh-CN',N'损坏'),
('Ci_HideDam','en-US',N'Hide DAM'),('Ci_HideDam','vi-VN',N'Ẩn DAM'),('Ci_HideDam','zh-CN',N'隐藏 DAM'),
('Ci_DemFree','en-US',N'DEM free'),('Ci_DemFree','vi-VN',N'DEM free'),('Ci_DemFree','zh-CN',N'DEM 免费'),
('Ci_DetFree','en-US',N'DET free'),('Ci_DetFree','vi-VN',N'DET free'),('Ci_DetFree','zh-CN',N'DET 免费'),
('Ci_DemMin','en-US',N'DEM ≥'),('Ci_DemMin','vi-VN',N'DEM ≥'),('Ci_DemMin','zh-CN',N'DEM ≥'),
('Ci_DetMin','en-US',N'DET ≥'),('Ci_DetMin','vi-VN',N'DET ≥'),('Ci_DetMin','zh-CN',N'DET ≥'),
('Ci_Other','en-US',N'OTHER'),('Ci_Other','vi-VN',N'KHÁC'),('Ci_Other','zh-CN',N'其他'),
('Ci_StatusInDepot','en-US',N'In Depot'),('Ci_StatusInDepot','vi-VN',N'Trong depot'),('Ci_StatusInDepot','zh-CN',N'在堆场'),
('Ci_StatusWaitingPort','en-US',N'Waiting Port Arrival'),('Ci_StatusWaitingPort','vi-VN',N'Chờ đến cảng'),('Ci_StatusWaitingPort','zh-CN',N'等待到港'),
('Ci_StatusArrivedPort','en-US',N'Arrived at Port'),('Ci_StatusArrivedPort','vi-VN',N'Đã đến cảng'),('Ci_StatusArrivedPort','zh-CN',N'已到港'),
('Ci_StatusInTransit','en-US',N'In Transit'),('Ci_StatusInTransit','vi-VN',N'Đang vận chuyển'),('Ci_StatusInTransit','zh-CN',N'在途'),
('Ci_LoadEmpty','en-US',N'E - Empty'),('Ci_LoadEmpty','vi-VN',N'E - Empty'),('Ci_LoadEmpty','zh-CN',N'E - 空'),
('Ci_LoadFull','en-US',N'F - Full'),('Ci_LoadFull','vi-VN',N'F - Full'),('Ci_LoadFull','zh-CN',N'F - 重'),
('Ci_LoadOther','en-US',N'Other / Unknown'),('Ci_LoadOther','vi-VN',N'Khác / Không rõ'),('Ci_LoadOther','zh-CN',N'其他/未知'),
('Ci_DamageDamaged','en-US',N'D - Damaged'),('Ci_DamageDamaged','vi-VN',N'D - Hư'),('Ci_DamageDamaged','zh-CN',N'D - 损坏'),
('Ci_Print','en-US',N'Print'),('Ci_Print','vi-VN',N'In'),('Ci_Print','zh-CN',N'打印'),
('Ci_SectionInDepot','en-US',N'IN DEPOT'),('Ci_SectionInDepot','vi-VN',N'TRONG DEPOT'),('Ci_SectionInDepot','zh-CN',N'在堆场'),
('Ci_SectionWaitingPort','en-US',N'WAITING PORT ARRIVAL'),('Ci_SectionWaitingPort','vi-VN',N'CHỜ ĐẾN CẢNG'),('Ci_SectionWaitingPort','zh-CN',N'等待到港'),
('Ci_SectionArrivedPort','en-US',N'ARRIVED AT PORT'),('Ci_SectionArrivedPort','vi-VN',N'ĐÃ ĐẾN CẢNG'),('Ci_SectionArrivedPort','zh-CN',N'已到港'),
('Ci_SectionInTransit','en-US',N'IN TRANSIT'),('Ci_SectionInTransit','vi-VN',N'ĐANG VẬN CHUYỂN'),('Ci_SectionInTransit','zh-CN',N'在途'),
('Ci_Col_ContainerType','en-US',N'CONTAINER TYPE'),('Ci_Col_ContainerType','vi-VN',N'LOẠI CONT'),('Ci_Col_ContainerType','zh-CN',N'箱型'),
('Ci_Col_Empty','en-US',N'E - Empty'),('Ci_Col_Empty','vi-VN',N'E - Empty'),('Ci_Col_Empty','zh-CN',N'E - 空'),
('Ci_Col_Full','en-US',N'F - Full'),('Ci_Col_Full','vi-VN',N'F - Full'),('Ci_Col_Full','zh-CN',N'F - 重'),
('Ci_Col_OtherLoad','en-US',N'Other Load'),('Ci_Col_OtherLoad','vi-VN',N'Load khác'),('Ci_Col_OtherLoad','zh-CN',N'其他装载'),
('Ci_Col_Damaged','en-US',N'D - Damaged'),('Ci_Col_Damaged','vi-VN',N'D - Hư'),('Ci_Col_Damaged','zh-CN',N'D - 损坏'),
('Ci_ContainerDetail','en-US',N'CONTAINER DETAIL'),('Ci_ContainerDetail','vi-VN',N'CHI TIẾT CONTAINER'),('Ci_ContainerDetail','zh-CN',N'集装箱明细'),
('Ci_RowsCount','en-US',N'Rows: {0:N0} / {1:N0}'),('Ci_RowsCount','vi-VN',N'Dòng: {0:N0} / {1:N0}'),('Ci_RowsCount','zh-CN',N'行数：{0:N0} / {1:N0}'),
('Ci_DetailChip','en-US',N'Latest container position, movement, all dates, seal and bill info'),('Ci_DetailChip','vi-VN',N'Vị trí, movement, ngày tháng, seal và thông tin bill mới nhất'),('Ci_DetailChip','zh-CN',N'最新箱位、动态、日期、封条及提单信息'),
('Ci_HideDetailList','en-US',N'Hide detail list'),('Ci_HideDetailList','vi-VN',N'Ẩn danh sách chi tiết'),('Ci_HideDetailList','zh-CN',N'隐藏明细列表'),
('Ci_ShowDetailList','en-US',N'Show detail list'),('Ci_ShowDetailList','vi-VN',N'Hiện danh sách chi tiết'),('Ci_ShowDetailList','zh-CN',N'显示明细列表'),
('Ci_Col_InOut','en-US',N'IN / OUT'),('Ci_Col_InOut','vi-VN',N'IN / OUT'),('Ci_Col_InOut','zh-CN',N'进/出'),
('Ci_Col_LastEvent','en-US',N'Last Event'),('Ci_Col_LastEvent','vi-VN',N'Sự kiện cuối'),('Ci_Col_LastEvent','zh-CN',N'最后事件'),
('Ci_Col_GateInDate','en-US',N'Gate In / Date In'),('Ci_Col_GateInDate','vi-VN',N'Gate In / Date In'),('Ci_Col_GateInDate','zh-CN',N'进闸/进港日期'),
('Ci_Col_GateOutDate','en-US',N'Gate Out / Date Out'),('Ci_Col_GateOutDate','vi-VN',N'Gate Out / Date Out'),('Ci_Col_GateOutDate','zh-CN',N'出闸/出港日期'),
('Ci_Col_DemDays','en-US',N'DEM Days'),('Ci_Col_DemDays','vi-VN',N'Ngày DEM'),('Ci_Col_DemDays','zh-CN',N'DEM 天数'),
('Ci_Col_DemBillable','en-US',N'DEM Billable'),('Ci_Col_DemBillable','vi-VN',N'DEM tính phí'),('Ci_Col_DemBillable','zh-CN',N'DEM 计费'),
('Ci_Col_DetDays','en-US',N'DET Days'),('Ci_Col_DetDays','vi-VN',N'Ngày DET'),('Ci_Col_DetDays','zh-CN',N'DET 天数'),
('Ci_Col_DetBillable','en-US',N'DET Billable'),('Ci_Col_DetBillable','vi-VN',N'DET tính phí'),('Ci_Col_DetBillable','zh-CN',N'DET 计费'),
('Ci_Col_InsDate','en-US',N'INS Date'),('Ci_Col_InsDate','vi-VN',N'Ngày INS'),('Ci_Col_InsDate','zh-CN',N'INS 日期'),
('Ci_Col_CustomsDate','en-US',N'Customs Date'),('Ci_Col_CustomsDate','vi-VN',N'Ngày hải quan'),('Ci_Col_CustomsDate','zh-CN',N'报关日期'),
('Ci_Col_CleanMethod','en-US',N'Clean Method'),('Ci_Col_CleanMethod','vi-VN',N'Phương pháp clean'),('Ci_Col_CleanMethod','zh-CN',N'清洁方式'),
('Ci_Col_CleanStatus','en-US',N'Clean Status'),('Ci_Col_CleanStatus','vi-VN',N'Trạng thái clean'),('Ci_Col_CleanStatus','zh-CN',N'清洁状态'),
('Ci_Col_PtiDate','en-US',N'PTI Date'),('Ci_Col_PtiDate','vi-VN',N'Ngày PTI'),('Ci_Col_PtiDate','zh-CN',N'PTI 日期'),
('Ci_Col_PtiSetting','en-US',N'PTI Setting'),('Ci_Col_PtiSetting','vi-VN',N'Cài đặt PTI'),('Ci_Col_PtiSetting','zh-CN',N'PTI 设置'),
('Ci_Col_PtiStatus','en-US',N'PTI Status'),('Ci_Col_PtiStatus','vi-VN',N'Trạng thái PTI'),('Ci_Col_PtiStatus','zh-CN',N'PTI 状态'),
('Ci_Col_EstimatedDate','en-US',N'Estimated Date'),('Ci_Col_EstimatedDate','vi-VN',N'Ngày dự kiến'),('Ci_Col_EstimatedDate','zh-CN',N'预计日期'),
('Ci_Col_ApprovalDate','en-US',N'Approval Date'),('Ci_Col_ApprovalDate','vi-VN',N'Ngày duyệt'),('Ci_Col_ApprovalDate','zh-CN',N'批准日期'),
('Ci_Col_RejectDate','en-US',N'Reject Date'),('Ci_Col_RejectDate','vi-VN',N'Ngày từ chối'),('Ci_Col_RejectDate','zh-CN',N'拒绝日期'),
('Ci_Col_RepairedDate','en-US',N'Repaired Date'),('Ci_Col_RepairedDate','vi-VN',N'Ngày sửa'),('Ci_Col_RepairedDate','zh-CN',N'维修日期'),
('Ci_Col_RegisteredDate','en-US',N'Registered Date'),('Ci_Col_RegisteredDate','vi-VN',N'Ngày đăng ký'),('Ci_Col_RegisteredDate','zh-CN',N'登记日期'),
('Ci_Col_CurrentLocation','en-US',N'Current Location'),('Ci_Col_CurrentLocation','vi-VN',N'Vị trí hiện tại'),('Ci_Col_CurrentLocation','zh-CN',N'当前位置'),
('Ci_Col_CurrentStatus','en-US',N'Current Status'),('Ci_Col_CurrentStatus','vi-VN',N'Trạng thái hiện tại'),('Ci_Col_CurrentStatus','zh-CN',N'当前状态'),
('Ci_Col_IsoSize','en-US',N'ISO / Size'),('Ci_Col_IsoSize','vi-VN',N'ISO / Size'),('Ci_Col_IsoSize','zh-CN',N'ISO/尺寸'),
('Ci_Col_SizeGroup','en-US',N'Size Group'),('Ci_Col_SizeGroup','vi-VN',N'Nhóm size'),('Ci_Col_SizeGroup','zh-CN',N'尺寸组'),
('Ci_Col_DamageStatus','en-US',N'Damage Status'),('Ci_Col_DamageStatus','vi-VN',N'Trạng thái hư'),('Ci_Col_DamageStatus','zh-CN',N'损坏状态'),
('Ci_Col_RawFel','en-US',N'Raw FEL'),('Ci_Col_RawFel','vi-VN',N'Raw FEL'),('Ci_Col_RawFel','zh-CN',N'原始 FEL'),
('Ci_Col_Weight','en-US',N'WEIGHT'),('Ci_Col_Weight','vi-VN',N'WEIGHT'),('Ci_Col_Weight','zh-CN',N'重量'),
('Ci_Col_BillBooking','en-US',N'Bill / Booking'),('Ci_Col_BillBooking','vi-VN',N'Bill / Booking'),('Ci_Col_BillBooking','zh-CN',N'提单/订舱'),
('Ci_Col_BL','en-US',N'B/L'),('Ci_Col_BL','vi-VN',N'B/L'),('Ci_Col_BL','zh-CN',N'B/L'),
('Ci_Col_Seal','en-US',N'Seal'),('Ci_Col_Seal','vi-VN',N'Seal'),('Ci_Col_Seal','zh-CN',N'封条'),
('Ci_Col_ImportSource','en-US',N'Import Source'),('Ci_Col_ImportSource','vi-VN',N'Nguồn import'),('Ci_Col_ImportSource','zh-CN',N'导入来源'),
('Ci_DetailHiddenAlert','en-US',N'Container detail list is hidden. Click <b>Show detail list</b> to display it again.'),('Ci_DetailHiddenAlert','vi-VN',N'Danh sách chi tiết đang ẩn. Bấm <b>Hiện danh sách chi tiết</b> để hiển thị lại.'),('Ci_DetailHiddenAlert','zh-CN',N'明细列表已隐藏。点击<b>显示明细列表</b>重新显示。'),
('Ci_EventDetailTitle','en-US',N'Container Event Detail: {0}'),('Ci_EventDetailTitle','vi-VN',N'Chi tiết sự kiện container: {0}'),('Ci_EventDetailTitle','zh-CN',N'集装箱事件明细：{0}'),
('Ci_LatestStatusCaption','en-US',N'Latest status: {0} · Movement: {1} · Events: {2:N0}'),('Ci_LatestStatusCaption','vi-VN',N'Trạng thái mới nhất: {0} · Movement: {1} · Sự kiện: {2:N0}'),('Ci_LatestStatusCaption','zh-CN',N'最新状态：{0} · 动态：{1} · 事件：{2:N0}'),
('Ci_HideEventList','en-US',N'Hide event list'),('Ci_HideEventList','vi-VN',N'Ẩn danh sách sự kiện'),('Ci_HideEventList','zh-CN',N'隐藏事件列表'),
('Ci_ShowEventList','en-US',N'Show event list'),('Ci_ShowEventList','vi-VN',N'Hiện danh sách sự kiện'),('Ci_ShowEventList','zh-CN',N'显示事件列表'),
('Ci_MiniContainerDepot','en-US',N'Container / Depot'),('Ci_MiniContainerDepot','vi-VN',N'Container / Depot'),('Ci_MiniContainerDepot','zh-CN',N'集装箱/堆场'),
('Ci_MiniMovementStatus','en-US',N'Movement / Status'),('Ci_MiniMovementStatus','vi-VN',N'Movement / Trạng thái'),('Ci_MiniMovementStatus','zh-CN',N'动态/状态'),
('Ci_MiniBillSeal','en-US',N'Bill / B/L / Seal'),('Ci_MiniBillSeal','vi-VN',N'Bill / B/L / Seal'),('Ci_MiniBillSeal','zh-CN',N'提单/B/L/封条'),
('Ci_MiniLocationDamage','en-US',N'Location / Damage'),('Ci_MiniLocationDamage','vi-VN',N'Vị trí / Hư hỏng'),('Ci_MiniLocationDamage','zh-CN',N'位置/损坏'),
('Ci_LoadedSuccess','en-US',N'Loaded {0:N0} distinct containers from {1}.'),('Ci_LoadedSuccess','vi-VN',N'Đã tải {0:N0} container từ {1}.'),('Ci_LoadedSuccess','zh-CN',N'已从 {1} 加载 {0:N0} 个不重复集装箱。'),
('Ci_Col_EventTime','en-US',N'Event Time'),('Ci_Col_EventTime','vi-VN',N'Thời gian sự kiện'),('Ci_Col_EventTime','zh-CN',N'事件时间'),
('Ci_Col_RawMethod','en-US',N'Raw Method'),('Ci_Col_RawMethod','vi-VN',N'Method gốc'),('Ci_Col_RawMethod','zh-CN',N'原始 Method'),
('Ci_EventHiddenAlert','en-US',N'Container event list is hidden. Click <b>Show event list</b> to display it again.'),('Ci_EventHiddenAlert','vi-VN',N'Danh sách sự kiện đang ẩn. Bấm <b>Hiện danh sách sự kiện</b> để hiển thị lại.'),('Ci_EventHiddenAlert','zh-CN',N'事件列表已隐藏。点击<b>显示事件列表</b>重新显示。');

COMMIT TRANSACTION;
-- After run: DbStringLocalizerFactory.ClearCache() or restart app.
