using System.ComponentModel.DataAnnotations;

namespace NVOAMASIS.Models
{
    public class Booking
    {
        [Key]
        public Guid ContainerOutBoundNotifyId { get; set; }
        public Guid quotationID { get; set; }
        public Guid? DocID { get; set; }
        public string? Fileno { get; set; }
        public string? bkcarrier { get; set; }
        public string? BookingNo { get; set; }
        public Guid? Customer_ID { get; set; }
        public string? ATTN { get; set; }
        public Guid? Market_id { get; set; }
        public string? Carrier { get; set; }
        public string? Vessel { get; set; }
        public string? VoyNo { get; set; }
        public DateTime? ETD { get; set; }
        public DateTime? ETA { get; set; }
        public Guid? Sale_ID { get; set; }
        public string? SaleName { get; set; }
        public string? SaleCode { get; set; }
        public string? hano_from { get; set; }
        public DateTime? hano_date { get; set; }
        public string? hano_Closing { get; set; }
        public string? hano_Closingdelivery { get; set; }
        public string? hanoFCL_Quality { get; set; }
        public string? hano_delivery { get; set; }
        public string? hano_Commodity { get; set; }
        public string? hano_WeightCBMPKG { get; set; }
        public string? hano_POR { get; set; }
        public string? hano_PORCode { get; set; }
        public string? hano_POL { get; set; }
        public string? hano_POLCode { get; set; }
        public string? hano_POD { get; set; }
        public string? hano_PODCode { get; set; }
        public string? hano_POT { get; set; }
        public string? hano_POTCode { get; set; }
        /// <summary>POT thứ 2 trở đi, ngăn cách bằng " | ". POT đầu tiên luôn nằm ở hano_POT vì report chỉ in POT 1.</summary>
        public string? hano_POT_Ext { get; set; }
        public string? hano_Payment { get; set; }
        public string? hanoLCL_Consolidator { get; set; }
        public string? hanoLCL_CFSWH { get; set; }
        public string? hanoLCL_Add { get; set; }
        public string? hanoLCL_VNACCSCODE { get; set; }
        public string? hanoLCL_WHPIC { get; set; }
        public string? hanoLCL_BookingPIC { get; set; }
        public string? hanoAir_AIRlines { get; set; }
        public string? hanoAir_AirportofDeparture { get; set; }
        public string? hanoAir_AirportofDestination { get; set; }
        public string? hanoAir_ShipperConsignee { get; set; }
        public string? hanoAir_Descriptionofgoods { get; set; }
        public string? hanoAir_Freightrateterm { get; set; }
        public string? hanoAIr_MAWBHAWBNo { get; set; }
        public string? hanoAir_RoutingVoyage { get; set; }
        public string? hanoAIr_Flighttime { get; set; }
        public string? hanoAir_Cutoffdatetime { get; set; }
        public string? hanoAir_Deliverycontactat { get; set; }
        public string? hanoAir_Morning { get; set; }
        public string? hanoAir_Afternoon { get; set; }
        public string? hanoAir_Placeofreceipt { get; set; }
        public string? remarksFCL { get; set; }
        public string? remarksLCL { get; set; }
        public string? remarksAir { get; set; }
        public string? FCL_LCL_Air { get; set; }
        public string? branch { get; set; }
        public string? iol { get; set; }
        public string? serviceContract { get; set; }
        public bool? Editable { get; set; }
        public bool? Continued { get; set; }
        public bool? Approve { get; set; }
        public string? UserID { get; set; }
        public DateTime? UpdateTime { get; set; }
        public string? Emptydepot { get; set; }
        public string? EmpContReDate { get; set; }
        public string? ReturnLadenPlace { get; set; }
        public string? OPSCode { get; set; }
        public string? PlaceOfStuffing { get; set; }
        public string? SpecialCont { get; set; }
        public string? FullReturnDate { get; set; }
        public string? SICutOff { get; set; }
 
        public string? PickupAt { get; set; }
        public string? DropOff { get; set; }
        public string? Lo { get; set; }
        public string? cncust { get; set; }
        public string? vat { get; set; }
        public Guid? agencyID { get; set; }
        public string? dateRelease { get; set; }
        public string? datecancel { get; set; }
        public string? trangthai { get; set; }
        public string? OperationCode { get; set; }
        public string? LoadingStuffingDate { get; set; }
        public string? BorderOfDelivery { get; set; }
        public string? PlaceOfDelivery { get; set; }
        public string? contact_Stuffing { get; set; }
        public string? routingInformation { get; set; }
        public string? kien { get; set; }
        public string? kgS { get; set; }
        public string? khoi { get; set; }
        public string? soxe { get; set; }
        public string? THOIGIANNHANHANG { get; set; }
        public string? diadiemnhanhang { get; set; }
        public string? nguoilienhenhanhang { get; set; }
        public string? THOIGIANgiaoHANG { get; set; }
        public string? diadiemgiaohang { get; set; }
        public string? nguoilienhegiaohang { get; set; }
        public string? chungtudinhkem { get; set; }
        public string? yeucaudacbiet { get; set; }
        public string? soxetai { get; set; }
        public string? congviecthuchien1 { get; set; }
        public string? congviecthuchien2 { get; set; }
        public string? congviecthuchien3 { get; set; }
        public string? congviecthuchien4 { get; set; }
        public string? congviecthuchien5 { get; set; }
        public string? thoigian1 { get; set; }
        public string? thoigian2 { get; set; }
        public string? thoigian3 { get; set; }
        public string? thoigian4 { get; set; }
        public string? thoigian5 { get; set; }
        public string? timecargo { get; set; }
        public string? timevgm { get; set; }
        public string? timesi { get; set; }
        public string? tendest { get; set; }
        public string? codedest { get; set; }
        public string? cont_type { get; set; }
        public string? agencyname_box { get; set; }
        /// <summary>Principle: lưu giống Agency Name (chuỗi "tên tắt___tên" chọn từ danh sách khách hàng).</summary>
        public string? principle { get; set; }
        public string? etatime { get; set; }
        public string? etdtime { get; set; }
        public string? hanoair_cutofdaytimetime { get; set; }
        public string? hanoair_cutoffdaytimetime { get; set; }
        public string? loaikien { get; set; }
        public string? PRICINGMAN { get; set; }
        public string? ANETA { get; set; }
        public string? BILLTYPE { get; set; }
        public Guid? CONSIGNEEID { get; set; }
        public string? containerno_bk { get; set; }
        public string? status_bk { get; set; }
        public string? tk1 { get; set; }
        public string? tk2 { get; set; }
        public string? tk3 { get; set; }
        public string? tk4 { get; set; }
        public string? tk5 { get; set; }
        public string? ngaytk1 { get; set; }
        public string? ngaytk2 { get; set; }
        public string? ngaytk3 { get; set; }
        public string? ngaytk4 { get; set; }
        public string? ngaytk5 { get; set; }
        public string? soinv1 { get; set; }
        public string? soinv2 { get; set; }
        public string? soinv3 { get; set; }
        public string? soinv4 { get; set; }
        public string? soinv5 { get; set; }
        public string? MaincusBk_Id { get; set; }
        public string? PricingRemarks { get; set; }
        public string? TPC { get; set; }
        public Guid? MaincusBk_Id_ { get; set; }
        public string? shipperfreetext { get; set; }
        public string? OperationCode_ { get; set; }
        public string? ngaytimeline { get; set; }
        public string? giotimeline { get; set; }
        public string? userstimeline { get; set; }
        public string? noidungtimeline { get; set; }
        public bool? daguitimeline { get; set; }
        public int? DC20 { get; set; }
        public int? HC40 { get; set; }
        public int? RF20 { get; set; }
        public int? RF40 { get; set; }
        public int? DC40 { get; set; }
        public int? RH40 { get; set; }
        public int? HC45 { get; set; }
        public int? OT20 { get; set; }
        public int? OT40 { get; set; }
        public int? FR20 { get; set; }
        public int? FR40 { get; set; }
        public int? TK20 { get; set; }
        public string? Ref { get; set; }
        public string? contnum { get; set; }
        public string? stuffingdate { get; set; }
        public string? Remarks_ { get; set; }
        public string? emailtaixe { get; set; }
        public bool chksea { get; set; }
        public bool chkair { get; set; }
        public bool chkcustoms { get; set; }
        public bool chktrucking { get; set; }
        public string? SettingTemperature { get; set; }
        public string? VentOpen { get; set; }
        public string? PIC { get; set; }
        public string? Code { get; set; }
        public string? Freight_Payable { get; set; }


    }
}
