using Microsoft.EntityFrameworkCore;

namespace NVOAMASIS.Models
{
    [Keyless]
    public class InboundFull
    {

            public Guid BLIB_ID { get; set; }
            public string? BLIB_NO { get; set; }
            public bool? printdebit { get; set; }
            public bool? clockCredit { get; set; }
            public bool? InvoiceRequest { get; set; }
            public string? InvoiceRequestDate { get; set; }
            public bool? DebitIssued { get; set; }
            public bool? InvoiceIssued { get; set; }
            public bool? Paid { get; set; }
            public string? MBL { get; set; }
            public string? HBL { get; set; }
            public string? REF { get; set; }
            public string? bkno { get; set; }
            public string? SHIPPER { get; set; }
            public string? CONSIGNEE { get; set; }
            public string? NOTIFY { get; set; }
            public string? CY_CFS_ITEM { get; set; }
            public string? BL_TYPE { get; set; }
            public string? KHO { get; set; }
            public string? ShippingMARKS { get; set; }
            public string? SAYCONTAINER { get; set; }
            public string? KgAvailable { get; set; }
            public string? DESCRIPTION { get; set; }
            public string? bkkcomm { get; set; }
            public bool? FCL { get; set; }
            public bool? LCL { get; set; }
            public bool? CONSOL { get; set; }
            public bool? air { get; set; }
            public string? VESSEL { get; set; }
            public string? VOYAGE { get; set; }
            public string? SAILINGDATE { get; set; }
            public string? ETA { get; set; }
            public string? POL { get; set; }
            public string? POD { get; set; }
            public string? DEL { get; set; }
            public string? DEST { get; set; }
            public string? ImportCY { get; set; }
            public string? ShippingLine { get; set; }
            public string? AgencyName { get; set; }
            public string? SaleCode { get; set; }
            public bool? Nhanlenh { get; set; }
            public string? Ngaynhanlenh { get; set; }
            public string? Nguoinhanlenh { get; set; }
            public string? Pkgs { get; set; }
            public string? attachList { get; set; }
            public string? ManifestDate { get; set; }
            public string? SentHPGDate { get; set; }
            public bool? closeFile { get; set; }
            public string? remarks { get; set; }
            public string? paidreceived { get; set; }
            public string? tigia { get; set; }
            public bool? Editable { get; set; }
            public bool? Continued { get; set; }
            public bool? Approve { get; set; }
            public string? UserUpdate { get; set; }
            public DateTime? DateUpdate { get; set; }
            public string? tongsoluong { get; set; }
            public string? loai { get; set; }
            public string? tongsoluong1 { get; set; }
            public string? loai1 { get; set; }
            public string? tongsoluong2 { get; set; }
            public string? loai2 { get; set; }
            public string? tongkien { get; set; }
            public string? tongkg { get; set; }
            public string? tongkhoi { get; set; }
            public string? soHoSo { get; set; }
            public string? namDangkyhoSo { get; set; }
            public string? loaiChungtu { get; set; }
            public string? chucNangCuaChungTu { get; set; }
            public string? loaichuyendi { get; set; }
            public string? tentau { get; set; }
            public string? soIMO { get; set; }
            public string? cangden { get; set; }
            public string? thoiGianDen { get; set; }
            public string? hohieu { get; set; }
            public string? nguoiGuiHang { get; set; }
            public string? nguoiNhanHang { get; set; }
            public string? cangChuyentai { get; set; }
            public string? cangGiaohang { get; set; }
            public string? cangXephang { get; set; }
            public string? cangDoHang { get; set; }
            public string? soVanDon { get; set; }
            public string? ngayPhatHanhVanDon { get; set; }
            public string? soVanDonGoc { get; set; }
            public string? ngayPhatHanhVanDonGoc { get; set; }
            public string? ngayKhoiHanh { get; set; }
            public string? tongSoKienLoaiKien { get; set; }
            public string? hsCode { get; set; }
            public string? notify1 { get; set; }
            public string? notify2 { get; set; }
            public string? diadiemgiaohang { get; set; }
            public string? loaihang { get; set; }
            public string? ghichu { get; set; }
            public int? stt { get; set; }
            public string? email { get; set; }
            public bool? daguiemail { get; set; }
            public string? tkhq { get; set; }
            public string? ItemSITC { get; set; }
            public string? thoihanhoantamung { get; set; }
            public string? ngaydi { get; set; }
            public string? ngayve { get; set; }
            public string? mucdich { get; set; }
            public string? NOMI { get; set; }
            public string? SALE { get; set; }
            public string? POLCode { get; set; }
            public string? podcode { get; set; }
            public string? ops { get; set; }
            public string? branch { get; set; }
            public string? datereport { get; set; }
            public Guid agentID { get; set; }
            public Guid customerid_showTC { get; set; }
            public string? NoDebit { get; set; }
            public string? noCredit { get; set; }
            public string? ItemSITC1 { get; set; }
            public string? ItemSITC2 { get; set; }
            public string? coquanhaiquan { get; set; }
            public string? status { get; set; }
            public string? arrival_kinhgui { get; set; }
            public string? arrival_tau { get; set; }
            public string? arrival_chuyen { get; set; }
            public string? arrival_POL { get; set; }
            public string? arrival_POD { get; set; }
            public string? arrival_ETA { get; set; }
            public string? arrival_hbl { get; set; }
            public string? arrival_mbl { get; set; }
            public string? arrival_soContSeal { get; set; }
            public string? arrival_soluong { get; set; }
            public string? arrival_chitiethanghoa { get; set; }
            public string? arrival_trongluong { get; set; }
            public string? arrival_khoiluong { get; set; }
            public string? arrival_BillType { get; set; }
            public string? arrival_phi { get; set; }
            public string? arrival_tongcong { get; set; }
            public string? DO_Kinhgui { get; set; }
            public string? DO_Consignee { get; set; }
            public string? bophan { get; set; }
            public string? loaikien { get; set; }
            public string? ngaynhanhang { get; set; }
            public string? ngaytravorong { get; set; }
            public string? GioGiaHanDien { get; set; }
            public string? NgayGiaHanDien { get; set; }
            public string? kinhguiGCV { get; set; }
            public string? soluongGCV { get; set; }
            public string? KhoiluongThetich { get; set; }
            public string? nhom { get; set; }
            public bool? rf { get; set; }
            public string? for_ { get; set; }
            public double? tongteu { get; set; }
            public double? tongcbm { get; set; }
            public bool? nvocc { get; set; }
            public string? thoihanlenh { get; set; }
            public string? d_thongtinbosung { get; set; }
            public string? d_noiky { get; set; }
            public string? d_ngayky { get; set; }
            public string? d_nguoiky { get; set; }
            public string? oprcode { get; set; }
            public string? ngayhabai { get; set; }
            public string? transit { get; set; }
            public string? showfreeDem { get; set; }
            public string? showfreeDet { get; set; }
            public string? MaKhaiBaoVNSW { get; set; }
            public string? DealineSubmitVNSW { get; set; }
            public string? guilan1 { get; set; }
            public string? guilan2 { get; set; }
            public string? macangFCL { get; set; }
            public string? giahanlan1 { get; set; }
            public string? giahanlan2 { get; set; }
            public string? giahanlan3 { get; set; }
            public string? gFLC { get; set; }
            public string? gSC { get; set; }
            public string? quotationno { get; set; }
            public string? lot { get; set; }
            public string? pickupdate { get; set; }
            public string? freeDemUpto { get; set; }
            public string? freestoUpto { get; set; }
            public string? nhamay { get; set; }
            public string? multiuser { get; set; }
            public string? loaihanghoa { get; set; }
            public string? oref { get; set; }
            public string? ngayhttthq { get; set; }
            public string? volume { get; set; }
            public string? schedule { get; set; }
            public string? COLOADER_INBOUND { get; set; }
            public string? tennhomphi { get; set; }
            public bool? paiddebit { get; set; }
            public bool? paidcredit { get; set; }
            public string? depot { get; set; }
            public string? phuongannhancontedo { get; set; }
            public string? hannhancontedo { get; set; }
            public string? hantracontedo { get; set; }
            public string? sotienedo { get; set; }
            public string? ghichuedo { get; set; }
            public string? solenhedo { get; set; }
            public string? mabaomatedo { get; set; }
            public string? remarksdo { get; set; }
            public string? destpreedays { get; set; }
            public string? expiri { get; set; }
            public string? songaymien { get; set; }
            public string? freestorage { get; set; }
            public string? deposit { get; set; }
            public string? subjectemail { get; set; }
            public string? FreightAmount { get; set; }
            public string? vprepaid { get; set; }
            public string? commodity { get; set; }
            public string? code_shippingline { get; set; }
            public string? charge_profit { get; set; }
            public string? payment { get; set; }
            public string? dc1 { get; set; }
            public string? dc2 { get; set; }
            public string? profit_new { get; set; }
            public string? charge_profit_incvat { get; set; }
            public string? payment_incvat { get; set; }
            public string? dc1_incvat { get; set; }
            public string? dc2_incvat { get; set; }
            public string? profit_new_incvat { get; set; }
        }
}
