using Microsoft.EntityFrameworkCore;

namespace NVOAMASIS.Models
{
	[Keyless]
	public class InboundFreightModel
	{
		public Guid Inboundfreightid {get;set;}
		public Guid Inboundid {get;set;}
		public Guid quotationID {get;set;}
		public string? debitcredit {get;set;}
		public Guid customerid {get;set;}
		public Guid itemid {get;set;}
		public string? currency {get;set;}
		public string? containertype {get;set;}
		public double? unitprice {get;set;}
		public double? pricetruocthue {get;set;}
		public double? pricenotaxvnd {get;set;}
		public double? taxprice {get;set;}
		public double? pricethue {get;set;}
		public double? price {get;set;}
		public string? note {get;set;}
		public string? quantity {get;set;}
		public bool? paycheck {get;set;}
		public bool? os {get;set;}
		public string? ngay {get;set;}
		public string? ngayhoadon {get;set;}
		public string? tigia {get;set;}
		public string? vitri {get;set;}
		public bool? editable {get;set;}
		public bool? approve {get;set;}
		public bool? continued {get;set;}
		public string? dateupdate {get;set;}
		public string? userupdate {get;set;}
		public bool? showarrival {get;set;}
		public string? soNgayCongNo {get;set;}
		public bool? othercredit {get;set;}
		public bool? onbehaft {get;set;}
		public bool? daily {get;set;}
		public int? stt {get;set;}
		public bool? showVND {get;set;}
		public string? container {get;set;}
		public int? freeDEM {get;set;}
		public int? freeDET {get;set;}
		public string? no_ {get;set;}
		public int? f1 {get;set;}
		public int? t1 {get;set;}
		public double? p1 {get;set;}
		public int? f2 {get;set;}
		public int? t2 {get;set;}
		public double? p2 {get;set;}
		public int? level {get;set;}
		public double? unitprice_ {get;set;}
		public double? price_ {get;set;}
		public bool? dntt {get;set;}
		public bool? KTT {get;set;}
		public bool? boss {get;set;}
		public bool? debit {get;set;}
		public double? dongiatruocthueVND {get;set;}
		public double? thanhtientruocthueVND {get;set;}
		public double? tienthueVND {get;set;}
		public double? thanhtiensauthueVND {get;set;}
		public string? ref_debitcredit {get;set;}
		public string? housebill_debitcredit {get;set;}
		public bool? kiemtra {get;set;}
		public string? userkiemtra {get;set;}
		public string? ngaykiemtra {get;set;}
		public string? pttt {get;set;}
		public string? KYHIEU {get;set;}
		public string? ngaythanhtoan {get;set;}
		public string? dept {get;set;}
		public string? nhatky {get;set;}
		public bool? dachuyen3a {get;set;}
		public string? seri {get;set;}
		public string? nh_dk {get;set;}
		public string? tkno_debitcredit {get;set;}
		public string? tkco_debitcredit {get;set;}
		public string? tkhq_dc {get;set;}
		public string? tkhq_dc_ {get;set;}
		public string? tennhomphi_debitcredit {get;set;}
		public string? sochungtu_3a {get;set;}
		public Guid tax_customerid {get;set;}
		public string? level1_phanquyen {get;set;}
		public string? level2_manager {get;set;}
		public string? level3_branchmanager {get;set;}
		public string? level4_general {get;set;}
		public string? mbl_debitcredit {get;set;}
		public string? tendntt {get;set;}
		public string? tenktt {get;set;}
		public string? tenboss {get;set;}
		public string? gio_dntt {get;set;}
		public DateTime? freightdatereport {get;set;}
		public string? quyenbaocao {get;set;}
		public bool? phu {get;set;}
		public string? EraseNo {get;set;}
		public string? Book_EraseNo {get;set;}
		public double? thuevat {get;set;}
		public string? Erase_Date {get;set;}
		public string? Ngay_Erase {get;set;}
	}
}
